#!/usr/bin/env python3
"""Build data/phrases.json — a scenario-organized lexical-chunk library.

Fluency is built from prefabricated chunks (collocations, fixed phrases,
sentence frames) retrieved as whole units, grouped by real-life scenario.
No finite list covers *all* usage — language is generative — but this aims
for broad high-frequency coverage of what you'd actually say per scenario.

Output schema mirrors words_merged.json so the app reuses the same
grid / filter / study / SRS / proficiency engine:
  theme           = 场景 (scenario)
  part_of_speech  = 类型 (短句 / 词组)
  parent_category = 短语
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "phrases.json"

# Each entry: (english, chinese, kind)  kind: "s"=短句  "c"=词组
SCENARIOS = {
    "问候寒暄": [
        ("How's it going?", "最近怎么样？", "s"),
        ("How have you been?", "你近来好吗？", "s"),
        ("Long time no see.", "好久不见。", "s"),
        ("It's been a while.", "有段时间没见了。", "s"),
        ("What have you been up to?", "你最近在忙什么？", "s"),
        ("How's everything going?", "一切都还好吗？", "s"),
        ("How's life treating you?", "最近过得怎么样？", "s"),
        ("Good to see you.", "见到你真好。", "s"),
        ("It's nice to finally meet you.", "很高兴终于见到你。", "s"),
        ("How are things at work?", "工作上怎么样？", "s"),
        ("Can't complain.", "还不错。", "s"),
        ("Pretty good, thanks.", "挺好的，谢谢。", "s"),
        ("Not too bad.", "还行吧。", "s"),
        ("Same as usual.", "老样子。", "s"),
        ("Same here.", "我也是。", "c"),
        ("What's new?", "有什么新鲜事吗？", "s"),
        ("What's up?", "怎么了 / 最近如何？", "s"),
        ("How's your day going?", "你今天过得怎么样？", "s"),
        ("Take care!", "保重！", "s"),
        ("Have a good one.", "祝你愉快。", "s"),
        ("Have a great day.", "祝你今天愉快。", "s"),
        ("Catch you later.", "回头见。", "s"),
        ("See you around.", "回头见。", "s"),
        ("Talk to you soon.", "回头聊。", "s"),
        ("How was your weekend?", "你周末过得怎么样？", "s"),
        ("Did you have a good weekend?", "周末过得开心吗？", "s"),
        ("Say hi to your family.", "代我向你家人问好。", "s"),
        ("Give my regards to Tom.", "替我向 Tom 问好。", "s"),
        ("It's been too long.", "太久没见了。", "s"),
        ("You look great!", "你气色真好！", "s"),
        ("Welcome back!", "欢迎回来！", "s"),
        ("How do you do?", "你好（初次见面）。", "s"),
        ("Nice to see you again.", "很高兴再次见到你。", "s"),
        ("I've heard a lot about you.", "久仰大名。", "s"),
        ("Let's keep in touch.", "保持联系。", "s"),
        ("Fancy meeting you here!", "真巧在这儿遇见你！", "s"),
        ("How's the family?", "家人都好吗？", "s"),
        ("Good morning, everyone.", "大家早上好。", "s"),
        ("Have a good evening.", "祝你晚上愉快。", "s"),
        ("It was great catching up.", "很高兴和你叙旧。", "s"),
    ],
    "自我介绍": [
        ("Let me introduce myself.", "请允许我自我介绍。", "s"),
        ("My name is Wang Lei.", "我叫王磊。", "s"),
        ("Please call me Leo.", "请叫我 Leo。", "s"),
        ("Feel free to call me Sam.", "你可以叫我 Sam。", "s"),
        ("I'm in charge of marketing.", "我负责市场营销。", "s"),
        ("I work as a software engineer.", "我是一名软件工程师。", "s"),
        ("I work in finance.", "我从事金融行业。", "s"),
        ("I'm a freelance designer.", "我是自由设计师。", "s"),
        ("I'm originally from Beijing.", "我老家在北京。", "s"),
        ("I was born and raised in Shanghai.", "我在上海土生土长。", "s"),
        ("I've been here for three years.", "我在这里三年了。", "s"),
        ("I just moved here.", "我刚搬来这里。", "s"),
        ("I'm currently studying for a master's.", "我正在读硕士。", "s"),
        ("I graduated from Peking University.", "我毕业于北京大学。", "s"),
        ("a background in design", "设计相关的背景", "c"),
        ("I majored in economics.", "我主修经济学。", "s"),
        ("I'm passionate about", "我热衷于……", "c"),
        ("In my free time, I like hiking.", "空闲时我喜欢徒步。", "s"),
        ("We met at the conference.", "我们在会议上见过。", "s"),
        ("I believe we've met before.", "我们好像见过。", "s"),
        ("I look forward to working with you.", "期待与你合作。", "s"),
        ("Here's my business card.", "这是我的名片。", "s"),
        ("What do you do?", "你是做什么的？", "s"),
        ("What line of work are you in?", "你从事哪一行？", "s"),
        ("How long have you been with the company?", "你在这家公司多久了？", "s"),
        ("It's a pleasure to meet you.", "很荣幸认识你。", "s"),
        ("I'm new here.", "我是新来的。", "s"),
        ("Let me tell you a bit about myself.", "我简单介绍一下自己。", "s"),
        ("on behalf of my team", "代表我的团队", "c"),
        ("I'm responsible for customer support.", "我负责客户支持。", "s"),
        ("How do you two know each other?", "你们俩怎么认识的？", "s"),
        ("We go way back.", "我们是老相识了。", "s"),
        ("I'm a friend of Anna's.", "我是 Anna 的朋友。", "s"),
        ("What brings you here?", "什么风把你吹来了？", "s"),
        ("I'm here with my colleagues.", "我和同事一起来的。", "s"),
        ("Can I get your name again?", "能再说一遍你的名字吗？", "s"),
        ("Sorry, I didn't catch your name.", "抱歉，我没听清你的名字。", "s"),
        ("Where are you based?", "你常驻在哪？", "s"),
        ("I switched careers last year.", "我去年转行了。", "s"),
        ("I'm self-employed.", "我自己创业 / 自雇。", "s"),
    ],
    "餐厅点餐": [
        ("A table for two, please.", "两位，谢谢。", "s"),
        ("Do you have a table available?", "有空桌吗？", "s"),
        ("I have a reservation under Chen.", "我有预订，名字是 Chen。", "s"),
        ("How long is the wait?", "要等多久？", "s"),
        ("Could we sit by the window?", "我们能坐靠窗吗？", "s"),
        ("Could I see the menu?", "我能看下菜单吗？", "s"),
        ("Could we have a few more minutes?", "能再给我们几分钟吗？", "s"),
        ("We're ready to order.", "我们可以点餐了。", "s"),
        ("What do you recommend?", "你有什么推荐？", "s"),
        ("What's today's special?", "今天的特色菜是什么？", "s"),
        ("What's this dish like?", "这道菜是怎样的？", "s"),
        ("What's popular here?", "这里什么菜受欢迎？", "s"),
        ("I'll have the steak.", "我要牛排。", "s"),
        ("I'll have the same.", "我要一样的。", "s"),
        ("Make it two.", "来两份一样的。", "s"),
        ("I'll start with a salad.", "我先来份沙拉。", "s"),
        ("for here or to go", "堂食还是外带", "c"),
        ("I'd like it to go.", "我要打包带走。", "s"),
        ("How would you like your steak?", "牛排要几分熟？", "s"),
        ("Medium rare, please.", "五分熟，谢谢。", "s"),
        ("Could you make it less salty?", "能少放点盐吗？", "s"),
        ("No onions, please.", "请不要放洋葱。", "s"),
        ("On the side, please.", "请单独放（不要拌在一起）。", "c"),
        ("Is this dish spicy?", "这道菜辣吗？", "s"),
        ("Could you make it mild?", "能做不辣的吗？", "s"),
        ("I'm allergic to nuts.", "我对坚果过敏。", "s"),
        ("I'm a vegetarian.", "我吃素。", "s"),
        ("Does it contain dairy?", "这里面有乳制品吗？", "s"),
        ("Could I get a glass of water?", "能给我杯水吗？", "c"),
        ("Could we get some napkins?", "能给我们些餐巾纸吗？", "s"),
        ("Could I get a refill?", "能续杯吗？", "s"),
        ("This isn't what I ordered.", "这不是我点的。", "s"),
        ("Excuse me, we're still waiting on our food.", "不好意思，我们的菜还没上。", "s"),
        ("Everything was delicious.", "一切都很美味。", "s"),
        ("Could I get the check, please?", "请结账。", "s"),
        ("Can we split the bill?", "我们能分开付吗？", "s"),
        ("Is service included?", "含服务费吗？", "s"),
        ("Keep the change.", "不用找了。", "s"),
        ("Could I get a to-go box?", "能给我个打包盒吗？", "s"),
        ("Cheers!", "干杯！", "s"),
        ("My compliments to the chef.", "请代我向厨师致意。", "s"),
        ("Could we get the dessert menu?", "能给我们甜点菜单吗？", "s"),
        ("I'd like to order now.", "我现在想点餐。", "s"),
        ("Still or sparkling water?", "无气还是有气的水？", "s"),
        ("Can I have the bill, please?", "请给我账单。", "s"),
        ("Could you box up the leftovers?", "能把剩菜打包吗？", "s"),
        ("What's in this dish?", "这道菜里有什么？", "s"),
        ("I'll pass on dessert.", "甜点就不要了。", "s"),
        ("Could we get separate checks?", "能分开结账吗？", "s"),
        ("Can I substitute fries for salad?", "能把薯条换成沙拉吗？", "s"),
    ],
    "购物": [
        ("How much is this?", "这个多少钱？", "s"),
        ("How much does it cost?", "这个要多少钱？", "s"),
        ("Do you have this in a larger size?", "这个有大码的吗？", "s"),
        ("Do you have this in a smaller size?", "这个有小码的吗？", "s"),
        ("Do you have this in another color?", "这个有别的颜色吗？", "s"),
        ("Can I try it on?", "我能试穿吗？", "s"),
        ("Where's the fitting room?", "试衣间在哪里？", "s"),
        ("It doesn't fit.", "不合身。", "s"),
        ("It's a bit too tight.", "有点紧。", "s"),
        ("It's a bit too loose.", "有点松。", "s"),
        ("It suits you.", "很适合你。", "s"),
        ("I'm just looking, thanks.", "我随便看看，谢谢。", "s"),
        ("Just browsing.", "随便逛逛。", "c"),
        ("Is this on sale?", "这个在打折吗？", "s"),
        ("a great deal", "很划算的交易", "c"),
        ("Is there a discount?", "有折扣吗？", "s"),
        ("Can you give me a discount?", "能便宜点吗？", "s"),
        ("That's too expensive.", "太贵了。", "s"),
        ("Do you take credit cards?", "你们收信用卡吗？", "s"),
        ("Can I pay by phone?", "能用手机支付吗？", "s"),
        ("I'll take it.", "我买了。", "s"),
        ("I'll take two.", "我要两个。", "s"),
        ("I'll think about it.", "我再考虑一下。", "s"),
        ("Could I get a receipt?", "能给我张收据吗？", "s"),
        ("Can I return this?", "这个能退吗？", "s"),
        ("Could I get a refund?", "我能退款吗？", "s"),
        ("Can I exchange it?", "能换货吗？", "s"),
        ("Do you have it in stock?", "有现货吗？", "s"),
        ("It's out of stock.", "缺货了。", "s"),
        ("When will it be back in stock?", "什么时候会补货？", "s"),
        ("Could you gift-wrap it?", "能帮我包成礼物吗？", "s"),
        ("Where do I check out?", "在哪里结账？", "s"),
        ("Do you offer free shipping?", "包邮吗？", "s"),
        ("What's your return policy?", "你们的退货政策是什么？", "s"),
        ("I'm looking for a gift.", "我在找礼物。", "s"),
        ("Could you hold this for me?", "能帮我留着这个吗？", "s"),
        ("Does it come with a warranty?", "有保修吗？", "s"),
        ("Can I get a bag?", "能给个袋子吗？", "s"),
        ("Where can I find the electronics?", "电子产品在哪个区？", "s"),
        ("Do you price match?", "你们有比价（保价）吗？", "s"),
        ("Is this the final price?", "这是最低价了吗？", "s"),
        ("Can I get a tax refund?", "我能退税吗？", "s"),
        ("It's a bit out of my price range.", "有点超出我的价位了。", "s"),
        ("Could you ring me up?", "能帮我结一下账吗？", "s"),
        ("Do you have any recommendations?", "你有什么推荐吗？", "s"),
        ("I changed my mind.", "我改主意了。", "s"),
        ("Can I see that one?", "能看下那个吗？", "s"),
        ("Are these two for one?", "这些是买一送一吗？", "s"),
        ("I'd like to pay separately.", "我想分开付。", "s"),
        ("That's all, thanks.", "就这些，谢谢。", "s"),
    ],
    "问路出行": [
        ("Excuse me, how do I get to the station?", "请问，去车站怎么走？", "s"),
        ("Could you tell me the way to the museum?", "能告诉我去博物馆的路吗？", "s"),
        ("Where's the nearest subway station?", "最近的地铁站在哪？", "s"),
        ("Is it within walking distance?", "走得到吗？", "s"),
        ("How far is it from here?", "离这儿多远？", "s"),
        ("How long does it take?", "要多久？", "s"),
        ("Go straight ahead.", "一直往前走。", "s"),
        ("Turn left at the corner.", "在路口左转。", "s"),
        ("Turn right at the traffic lights.", "在红绿灯处右转。", "s"),
        ("It's just around the corner.", "就在拐角处。", "s"),
        ("It's on your right.", "在你右手边。", "c"),
        ("It's across from the bank.", "在银行对面。", "s"),
        ("It's next to the post office.", "在邮局旁边。", "s"),
        ("It's between the cafe and the bank.", "在咖啡馆和银行之间。", "s"),
        ("You can't miss it.", "你肯定找得到。", "s"),
        ("Take the second left.", "在第二个路口左拐。", "s"),
        ("Keep going for two blocks.", "再走两个街区。", "s"),
        ("I think I'm lost.", "我好像迷路了。", "s"),
        ("Am I going the right way?", "我走对方向了吗？", "s"),
        ("Could you show me on the map?", "能在地图上指给我看吗？", "s"),
        ("Which way is downtown?", "市中心在哪个方向？", "s"),
        ("Is this the right way to the airport?", "去机场是走这边吗？", "s"),
        ("Could you draw me a map?", "能给我画个图吗？", "s"),
        ("Is it far on foot?", "走路远吗？", "s"),
        ("You're going the wrong way.", "你走反了。", "s"),
        ("It's a five-minute walk.", "走路五分钟。", "s"),
        ("Follow this road.", "顺着这条路走。", "s"),
        ("It's at the end of the street.", "在街的尽头。", "s"),
        ("Go past the bank.", "走过那家银行。", "s"),
        ("It's right there.", "就在那儿。", "s"),
        ("Head north for a bit.", "往北走一段。", "s"),
        ("Take the stairs to the second floor.", "上二楼。", "s"),
        ("Sorry, I'm not from around here.", "抱歉，我不是本地人。", "s"),
        ("Could you repeat that?", "能再说一遍吗？", "s"),
        ("Is there a shortcut?", "有近路吗？", "s"),
    ],
    "交通出行": [
        ("Could you take me to the airport?", "能送我去机场吗？", "s"),
        ("How much is the fare?", "车费多少？", "s"),
        ("Please turn on the meter.", "请打表。", "s"),
        ("Keep the change.", "不用找了。", "s"),
        ("Could you pull over here?", "能在这儿靠边停吗？", "s"),
        ("Drop me off at the corner.", "在路口让我下车。", "s"),
        ("I'm in a hurry.", "我赶时间。", "s"),
        ("Could you drive a bit faster?", "能开快点吗？", "s"),
        ("Could you slow down a bit?", "能开慢点吗？", "s"),
        ("Which platform is it?", "在几号站台？", "s"),
        ("Which line goes to downtown?", "哪条线去市中心？", "s"),
        ("Where do I transfer?", "在哪里换乘？", "s"),
        ("How many stops is it?", "还有几站？", "s"),
        ("Does this bus stop at the mall?", "这趟车在商场停吗？", "s"),
        ("Could you tell me when to get off?", "到站能提醒我下车吗？", "s"),
        ("A one-way ticket, please.", "一张单程票，谢谢。", "s"),
        ("A round-trip ticket to Boston.", "一张去波士顿的往返票。", "s"),
        ("What time does the next train leave?", "下一班火车几点开？", "s"),
        ("Did I miss the bus?", "我错过那趟公交了吗？", "s"),
        ("Is this seat taken?", "这个座位有人吗？", "s"),
        ("I missed my stop.", "我坐过站了。", "s"),
        ("rush hour", "高峰期", "c"),
        ("stuck in traffic", "堵在路上", "c"),
        ("Where can I get a taxi?", "哪里能打到车？", "s"),
        ("Could you call me a cab?", "能帮我叫辆出租车吗？", "s"),
        ("How long is the ride?", "车程多久？", "s"),
        ("Does this train go to the airport?", "这趟车去机场吗？", "s"),
        ("I'd like to rent a car.", "我想租辆车。", "s"),
        ("Where's the nearest bus stop?", "最近的公交站在哪？", "s"),
        ("Tap your card here.", "在这里刷卡。", "s"),
        ("Where do I buy a ticket?", "在哪买票？", "s"),
        ("Could you wait here for a moment?", "能在这儿等我一下吗？", "s"),
        ("Is there a direct train?", "有直达车吗？", "s"),
        ("I'd like to top up my card.", "我想给卡充值。", "s"),
        ("My flight is at six, so I need to hurry.", "我六点的飞机，得快点。", "s"),
        ("Take the next exit.", "走下一个出口。", "s"),
        ("Could you turn on the AC?", "能开下空调吗？", "s"),
    ],
    "机场出行": [
        ("I'd like to check in.", "我想办理登机。", "s"),
        ("Here's my passport.", "这是我的护照。", "s"),
        ("a window seat", "靠窗的座位", "c"),
        ("an aisle seat", "靠过道的座位", "c"),
        ("Could I get an aisle seat?", "能给我靠过道的座位吗？", "s"),
        ("How many bags are you checking?", "你要托运几件行李？", "s"),
        ("carry-on luggage", "随身行李", "c"),
        ("Is my bag within the weight limit?", "我的行李超重吗？", "s"),
        ("Is the flight on time?", "航班准点吗？", "s"),
        ("The flight has been delayed.", "航班延误了。", "s"),
        ("The flight got canceled.", "航班取消了。", "s"),
        ("What's the gate number?", "登机口是几号？", "s"),
        ("Where is the boarding gate?", "登机口在哪里？", "s"),
        ("When does boarding start?", "什么时候开始登机？", "s"),
        ("Final call for boarding.", "最后一次登机广播。", "c"),
        ("Could I see your boarding pass?", "能看下你的登机牌吗？", "s"),
        ("I have nothing to declare.", "我没有要申报的物品。", "s"),
        ("What's the purpose of your visit?", "你此行的目的是什么？", "s"),
        ("I'm here on business.", "我来出差。", "s"),
        ("I'm here for tourism.", "我来旅游。", "s"),
        ("How long will you be staying?", "你要待多久？", "s"),
        ("I'm staying for a week.", "我待一周。", "s"),
        ("I missed my connection.", "我错过了转机。", "s"),
        ("Where do I claim my baggage?", "在哪里取行李？", "c"),
        ("My luggage is missing.", "我的行李丢了。", "s"),
        ("My suitcase is damaged.", "我的箱子破损了。", "s"),
        ("Where can I exchange money?", "哪里能换钱？", "s"),
        ("Is there free Wi-Fi here?", "这里有免费 Wi-Fi 吗？", "s"),
        ("Could you help me find my gate?", "你能帮我找登机口吗？", "s"),
        ("Where's the duty-free shop?", "免税店在哪？", "s"),
        ("Please fasten your seatbelt.", "请系好安全带。", "s"),
        ("Could I have a blanket?", "能给我条毯子吗？", "s"),
        ("Window or aisle?", "靠窗还是靠过道？", "s"),
        ("Do I need to take off my shoes?", "我需要脱鞋吗（过安检）？", "s"),
        ("Where's the security checkpoint?", "安检口在哪？", "s"),
    ],
    "酒店住宿": [
        ("I have a reservation under Li.", "我有个预订，名字是 Li。", "s"),
        ("I'd like to check in.", "我想办理入住。", "s"),
        ("Do you have any rooms available?", "还有空房吗？", "s"),
        ("I'd like to book a room for two nights.", "我想订一个房间，住两晚。", "s"),
        ("a non-smoking room", "无烟房", "c"),
        ("a double room", "双人间", "c"),
        ("Is there a room with a king bed?", "有大床房吗？", "s"),
        ("What time is check-in?", "几点可以入住？", "s"),
        ("What time is check-out?", "几点退房？", "s"),
        ("checkout is at noon", "中午退房", "c"),
        ("Is breakfast included?", "含早餐吗？", "s"),
        ("What time is breakfast?", "早餐几点？", "s"),
        ("Could I have a wake-up call?", "能帮我设个叫醒服务吗？", "s"),
        ("Could I get a late checkout?", "能延迟退房吗？", "s"),
        ("Is there free Wi-Fi?", "有免费 Wi-Fi 吗？", "s"),
        ("What's the Wi-Fi password?", "Wi-Fi 密码是多少？", "s"),
        ("The room hasn't been cleaned.", "房间还没打扫。", "s"),
        ("The air conditioning isn't working.", "空调坏了。", "s"),
        ("The hot water isn't working.", "没有热水。", "s"),
        ("Could you send up some towels?", "能送些毛巾上来吗？", "s"),
        ("Can I leave my luggage here?", "我能把行李寄存在这吗？", "s"),
        ("Could you call me a taxi?", "能帮我叫辆出租车吗？", "s"),
        ("Is there a gym in the hotel?", "酒店有健身房吗？", "s"),
        ("Could I have an extra blanket?", "能再给条毯子吗？", "s"),
        ("The room next door is too noisy.", "隔壁房间太吵了。", "s"),
        ("Could I switch rooms?", "我能换个房间吗？", "s"),
        ("I'd like to extend my stay.", "我想续住。", "s"),
        ("Could I have a room with a view?", "能给我个有景观的房间吗？", "s"),
        ("Is there room service?", "有客房服务吗？", "s"),
        ("Could I get a receipt?", "能给我开张发票吗？", "s"),
        ("I'd like to check out.", "我想退房。", "s"),
        ("Could you break this down for me?", "能帮我解释下这笔账吗？", "s"),
        ("Is there a safe in the room?", "房间里有保险箱吗？", "s"),
        ("How do I get to the elevator?", "电梯怎么走？", "s"),
        ("Could I have a city map?", "能给我张城市地图吗？", "s"),
        ("Do you offer airport pickup?", "你们有机场接送吗？", "s"),
        ("There's no toilet paper.", "没有卫生纸了。", "s"),
    ],
    "看病就医": [
        ("I'd like to make an appointment.", "我想预约。", "s"),
        ("I'm not feeling well.", "我不太舒服。", "s"),
        ("I think I'm coming down with a cold.", "我好像要感冒了。", "s"),
        ("I have a sore throat.", "我嗓子疼。", "s"),
        ("a runny nose", "流鼻涕", "c"),
        ("a stuffy nose", "鼻塞", "c"),
        ("I've had a headache since yesterday.", "我从昨天就头疼。", "s"),
        ("I have a fever.", "我发烧了。", "s"),
        ("I have a high temperature.", "我体温很高。", "s"),
        ("It hurts right here.", "就是这里疼。", "s"),
        ("I feel dizzy.", "我头晕。", "s"),
        ("I feel nauseous.", "我想吐。", "s"),
        ("I've been coughing a lot.", "我一直咳嗽。", "s"),
        ("My stomach hurts.", "我肚子疼。", "s"),
        ("My back is killing me.", "我背疼得要命。", "s"),
        ("I can't sleep well.", "我睡不好。", "s"),
        ("How long have you had these symptoms?", "这些症状有多久了？", "s"),
        ("Are you allergic to any medication?", "你对什么药过敏吗？", "s"),
        ("Are you on any medication?", "你在吃什么药吗？", "s"),
        ("Do I need a prescription?", "我需要处方吗？", "s"),
        ("How often should I take this?", "这个我该多久吃一次？", "s"),
        ("Take it twice a day.", "一天吃两次。", "s"),
        ("Take it after meals.", "饭后服用。", "s"),
        ("Are there any side effects?", "有副作用吗？", "s"),
        ("Is it serious?", "严重吗？", "s"),
        ("Get plenty of rest.", "多休息。", "s"),
        ("Drink lots of water.", "多喝水。", "s"),
        ("Where's the nearest pharmacy?", "最近的药店在哪？", "s"),
        ("I need to see a doctor.", "我需要看医生。", "s"),
        ("Could you write me a sick note?", "能给我开张病假条吗？", "s"),
        ("I've been feeling tired lately.", "我最近一直很累。", "s"),
        ("Do you have anything for a cough?", "有治咳嗽的药吗？", "s"),
        ("It's been hurting for a few days.", "已经疼了几天了。", "s"),
        ("I twisted my ankle.", "我扭到脚踝了。", "s"),
        ("I think I caught a cold.", "我好像感冒了。", "s"),
        ("Should I see a specialist?", "我需要看专科吗？", "s"),
        ("When should I come back?", "我什么时候该复诊？", "s"),
        ("Is this covered by insurance?", "这个保险报销吗？", "s"),
        ("I feel a little better today.", "我今天好点了。", "s"),
        ("Take care of yourself.", "好好照顾自己。", "s"),
    ],
    "打电话": [
        ("Hello, this is Anna speaking.", "你好，我是 Anna。", "s"),
        ("Could I speak to Mr. Lee, please?", "请问 Lee 先生在吗？", "s"),
        ("Who's calling, please?", "请问您是哪位？", "s"),
        ("May I ask who's calling?", "请问您是哪位？", "s"),
        ("Hold on a second.", "请稍等。", "s"),
        ("Please hold.", "请稍候。", "s"),
        ("I'll put you through.", "我帮你转接。", "s"),
        ("He's not available right now.", "他现在不方便接电话。", "s"),
        ("He's in a meeting.", "他在开会。", "s"),
        ("Could you take a message?", "能帮我留个口信吗？", "s"),
        ("Can I leave a message?", "我能留言吗？", "s"),
        ("I'll call you back.", "我回头打给你。", "s"),
        ("Could you call me back later?", "你能晚点回电吗？", "s"),
        ("You've got the wrong number.", "你打错电话了。", "s"),
        ("The line is busy.", "电话占线。", "s"),
        ("We got cut off.", "电话断了。", "s"),
        ("Can you hear me?", "你能听到我吗？", "s"),
        ("You're breaking up.", "你的声音断断续续。", "s"),
        ("Can you speak up a little?", "你能说大声点吗？", "s"),
        ("I'm calling about...", "我打来是想问……", "c"),
        ("I'm returning your call.", "我回你电话。", "s"),
        ("Thanks for calling.", "谢谢来电。", "s"),
        ("Let me check and get back to you.", "我查一下再回复你。", "s"),
        ("Could you spell that for me?", "能拼一下吗？", "s"),
        ("Hold the line, please.", "请别挂断。", "s"),
        ("Sorry to keep you waiting.", "抱歉让你久等了。", "s"),
        ("Can I call you back in five minutes?", "我五分钟后回你电话好吗？", "s"),
        ("Is now a good time to talk?", "现在方便讲话吗？", "s"),
        ("Could you transfer me to sales?", "能帮我转接销售部吗？", "s"),
        ("My battery is about to die.", "我手机快没电了。", "s"),
        ("Let me write that down.", "我记一下。", "s"),
        ("Speaking.", "我就是（接电话找本人时）。", "s"),
        ("I'll text you instead.", "我改发短信给你吧。", "s"),
        ("Sorry, wrong number.", "抱歉，打错了。", "s"),
    ],
    "职场会议": [
        ("Let's get started.", "我们开始吧。", "s"),
        ("Let's get down to business.", "我们言归正传。", "s"),
        ("Thanks for joining.", "感谢各位参加。", "s"),
        ("Let's go around the room.", "我们逐个发言。", "s"),
        ("Let's do a quick round of intros.", "我们简单互相介绍下。", "s"),
        ("Could you walk me through it?", "你能给我讲一遍吗？", "s"),
        ("Let me share my screen.", "我来共享一下屏幕。", "s"),
        ("Can everyone see my screen?", "大家能看到我的屏幕吗？", "s"),
        ("You're on mute.", "你静音了。", "s"),
        ("Could you mute yourself?", "能麻烦你静音吗？", "s"),
        ("Let's circle back to that.", "这个我们稍后再说。", "s"),
        ("Let's take this offline.", "这个我们会后再谈。", "s"),
        ("Let's table this for now.", "这个先搁置一下。", "s"),
        ("on the same page", "达成共识", "c"),
        ("Let's touch base next week.", "下周我们再沟通。", "s"),
        ("I'll keep you posted.", "我会随时通知你。", "s"),
        ("I'll follow up with an email.", "我会发邮件跟进。", "s"),
        ("Let's set up a meeting.", "我们约个会吧。", "s"),
        ("Can we move the meeting?", "会议能改时间吗？", "s"),
        ("Let's push it to Thursday.", "推到周四吧。", "s"),
        ("What's the deadline?", "截止日期是什么时候？", "s"),
        ("We're behind schedule.", "我们进度落后了。", "s"),
        ("Let's prioritize this.", "我们优先处理这个。", "s"),
        ("Who's taking the lead on this?", "这个谁来牵头？", "s"),
        ("Let's divide up the work.", "我们分一下工。", "s"),
        ("a quick recap", "简短回顾", "c"),
        ("To sum up,", "总结一下，", "c"),
        ("Let me play devil's advocate.", "我故意唱个反调。", "s"),
        ("Does that work for you?", "这样行吗？", "s"),
        ("Any questions so far?", "到目前有什么问题吗？", "s"),
        ("Let's hear your thoughts.", "说说你的想法。", "s"),
        ("Could you elaborate on that?", "能展开讲讲吗？", "s"),
        ("Let's wrap up.", "我们收尾吧。", "s"),
        ("Let's call it a day.", "今天就到这儿吧。", "s"),
        ("Could you send me the minutes?", "能把会议纪要发我吗？", "s"),
        ("Let's keep it brief.", "我们简短点。", "s"),
        ("I'll loop you in.", "我会把你加进来。", "s"),
        ("Let's align on the next steps.", "我们对齐下一步。", "s"),
        ("action items", "待办事项", "c"),
        ("Let's park that idea.", "这个想法先放一放。", "s"),
        ("I'm swamped this week.", "我这周忙得不可开交。", "s"),
        ("Let's touch on the budget.", "我们聊聊预算。", "s"),
        ("Can we take a five-minute break?", "我们能休息五分钟吗？", "s"),
        ("Let's reconvene at two.", "两点继续。", "s"),
        ("I'll circulate the deck.", "我把幻灯片发给大家。", "s"),
    ],
    "求职面试": [
        ("Tell me about yourself.", "请介绍一下你自己。", "s"),
        ("Walk me through your resume.", "讲一下你的简历。", "s"),
        ("What are your strengths?", "你的优势是什么？", "s"),
        ("What's your biggest weakness?", "你最大的弱点是什么？", "s"),
        ("Why do you want this job?", "你为什么想要这份工作？", "s"),
        ("Why should we hire you?", "我们为什么要录用你？", "s"),
        ("Why are you leaving your current job?", "你为什么离开现在的工作？", "s"),
        ("I'm a quick learner.", "我学东西很快。", "s"),
        ("I work well under pressure.", "我抗压能力强。", "s"),
        ("under pressure", "在压力之下", "c"),
        ("a team player", "有团队精神的人", "c"),
        ("I have hands-on experience.", "我有实践经验。", "s"),
        ("I'm detail-oriented.", "我做事注重细节。", "s"),
        ("I take initiative.", "我做事主动。", "s"),
        ("I'm a self-starter.", "我有很强的自驱力。", "s"),
        ("Where do you see yourself in five years?", "你五年后想做什么？", "s"),
        ("What are your salary expectations?", "你的薪资期望是多少？", "s"),
        ("When can you start?", "你什么时候能入职？", "s"),
        ("I can start immediately.", "我可以马上入职。", "s"),
        ("I need to give two weeks' notice.", "我需要提前两周辞职。", "s"),
        ("Do you have any questions for us?", "你有什么想问我们的吗？", "s"),
        ("Could you tell me about the team?", "能介绍下团队吗？", "s"),
        ("What's the company culture like?", "公司文化怎么样？", "s"),
        ("What's the next step?", "下一步是什么？", "s"),
        ("I'm excited about this opportunity.", "我对这个机会很期待。", "s"),
        ("Thank you for your time.", "感谢你抽出时间。", "s"),
        ("I look forward to hearing from you.", "期待你的回复。", "s"),
        ("Could you describe a typical day?", "能描述下日常工作吗？", "s"),
        ("I have over five years of experience.", "我有五年以上的经验。", "s"),
        ("Tell me about a challenge you faced.", "讲讲你遇到的一个挑战。", "s"),
        ("Tell me about a time you failed.", "讲讲一次你失败的经历。", "s"),
        ("How do you handle conflict?", "你怎么处理冲突？", "s"),
        ("What motivates you?", "什么能激励你？", "s"),
        ("I'm looking for growth.", "我希望有成长空间。", "s"),
        ("It's a great fit for my skills.", "这和我的技能很匹配。", "s"),
        ("Is the role remote or on-site?", "这个岗位是远程还是坐班？", "s"),
        ("What does success look like in this role?", "这个岗位怎样算做得好？", "s"),
        ("I'd be happy to do a trial task.", "我很乐意做个试岗任务。", "s"),
        ("I'm open to relocation.", "我可以接受异地。", "s"),
        ("I'd appreciate any feedback.", "我很乐意听取反馈。", "s"),
    ],
    "社交邀约": [
        ("Are you free this weekend?", "你这周末有空吗？", "s"),
        ("Do you want to grab a coffee?", "想去喝杯咖啡吗？", "s"),
        ("Do you want to grab lunch?", "一起吃午饭吗？", "s"),
        ("Let's grab a drink sometime.", "改天一起喝一杯。", "s"),
        ("Let's hang out sometime.", "改天一起玩吧。", "s"),
        ("We should catch up soon.", "我们该聚聚了。", "s"),
        ("Want to come over?", "要来我家吗？", "s"),
        ("Want to join us?", "要一起来吗？", "s"),
        ("How about Friday night?", "周五晚上怎么样？", "s"),
        ("What time works for you?", "你几点方便？", "s"),
        ("Where should we meet?", "我们在哪儿见？", "s"),
        ("Let's meet at the entrance.", "我们在门口见。", "s"),
        ("Count me in.", "算我一个。", "s"),
        ("I'm in.", "我参加。", "s"),
        ("Sounds great!", "听起来不错！", "s"),
        ("Sounds like a plan.", "就这么定了。", "s"),
        ("I'd love to.", "我很乐意。", "s"),
        ("I'd love to, but I'm busy.", "我很想去，但我有事。", "s"),
        ("Maybe some other time.", "改天吧。", "s"),
        ("I'll take a rain check.", "下次吧。", "s"),
        ("Can I bring a friend?", "我能带个朋友吗？", "s"),
        ("It's on me.", "我请客。", "s"),
        ("Let's split it.", "我们 AA 吧。", "s"),
        ("Thanks for having me.", "谢谢你的款待。", "s"),
        ("I had a great time.", "我玩得很开心。", "s"),
        ("We should do this again.", "我们该再聚一次。", "s"),
        ("Are you doing anything tonight?", "你今晚有安排吗？", "s"),
        ("Let me check my schedule.", "我看下日程。", "s"),
        ("I'll let you know.", "我回头告诉你。", "s"),
        ("Can we reschedule?", "我们能改约吗？", "s"),
        ("Something came up.", "我临时有事。", "s"),
        ("I'm running a bit late.", "我会晚到一点。", "s"),
        ("Save me a seat.", "帮我占个位。", "s"),
        ("Let's make it a group thing.", "干脆大家一起来吧。", "s"),
        ("Feel free to drop by.", "随时来玩。", "s"),
        ("I'm looking forward to it.", "我很期待。", "s"),
        ("Don't be a stranger.", "常联系啊。", "s"),
        ("Let's call it a night.", "今晚就到这儿吧。", "s"),
    ],
    "约会恋爱": [
        ("Can I buy you a drink?", "我能请你喝一杯吗？", "s"),
        ("Is this seat taken?", "这位子有人吗？", "s"),
        ("Do you come here often?", "你常来这儿吗？", "s"),
        ("Would you like to go out sometime?", "改天一起出去玩好吗？", "s"),
        ("Can I get your number?", "能给我你的电话吗？", "s"),
        ("I had a really nice time tonight.", "今晚我很开心。", "s"),
        ("I like spending time with you.", "我喜欢和你在一起。", "s"),
        ("You look amazing tonight.", "你今晚真好看。", "s"),
        ("I've been thinking about you.", "我一直在想你。", "s"),
        ("Can I walk you home?", "我能送你回家吗？", "s"),
        ("Would you like to have dinner with me?", "愿意和我共进晚餐吗？", "s"),
        ("I really enjoy your company.", "和你在一起很愉快。", "s"),
        ("We have a lot in common.", "我们有很多共同点。", "s"),
        ("Are you seeing anyone?", "你有在和谁约会吗？", "s"),
        ("I'm single.", "我是单身。", "s"),
        ("Let's take it slow.", "我们慢慢来。", "s"),
        ("I think we should just be friends.", "我觉得我们还是做朋友吧。", "s"),
        ("It's not you, it's me.", "不是你的问题，是我。", "s"),
        ("I'm not ready for a relationship.", "我还没准备好谈恋爱。", "s"),
        ("Do you want to be my girlfriend?", "你愿意做我女朋友吗？", "s"),
        ("I really like you.", "我很喜欢你。", "s"),
        ("I miss you.", "我想你。", "s"),
        ("Text me when you get home.", "到家给我发消息。", "s"),
        ("Let's hang out again soon.", "我们尽快再约。", "s"),
        ("I had butterflies.", "我心里小鹿乱撞。", "s"),
        ("We hit it off.", "我们一见如故。", "s"),
        ("Can I see you again?", "我能再见你吗？", "s"),
        ("You mean a lot to me.", "你对我很重要。", "s"),
    ],
    "租房居住": [
        ("I'm looking for an apartment.", "我在找公寓。", "s"),
        ("How much is the rent?", "房租多少？", "s"),
        ("Are utilities included?", "包水电吗？", "s"),
        ("Is there a deposit?", "要押金吗？", "s"),
        ("How long is the lease?", "租期多长？", "s"),
        ("Can I see the place?", "我能看下房子吗？", "s"),
        ("Is it furnished?", "是带家具的吗？", "s"),
        ("Are pets allowed?", "可以养宠物吗？", "s"),
        ("When can I move in?", "我什么时候能搬进来？", "s"),
        ("Is the neighborhood safe?", "这个小区安全吗？", "s"),
        ("Is it close to the subway?", "离地铁近吗？", "s"),
        ("The faucet is leaking.", "水龙头漏水。", "s"),
        ("The heater is broken.", "暖气坏了。", "s"),
        ("Could you fix the door?", "能修下门吗？", "s"),
        ("I'd like to renew the lease.", "我想续租。", "s"),
        ("I'm moving out next month.", "我下个月搬走。", "s"),
        ("Can I get my deposit back?", "我能拿回押金吗？", "s"),
        ("Who pays for repairs?", "维修费谁出？", "s"),
        ("Is there parking?", "有停车位吗？", "s"),
        ("Could you turn down the music?", "能把音乐关小点吗？", "s"),
        ("My neighbors are really loud.", "我邻居很吵。", "s"),
        ("When is the rent due?", "房租什么时候交？", "s"),
        ("a one-bedroom apartment", "一居室公寓", "c"),
        ("The lease is up next month.", "下个月租约到期。", "s"),
        ("Can I sublet the room?", "我能转租这个房间吗？", "s"),
        ("Is there a washing machine?", "有洗衣机吗？", "s"),
        ("The Wi-Fi is included.", "网络包含在内。", "s"),
        ("Could you call a plumber?", "能叫个水管工吗？", "s"),
    ],
    "校园学习": [
        ("What's our homework?", "我们的作业是什么？", "s"),
        ("When is the assignment due?", "作业什么时候交？", "s"),
        ("Could you explain that again?", "能再讲一遍吗？", "s"),
        ("I don't quite get it.", "我不太懂。", "s"),
        ("Could you give an example?", "能举个例子吗？", "s"),
        ("I have a question.", "我有个问题。", "s"),
        ("Can I ask a question?", "我能问个问题吗？", "s"),
        ("How do you spell that?", "那个怎么拼？", "s"),
        ("Could you slow down a bit?", "能讲慢点吗？", "s"),
        ("I missed the last class.", "我上节课缺席了。", "s"),
        ("Could I borrow your notes?", "能借我看下笔记吗？", "s"),
        ("Is this going to be on the exam?", "考试会考这个吗？", "s"),
        ("When's the deadline?", "截止日期是什么时候？", "s"),
        ("Could I get an extension?", "能延期吗？", "s"),
        ("I'm cramming for the exam.", "我在临时抱佛脚备考。", "s"),
        ("I aced the test.", "我考试考得很好。", "s"),
        ("I failed the quiz.", "我小测没及格。", "s"),
        ("Let's study together.", "我们一起学习吧。", "s"),
        ("Let's form a study group.", "我们组个学习小组吧。", "s"),
        ("What's the main idea?", "中心思想是什么？", "s"),
        ("Could you check my work?", "能帮我检查下吗？", "s"),
        ("I need to hand in my paper.", "我得交论文了。", "s"),
        ("Can I sit in on this class?", "我能旁听这门课吗？", "s"),
        ("Take notes.", "记笔记。", "c"),
        ("Pay attention, please.", "请注意听。", "s"),
        ("Raise your hand.", "举手。", "c"),
        ("Time's up, pencils down.", "时间到，停笔。", "s"),
        ("Could you go over that one more time?", "能再过一遍吗？", "s"),
        ("I'm majoring in computer science.", "我主修计算机。", "s"),
        ("What's the reading for next week?", "下周要读什么？", "s"),
        ("Don't forget to cite your sources.", "别忘了标注出处。", "s"),
        ("Let's review for the final.", "我们复习期末考吧。", "s"),
    ],
    "闲聊天气": [
        ("Nice weather today, isn't it?", "今天天气不错，是吧？", "s"),
        ("It's a beautiful day.", "今天天气真好。", "s"),
        ("It's freezing out there.", "外面冷死了。", "s"),
        ("It's boiling hot.", "热得要命。", "s"),
        ("It looks like rain.", "看起来要下雨了。", "s"),
        ("Don't forget your umbrella.", "别忘了带伞。", "s"),
        ("It's pouring.", "下大雨了。", "s"),
        ("The forecast says it'll be sunny.", "预报说会是晴天。", "s"),
        ("It's so humid today.", "今天好潮湿。", "s"),
        ("It's getting colder.", "天越来越冷了。", "s"),
        ("What's the weather like there?", "那边天气怎么样？", "s"),
        ("It's a bit chilly.", "有点凉。", "s"),
        ("The sun is finally out.", "终于出太阳了。", "s"),
        ("It's windy today.", "今天风很大。", "s"),
        ("I hope it clears up.", "希望天能放晴。", "s"),
        ("Stay warm!", "注意保暖！", "s"),
        ("It's snowing!", "下雪了！", "s"),
        ("What a gloomy day.", "天气真阴沉。", "s"),
        ("It's supposed to warm up tomorrow.", "明天应该会暖和些。", "s"),
        ("Perfect weather for a walk.", "正适合散步。", "s"),
        ("It's drizzling.", "下着毛毛雨。", "s"),
        ("There's not a cloud in the sky.", "万里无云。", "s"),
        ("It's foggy this morning.", "今早有雾。", "s"),
        ("The heat is unbearable.", "热得受不了。", "s"),
        ("Bundle up, it's cold.", "多穿点，冷。", "s"),
    ],
    "时间日期": [
        ("What time is it?", "几点了？", "s"),
        ("Do you have the time?", "请问几点了？", "s"),
        ("It's half past three.", "三点半。", "s"),
        ("It's a quarter to nine.", "差一刻九点。", "s"),
        ("It's ten past five.", "五点十分。", "s"),
        ("What time do you open?", "你们几点开门？", "s"),
        ("What time do you close?", "你们几点关门？", "s"),
        ("What's the date today?", "今天几号？", "s"),
        ("What day is it today?", "今天星期几？", "s"),
        ("Let's meet at noon.", "我们中午见。", "s"),
        ("I'm running late.", "我要迟到了。", "s"),
        ("Sorry I'm late.", "抱歉我迟到了。", "s"),
        ("Take your time.", "慢慢来。", "s"),
        ("We're running out of time.", "我们时间不多了。", "s"),
        ("Are you free at three?", "你三点有空吗？", "s"),
        ("Let's push it back an hour.", "我们往后推一小时。", "s"),
        ("Let's move it up an hour.", "我们提前一小时。", "s"),
        ("It's almost time.", "快到时间了。", "s"),
        ("on time", "准时", "c"),
        ("ahead of schedule", "提前", "c"),
        ("the day after tomorrow", "后天", "c"),
        ("the day before yesterday", "前天", "c"),
        ("Let's do it first thing tomorrow.", "明天一早就做。", "s"),
        ("See you in ten minutes.", "十分钟后见。", "s"),
        ("Can we meet earlier?", "我们能早点见吗？", "s"),
        ("It won't take long.", "用不了多久。", "s"),
        ("I'll be there in five.", "我五分钟就到。", "s"),
        ("Let's call it around eight.", "就约八点左右吧。", "s"),
        ("How about later this week?", "这周晚些时候怎么样？", "s"),
        ("It's about time.", "也该是时候了。", "s"),
    ],
    "价格数字": [
        ("How much do I owe you?", "我该付你多少？", "s"),
        ("It costs ten dollars.", "这个十美元。", "s"),
        ("That's a bit pricey.", "有点贵。", "s"),
        ("That's a bargain.", "这很便宜。", "s"),
        ("Can I pay in cash?", "我能付现金吗？", "s"),
        ("Do you accept mobile payment?", "你们收手机支付吗？", "s"),
        ("Could I get a receipt?", "能给我张收据吗？", "s"),
        ("Keep the change.", "不用找了。", "s"),
        ("Is the tip included?", "含小费吗？", "s"),
        ("How much is it altogether?", "一共多少钱？", "s"),
        ("Could you break a hundred?", "能换开一百块吗？", "s"),
        ("It's on sale for half price.", "现在半价。", "s"),
        ("buy one, get one free", "买一送一", "c"),
        ("Can you give me a better price?", "能给个更好的价吗？", "s"),
        ("That's over my budget.", "超出我的预算了。", "s"),
        ("It's twenty percent off.", "打八折。", "s"),
        ("Let's split it evenly.", "我们平摊吧。", "s"),
        ("You owe me twenty bucks.", "你欠我二十块。", "s"),
        ("Round it up to fifty.", "凑个整五十。", "s"),
        ("How much per person?", "每人多少钱？", "s"),
        ("That comes to forty dollars.", "总共四十美元。", "s"),
        ("Do you have change?", "你有零钱吗？", "s"),
        ("Can I pay in installments?", "我能分期付吗？", "s"),
        ("It's worth every penny.", "物有所值。", "s"),
        ("That's a rip-off.", "这是宰人。", "s"),
        ("Prices have gone up.", "价格涨了。", "s"),
        ("It's within my budget.", "在我预算之内。", "s"),
    ],
    "银行邮局": [
        ("I'd like to open an account.", "我想开个账户。", "s"),
        ("I'd like to deposit some money.", "我想存点钱。", "s"),
        ("I'd like to withdraw cash.", "我想取现金。", "s"),
        ("Where's the nearest ATM?", "最近的取款机在哪？", "s"),
        ("I'd like to transfer money.", "我想转账。", "s"),
        ("What's the exchange rate?", "汇率是多少？", "s"),
        ("I'd like to exchange dollars for yuan.", "我想把美元换成人民币。", "s"),
        ("My card was declined.", "我的卡被拒了。", "s"),
        ("I forgot my PIN.", "我忘了密码。", "s"),
        ("I'd like to report a lost card.", "我想挂失银行卡。", "s"),
        ("Is there a service fee?", "有手续费吗？", "s"),
        ("Could you check my balance?", "能查下我的余额吗？", "s"),
        ("I'd like to apply for a credit card.", "我想申请信用卡。", "s"),
        ("How do I activate my card?", "怎么激活我的卡？", "s"),
        ("I'd like to send this package.", "我想寄这个包裹。", "s"),
        ("How much is postage?", "邮费多少？", "s"),
        ("How long will it take to arrive?", "多久能到？", "s"),
        ("I'd like to send it by express.", "我想寄快递。", "s"),
        ("Could I get tracking?", "能给我个单号追踪吗？", "s"),
        ("Please fill out this form.", "请填一下这张表。", "s"),
        ("Sign here, please.", "请在这里签名。", "s"),
        ("Do you have ID with you?", "你带身份证件了吗？", "s"),
        ("I'd like to set up online banking.", "我想开通网上银行。", "s"),
        ("Could you waive the fee?", "能免手续费吗？", "s"),
        ("Is there a minimum balance?", "有最低存款要求吗？", "s"),
        ("I need to update my address.", "我需要更新地址。", "s"),
        ("Take a number and wait.", "取个号等候。", "s"),
        ("My account has been frozen.", "我的账户被冻结了。", "s"),
        ("Could I get smaller bills?", "能换些小面额的吗？", "s"),
        ("Is the package insured?", "包裹有保价吗？", "s"),
        ("It's fragile, please handle with care.", "易碎品，请小心轻放。", "s"),
    ],
    "网络科技": [
        ("The Wi-Fi isn't working.", "Wi-Fi 连不上。", "s"),
        ("What's the Wi-Fi password?", "Wi-Fi 密码是多少？", "s"),
        ("My phone is dead.", "我手机没电了。", "s"),
        ("Can I charge my phone here?", "我能在这儿充电吗？", "s"),
        ("The connection is slow.", "网速很慢。", "s"),
        ("Let me google it.", "我搜一下。", "s"),
        ("Could you send me the link?", "能把链接发我吗？", "s"),
        ("I'll text you the details.", "我把细节发短信给你。", "s"),
        ("Add me on WeChat.", "加我微信。", "s"),
        ("Let's video call.", "我们视频通话吧。", "s"),
        ("The app keeps crashing.", "这个应用一直闪退。", "s"),
        ("Try restarting it.", "试试重启。", "s"),
        ("Have you tried turning it off and on?", "你试过关机重开吗？", "s"),
        ("Did you get my email?", "你收到我的邮件了吗？", "s"),
        ("It went to spam.", "进垃圾邮件了。", "s"),
        ("My computer froze.", "我电脑卡死了。", "s"),
        ("Could you share the file?", "能分享下文件吗？", "s"),
        ("I'll back it up.", "我会备份。", "s"),
        ("Scan the QR code.", "扫一下二维码。", "s"),
        ("I ran out of storage.", "我存储满了。", "s"),
        ("Update the app first.", "先更新应用。", "s"),
        ("I forgot my password.", "我忘记密码了。", "s"),
        ("Could you reset my password?", "能帮我重置密码吗？", "s"),
        ("The screen froze.", "屏幕卡住了。", "s"),
        ("It's loading.", "正在加载。", "s"),
        ("My account got hacked.", "我账号被盗了。", "s"),
        ("Turn on airplane mode.", "开飞行模式。", "s"),
        ("Could you screenshot it?", "能截个图吗？", "s"),
        ("The signal is weak here.", "这里信号弱。", "s"),
        ("Log in with your email.", "用邮箱登录。", "s"),
        ("Clear your cache.", "清一下缓存。", "s"),
        ("It's compatible with both systems.", "两个系统都兼容。", "s"),
    ],
    "客服售后": [
        ("How can I help you?", "有什么可以帮您？", "s"),
        ("I'd like to file a complaint.", "我想投诉。", "s"),
        ("My order hasn't arrived yet.", "我的订单还没到。", "s"),
        ("The item arrived damaged.", "商品到货时是坏的。", "s"),
        ("I received the wrong item.", "我收到了错的商品。", "s"),
        ("I'd like to track my order.", "我想查物流。", "s"),
        ("What's your order number?", "您的订单号是多少？", "s"),
        ("Could you look into it?", "您能帮我查一下吗？", "s"),
        ("I'd like a refund.", "我想退款。", "s"),
        ("How long does a refund take?", "退款要多久？", "s"),
        ("Can you waive the shipping fee?", "能免运费吗？", "s"),
        ("Is it still under warranty?", "还在保修期内吗？", "s"),
        ("Could you transfer me to a supervisor?", "能帮我转接主管吗？", "s"),
        ("Could you escalate this?", "能帮我升级处理吗？", "s"),
        ("I've been on hold for ages.", "我等了好久了。", "s"),
        ("Let me look into that for you.", "我帮您查一下。", "s"),
        ("I apologize for the inconvenience.", "抱歉给您带来不便。", "s"),
        ("We'll send a replacement.", "我们会寄个替换品。", "s"),
        ("Could I get a reference number?", "能给我个处理编号吗？", "s"),
        ("When will this be resolved?", "什么时候能解决？", "s"),
        ("Is there anything else I can help with?", "还有别的需要帮忙吗？", "s"),
        ("Thank you for your patience.", "感谢您的耐心。", "s"),
        ("I'll get back to you within 24 hours.", "我会在 24 小时内回复您。", "s"),
        ("Could you confirm your details?", "能确认下您的信息吗？", "s"),
        ("Your request has been processed.", "您的请求已处理。", "s"),
        ("I'd like to cancel my subscription.", "我想取消订阅。", "s"),
        ("Could you resend the invoice?", "能重发下发票吗？", "s"),
    ],
    "兴趣闲聊": [
        ("What do you do for fun?", "你平时有什么爱好？", "s"),
        ("What are you into?", "你喜欢什么？", "s"),
        ("I'm really into photography.", "我很喜欢摄影。", "s"),
        ("I'm a big fan of jazz.", "我很喜欢爵士乐。", "s"),
        ("Have you seen this movie?", "你看过这部电影吗？", "s"),
        ("What kind of music do you like?", "你喜欢什么音乐？", "s"),
        ("Do you play any sports?", "你做什么运动吗？", "s"),
        ("I work out three times a week.", "我一周健身三次。", "s"),
        ("I'm trying to read more.", "我在努力多读书。", "s"),
        ("What are you watching these days?", "你最近在追什么剧？", "s"),
        ("I can't get into it.", "我看不进去。", "s"),
        ("It's not really my thing.", "这不太合我口味。", "s"),
        ("I'm hooked on this show.", "我迷上这部剧了。", "s"),
        ("Have you been anywhere nice lately?", "最近去哪儿玩了吗？", "s"),
        ("I love trying new restaurants.", "我喜欢尝试新餐厅。", "s"),
        ("Do you have any plans for the holiday?", "假期有安排吗？", "s"),
        ("I picked up a new hobby.", "我培养了个新爱好。", "s"),
        ("How was your trip?", "你旅行怎么样？", "s"),
        ("Tell me more about it.", "再跟我说说。", "s"),
        ("That sounds fun.", "听起来很有趣。", "s"),
        ("I've always wanted to try that.", "我一直想试试。", "s"),
        ("We have similar tastes.", "我们口味相近。", "s"),
        ("What got you into it?", "你怎么喜欢上这个的？", "s"),
        ("I'm learning to play the guitar.", "我在学吉他。", "s"),
        ("Let's plan a trip together.", "我们一起计划次旅行吧。", "s"),
    ],
    "邮件书面": [
        ("I hope this email finds you well.", "顺祝商祺（邮件开头问候）。", "s"),
        ("I'm writing to follow up on...", "我写信是想跟进……", "c"),
        ("I'm writing regarding...", "我就……一事写信。", "c"),
        ("Thank you for your prompt reply.", "感谢您的及时回复。", "s"),
        ("Please find attached...", "请见附件……", "c"),
        ("As discussed,", "如先前所讨论，", "c"),
        ("Please let me know if you have any questions.", "如有疑问请告知。", "s"),
        ("I look forward to your reply.", "期待您的回复。", "s"),
        ("Sorry for the late reply.", "抱歉回复晚了。", "s"),
        ("Just a gentle reminder.", "温馨提醒一下。", "s"),
        ("Could you confirm by end of day?", "能在今天内确认吗？", "s"),
        ("Please don't hesitate to reach out.", "有需要请随时联系。", "s"),
        ("I'd appreciate your feedback.", "期待您的反馈。", "s"),
        ("Apologies for any confusion.", "如有误解还请见谅。", "s"),
        ("Let me know your availability.", "请告知您方便的时间。", "s"),
        ("I'll keep you in the loop.", "我会随时同步给您。", "s"),
        ("Thanks in advance.", "提前致谢。", "s"),
        ("Looking forward to hearing from you.", "期待您的回音。", "s"),
        ("Best regards,", "此致敬礼，", "c"),
        ("Feel free to reach out anytime.", "随时欢迎联系。", "s"),
        ("Please see below.", "详见下文。", "c"),
        ("I'll circle back next week.", "下周我再跟进。", "s"),
        ("Could you cc me on that?", "能把我抄送进去吗？", "s"),
        ("Per our conversation,", "根据我们的沟通，", "c"),
        ("I wanted to touch base.", "我想跟你确认一下。", "s"),
        ("Noted, thanks.", "收到，谢谢。", "s"),
    ],
    "谈判商务": [
        ("Let's talk about the terms.", "我们谈谈条款吧。", "s"),
        ("What's your best offer?", "你能给的最优价是多少？", "s"),
        ("That's a bit steep.", "这价格有点高。", "s"),
        ("Can we meet in the middle?", "我们能各让一步吗？", "s"),
        ("Let's find a win-win.", "我们找个双赢方案。", "s"),
        ("I'll need to run this by my boss.", "我得跟我老板汇报一下。", "s"),
        ("Let me think it over.", "让我考虑一下。", "s"),
        ("That works for us.", "这个我们可以接受。", "s"),
        ("It's a deal.", "成交。", "s"),
        ("Let's put it in writing.", "我们书面确认吧。", "s"),
        ("We have a tight budget.", "我们预算很紧。", "s"),
        ("Could you throw in free shipping?", "能再送个免运费吗？", "s"),
        ("That's our bottom line.", "这是我们的底线。", "s"),
        ("Let's table the price for now.", "价格的事先放一放。", "s"),
        ("I'm open to negotiation.", "价格可以商量。", "s"),
        ("Let's circle back on the details.", "细节我们再谈。", "s"),
        ("We're on the same page.", "我们达成共识了。", "s"),
        ("Can we get a bulk discount?", "批量采购有折扣吗？", "s"),
        ("What's the lead time?", "交货周期多长？", "s"),
        ("Let's sign the contract.", "我们签合同吧。", "s"),
        ("Subject to approval,", "需经批准后，", "c"),
        ("Let's set up a follow-up call.", "我们再约个电话沟通。", "s"),
        ("I'll send over a proposal.", "我会发份方案过来。", "s"),
        ("Let's not rush this.", "这事我们别着急。", "s"),
        ("That's outside our scope.", "那超出我们的范围了。", "s"),
        ("Let's keep our options open.", "我们多留几个选择。", "s"),
    ],
    "紧急求助": [
        ("Help!", "救命！", "s"),
        ("Call an ambulance!", "叫救护车！", "s"),
        ("Call the police!", "报警！", "s"),
        ("It's an emergency.", "这是紧急情况。", "s"),
        ("Is anyone hurt?", "有人受伤吗？", "s"),
        ("Are you okay?", "你还好吗？", "s"),
        ("I need help right now.", "我现在就需要帮助。", "s"),
        ("There's been an accident.", "出事故了。", "s"),
        ("Where does it hurt?", "哪里疼？", "s"),
        ("Stay calm.", "保持冷静。", "s"),
        ("Watch out!", "小心！", "s"),
        ("Look out!", "当心！", "s"),
        ("I lost my passport.", "我护照丢了。", "s"),
        ("I lost my wallet.", "我钱包丢了。", "s"),
        ("My bag was stolen.", "我的包被偷了。", "s"),
        ("Could you call for help?", "你能叫人帮忙吗？", "s"),
        ("I'm lost and my phone died.", "我迷路了，手机还没电。", "s"),
        ("Where's the nearest hospital?", "最近的医院在哪？", "s"),
        ("Is there a doctor here?", "这里有医生吗？", "s"),
        ("Please hurry.", "请快点。", "s"),
        ("I think I'm having an allergic reaction.", "我好像过敏了。", "s"),
        ("Don't move him.", "别移动他。", "s"),
        ("Step back, please.", "请退后。", "s"),
        ("Fire! Get out!", "着火了！快出去！", "s"),
    ],
    "表达观点": [
        ("In my opinion,", "在我看来，", "c"),
        ("If you ask me,", "要我说，", "c"),
        ("The way I see it,", "在我看来，", "c"),
        ("I think so too.", "我也这么认为。", "s"),
        ("I see your point, but...", "我明白你的意思，但是……", "s"),
        ("That makes sense.", "有道理。", "s"),
        ("Fair enough.", "有道理 / 行吧。", "s"),
        ("I couldn't agree more.", "我完全同意。", "s"),
        ("I beg to differ.", "恕我不能苟同。", "s"),
        ("I'm not so sure about that.", "这点我不太确定。", "s"),
        ("It depends.", "看情况。", "s"),
        ("to be honest", "说实话", "c"),
        ("to be fair", "平心而论", "c"),
        ("Let me put it this way.", "我换个说法。", "s"),
        ("on the other hand", "另一方面", "c"),
        ("That's a good point.", "说得好。", "s"),
        ("I get where you're coming from.", "我理解你的立场。", "s"),
        ("Let's agree to disagree.", "我们保留各自意见吧。", "s"),
        ("What's your take on this?", "你怎么看？", "s"),
        ("It's hard to say.", "很难说。", "s"),
        ("I'd argue that...", "我认为……", "c"),
        ("Personally, I'd say...", "就我个人而言……", "c"),
        ("That's debatable.", "这有待商榷。", "s"),
        ("Exactly!", "正是如此！", "s"),
        ("Absolutely.", "完全正确。", "s"),
        ("Not necessarily.", "不一定。", "s"),
        ("That's exactly my point.", "这正是我的意思。", "s"),
        ("I have mixed feelings about it.", "我对此感受复杂。", "s"),
        ("Correct me if I'm wrong.", "如果我说错请纠正。", "s"),
        ("From my perspective,", "从我的角度看，", "c"),
        ("All things considered,", "综合来看，", "c"),
        ("That's beside the point.", "那不是重点。", "s"),
    ],
    "情绪感受": [
        ("I'm thrilled about it.", "我对此很激动。", "s"),
        ("I'm so excited!", "我太兴奋了！", "s"),
        ("I'm over the moon.", "我高兴极了。", "s"),
        ("I'm a bit nervous.", "我有点紧张。", "s"),
        ("That's such a relief.", "真是松了口气。", "s"),
        ("I'm worried about it.", "我很担心。", "s"),
        ("I'm fed up with this.", "我受够了。", "s"),
        ("It drives me crazy.", "这让我抓狂。", "s"),
        ("I'm so frustrated.", "我太沮丧了。", "s"),
        ("I feel under the weather.", "我感觉不舒服。", "s"),
        ("It's no big deal.", "没什么大不了。", "s"),
        ("I'm in a good mood.", "我心情不错。", "s"),
        ("I'm exhausted.", "我累坏了。", "s"),
        ("I can't believe it.", "我简直不敢相信。", "s"),
        ("That's a shame.", "真遗憾。", "s"),
        ("I'm proud of you.", "我为你骄傲。", "s"),
        ("Cheer up!", "振作点！", "s"),
        ("Don't worry about it.", "别担心。", "s"),
        ("I feel much better now.", "我现在好多了。", "s"),
        ("I'm touched.", "我很感动。", "s"),
        ("What a relief!", "太让人安心了！", "s"),
        ("I'm scared.", "我害怕。", "s"),
        ("It broke my heart.", "我很伤心。", "s"),
        ("I'm grateful for that.", "我很感激。", "s"),
        ("I'm on top of the world.", "我感觉好极了。", "s"),
        ("I'm stressed out.", "我压力很大。", "s"),
        ("I feel left out.", "我感觉被冷落了。", "s"),
        ("That made my day.", "今天因此变美好了。", "s"),
        ("I'm bored to death.", "我无聊死了。", "s"),
        ("I'm speechless.", "我无言以对。", "s"),
        ("Calm down.", "冷静点。", "s"),
        ("Take it easy.", "放轻松。", "s"),
    ],
    "请求帮助": [
        ("Could you give me a hand?", "你能帮我个忙吗？", "s"),
        ("Do you mind helping me?", "你介意帮我一下吗？", "s"),
        ("Could you do me a favor?", "能帮我个忙吗？", "s"),
        ("Can you help me out?", "你能帮帮我吗？", "s"),
        ("I was wondering if you could...", "不知你能否……", "c"),
        ("Would it be possible to...?", "有没有可能……？", "c"),
        ("Let me give you a hand.", "我来帮你。", "s"),
        ("No problem at all.", "完全没问题。", "s"),
        ("Sure, what do you need?", "当然，你需要什么？", "s"),
        ("Sorry to bother you.", "抱歉打扰你。", "s"),
        ("Could you explain that again?", "你能再解释一遍吗？", "s"),
        ("Could you say that again?", "能再说一遍吗？", "s"),
        ("Could you speak more slowly?", "能说慢点吗？", "s"),
        ("What does this mean?", "这是什么意思？", "s"),
        ("How do you say this in English?", "这个用英语怎么说？", "s"),
        ("Could you show me how?", "能教我怎么做吗？", "s"),
        ("Can you pass me the salt?", "能把盐递给我吗？", "s"),
        ("Could you hold the door?", "能帮我扶下门吗？", "s"),
        ("Thanks for your help.", "谢谢你的帮忙。", "s"),
        ("I appreciate it.", "我很感激。", "s"),
        ("Let me know if you need anything.", "需要什么就告诉我。", "s"),
        ("Could you keep an eye on my bag?", "能帮我看下包吗？", "s"),
        ("Mind giving me a lift?", "能捎我一程吗？", "s"),
        ("Could you point me in the right direction?", "能给我指个方向吗？", "s"),
        ("I could use some help.", "我需要点帮助。", "s"),
        ("Would you mind?", "你介意吗？", "s"),
        ("Be my guest.", "请便。", "s"),
        ("I'm happy to help.", "我很乐意帮忙。", "s"),
        ("Could you lend me a pen?", "能借我支笔吗？", "s"),
        ("Can you cover for me?", "你能帮我顶一下吗？", "s"),
    ],
    "道歉感谢": [
        ("Thank you so much.", "非常感谢。", "s"),
        ("I really appreciate it.", "我非常感激。", "s"),
        ("Thanks a lot for everything.", "万分感谢。", "s"),
        ("I owe you one.", "我欠你一个人情。", "s"),
        ("You're a lifesaver.", "你真是帮了大忙。", "s"),
        ("I can't thank you enough.", "感激不尽。", "s"),
        ("It's very kind of you.", "你真好心。", "s"),
        ("You shouldn't have.", "你太客气了。", "s"),
        ("My apologies for the delay.", "抱歉耽搁了。", "s"),
        ("I'm so sorry.", "我很抱歉。", "s"),
        ("It was my fault.", "是我的错。", "s"),
        ("I didn't mean to.", "我不是故意的。", "s"),
        ("Please forgive me.", "请原谅我。", "s"),
        ("I apologize for the inconvenience.", "抱歉给您带来不便。", "s"),
        ("It won't happen again.", "不会再发生了。", "s"),
        ("Don't mention it.", "别客气。", "s"),
        ("No worries.", "没关系。", "s"),
        ("That's all right.", "没事。", "s"),
        ("It's okay, don't worry.", "没事，别担心。", "s"),
        ("You're welcome.", "不客气。", "s"),
        ("Anytime.", "随时乐意效劳。", "s"),
        ("My bad.", "我的错。", "s"),
        ("No harm done.", "没造成什么损失。", "s"),
        ("Apology accepted.", "我接受你的道歉。", "s"),
        ("I owe you an apology.", "我该向你道歉。", "s"),
        ("Please accept my apologies.", "请接受我的歉意。", "s"),
        ("Thanks for understanding.", "谢谢你的理解。", "s"),
        ("I appreciate your patience.", "谢谢你的耐心。", "s"),
        ("It means a lot to me.", "这对我意义重大。", "s"),
        ("Forget about it.", "别放在心上。", "s"),
    ],
    "投诉抱怨": [
        ("I'd like to make a complaint.", "我想投诉。", "s"),
        ("This isn't what I ordered.", "这不是我点的。", "s"),
        ("There's a problem with my order.", "我的订单有问题。", "s"),
        ("It doesn't work.", "它用不了。", "s"),
        ("It's broken.", "它坏了。", "s"),
        ("I'd like a refund.", "我想退款。", "s"),
        ("I'd like to speak to the manager.", "我想找经理。", "s"),
        ("This is unacceptable.", "这无法接受。", "s"),
        ("I've been waiting for an hour.", "我已经等了一个小时。", "s"),
        ("You charged me twice.", "你们多收了我一次钱。", "s"),
        ("The bill is wrong.", "账单有误。", "s"),
        ("I was overcharged.", "我被多收钱了。", "s"),
        ("Could you fix this?", "能解决一下吗？", "s"),
        ("I'm not satisfied with this.", "我对此不满意。", "s"),
        ("This is not good enough.", "这不够好。", "s"),
        ("Could I get a replacement?", "能给我换一个吗？", "s"),
        ("I expect a full refund.", "我要求全额退款。", "s"),
        ("Who's responsible for this?", "这是谁负责的？", "s"),
        ("I demand an explanation.", "我要一个解释。", "s"),
        ("This is the last straw.", "我忍无可忍了。", "s"),
        ("I'm very disappointed.", "我非常失望。", "s"),
        ("The service was terrible.", "服务太差了。", "s"),
        ("I want to cancel my order.", "我要取消订单。", "s"),
        ("This is a waste of my time.", "这是在浪费我的时间。", "s"),
        ("Can you make this right?", "你们能补救一下吗？", "s"),
        ("I won't be coming back.", "我不会再来了。", "s"),
    ],
}

KIND_LABEL = {"s": "短句", "c": "词组"}


def build():
    out = []
    for scenario, items in SCENARIOS.items():
        for english, chinese, kind in items:
            out.append({
                "english": english.strip(),
                "phonetic": "",
                "chinese": chinese.strip(),
                "example": "",
                "category": scenario,
                "part_of_speech": KIND_LABEL[kind],
                "theme": scenario,
                "parent_category": "短语",
                "child_category": KIND_LABEL[kind],
            })
    return out


def main():
    data = build()
    OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {len(data)} phrases across {len(SCENARIOS)} scenarios -> {OUT.name}")
    for s, items in SCENARIOS.items():
        print(f"  {len(items):>3}  {s}")


if __name__ == "__main__":
    main()
