import sqlite3

def expand_to_5000_batch9():
    conn = sqlite3.connect('../words.db')
    cursor = conn.cursor()
    
    new_words = [
        # 科学研究类
        {"english": "algorithm", "phonetic": "/ˈælɡərɪðəm/", "chinese": "n. 算法", "example": "Learn algorithm.", "category": "科学研究"},
        {"english": "analysis", "phonetic": "/əˈnæləsɪs/", "chinese": "n. 分析", "example": "Data analysis.", "category": "科学研究"},
        {"english": "assumption", "phonetic": "/əˈsʌmpʃn/", "chinese": "n. 假设", "example": "Make assumption.", "category": "科学研究"},
        {"english": "calculation", "phonetic": "/ˌkælkjuˈleɪʃn/", "chinese": "n. 计算", "example": "Do calculation.", "category": "科学研究"},
        {"english": "classification", "phonetic": "/ˌklæsɪfɪˈkeɪʃn/", "chinese": "n. 分类", "example": "Classification system.", "category": "科学研究"},
        {"english": "conclusion", "phonetic": "/kənˈkluːʒn/", "chinese": "n. 结论", "example": "Draw conclusion.", "category": "科学研究"},
        {"english": "correlation", "phonetic": "/ˌkɔːrəˈleɪʃn/", "chinese": "n. 相关性", "example": "Find correlation.", "category": "科学研究"},
        {"english": "demonstration", "phonetic": "/ˌdemənˈstreɪʃn/", "chinese": "n. 演示", "example": "Give demonstration.", "category": "科学研究"},
        {"english": "derivation", "phonetic": "/ˌderɪˈveɪʃn/", "chinese": "n. 推导", "example": "Derivation process.", "category": "科学研究"},
        {"english": "determination", "phonetic": "/dɪˌtɜːrmɪˈneɪʃn/", "chinese": "n. 测定", "example": "Determination method.", "category": "科学研究"},
        {"english": "diagnosis", "phonetic": "/ˌdaɪəɡˈnoʊsɪs/", "chinese": "n. 诊断", "example": "Make diagnosis.", "category": "科学研究"},
        {"english": "discovery", "phonetic": "/dɪˈskʌvəri/", "chinese": "n. 发现", "example": "Great discovery.", "category": "科学研究"},
        {"english": "evaluation", "phonetic": "/ɪˌvæljʊˈeɪʃn/", "chinese": "n. 评估", "example": "Evaluation report.", "category": "科学研究"},
        {"english": "examination", "phonetic": "/ɪɡˌzæmɪˈneɪʃn/", "chinese": "n. 检查", "example": "Medical examination.", "category": "科学研究"},
        {"english": "experiment", "phonetic": "/ɪkˈsperɪmənt/", "chinese": "n. 实验", "example": "Do experiment.", "category": "科学研究"},
        {"english": "explanation", "phonetic": "/ˌekspləˈneɪʃn/", "chinese": "n. 解释", "example": "Give explanation.", "category": "科学研究"},
        {"english": "exploration", "phonetic": "/ˌekspləˈreɪʃn/", "chinese": "n. 探索", "example": "Space exploration.", "category": "科学研究"},
        {"english": "formulation", "phonetic": "/ˌfɔːrmjʊˈleɪʃn/", "chinese": "n. 制定", "example": "Formulation plan.", "category": "科学研究"},
        {"english": "identification", "phonetic": "/aɪˌdentɪfɪˈkeɪʃn/", "chinese": "n. 识别", "example": "Identification card.", "category": "科学研究"},
        {"english": "implementation", "phonetic": "/ˌɪmplɪmenˈteɪʃn/", "chinese": "n. 实施", "example": "Implementation phase.", "category": "科学研究"},
        {"english": "investigation", "phonetic": "/ɪnˌvestɪˈɡeɪʃn/", "chinese": "n. 调查", "example": "Investigation report.", "category": "科学研究"},
        {"english": "justification", "phonetic": "/ˌdʒʌstɪfɪˈkeɪʃn/", "chinese": "n. 理由", "example": "Provide justification.", "category": "科学研究"},
        {"english": "measurement", "phonetic": "/ˈmeʒərmənt/", "chinese": "n. 测量", "example": "Take measurement.", "category": "科学研究"},
        {"english": "methodology", "phonetic": "/ˌmeθəˈdɑːlədʒi/", "chinese": "n. 方法论", "example": "Research methodology.", "category": "科学研究"},
        {"english": "observation", "phonetic": "/ˌɑːbzərˈveɪʃn/", "chinese": "n. 观察", "example": "Make observation.", "category": "科学研究"},
        {"english": "optimization", "phonetic": "/ˌɑːptɪmɪˈzeɪʃn/", "chinese": "n. 优化", "example": "Process optimization.", "category": "科学研究"},
        {"english": "prediction", "phonetic": "/prɪˈdɪkʃn/", "chinese": "n. 预测", "example": "Make prediction.", "category": "科学研究"},
        {"english": "procedure", "phonetic": "/prəˈsiːdʒər/", "chinese": "n. 程序", "example": "Follow procedure.", "category": "科学研究"},
        {"english": "proof", "phonetic": "/pruːf/", "chinese": "n. 证明", "example": "Provide proof.", "category": "科学研究"},
        {"english": "quantification", "phonetic": "/ˌkwɑːntɪfɪˈkeɪʃn/", "chinese": "n. 量化", "example": "Data quantification.", "category": "科学研究"},
        {"english": "recognition", "phonetic": "/ˌrekəɡˈnɪʃn/", "chinese": "n. 识别", "example": "Pattern recognition.", "category": "科学研究"},
        {"english": "refutation", "phonetic": "/ˌrefjʊˈteɪʃn/", "chinese": "n. 反驳", "example": "Provide refutation.", "category": "科学研究"},
        {"english": "replication", "phonetic": "/ˌreplɪˈkeɪʃn/", "chinese": "n. 复制", "example": "DNA replication.", "category": "科学研究"},
        {"english": "simulation", "phonetic": "/ˌsɪmjʊˈleɪʃn/", "chinese": "n. 模拟", "example": "Computer simulation.", "category": "科学研究"},
        {"english": "specification", "phonetic": "/ˌspesɪfɪˈkeɪʃn/", "chinese": "n. 规格", "example": "Technical specification.", "category": "科学研究"},
        {"english": "synthesis", "phonetic": "/ˈsɪnθəsɪs/", "chinese": "n. 合成", "example": "Chemical synthesis.", "category": "科学研究"},
        {"english": "testing", "phonetic": "/ˈtestɪŋ/", "chinese": "n. 测试", "example": "Software testing.", "category": "科学研究"},
        {"english": "theory", "phonetic": "/ˈθiːəri/", "chinese": "n. 理论", "example": "Develop theory.", "category": "科学研究"},
        {"english": "validation", "phonetic": "/ˌvælɪˈdeɪʃn/", "chinese": "n. 验证", "example": "Data validation.", "category": "科学研究"},
        {"english": "verification", "phonetic": "/ˌverɪfɪˈkeɪʃn/", "chinese": "n. 核实", "example": "Identity verification.", "category": "科学研究"},
        
        # 商业管理类
        {"english": "acquisition", "phonetic": "/ˌækwɪˈzɪʃn/", "chinese": "n. 收购", "example": "Company acquisition.", "category": "商业管理"},
        {"english": "administration", "phonetic": "/ədˌmɪnɪˈstreɪʃn/", "chinese": "n. 管理", "example": "Business administration.", "category": "商业管理"},
        {"english": "affiliation", "phonetic": "/əˌfɪliˈeɪʃn/", "chinese": "n. 联盟", "example": "Business affiliation.", "category": "商业管理"},
        {"english": "allocation", "phonetic": "/ˌæləˈkeɪʃn/", "chinese": "n. 分配", "example": "Resource allocation.", "category": "商业管理"},
        {"english": "appointment", "phonetic": "/əˈpɔɪntmənt/", "chinese": "n. 任命", "example": "Make appointment.", "category": "商业管理"},
        {"english": "assessment", "phonetic": "/əˈsesmənt/", "chinese": "n. 评估", "example": "Risk assessment.", "category": "商业管理"},
        {"english": "assignment", "phonetic": "/əˈsaɪnmənt/", "chinese": "n. 任务", "example": "Complete assignment.", "category": "商业管理"},
        {"english": "auditing", "phonetic": "/ˈɔːdɪtɪŋ/", "chinese": "n. 审计", "example": "Financial auditing.", "category": "商业管理"},
        {"english": "budgeting", "phonetic": "/ˈbʌdʒɪtɪŋ/", "chinese": "n. 预算", "example": "Annual budgeting.", "category": "商业管理"},
        {"english": "collaboration", "phonetic": "/kəˌlæbəˈreɪʃn/", "chinese": "n. 合作", "example": "Team collaboration.", "category": "商业管理"},
        {"english": "communication", "phonetic": "/kəˌmjuːnɪˈkeɪʃn/", "chinese": "n. 沟通", "example": "Effective communication.", "category": "商业管理"},
        {"english": "competition", "phonetic": "/ˌkɑːmpəˈtɪʃn/", "chinese": "n. 竞争", "example": "Market competition.", "category": "商业管理"},
        {"english": "compliance", "phonetic": "/kəmˈplaɪəns/", "chinese": "n. 合规", "example": "Regulatory compliance.", "category": "商业管理"},
        {"english": "consultation", "phonetic": "/ˌkɑːnsəlˈteɪʃn/", "chinese": "n. 咨询", "example": "Business consultation.", "category": "商业管理"},
        {"english": "coordination", "phonetic": "/koʊˌɔːrdɪˈneɪʃn/", "chinese": "n. 协调", "example": "Project coordination.", "category": "商业管理"},
        {"english": "delegation", "phonetic": "/ˌdelɪˈɡeɪʃn/", "chinese": "n. 授权", "example": "Task delegation.", "category": "商业管理"},
        {"english": "development", "phonetic": "/dɪˈveləpmənt/", "chinese": "n. 发展", "example": "Business development.", "category": "商业管理"},
        {"english": "diversification", "phonetic": "/daɪˌvɜːrsɪfɪˈkeɪʃn/", "chinese": "n. 多样化", "example": "Product diversification.", "category": "商业管理"},
        {"english": "documentation", "phonetic": "/ˌdɑːkjumenˈteɪʃn/", "chinese": "n. 文档", "example": "Project documentation.", "category": "商业管理"},
        {"english": "employment", "phonetic": "/ɪmˈplɔɪmənt/", "chinese": "n. 就业", "example": "Find employment.", "category": "商业管理"},
        {"english": "enterprise", "phonetic": "/ˈentərpraɪz/", "chinese": "n. 企业", "example": "Large enterprise.", "category": "商业管理"},
        {"english": "entrepreneurship", "phonetic": "/ˌɑːntrəprəˈnɜːrʃɪp/", "chinese": "n. 创业", "example": "Start entrepreneurship.", "category": "商业管理"},
        {"english": "estimation", "phonetic": "/ˌestɪˈmeɪʃn/", "chinese": "n. 估算", "example": "Cost estimation.", "category": "商业管理"},
        {"english": "execution", "phonetic": "/ˌeksɪˈkjuːʃn/", "chinese": "n. 执行", "example": "Plan execution.", "category": "商业管理"},
        {"english": "expansion", "phonetic": "/ɪkˈspænʃn/", "chinese": "n. 扩张", "example": "Business expansion.", "category": "商业管理"},
        {"english": "franchise", "phonetic": "/ˈfræntʃaɪz/", "chinese": "n. 特许经营", "example": "Buy franchise.", "category": "商业管理"},
        {"english": "globalization", "phonetic": "/ˌɡloʊbəlaɪˈzeɪʃn/", "chinese": "n. 全球化", "example": "Market globalization.", "category": "商业管理"},
        {"english": "governance", "phonetic": "/ˈɡʌvərnəns/", "chinese": "n. 治理", "example": "Corporate governance.", "category": "商业管理"},
        {"english": "headquarters", "phonetic": "/ˈhedkwɔːrtərz/", "chinese": "n. 总部", "example": "Company headquarters.", "category": "商业管理"},
        {"english": "incorporation", "phonetic": "/ɪnˌkɔːrpəˈreɪʃn/", "chinese": "n. 注册", "example": "Business incorporation.", "category": "商业管理"},
        {"english": "innovation", "phonetic": "/ˌɪnəˈveɪʃn/", "chinese": "n. 创新", "example": "Product innovation.", "category": "商业管理"},
        {"english": "integration", "phonetic": "/ˌɪntɪˈɡreɪʃn/", "chinese": "n. 整合", "example": "System integration.", "category": "商业管理"},
        {"english": "investment", "phonetic": "/ɪnˈvestmənt/", "chinese": "n. 投资", "example": "Make investment.", "category": "商业管理"},
        {"english": "leadership", "phonetic": "/ˈliːdərʃɪp/", "chinese": "n. 领导力", "example": "Show leadership.", "category": "商业管理"},
        {"english": "licensing", "phonetic": "/ˈlaɪsənsɪŋ/", "chinese": "n. 许可", "example": "Software licensing.", "category": "商业管理"},
        {"english": "management", "phonetic": "/ˈmænɪdʒmənt/", "chinese": "n. 管理", "example": "Project management.", "category": "商业管理"},
        {"english": "marketing", "phonetic": "/ˈmɑːrkɪtɪŋ/", "chinese": "n. 营销", "example": "Digital marketing.", "category": "商业管理"},
        {"english": "merger", "phonetic": "/ˈmɜːrdʒər/", "chinese": "n. 合并", "example": "Company merger.", "category": "商业管理"},
        {"english": "negotiation", "phonetic": "/nɪˌɡoʊʃiˈeɪʃn/", "chinese": "n. 谈判", "example": "Salary negotiation.", "category": "商业管理"},
        {"english": "operation", "phonetic": "/ˌɑːpəˈreɪʃn/", "chinese": "n. 运营", "example": "Business operation.", "category": "商业管理"},
        {"english": "organization", "phonetic": "/ˌɔːrɡənaɪˈzeɪʃn/", "chinese": "n. 组织", "example": "Non-profit organization.", "category": "商业管理"},
        {"english": "outsourcing", "phonetic": "/ˈaʊtsɔːrsɪŋ/", "chinese": "n. 外包", "example": "IT outsourcing.", "category": "商业管理"},
        {"english": "ownership", "phonetic": "/ˈoʊnərʃɪp/", "chinese": "n. 所有权", "example": "Business ownership.", "category": "商业管理"},
        {"english": "partnership", "phonetic": "/ˈpɑːrtnərʃɪp/", "chinese": "n. 合作关系", "example": "Strategic partnership.", "category": "商业管理"},
        {"english": "performance", "phonetic": "/pərˈfɔːrməns/", "chinese": "n. 绩效", "example": "Employee performance.", "category": "商业管理"},
        {"english": "planning", "phonetic": "/ˈplænɪŋ/", "chinese": "n. 规划", "example": "Strategic planning.", "category": "商业管理"},
        {"english": "procurement", "phonetic": "/prəˈkjʊrmənt/", "chinese": "n. 采购", "example": "Government procurement.", "category": "商业管理"},
        {"english": "production", "phonetic": "/prəˈdʌkʃn/", "chinese": "n. 生产", "example": "Mass production.", "category": "商业管理"},
        {"english": "profitability", "phonetic": "/ˌprɑːfɪtəˈbɪləti/", "chinese": "n. 盈利能力", "example": "Assess profitability.", "category": "商业管理"},
        {"english": "promotion", "phonetic": "/prəˈmoʊʃn/", "chinese": "n. 晋升", "example": "Get promotion.", "category": "商业管理"},
        {"english": "recruitment", "phonetic": "/rɪˈkruːtmənt/", "chinese": "n. 招聘", "example": "Employee recruitment.", "category": "商业管理"},
        {"english": "restructuring", "phonetic": "/ˌriːˈstrʌktʃərɪŋ/", "chinese": "n. 重组", "example": "Company restructuring.", "category": "商业管理"},
        {"english": "retention", "phonetic": "/rɪˈtenʃn/", "chinese": "n. 留存", "example": "Customer retention.", "category": "商业管理"},
        {"english": "revenue", "phonetic": "/ˈrevənuː/", "chinese": "n. 收入", "example": "Generate revenue.", "category": "商业管理"},
        {"english": "scheduling", "phonetic": "/ˈskedʒuːlɪŋ/", "chinese": "n. 排程", "example": "Task scheduling.", "category": "商业管理"},
        {"english": "strategic", "phonetic": "/strəˈtiːdʒɪk/", "chinese": "adj. 战略的", "example": "Strategic plan.", "category": "商业管理"},
        {"english": "subsidiary", "phonetic": "/səbˈsɪdieri/", "chinese": "n. 子公司", "example": "Foreign subsidiary.", "category": "商业管理"},
        {"english": "supervision", "phonetic": "/ˌsuːpərˈvɪʒn/", "chinese": "n. 监督", "example": "Project supervision.", "category": "商业管理"},
        {"english": "supply", "phonetic": "/səˈplaɪ/", "chinese": "n. 供应", "example": "Power supply.", "category": "商业管理"},
        {"english": "training", "phonetic": "/ˈtreɪnɪŋ/", "chinese": "n. 培训", "example": "Job training.", "category": "商业管理"},
        {"english": "valuation", "phonetic": "/ˌvæljuˈeɪʃn/", "chinese": "n. 估值", "example": "Company valuation.", "category": "商业管理"},
        {"english": "venture", "phonetic": "/ˈventʃər/", "chinese": "n. 风险投资", "example": "Joint venture.", "category": "商业管理"},
        
        # 法律政治类
        {"english": "advocacy", "phonetic": "/ˈædvəkəsi/", "chinese": "n. 倡导", "example": "Legal advocacy.", "category": "法律政治"},
        {"english": "amendment", "phonetic": "/əˈmendmənt/", "chinese": "n. 修正案", "example": "Constitutional amendment.", "category": "法律政治"},
        {"english": "arbitration", "phonetic": "/ˌɑːrbɪˈtreɪʃn/", "chinese": "n. 仲裁", "example": "International arbitration.", "category": "法律政治"},
        {"english": "authority", "phonetic": "/əˈθɔːrəti/", "chinese": "n. 权威", "example": "Legal authority.", "category": "法律政治"},
        {"english": "ballot", "phonetic": "/ˈbælət/", "chinese": "n. 选票", "example": "Cast ballot.", "category": "法律政治"},
        {"english": "campaign", "phonetic": "/kæmˈpeɪn/", "chinese": "n. 竞选活动", "example": "Election campaign.", "category": "法律政治"},
        {"english": "candidacy", "phonetic": "/ˈkændɪdəsi/", "chinese": "n. 候选资格", "example": "Announce candidacy.", "category": "法律政治"},
        {"english": "citizenship", "phonetic": "/ˈsɪtɪzənʃɪp/", "chinese": "n. 公民身份", "example": "Apply for citizenship.", "category": "法律政治"},
        {"english": "coalition", "phonetic": "/ˌkoʊəˈlɪʃn/", "chinese": "n. 联盟", "example": "Political coalition.", "category": "法律政治"},
        {"english": "commission", "phonetic": "/kəˈmɪʃn/", "chinese": "n. 委员会", "example": "European commission.", "category": "法律政治"},
        {"english": "constitution", "phonetic": "/ˌkɑːnstɪˈtuːʃn/", "chinese": "n. 宪法", "example": "National constitution.", "category": "法律政治"},
        {"english": "convention", "phonetic": "/kənˈvenʃn/", "chinese": "n. 公约", "example": "Geneva convention.", "category": "法律政治"},
        {"english": "democracy", "phonetic": "/dɪˈmɑːkrəsi/", "chinese": "n. 民主", "example": "Practice democracy.", "category": "法律政治"},
        {"english": "diplomacy", "phonetic": "/dɪˈploʊməsi/", "chinese": "n. 外交", "example": "International diplomacy.", "category": "法律政治"},
        {"english": "election", "phonetic": "/ɪˈlekʃn/", "chinese": "n. 选举", "example": "General election.", "category": "法律政治"},
        {"english": "enforcement", "phonetic": "/ɪnˈfɔːrsmənt/", "chinese": "n. 执行", "example": "Law enforcement.", "category": "法律政治"},
        {"english": "hearing", "phonetic": "/ˈhɪrɪŋ/", "chinese": "n. 听证会", "example": "Court hearing.", "category": "法律政治"},
        {"english": "immigration", "phonetic": "/ˌɪmɪˈɡreɪʃn/", "chinese": "n. 移民", "example": "Immigration policy.", "category": "法律政治"},
        {"english": "injunction", "phonetic": "/ɪnˈdʒʌŋkʃn/", "chinese": "n. 禁令", "example": "Court injunction.", "category": "法律政治"},
        {"english": "jurisdiction", "phonetic": "/ˌdʒʊrɪsˈdɪkʃn/", "chinese": "n. 管辖权", "example": "Federal jurisdiction.", "category": "法律政治"},
        {"english": "legislation", "phonetic": "/ˌledʒɪsˈleɪʃn/", "chinese": "n. 立法", "example": "Pass legislation.", "category": "法律政治"},
        {"english": "litigation", "phonetic": "/ˌlɪtɪˈɡeɪʃn/", "chinese": "n. 诉讼", "example": "Civil litigation.", "category": "法律政治"},
        {"english": "mandate", "phonetic": "/ˈmændeɪt/", "chinese": "n. 授权", "example": "Government mandate.", "category": "法律政治"},
        {"english": "nomination", "phonetic": "/ˌnɑːmɪˈneɪʃn/", "chinese": "n. 提名", "example": "Party nomination.", "category": "法律政治"},
        {"english": "parliament", "phonetic": "/ˈpɑːrləmənt/", "chinese": "n. 议会", "example": "European parliament.", "category": "法律政治"},
        {"english": "petition", "phonetic": "/pəˈtɪʃn/", "chinese": "n. 请愿", "example": "Sign petition.", "category": "法律政治"},
        {"english": "policy", "phonetic": "/ˈpɑːləsi/", "chinese": "n. 政策", "example": "Foreign policy.", "category": "法律政治"},
        {"english": "prosecution", "phonetic": "/ˌprɑːsɪˈkjuːʃn/", "chinese": "n. 起诉", "example": "Criminal prosecution.", "category": "法律政治"},
        {"english": "ratification", "phonetic": "/ˌrætɪfɪˈkeɪʃn/", "chinese": "n. 批准", "example": "Treaty ratification.", "category": "法律政治"},
        {"english": "regulation", "phonetic": "/ˌreɡjʊˈleɪʃn/", "chinese": "n. 法规", "example": "Safety regulation.", "category": "法律政治"},
        {"english": "representation", "phonetic": "/ˌreprɪzenˈteɪʃn/", "chinese": "n. 代表", "example": "Legal representation.", "category": "法律政治"},
        {"english": "resolution", "phonetic": "/ˌrezəˈluːʃn/", "chinese": "n. 决议", "example": "UN resolution.", "category": "法律政治"},
        {"english": "sanction", "phonetic": "/ˈsæŋkʃn/", "chinese": "n. 制裁", "example": "Economic sanction.", "category": "法律政治"},
        {"english": "sovereignty", "phonetic": "/ˈsɑːvrənti/", "chinese": "n. 主权", "example": "National sovereignty.", "category": "法律政治"},
        {"english": "statute", "phonetic": "/ˈstætʃuːt/", "chinese": "n. 法令", "example": "Federal statute.", "category": "法律政治"},
        {"english": "treaty", "phonetic": "/ˈtriːti/", "chinese": "n. 条约", "example": "Peace treaty.", "category": "法律政治"},
        {"english": "verdict", "phonetic": "/ˈvɜːrdɪkt/", "chinese": "n. 裁决", "example": "Jury verdict.", "category": "法律政治"},
        {"english": "veto", "phonetic": "/ˈviːtoʊ/", "chinese": "n. 否决权", "example": "Exercise veto.", "category": "法律政治"},
        {"english": "vote", "phonetic": "/voʊt/", "chinese": "n. 投票", "example": "Cast vote.", "category": "法律政治"},
        
        # 医疗健康类
        {"english": "anesthesia", "phonetic": "/ˌænɪsˈθiːʒə/", "chinese": "n. 麻醉", "example": "General anesthesia.", "category": "医疗健康"},
        {"english": "antibiotic", "phonetic": "/ˌæntibaɪˈɑːtɪk/", "chinese": "n. 抗生素", "example": "Take antibiotic.", "category": "医疗健康"},
        {"english": "biopsy", "phonetic": "/ˈbaɪɑːpsi/", "chinese": "n. 活检", "example": "Tissue biopsy.", "category": "医疗健康"},
        {"english": "cardiology", "phonetic": "/ˌkɑːrdiˈɑːlədʒi/", "chinese": "n. 心脏病学", "example": "Study cardiology.", "category": "医疗健康"},
        {"english": "chemotherapy", "phonetic": "/ˌkiːmoʊˈθerəpi/", "chinese": "n. 化疗", "example": "Undergo chemotherapy.", "category": "医疗健康"},
        {"english": "diagnosis", "phonetic": "/ˌdaɪəɡˈnoʊsɪs/", "chinese": "n. 诊断", "example": "Medical diagnosis.", "category": "医疗健康"},
        {"english": "endocrinology", "phonetic": "/ˌendoʊkrɪˈnɑːlədʒi/", "chinese": "n. 内分泌学", "example": "Endocrinology department.", "category": "医疗健康"},
        {"english": "epidemiology", "phonetic": "/ˌepɪˌdiːmiˈɑːlədʒi/", "chinese": "n. 流行病学", "example": "Study epidemiology.", "category": "医疗健康"},
        {"english": "genetics", "phonetic": "/dʒəˈnetɪks/", "chinese": "n. 遗传学", "example": "Human genetics.", "category": "医疗健康"},
        {"english": "gynecology", "phonetic": "/ˌɡaɪnəˈkɑːlədʒi/", "chinese": "n. 妇科", "example": "Gynecology clinic.", "category": "医疗健康"},
        {"english": "immunology", "phonetic": "/ˌɪmjʊˈnɑːlədʒi/", "chinese": "n. 免疫学", "example": "Clinical immunology.", "category": "医疗健康"},
        {"english": "infection", "phonetic": "/ɪnˈfekʃn/", "chinese": "n. 感染", "example": "Viral infection.", "category": "医疗健康"},
        {"english": "medication", "phonetic": "/ˌmedɪˈkeɪʃn/", "chinese": "n. 药物", "example": "Take medication.", "category": "医疗健康"},
        {"english": "neurology", "phonetic": "/nʊˈrɑːlədʒi/", "chinese": "n. 神经学", "example": "Neurology department.", "category": "医疗健康"},
        {"english": "oncology", "phonetic": "/ɑːŋˈkɑːlədʒi/", "chinese": "n. 肿瘤学", "example": "Clinical oncology.", "category": "医疗健康"},
        {"english": "pathology", "phonetic": "/pəˈθɑːlədʒi/", "chinese": "n. 病理学", "example": "Pathology report.", "category": "医疗健康"},
        {"english": "pediatrics", "phonetic": "/ˌpiːdiˈætrɪks/", "chinese": "n. 儿科", "example": "Pediatrics department.", "category": "医疗健康"},
        {"english": "pharmacy", "phonetic": "/ˈfɑːrməsi/", "chinese": "n. 药房", "example": "Hospital pharmacy.", "category": "医疗健康"},
        {"english": "physiology", "phonetic": "/ˌfɪziˈɑːlədʒi/", "chinese": "n. 生理学", "example": "Human physiology.", "category": "医疗健康"},
        {"english": "psychiatry", "phonetic": "/saɪˈkaɪətri/", "chinese": "n. 精神病学", "example": "Psychiatry clinic.", "category": "医疗健康"},
        {"english": "radiology", "phonetic": "/ˌreɪdiˈɑːlədʒi/", "chinese": "n. 放射学", "example": "Radiology department.", "category": "医疗健康"},
        {"english": "rehabilitation", "phonetic": "/ˌriːəˌbɪlɪˈteɪʃn/", "chinese": "n. 康复", "example": "Physical rehabilitation.", "category": "医疗健康"},
        {"english": "surgery", "phonetic": "/ˈsɜːrdʒəri/", "chinese": "n. 手术", "example": "Undergo surgery.", "category": "医疗健康"},
        {"english": "symptom", "phonetic": "/ˈsɪmptəm/", "chinese": "n. 症状", "example": "Show symptom.", "category": "医疗健康"},
        {"english": "therapy", "phonetic": "/ˈθerəpi/", "chinese": "n. 治疗", "example": "Physical therapy.", "category": "医疗健康"},
        {"english": "transplant", "phonetic": "/trænsˈplænt/", "chinese": "n. 移植", "example": "Organ transplant.", "category": "医疗健康"},
        {"english": "vaccination", "phonetic": "/ˌvæksɪˈneɪʃn/", "chinese": "n. 疫苗接种", "example": "Get vaccination.", "category": "医疗健康"},
        {"english": "virus", "phonetic": "/ˈvaɪrəs/", "chinese": "n. 病毒", "example": "Computer virus.", "category": "医疗健康"},
        
        # 教育学习类
        {"english": "academic", "phonetic": "/ˌækəˈdemɪk/", "chinese": "adj. 学术的", "example": "Academic research.", "category": "教育学习"},
        {"english": "curriculum", "phonetic": "/kəˈrɪkjələm/", "chinese": "n. 课程", "example": "School curriculum.", "category": "教育学习"},
        {"english": "diploma", "phonetic": "/dɪˈploʊmə/", "chinese": "n. 文凭", "example": "High school diploma.", "category": "教育学习"},
        {"english": "enrollment", "phonetic": "/ɪnˈroʊlmənt/", "chinese": "n. 入学", "example": "Course enrollment.", "category": "教育学习"},
        {"english": "faculty", "phonetic": "/ˈfæklti/", "chinese": "n. 教职工", "example": "University faculty.", "category": "教育学习"},
        {"english": "graduation", "phonetic": "/ˌɡrædʒuˈeɪʃn/", "chinese": "n. 毕业", "example": "College graduation.", "category": "教育学习"},
        {"english": "instruction", "phonetic": "/ɪnˈstrʌkʃn/", "chinese": "n. 指导", "example": "Classroom instruction.", "category": "教育学习"},
        {"english": "learning", "phonetic": "/ˈlɜːrnɪŋ/", "chinese": "n. 学习", "example": "Lifelong learning.", "category": "教育学习"},
        {"english": "professor", "phonetic": "/prəˈfesər/", "chinese": "n. 教授", "example": "Biology professor.", "category": "教育学习"},
        {"english": "scholarship", "phonetic": "/ˈskɑːlərʃɪp/", "chinese": "n. 奖学金", "example": "Apply for scholarship.", "category": "教育学习"},
        {"english": "semester", "phonetic": "/sɪˈmestər/", "chinese": "n. 学期", "example": "Fall semester.", "category": "教育学习"},
        {"english": "tuition", "phonetic": "/tuˈɪʃn/", "chinese": "n. 学费", "example": "Pay tuition.", "category": "教育学习"},
        {"english": "university", "phonetic": "/ˌjuːnɪˈvɜːrsəti/", "chinese": "n. 大学", "example": "State university.", "category": "教育学习"},
        
        # 技术创新类
        {"english": "automation", "phonetic": "/ˌɔːtəˈmeɪʃn/", "chinese": "n. 自动化", "example": "Industrial automation.", "category": "技术创新"},
        {"english": "blockchain", "phonetic": "/ˈblɑːktʃeɪn/", "chinese": "n. 区块链", "example": "Blockchain technology.", "category": "技术创新"},
        {"english": "cybersecurity", "phonetic": "/ˌsaɪbərsɪˈkjʊrəti/", "chinese": "n. 网络安全", "example": "Cybersecurity expert.", "category": "技术创新"},
        {"english": "encryption", "phonetic": "/ɪnˈkrɪpʃn/", "chinese": "n. 加密", "example": "Data encryption.", "category": "技术创新"},
        {"english": "infrastructure", "phonetic": "/ˈɪnfrəstrʌktʃər/", "chinese": "n. 基础设施", "example": "IT infrastructure.", "category": "技术创新"},
        {"english": "innovation", "phonetic": "/ˌɪnəˈveɪʃn/", "chinese": "n. 创新", "example": "Technological innovation.", "category": "技术创新"},
        {"english": "programming", "phonetic": "/ˈproʊɡræmɪŋ/", "chinese": "n. 编程", "example": "Learn programming.", "category": "技术创新"},
        {"english": "robotics", "phonetic": "/roʊˈbɑːtɪks/", "chinese": "n. 机器人技术", "example": "Industrial robotics.", "category": "技术创新"},
        {"english": "software", "phonetic": "/ˈsɔːftwer/", "chinese": "n. 软件", "example": "Install software.", "category": "技术创新"},
        {"english": "virtual", "phonetic": "/ˈvɜːrtʃuəl/", "chinese": "adj. 虚拟的", "example": "Virtual reality.", "category": "技术创新"},
        
        # 自然地理类
        {"english": "atmosphere", "phonetic": "/ˈætməsfɪr/", "chinese": "n. 大气", "example": "Earth atmosphere.", "category": "自然地理"},
        {"english": "climate", "phonetic": "/ˈklaɪmət/", "chinese": "n. 气候", "example": "Tropical climate.", "category": "自然地理"},
        {"english": "ecosystem", "phonetic": "/ˈiːkoʊsɪstəm/", "chinese": "n. 生态系统", "example": "Marine ecosystem.", "category": "自然地理"},
        {"english": "environment", "phonetic": "/ɪnˈvaɪrənmənt/", "chinese": "n. 环境", "example": "Protect environment.", "category": "自然地理"},
        {"english": "geography", "phonetic": "/dʒiˈɑːɡrəfi/", "chinese": "n. 地理", "example": "Physical geography.", "category": "自然地理"},
        {"english": "habitat", "phonetic": "/ˈhæbɪtæt/", "chinese": "n. 栖息地", "example": "Natural habitat.", "category": "自然地理"},
        {"english": "landscape", "phonetic": "/ˈlændskeɪp/", "chinese": "n. 景观", "example": "Beautiful landscape.", "category": "自然地理"},
        {"english": "pollution", "phonetic": "/pəˈluːʃn/", "chinese": "n. 污染", "example": "Air pollution.", "category": "自然地理"},
        {"english": "resource", "phonetic": "/ˈriːsɔːrs/", "chinese": "n. 资源", "example": "Natural resource.", "category": "自然地理"},
        {"english": "wildlife", "phonetic": "/ˈwaɪldlaɪf/", "chinese": "n. 野生动物", "example": "Protect wildlife.", "category": "自然地理"},
        
        # 社会文化类
        {"english": "community", "phonetic": "/kəˈmjuːnəti/", "chinese": "n. 社区", "example": "Local community.", "category": "社会文化"},
        {"english": "culture", "phonetic": "/ˈkʌltʃər/", "chinese": "n. 文化", "example": "Corporate culture.", "category": "社会文化"},
        {"english": "diversity", "phonetic": "/daɪˈvɜːrsəti/", "chinese": "n. 多样性", "example": "Cultural diversity.", "category": "社会文化"},
        {"english": "heritage", "phonetic": "/ˈherɪtɪdʒ/", "chinese": "n. 遗产", "example": "Cultural heritage.", "category": "社会文化"},
        {"english": "identity", "phonetic": "/aɪˈdentəti/", "chinese": "n. 身份", "example": "National identity.", "category": "社会文化"},
        {"english": "integration", "phonetic": "/ˌɪntɪˈɡreɪʃn/", "chinese": "n. 融合", "example": "Social integration.", "category": "社会文化"},
        {"english": "society", "phonetic": "/səˈsaɪəti/", "chinese": "n. 社会", "example": "Modern society.", "category": "社会文化"},
        {"english": "tradition", "phonetic": "/trəˈdɪʃn/", "chinese": "n. 传统", "example": "Family tradition.", "category": "社会文化"},
        
        # 旅行交通类
        {"english": "accommodation", "phonetic": "/əˌkɑːməˈdeɪʃn/", "chinese": "n. 住宿", "example": "Book accommodation.", "category": "旅行交通"},
        {"english": "destination", "phonetic": "/ˌdestɪˈneɪʃn/", "chinese": "n. 目的地", "example": "Travel destination.", "category": "旅行交通"},
        {"english": "itinerary", "phonetic": "/aɪˈtɪnəreri/", "chinese": "n. 行程", "example": "Plan itinerary.", "category": "旅行交通"},
        {"english": "navigation", "phonetic": "/ˌnævɪˈɡeɪʃn/", "chinese": "n. 导航", "example": "GPS navigation.", "category": "旅行交通"},
        {"english": "reservation", "phonetic": "/ˌrezərˈveɪʃn/", "chinese": "n. 预订", "example": "Make reservation.", "category": "旅行交通"},
        {"english": "transportation", "phonetic": "/ˌtrænspɔːrˈteɪʃn/", "chinese": "n. 交通", "example": "Public transportation.", "category": "旅行交通"},
        {"english": "vacation", "phonetic": "/veɪˈkeɪʃn/", "chinese": "n. 假期", "example": "Summer vacation.", "category": "旅行交通"},
        
        # 食物烹饪类
        {"english": "cuisine", "phonetic": "/kwɪˈziːn/", "chinese": "n. 烹饪", "example": "French cuisine.", "category": "食物烹饪"},
        {"english": "ingredient", "phonetic": "/ɪnˈɡriːdiənt/", "chinese": "n. 食材", "example": "Main ingredient.", "category": "食物烹饪"},
        {"english": "nutrition", "phonetic": "/nuˈtrɪʃn/", "chinese": "n. 营养", "example": "Good nutrition.", "category": "食物烹饪"},
        {"english": "recipe", "phonetic": "/ˈresəpi/", "chinese": "n. 食谱", "example": "Follow recipe.", "category": "食物烹饪"},
        {"english": "restaurant", "phonetic": "/ˈrestərɑːnt/", "chinese": "n. 餐厅", "example": "Italian restaurant.", "category": "食物烹饪"},
        
        # 心理情感类
        {"english": "anxiety", "phonetic": "/æŋˈzaɪəti/", "chinese": "n. 焦虑", "example": "Social anxiety.", "category": "心理情感"},
        {"english": "behavior", "phonetic": "/bɪˈheɪvjər/", "chinese": "n. 行为", "example": "Human behavior.", "category": "心理情感"},
        {"english": "cognition", "phonetic": "/kɑːɡˈnɪʃn/", "chinese": "n. 认知", "example": "Cognitive process.", "category": "心理情感"},
        {"english": "emotion", "phonetic": "/ɪˈmoʊʃn/", "chinese": "n. 情感", "example": "Express emotion.", "category": "心理情感"},
        {"english": "motivation", "phonetic": "/ˌmoʊtɪˈveɪʃn/", "chinese": "n. 动机", "example": "Find motivation.", "category": "心理情感"},
        {"english": "personality", "phonetic": "/ˌpɜːrsəˈnæləti/", "chinese": "n. 个性", "example": "Strong personality.", "category": "心理情感"},
        {"english": "psychology", "phonetic": "/saɪˈkɑːlədʒi/", "chinese": "n. 心理学", "example": "Study psychology.", "category": "心理情感"},
        {"english": "stress", "phonetic": "/stres/", "chinese": "n. 压力", "example": "Reduce stress.", "category": "心理情感"},
        
        # 运动健身类
        {"english": "athletics", "phonetic": "/æθˈletɪks/", "chinese": "n. 田径运动", "example": "Track athletics.", "category": "运动健身"},
        {"english": "exercise", "phonetic": "/ˈeksərsaɪz/", "chinese": "n. 锻炼", "example": "Daily exercise.", "category": "运动健身"},
        {"english": "fitness", "phonetic": "/ˈfɪtnəs/", "chinese": "n. 健身", "example": "Physical fitness.", "category": "运动健身"},
        {"english": "nutrition", "phonetic": "/nuˈtrɪʃn/", "chinese": "n. 营养", "example": "Sports nutrition.", "category": "运动健身"},
        {"english": "recreation", "phonetic": "/ˌriːkriˈeɪʃn/", "chinese": "n. 娱乐", "example": "Outdoor recreation.", "category": "运动健身"},
        {"english": "training", "phonetic": "/ˈtreɪnɪŋ/", "chinese": "n. 训练", "example": "Strength training.", "category": "运动健身"},
        
        # 金融经济类
        {"english": "banking", "phonetic": "/ˈbæŋkɪŋ/", "chinese": "n. 银行业", "example": "Online banking.", "category": "金融经济"},
        {"english": "capital", "phonetic": "/ˈkæpɪtl/", "chinese": "n. 资本", "example": "Human capital.", "category": "金融经济"},
        {"english": "currency", "phonetic": "/ˈkɜːrənsi/", "chinese": "n. 货币", "example": "Foreign currency.", "category": "金融经济"},
        {"english": "economics", "phonetic": "/ˌiːkəˈnɑːmɪks/", "chinese": "n. 经济学", "example": "Study economics.", "category": "金融经济"},
        {"english": "finance", "phonetic": "/ˈfaɪnæns/", "chinese": "n. 金融", "example": "Corporate finance.", "category": "金融经济"},
        {"english": "inflation", "phonetic": "/ɪnˈfleɪʃn/", "chinese": "n. 通货膨胀", "example": "Control inflation.", "category": "金融经济"},
        {"english": "investment", "phonetic": "/ɪnˈvestmənt/", "chinese": "n. 投资", "example": "Smart investment.", "category": "金融经济"},
        {"english": "market", "phonetic": "/ˈmɑːrkɪt/", "chinese": "n. 市场", "example": "Stock market.", "category": "金融经济"},
        {"english": "revenue", "phonetic": "/ˈrevənuː/", "chinese": "n. 收入", "example": "Annual revenue.", "category": "金融经济"},
        {"english": "taxation", "phonetic": "/tækˈseɪʃn/", "chinese": "n. 税收", "example": "Income taxation.", "category": "金融经济"},
        
        # 艺术文化类
        {"english": "architecture", "phonetic": "/ˈɑːrkɪtektʃər/", "chinese": "n. 建筑", "example": "Modern architecture.", "category": "艺术文化"},
        {"english": "art", "phonetic": "/ɑːrt/", "chinese": "n. 艺术", "example": "Fine art.", "category": "艺术文化"},
        {"english": "design", "phonetic": "/dɪˈzaɪn/", "chinese": "n. 设计", "example": "Graphic design.", "category": "艺术文化"},
        {"english": "exhibition", "phonetic": "/ˌeksɪˈbɪʃn/", "chinese": "n. 展览", "example": "Art exhibition.", "category": "艺术文化"},
        {"english": "gallery", "phonetic": "/ˈɡæləri/", "chinese": "n. 画廊", "example": "Art gallery.", "category": "艺术文化"},
        {"english": "literature", "phonetic": "/ˈlɪtrətʃər/", "chinese": "n. 文学", "example": "English literature.", "category": "艺术文化"},
        {"english": "museum", "phonetic": "/mjuˈziːəm/", "chinese": "n. 博物馆", "example": "History museum.", "category": "艺术文化"},
        {"english": "music", "phonetic": "/ˈmjuːzɪk/", "chinese": "n. 音乐", "example": "Classical music.", "category": "艺术文化"},
        {"english": "performance", "phonetic": "/pərˈfɔːrməns/", "chinese": "n. 表演", "example": "Live performance.", "category": "艺术文化"},
        {"english": "theater", "phonetic": "/ˈθiːətər/", "chinese": "n. 剧院", "example": "Movie theater.", "category": "艺术文化"}
    ]
    
    added_count = 0
    for word in new_words:
        cursor.execute('''
            INSERT OR IGNORE INTO words (english, phonetic, chinese, example, category, subcategory)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (word['english'], word['phonetic'], word['chinese'], word['example'], word['category'], ''))
        
        if cursor.rowcount > 0:
            added_count += 1
    
    conn.commit()
    
    cursor.execute('SELECT COUNT(*) FROM words')
    total = cursor.fetchone()[0]
    
    print(f"成功添加 {added_count} 个新单词到数据库")
    print(f"数据库总单词数: {total}")
    
    conn.close()

if __name__ == "__main__":
    expand_to_5000_batch9()
