import sqlite3

def expand_to_5000_batch13():
    conn = sqlite3.connect('../words.db')
    cursor = conn.cursor()
    
    new_words = [
        {"english": "cabinet", "phonetic": "/ˈkæbɪnət/", "chinese": "n. 橱柜", "example": "Kitchen cabinet.", "category": "通用词汇"},
        {"english": "cable", "phonetic": "/ˈkeɪbl/", "chinese": "n. 电缆", "example": "Power cable.", "category": "通用词汇"},
        {"english": "cafe", "phonetic": "/kæˈfeɪ/", "chinese": "n. 咖啡馆", "example": "Visit cafe.", "category": "通用词汇"},
        {"english": "cage", "phonetic": "/keɪdʒ/", "chinese": "n. 笼子", "example": "Bird cage.", "category": "通用词汇"},
        {"english": "cake", "phonetic": "/keɪk/", "chinese": "n. 蛋糕", "example": "Birthday cake.", "category": "通用词汇"},
        {"english": "calculate", "phonetic": "/ˈkælkjʊleɪt/", "chinese": "v. 计算", "example": "Calculate cost.", "category": "通用词汇"},
        {"english": "calendar", "phonetic": "/ˈkæləndər/", "chinese": "n. 日历", "example": "Check calendar.", "category": "通用词汇"},
        {"english": "calm", "phonetic": "/kɑːm/", "chinese": "adj. 平静的", "example": "Stay calm.", "category": "通用词汇"},
        {"english": "camera", "phonetic": "/ˈkæmərə/", "chinese": "n. 相机", "example": "Digital camera.", "category": "通用词汇"},
        {"english": "camp", "phonetic": "/kæmp/", "chinese": "n. 露营", "example": "Summer camp.", "category": "通用词汇"},
        {"english": "campaign", "phonetic": "/kæmˈpeɪn/", "chinese": "n. 活动", "example": "Marketing campaign.", "category": "通用词汇"},
        {"english": "campus", "phonetic": "/ˈkæmpəs/", "chinese": "n. 校园", "example": "University campus.", "category": "通用词汇"},
        {"english": "canal", "phonetic": "/kəˈnæl/", "chinese": "n. 运河", "example": "Panama Canal.", "category": "通用词汇"},
        {"english": "cancel", "phonetic": "/ˈkænsəl/", "chinese": "v. 取消", "example": "Cancel meeting.", "category": "通用词汇"},
        {"english": "cancer", "phonetic": "/ˈkænsər/", "chinese": "n. 癌症", "example": "Lung cancer.", "category": "通用词汇"},
        {"english": "candidate", "phonetic": "/ˈkændɪdeɪt/", "chinese": "n. 候选人", "example": "Job candidate.", "category": "通用词汇"},
        {"english": "candle", "phonetic": "/ˈkændl/", "chinese": "n. 蜡烛", "example": "Light candle.", "category": "通用词汇"},
        {"english": "candy", "phonetic": "/ˈkændi/", "chinese": "n. 糖果", "example": "Eat candy.", "category": "通用词汇"},
        {"english": "capable", "phonetic": "/ˈkeɪpəbl/", "chinese": "adj. 有能力的", "example": "Capable person.", "category": "通用词汇"},
        {"english": "capacity", "phonetic": "/kəˈpæsəti/", "chinese": "n. 容量", "example": "Storage capacity.", "category": "通用词汇"},
        {"english": "capital", "phonetic": "/ˈkæpɪtl/", "chinese": "n. 首都", "example": "National capital.", "category": "通用词汇"},
        {"english": "captain", "phonetic": "/ˈkæptɪn/", "chinese": "n. 船长", "example": "Ship captain.", "category": "通用词汇"},
        {"english": "capture", "phonetic": "/ˈkæptʃər/", "chinese": "v. 捕获", "example": "Capture moment.", "category": "通用词汇"},
        {"english": "carbon", "phonetic": "/ˈkɑːrbən/", "chinese": "n. 碳", "example": "Carbon footprint.", "category": "通用词汇"},
        {"english": "card", "phonetic": "/kɑːrd/", "chinese": "n. 卡片", "example": "Credit card.", "category": "通用词汇"},
        {"english": "care", "phonetic": "/ker/", "chinese": "n. 关心", "example": "Take care.", "category": "通用词汇"},
        {"english": "career", "phonetic": "/kəˈrɪr/", "chinese": "n. 职业", "example": "Career path.", "category": "通用词汇"},
        {"english": "careful", "phonetic": "/ˈkerfl/", "chinese": "adj. 小心的", "example": "Be careful.", "category": "通用词汇"},
        {"english": "cargo", "phonetic": "/ˈkɑːrɡoʊ/", "chinese": "n. 货物", "example": "Cargo ship.", "category": "通用词汇"},
        {"english": "carpet", "phonetic": "/ˈkɑːrpɪt/", "chinese": "n. 地毯", "example": "Red carpet.", "category": "通用词汇"},
        {"english": "carriage", "phonetic": "/ˈkærɪdʒ/", "chinese": "n. 马车", "example": "Horse carriage.", "category": "通用词汇"},
        {"english": "carry", "phonetic": "/ˈkæri/", "chinese": "v. 携带", "example": "Carry bag.", "category": "通用词汇"},
        {"english": "cart", "phonetic": "/kɑːrt/", "chinese": "n. 购物车", "example": "Shopping cart.", "category": "通用词汇"},
        {"english": "cartoon", "phonetic": "/kɑːrˈtuːn/", "chinese": "n. 卡通", "example": "Watch cartoon.", "category": "通用词汇"},
        {"english": "carve", "phonetic": "/kɑːrv/", "chinese": "v. 雕刻", "example": "Carve wood.", "category": "通用词汇"},
        {"english": "case", "phonetic": "/keɪs/", "chinese": "n. 情况", "example": "In case.", "category": "通用词汇"},
        {"english": "cash", "phonetic": "/kæʃ/", "chinese": "n. 现金", "example": "Pay cash.", "category": "通用词汇"},
        {"english": "cast", "phonetic": "/kæst/", "chinese": "v. 投射", "example": "Cast vote.", "category": "通用词汇"},
        {"english": "castle", "phonetic": "/ˈkæsl/", "chinese": "n. 城堡", "example": "Old castle.", "category": "通用词汇"},
        {"english": "casual", "phonetic": "/ˈkæʒuəl/", "chinese": "adj. 随意的", "example": "Casual dress.", "category": "通用词汇"},
        {"english": "cat", "phonetic": "/kæt/", "chinese": "n. 猫", "example": "Pet cat.", "category": "通用词汇"},
        {"english": "catalog", "phonetic": "/ˈkætəlɔːɡ/", "chinese": "n. 目录", "example": "Product catalog.", "category": "通用词汇"},
        {"english": "catch", "phonetic": "/kætʃ/", "chinese": "v. 抓住", "example": "Catch ball.", "category": "通用词汇"},
        {"english": "category", "phonetic": "/ˈkætəɡɔːri/", "chinese": "n. 类别", "example": "Product category.", "category": "通用词汇"},
        {"english": "cause", "phonetic": "/kɔːz/", "chinese": "n. 原因", "example": "Root cause.", "category": "通用词汇"},
        {"english": "caution", "phonetic": "/ˈkɔːʃn/", "chinese": "n. 警告", "example": "Use caution.", "category": "通用词汇"},
        {"english": "cave", "phonetic": "/keɪv/", "chinese": "n. 洞穴", "example": "Dark cave.", "category": "通用词汇"},
        {"english": "cease", "phonetic": "/siːs/", "chinese": "v. 停止", "example": "Cease fire.", "category": "通用词汇"},
        {"english": "ceiling", "phonetic": "/ˈsiːlɪŋ/", "chinese": "n. 天花板", "example": "High ceiling.", "category": "通用词汇"},
        {"english": "celebrate", "phonetic": "/ˈselɪbreɪt/", "chinese": "v. 庆祝", "example": "Celebrate success.", "category": "通用词汇"},
        {"english": "celebration", "phonetic": "/ˌselɪˈbreɪʃn/", "chinese": "n. 庆祝", "example": "Birthday celebration.", "category": "通用词汇"},
        {"english": "cell", "phonetic": "/sel/", "chinese": "n. 细胞", "example": "Blood cell.", "category": "通用词汇"},
        {"english": "cellar", "phonetic": "/ˈselər/", "chinese": "n. 地窖", "example": "Wine cellar.", "category": "通用词汇"},
        {"english": "cement", "phonetic": "/sɪˈment/", "chinese": "n. 水泥", "example": "Cement floor.", "category": "通用词汇"},
        {"english": "cemetery", "phonetic": "/ˈseməteri/", "chinese": "n. 墓地", "example": "Old cemetery.", "category": "通用词汇"},
        {"english": "census", "phonetic": "/ˈsensəs/", "chinese": "n. 人口普查", "example": "National census.", "category": "通用词汇"},
        {"english": "cent", "phonetic": "/sent/", "chinese": "n. 分", "example": "Five cents.", "category": "通用词汇"},
        {"english": "center", "phonetic": "/ˈsentər/", "chinese": "n. 中心", "example": "City center.", "category": "通用词汇"},
        {"english": "central", "phonetic": "/ˈsentrəl/", "chinese": "adj. 中央的", "example": "Central bank.", "category": "通用词汇"},
        {"english": "century", "phonetic": "/ˈsentʃuri/", "chinese": "n. 世纪", "example": "21st century.", "category": "通用词汇"},
        {"english": "ceremony", "phonetic": "/ˈserəmoʊni/", "chinese": "n. 仪式", "example": "Wedding ceremony.", "category": "通用词汇"},
        {"english": "certain", "phonetic": "/ˈsɜːrtn/", "chinese": "adj. 确定的", "example": "Certain result.", "category": "通用词汇"},
        {"english": "certificate", "phonetic": "/sərˈtɪfɪkət/", "chinese": "n. 证书", "example": "Birth certificate.", "category": "通用词汇"},
        {"english": "chain", "phonetic": "/tʃeɪn/", "chinese": "n. 链条", "example": "Gold chain.", "category": "通用词汇"},
        {"english": "chair", "phonetic": "/tʃer/", "chinese": "n. 椅子", "example": "Sit on chair.", "category": "通用词汇"},
        {"english": "chairman", "phonetic": "/ˈtʃermən/", "chinese": "n. 主席", "example": "Board chairman.", "category": "通用词汇"},
        {"english": "chalk", "phonetic": "/tʃɔːk/", "chinese": "n. 粉笔", "example": "Write with chalk.", "category": "通用词汇"},
        {"english": "challenge", "phonetic": "/ˈtʃælɪndʒ/", "chinese": "n. 挑战", "example": "Face challenge.", "category": "通用词汇"},
        {"english": "chamber", "phonetic": "/ˈtʃeɪmbər/", "chinese": "n. 房间", "example": "Council chamber.", "category": "通用词汇"},
        {"english": "champion", "phonetic": "/ˈtʃæmpiən/", "chinese": "n. 冠军", "example": "World champion.", "category": "通用词汇"},
        {"english": "chance", "phonetic": "/tʃæns/", "chinese": "n. 机会", "example": "Take chance.", "category": "通用词汇"},
        {"english": "change", "phonetic": "/tʃeɪndʒ/", "chinese": "v. 改变", "example": "Change plan.", "category": "通用词汇"},
        {"english": "channel", "phonetic": "/ˈtʃænl/", "chinese": "n. 频道", "example": "TV channel.", "category": "通用词汇"},
        {"english": "chaos", "phonetic": "/ˈkeɪɑːs/", "chinese": "n. 混乱", "example": "Total chaos.", "category": "通用词汇"},
        {"english": "chapter", "phonetic": "/ˈtʃæptər/", "chinese": "n. 章节", "example": "Read chapter.", "category": "通用词汇"},
        {"english": "character", "phonetic": "/ˈkærəktər/", "chinese": "n. 性格", "example": "Strong character.", "category": "通用词汇"},
        {"english": "charge", "phonetic": "/tʃɑːrdʒ/", "chinese": "v. 收费", "example": "Charge fee.", "category": "通用词汇"},
        {"english": "charity", "phonetic": "/ˈtʃærəti/", "chinese": "n. 慈善", "example": "Charity work.", "category": "通用词汇"},
        {"english": "charm", "phonetic": "/tʃɑːrm/", "chinese": "n. 魅力", "example": "Personal charm.", "category": "通用词汇"},
        {"english": "chart", "phonetic": "/tʃɑːrt/", "chinese": "n. 图表", "example": "Bar chart.", "category": "通用词汇"},
        {"english": "chase", "phonetic": "/tʃeɪs/", "chinese": "v. 追逐", "example": "Chase dream.", "category": "通用词汇"},
        {"english": "chat", "phonetic": "/tʃæt/", "chinese": "v. 聊天", "example": "Chat online.", "category": "通用词汇"},
        {"english": "cheap", "phonetic": "/tʃiːp/", "chinese": "adj. 便宜的", "example": "Cheap price.", "category": "通用词汇"},
        {"english": "cheat", "phonetic": "/tʃiːt/", "chinese": "v. 欺骗", "example": "Cheat on test.", "category": "通用词汇"},
        {"english": "check", "phonetic": "/tʃek/", "chinese": "v. 检查", "example": "Check email.", "category": "通用词汇"},
        {"english": "cheek", "phonetic": "/tʃiːk/", "chinese": "n. 脸颊", "example": "Rosy cheek.", "category": "通用词汇"},
        {"english": "cheer", "phonetic": "/tʃɪr/", "chinese": "v. 欢呼", "example": "Cheer for team.", "category": "通用词汇"},
        {"english": "cheese", "phonetic": "/tʃiːz/", "chinese": "n. 奶酪", "example": "Eat cheese.", "category": "通用词汇"},
        {"english": "chef", "phonetic": "/ʃef/", "chinese": "n. 厨师", "example": "Head chef.", "category": "通用词汇"},
        {"english": "chemical", "phonetic": "/ˈkemɪkl/", "chinese": "n. 化学品", "example": "Chemical reaction.", "category": "通用词汇"},
        {"english": "chemistry", "phonetic": "/ˈkemɪstri/", "chinese": "n. 化学", "example": "Study chemistry.", "category": "通用词汇"},
        {"english": "cheque", "phonetic": "/tʃek/", "chinese": "n. 支票", "example": "Write cheque.", "category": "通用词汇"},
        {"english": "cherry", "phonetic": "/ˈtʃeri/", "chinese": "n. 樱桃", "example": "Eat cherry.", "category": "通用词汇"},
        {"english": "chess", "phonetic": "/tʃes/", "chinese": "n. 国际象棋", "example": "Play chess.", "category": "通用词汇"},
        {"english": "chest", "phonetic": "/tʃest/", "chinese": "n. 胸部", "example": "Chest pain.", "category": "通用词汇"},
        {"english": "chew", "phonetic": "/tʃuː/", "chinese": "v. 咀嚼", "example": "Chew food.", "category": "通用词汇"},
        {"english": "chicken", "phonetic": "/ˈtʃɪkɪn/", "chinese": "n. 鸡肉", "example": "Cook chicken.", "category": "通用词汇"},
        {"english": "chief", "phonetic": "/tʃiːf/", "chinese": "n. 首领", "example": "Police chief.", "category": "通用词汇"},
        {"english": "child", "phonetic": "/tʃaɪld/", "chinese": "n. 孩子", "example": "Young child.", "category": "通用词汇"},
        {"english": "childhood", "phonetic": "/ˈtʃaɪldhʊd/", "chinese": "n. 童年", "example": "Happy childhood.", "category": "通用词汇"},
        {"english": "chill", "phonetic": "/tʃɪl/", "chinese": "n. 寒冷", "example": "Catch chill.", "category": "通用词汇"},
        {"english": "chimney", "phonetic": "/ˈtʃɪmni/", "chinese": "n. 烟囱", "example": "Clean chimney.", "category": "通用词汇"},
        {"english": "chin", "phonetic": "/tʃɪn/", "chinese": "n. 下巴", "example": "Lift chin.", "category": "通用词汇"},
        {"english": "china", "phonetic": "/ˈtʃaɪnə/", "chinese": "n. 瓷器", "example": "Fine china.", "category": "通用词汇"},
        {"english": "chip", "phonetic": "/tʃɪp/", "chinese": "n. 薯片", "example": "Eat chips.", "category": "通用词汇"},
        {"english": "chocolate", "phonetic": "/ˈtʃɔːklət/", "chinese": "n. 巧克力", "example": "Dark chocolate.", "category": "通用词汇"},
        {"english": "choice", "phonetic": "/tʃɔɪs/", "chinese": "n. 选择", "example": "Make choice.", "category": "通用词汇"},
        {"english": "choose", "phonetic": "/tʃuːz/", "chinese": "v. 选择", "example": "Choose wisely.", "category": "通用词汇"},
        {"english": "chop", "phonetic": "/tʃɑːp/", "chinese": "v. 切", "example": "Chop vegetables.", "category": "通用词汇"},
        {"english": "chorus", "phonetic": "/ˈkɔːrəs/", "chinese": "n. 合唱", "example": "Join chorus.", "category": "通用词汇"},
        {"english": "Christian", "phonetic": "/ˈkrɪstʃən/", "chinese": "n. 基督徒", "example": "Christian faith.", "category": "通用词汇"},
        {"english": "Christmas", "phonetic": "/ˈkrɪsməs/", "chinese": "n. 圣诞节", "example": "Merry Christmas.", "category": "通用词汇"},
        {"english": "church", "phonetic": "/tʃɜːrtʃ/", "chinese": "n. 教堂", "example": "Go to church.", "category": "通用词汇"},
        {"english": "cigarette", "phonetic": "/ˌsɪɡəˈret/", "chinese": "n. 香烟", "example": "Smoke cigarette.", "category": "通用词汇"},
        {"english": "cinema", "phonetic": "/ˈsɪnəmə/", "chinese": "n. 电影院", "example": "Go to cinema.", "category": "通用词汇"},
        {"english": "circle", "phonetic": "/ˈsɜːrkl/", "chinese": "n. 圆圈", "example": "Draw circle.", "category": "通用词汇"},
        {"english": "circumstance", "phonetic": "/ˈsɜːrkəmstæns/", "chinese": "n. 情况", "example": "Under circumstance.", "category": "通用词汇"},
        {"english": "circus", "phonetic": "/ˈsɜːrkəs/", "chinese": "n. 马戏团", "example": "Watch circus.", "category": "通用词汇"},
        {"english": "citizen", "phonetic": "/ˈsɪtɪzn/", "chinese": "n. 公民", "example": "Good citizen.", "category": "通用词汇"},
        {"english": "city", "phonetic": "/ˈsɪti/", "chinese": "n. 城市", "example": "Big city.", "category": "通用词汇"},
        {"english": "civil", "phonetic": "/ˈsɪvl/", "chinese": "adj. 民事的", "example": "Civil war.", "category": "通用词汇"},
        {"english": "civilization", "phonetic": "/ˌsɪvəlaɪˈzeɪʃn/", "chinese": "n. 文明", "example": "Human civilization.", "category": "通用词汇"},
        {"english": "claim", "phonetic": "/kleɪm/", "chinese": "v. 声称", "example": "Make claim.", "category": "通用词汇"},
        {"english": "clap", "phonetic": "/klæp/", "chinese": "v. 鼓掌", "example": "Clap hands.", "category": "通用词汇"},
        {"english": "clarify", "phonetic": "/ˈklærəfaɪ/", "chinese": "v. 澄清", "example": "Clarify point.", "category": "通用词汇"},
        {"english": "clash", "phonetic": "/klæʃ/", "chinese": "n. 冲突", "example": "Cultural clash.", "category": "通用词汇"},
        {"english": "class", "phonetic": "/klæs/", "chinese": "n. 班级", "example": "Attend class.", "category": "通用词汇"},
        {"english": "classic", "phonetic": "/ˈklæsɪk/", "chinese": "adj. 经典的", "example": "Classic movie.", "category": "通用词汇"},
        {"english": "classroom", "phonetic": "/ˈklæsruːm/", "chinese": "n. 教室", "example": "In classroom.", "category": "通用词汇"},
        {"english": "claw", "phonetic": "/klɔː/", "chinese": "n. 爪子", "example": "Sharp claw.", "category": "通用词汇"},
        {"english": "clay", "phonetic": "/kleɪ/", "chinese": "n. 黏土", "example": "Wet clay.", "category": "通用词汇"},
        {"english": "clean", "phonetic": "/kliːn/", "chinese": "adj. 干净的", "example": "Clean room.", "category": "通用词汇"},
        {"english": "clear", "phonetic": "/klɪr/", "chinese": "adj. 清楚的", "example": "Clear answer.", "category": "通用词汇"},
        {"english": "clerk", "phonetic": "/klɜːrk/", "chinese": "n. 职员", "example": "Office clerk.", "category": "通用词汇"},
        {"english": "clever", "phonetic": "/ˈklevər/", "chinese": "adj. 聪明的", "example": "Clever idea.", "category": "通用词汇"},
        {"english": "click", "phonetic": "/klɪk/", "chinese": "v. 点击", "example": "Click button.", "category": "通用词汇"},
        {"english": "client", "phonetic": "/ˈklaɪənt/", "chinese": "n. 客户", "example": "New client.", "category": "通用词汇"},
        {"english": "cliff", "phonetic": "/klɪf/", "chinese": "n. 悬崖", "example": "High cliff.", "category": "通用词汇"},
        {"english": "climate", "phonetic": "/ˈklaɪmət/", "chinese": "n. 气候", "example": "Tropical climate.", "category": "通用词汇"},
        {"english": "climb", "phonetic": "/klaɪm/", "chinese": "v. 攀爬", "example": "Climb mountain.", "category": "通用词汇"},
        {"english": "clock", "phonetic": "/klɑːk/", "chinese": "n. 时钟", "example": "Wall clock.", "category": "通用词汇"},
        {"english": "close", "phonetic": "/kloʊz/", "chinese": "v. 关闭", "example": "Close door.", "category": "通用词汇"},
        {"english": "cloth", "phonetic": "/klɔːθ/", "chinese": "n. 布料", "example": "Piece of cloth.", "category": "通用词汇"},
        {"english": "clothes", "phonetic": "/kloʊðz/", "chinese": "n. 衣服", "example": "Wear clothes.", "category": "通用词汇"},
        {"english": "cloud", "phonetic": "/klaʊd/", "chinese": "n. 云", "example": "Dark cloud.", "category": "通用词汇"},
        {"english": "cloudy", "phonetic": "/ˈklaʊdi/", "chinese": "adj. 多云的", "example": "Cloudy day.", "category": "通用词汇"},
        {"english": "club", "phonetic": "/klʌb/", "chinese": "n. 俱乐部", "example": "Join club.", "category": "通用词汇"},
        {"english": "clue", "phonetic": "/kluː/", "chinese": "n. 线索", "example": "Find clue.", "category": "通用词汇"},
        {"english": "coach", "phonetic": "/koʊtʃ/", "chinese": "n. 教练", "example": "Sports coach.", "category": "通用词汇"},
        {"english": "coal", "phonetic": "/koʊl/", "chinese": "n. 煤炭", "example": "Burn coal.", "category": "通用词汇"},
        {"english": "coast", "phonetic": "/koʊst/", "chinese": "n. 海岸", "example": "East coast.", "category": "通用词汇"},
        {"english": "coat", "phonetic": "/koʊt/", "chinese": "n. 外套", "example": "Wear coat.", "category": "通用词汇"},
        {"english": "cock", "phonetic": "/kɑːk/", "chinese": "n. 公鸡", "example": "Rooster cock.", "category": "通用词汇"},
        {"english": "code", "phonetic": "/koʊd/", "chinese": "n. 代码", "example": "Write code.", "category": "通用词汇"},
        {"english": "coffee", "phonetic": "/ˈkɔːfi/", "chinese": "n. 咖啡", "example": "Drink coffee.", "category": "通用词汇"},
        {"english": "coil", "phonetic": "/kɔɪl/", "chinese": "n. 线圈", "example": "Copper coil.", "category": "通用词汇"},
        {"english": "coin", "phonetic": "/kɔɪn/", "chinese": "n. 硬币", "example": "Gold coin.", "category": "通用词汇"},
        {"english": "cold", "phonetic": "/koʊld/", "chinese": "adj. 冷的", "example": "Cold water.", "category": "通用词汇"},
        {"english": "collar", "phonetic": "/ˈkɑːlər/", "chinese": "n. 衣领", "example": "White collar.", "category": "通用词汇"},
        {"english": "colleague", "phonetic": "/ˈkɑːliːɡ/", "chinese": "n. 同事", "example": "Work colleague.", "category": "通用词汇"},
        {"english": "collect", "phonetic": "/kəˈlekt/", "chinese": "v. 收集", "example": "Collect stamps.", "category": "通用词汇"},
        {"english": "collection", "phonetic": "/kəˈlekʃn/", "chinese": "n. 收集", "example": "Art collection.", "category": "通用词汇"},
        {"english": "college", "phonetic": "/ˈkɑːlɪdʒ/", "chinese": "n. 大学", "example": "Go to college.", "category": "通用词汇"},
        {"english": "collision", "phonetic": "/kəˈlɪʒn/", "chinese": "n. 碰撞", "example": "Car collision.", "category": "通用词汇"},
        {"english": "colonial", "phonetic": "/kəˈloʊniəl/", "chinese": "adj. 殖民的", "example": "Colonial period.", "category": "通用词汇"},
        {"english": "colony", "phonetic": "/ˈkɑːləni/", "chinese": "n. 殖民地", "example": "Former colony.", "category": "通用词汇"},
        {"english": "color", "phonetic": "/ˈkʌlər/", "chinese": "n. 颜色", "example": "Bright color.", "category": "通用词汇"},
        {"english": "column", "phonetic": "/ˈkɑːləm/", "chinese": "n. 柱子", "example": "Stone column.", "category": "通用词汇"},
        {"english": "comb", "phonetic": "/koʊm/", "chinese": "n. 梳子", "example": "Use comb.", "category": "通用词汇"},
        {"english": "combat", "phonetic": "/ˈkɑːmbæt/", "chinese": "n. 战斗", "example": "Close combat.", "category": "通用词汇"},
        {"english": "combine", "phonetic": "/kəmˈbaɪn/", "chinese": "v. 结合", "example": "Combine forces.", "category": "通用词汇"},
        {"english": "come", "phonetic": "/kʌm/", "chinese": "v. 来", "example": "Come here.", "category": "通用词汇"},
        {"english": "comedy", "phonetic": "/ˈkɑːmədi/", "chinese": "n. 喜剧", "example": "Watch comedy.", "category": "通用词汇"},
        {"english": "comfort", "phonetic": "/ˈkʌmfərt/", "chinese": "n. 舒适", "example": "Find comfort.", "category": "通用词汇"},
        {"english": "comfortable", "phonetic": "/ˈkʌmfərtəbl/", "chinese": "adj. 舒适的", "example": "Comfortable chair.", "category": "通用词汇"},
        {"english": "comic", "phonetic": "/ˈkɑːmɪk/", "chinese": "n. 漫画", "example": "Read comic.", "category": "通用词汇"},
        {"english": "command", "phonetic": "/kəˈmænd/", "chinese": "n. 命令", "example": "Give command.", "category": "通用词汇"},
        {"english": "comment", "phonetic": "/ˈkɑːment/", "chinese": "n. 评论", "example": "Leave comment.", "category": "通用词汇"},
        {"english": "commercial", "phonetic": "/kəˈmɜːrʃl/", "chinese": "adj. 商业的", "example": "Commercial bank.", "category": "通用词汇"},
        {"english": "common", "phonetic": "/ˈkɑːmən/", "chinese": "adj. 共同的", "example": "Common interest.", "category": "通用词汇"},
        {"english": "communicate", "phonetic": "/kəˈmjuːnɪkeɪt/", "chinese": "v. 交流", "example": "Communicate well.", "category": "通用词汇"},
        {"english": "communication", "phonetic": "/kəˌmjuːnɪˈkeɪʃn/", "chinese": "n. 交流", "example": "Good communication.", "category": "通用词汇"},
        {"english": "community", "phonetic": "/kəˈmjuːnəti/", "chinese": "n. 社区", "example": "Local community.", "category": "通用词汇"},
        {"english": "company", "phonetic": "/ˈkʌmpəni/", "chinese": "n. 公司", "example": "Big company.", "category": "通用词汇"},
        {"english": "compare", "phonetic": "/kəmˈper/", "chinese": "v. 比较", "example": "Compare prices.", "category": "通用词汇"},
        {"english": "comparison", "phonetic": "/kəmˈpærɪsn/", "chinese": "n. 比较", "example": "Make comparison.", "category": "通用词汇"},
        {"english": "compete", "phonetic": "/kəmˈpiːt/", "chinese": "v. 竞争", "example": "Compete hard.", "category": "通用词汇"},
        {"english": "competition", "phonetic": "/ˌkɑːmpəˈtɪʃn/", "chinese": "n. 竞争", "example": "Fierce competition.", "category": "通用词汇"},
        {"english": "complete", "phonetic": "/kəmˈpliːt/", "chinese": "adj. 完整的", "example": "Complete set.", "category": "通用词汇"},
        {"english": "complex", "phonetic": "/kəmˈpleks/", "chinese": "adj. 复杂的", "example": "Complex problem.", "category": "通用词汇"},
        {"english": "complicated", "phonetic": "/ˈkɑːmplɪkeɪtɪd/", "chinese": "adj. 复杂的", "example": "Complicated situation.", "category": "通用词汇"},
        {"english": "component", "phonetic": "/kəmˈpoʊnənt/", "chinese": "n. 组件", "example": "Key component.", "category": "通用词汇"},
        {"english": "compose", "phonetic": "/kəmˈpoʊz/", "chinese": "v. 组成", "example": "Compose music.", "category": "通用词汇"},
        {"english": "composition", "phonetic": "/ˌkɑːmpəˈzɪʃn/", "chinese": "n. 作文", "example": "Write composition.", "category": "通用词汇"},
        {"english": "compound", "phonetic": "/ˈkɑːmpaʊnd/", "chinese": "n. 化合物", "example": "Chemical compound.", "category": "通用词汇"},
        {"english": "comprehend", "phonetic": "/ˌkɑːmprɪˈhend/", "chinese": "v. 理解", "example": "Comprehend text.", "category": "通用词汇"},
        {"english": "comprehensive", "phonetic": "/ˌkɑːmprɪˈhensɪv/", "chinese": "adj. 全面的", "example": "Comprehensive plan.", "category": "通用词汇"},
        {"english": "compress", "phonetic": "/kəmˈpres/", "chinese": "v. 压缩", "example": "Compress file.", "category": "通用词汇"},
        {"english": "comprise", "phonetic": "/kəmˈpraɪz/", "chinese": "v. 包含", "example": "Comprise many.", "category": "通用词汇"},
        {"english": "compute", "phonetic": "/kəmˈpjuːt/", "chinese": "v. 计算", "example": "Compute data.", "category": "通用词汇"},
        {"english": "computer", "phonetic": "/kəmˈpjuːtər/", "chinese": "n. 电脑", "example": "Use computer.", "category": "通用词汇"},
        {"english": "concentrate", "phonetic": "/ˈkɑːnsntreɪt/", "chinese": "v. 集中", "example": "Concentrate hard.", "category": "通用词汇"},
        {"english": "concept", "phonetic": "/ˈkɑːnsept/", "chinese": "n. 概念", "example": "Basic concept.", "category": "通用词汇"},
        {"english": "concern", "phonetic": "/kənˈsɜːrn/", "chinese": "n. 担心", "example": "Express concern.", "category": "通用词汇"},
        {"english": "concert", "phonetic": "/ˈkɑːnsərt/", "chinese": "n. 音乐会", "example": "Attend concert.", "category": "通用词汇"},
        {"english": "conclude", "phonetic": "/kənˈkluːd/", "chinese": "v. 结论", "example": "Conclude meeting.", "category": "通用词汇"},
        {"english": "conclusion", "phonetic": "/kənˈkluːʒn/", "chinese": "n. 结论", "example": "Draw conclusion.", "category": "通用词汇"},
        {"english": "concrete", "phonetic": "/ˈkɑːnkriːt/", "chinese": "n. 混凝土", "example": "Concrete wall.", "category": "通用词汇"},
        {"english": "condemn", "phonetic": "/kənˈdem/", "chinese": "v. 谴责", "example": "Condemn action.", "category": "通用词汇"},
        {"english": "condition", "phonetic": "/kənˈdɪʃn/", "chinese": "n. 条件", "example": "Good condition.", "category": "通用词汇"},
        {"english": "conduct", "phonetic": "/kənˈdʌkt/", "chinese": "v. 进行", "example": "Conduct survey.", "category": "通用词汇"},
        {"english": "conductor", "phonetic": "/kənˈdʌktər/", "chinese": "n. 指挥", "example": "Train conductor.", "category": "通用词汇"},
        {"english": "conference", "phonetic": "/ˈkɑːnfərəns/", "chinese": "n. 会议", "example": "Press conference.", "category": "通用词汇"},
        {"english": "confess", "phonetic": "/kənˈfes/", "chinese": "v. 坦白", "example": "Confess crime.", "category": "通用词汇"},
        {"english": "confidence", "phonetic": "/ˈkɑːnfɪdəns/", "chinese": "n. 自信", "example": "Build confidence.", "category": "通用词汇"},
        {"english": "confident", "phonetic": "/ˈkɑːnfɪdənt/", "chinese": "adj. 自信的", "example": "Confident smile.", "category": "通用词汇"},
        {"english": "confine", "phonetic": "/kənˈfaɪn/", "chinese": "v. 限制", "example": "Confine space.", "category": "通用词汇"},
        {"english": "confirm", "phonetic": "/kənˈfɜːrm/", "chinese": "v. 确认", "example": "Confirm date.", "category": "通用词汇"},
        {"english": "conflict", "phonetic": "/ˈkɑːnflɪkt/", "chinese": "n. 冲突", "example": "Resolve conflict.", "category": "通用词汇"},
        {"english": "confuse", "phonetic": "/kənˈfjuːz/", "chinese": "v. 困惑", "example": "Confuse issue.", "category": "通用词汇"},
        {"english": "congratulate", "phonetic": "/kənˈɡrætʃʊleɪt/", "chinese": "v. 祝贺", "example": "Congratulate winner.", "category": "通用词汇"},
        {"english": "congress", "phonetic": "/ˈkɑːŋɡrəs/", "chinese": "n. 国会", "example": "US Congress.", "category": "通用词汇"},
        {"english": "conjunction", "phonetic": "/kənˈdʒʌŋkʃn/", "chinese": "n. 连词", "example": "Use conjunction.", "category": "通用词汇"},
        {"english": "connect", "phonetic": "/kəˈnekt/", "chinese": "v. 连接", "example": "Connect wire.", "category": "通用词汇"},
        {"english": "connection", "phonetic": "/kəˈnekʃn/", "chinese": "n. 连接", "example": "Internet connection.", "category": "通用词汇"},
        {"english": "conquer", "phonetic": "/ˈkɑːŋkər/", "chinese": "v. 征服", "example": "Conquer fear.", "category": "通用词汇"},
        {"english": "conquest", "phonetic": "/ˈkɑːŋkwest/", "chinese": "n. 征服", "example": "Military conquest.", "category": "通用词汇"},
        {"english": "conscience", "phonetic": "/ˈkɑːnʃəns/", "chinese": "n. 良心", "example": "Clear conscience.", "category": "通用词汇"},
        {"english": "conscious", "phonetic": "/ˈkɑːnʃəs/", "chinese": "adj. 有意识的", "example": "Conscious decision.", "category": "通用词汇"},
        {"english": "consent", "phonetic": "/kənˈsent/", "chinese": "n. 同意", "example": "Give consent.", "category": "通用词汇"},
        {"english": "consequence", "phonetic": "/ˈkɑːnsɪkwens/", "chinese": "n. 后果", "example": "Face consequence.", "category": "通用词汇"},
        {"english": "consequently", "phonetic": "/ˈkɑːnsɪkwentli/", "chinese": "adv. 因此", "example": "Consequently fail.", "category": "通用词汇"},
        {"english": "conservation", "phonetic": "/ˌkɑːnsərˈveɪʃn/", "chinese": "n. 保护", "example": "Wildlife conservation.", "category": "通用词汇"},
        {"english": "conservative", "phonetic": "/kənˈsɜːrvətɪv/", "chinese": "adj. 保守的", "example": "Conservative view.", "category": "通用词汇"},
        {"english": "consider", "phonetic": "/kənˈsɪdər/", "chinese": "v. 考虑", "example": "Consider option.", "category": "通用词汇"},
        {"english": "considerable", "phonetic": "/kənˈsɪdərəbl/", "chinese": "adj. 相当大的", "example": "Considerable amount.", "category": "通用词汇"},
        {"english": "considerate", "phonetic": "/kənˈsɪdərət/", "chinese": "adj. 体贴的", "example": "Considerate person.", "category": "通用词汇"},
        {"english": "consideration", "phonetic": "/kənˌsɪdəˈreɪʃn/", "chinese": "n. 考虑", "example": "Take consideration.", "category": "通用词汇"},
        {"english": "consist", "phonetic": "/kənˈsɪst/", "chinese": "v. 由...组成", "example": "Consist of.", "category": "通用词汇"},
        {"english": "consistent", "phonetic": "/kənˈsɪstənt/", "chinese": "adj. 一致的", "example": "Consistent result.", "category": "通用词汇"},
        {"english": "constant", "phonetic": "/ˈkɑːnstənt/", "chinese": "adj. 持续的", "example": "Constant effort.", "category": "通用词汇"},
        {"english": "constantly", "phonetic": "/ˈkɑːnstəntli/", "chinese": "adv. 不断地", "example": "Constantly improve.", "category": "通用词汇"},
        {"english": "constitute", "phonetic": "/ˈkɑːnstɪtuːt/", "chinese": "v. 构成", "example": "Constitute team.", "category": "通用词汇"},
        {"english": "constitution", "phonetic": "/ˌkɑːnstɪˈtuːʃn/", "chinese": "n. 宪法", "example": "US Constitution.", "category": "通用词汇"},
        {"english": "construct", "phonetic": "/kənˈstrʌkt/", "chinese": "v. 建造", "example": "Construct building.", "category": "通用词汇"},
        {"english": "construction", "phonetic": "/kənˈstrʌkʃn/", "chinese": "n. 建造", "example": "Under construction.", "category": "通用词汇"},
        {"english": "consult", "phonetic": "/kənˈsʌlt/", "chinese": "v. 咨询", "example": "Consult doctor.", "category": "通用词汇"},
        {"english": "consultant", "phonetic": "/kənˈsʌltənt/", "chinese": "n. 顾问", "example": "Business consultant.", "category": "通用词汇"},
        {"english": "consume", "phonetic": "/kənˈsuːm/", "chinese": "v. 消费", "example": "Consume energy.", "category": "通用词汇"},
        {"english": "consumer", "phonetic": "/kənˈsuːmər/", "chinese": "n. 消费者", "example": "Consumer goods.", "category": "通用词汇"},
        {"english": "contact", "phonetic": "/ˈkɑːntækt/", "chinese": "n. 联系", "example": "Make contact.", "category": "通用词汇"},
        {"english": "contain", "phonetic": "/kənˈteɪn/", "chinese": "v. 包含", "example": "Contain water.", "category": "通用词汇"},
        {"english": "container", "phonetic": "/kənˈteɪnər/", "chinese": "n. 容器", "example": "Storage container.", "category": "通用词汇"},
        {"english": "contemporary", "phonetic": "/kənˈtempəreri/", "chinese": "adj. 当代的", "example": "Contemporary art.", "category": "通用词汇"},
        {"english": "content", "phonetic": "/ˈkɑːntent/", "chinese": "n. 内容", "example": "Website content.", "category": "通用词汇"},
        {"english": "contest", "phonetic": "/ˈkɑːntest/", "chinese": "n. 比赛", "example": "Enter contest.", "category": "通用词汇"},
        {"english": "context", "phonetic": "/ˈkɑːntekst/", "chinese": "n. 上下文", "example": "In context.", "category": "通用词汇"},
        {"english": "continent", "phonetic": "/ˈkɑːntɪnənt/", "chinese": "n. 大陆", "example": "Asian continent.", "category": "通用词汇"},
        {"english": "continue", "phonetic": "/kənˈtɪnjuː/", "chinese": "v. 继续", "example": "Continue work.", "category": "通用词汇"},
        {"english": "continuous", "phonetic": "/kənˈtɪnjuəs/", "chinese": "adj. 连续的", "example": "Continuous rain.", "category": "通用词汇"},
        {"english": "contract", "phonetic": "/ˈkɑːntrækt/", "chinese": "n. 合同", "example": "Sign contract.", "category": "通用词汇"},
        {"english": "contradict", "phonetic": "/ˌkɑːntrəˈdɪkt/", "chinese": "v. 矛盾", "example": "Contradict statement.", "category": "通用词汇"},
        {"english": "contrary", "phonetic": "/ˈkɑːntreri/", "chinese": "adj. 相反的", "example": "Contrary opinion.", "category": "通用词汇"},
        {"english": "contrast", "phonetic": "/ˈkɑːntræst/", "chinese": "n. 对比", "example": "In contrast.", "category": "通用词汇"},
        {"english": "contribute", "phonetic": "/kənˈtrɪbjuːt/", "chinese": "v. 贡献", "example": "Contribute time.", "category": "通用词汇"},
        {"english": "contribution", "phonetic": "/ˌkɑːntrɪˈbjuːʃn/", "chinese": "n. 贡献", "example": "Make contribution.", "category": "通用词汇"},
        {"english": "control", "phonetic": "/kənˈtroʊl/", "chinese": "v. 控制", "example": "Control situation.", "category": "通用词汇"},
        {"english": "controversial", "phonetic": "/ˌkɑːntrəˈvɜːrʃl/", "chinese": "adj. 有争议的", "example": "Controversial topic.", "category": "通用词汇"},
        {"english": "convenience", "phonetic": "/kənˈviːniəns/", "chinese": "n. 便利", "example": "For convenience.", "category": "通用词汇"},
        {"english": "convenient", "phonetic": "/kənˈviːniənt/", "chinese": "adj. 便利的", "example": "Convenient location.", "category": "通用词汇"},
        {"english": "convention", "phonetic": "/kənˈvenʃn/", "chinese": "n. 大会", "example": "Attend convention.", "category": "通用词汇"},
        {"english": "conventional", "phonetic": "/kənˈvenʃənl/", "chinese": "adj. 传统的", "example": "Conventional method.", "category": "通用词汇"},
        {"english": "conversation", "phonetic": "/ˌkɑːnvərˈseɪʃn/", "chinese": "n. 对话", "example": "Have conversation.", "category": "通用词汇"},
        {"english": "conversely", "phonetic": "/ˈkɑːnvɜːrsli/", "chinese": "adv. 相反地", "example": "Conversely true.", "category": "通用词汇"},
        {"english": "conversion", "phonetic": "/kənˈvɜːrʒn/", "chinese": "n. 转换", "example": "Currency conversion.", "category": "通用词汇"},
        {"english": "convert", "phonetic": "/kənˈvɜːrt/", "chinese": "v. 转换", "example": "Convert file.", "category": "通用词汇"},
        {"english": "convey", "phonetic": "/kənˈveɪ/", "chinese": "v. 传达", "example": "Convey message.", "category": "通用词汇"},
        {"english": "convict", "phonetic": "/kənˈvɪkt/", "chinese": "v. 定罪", "example": "Convict criminal.", "category": "通用词汇"},
        {"english": "conviction", "phonetic": "/kənˈvɪkʃn/", "chinese": "n. 定罪", "example": "Strong conviction.", "category": "通用词汇"},
        {"english": "convince", "phonetic": "/kənˈvɪns/", "chinese": "v. 说服", "example": "Convince boss.", "category": "通用词汇"},
        {"english": "cook", "phonetic": "/kʊk/", "chinese": "v. 烹饪", "example": "Cook dinner.", "category": "通用词汇"},
        {"english": "cooking", "phonetic": "/ˈkʊkɪŋ/", "chinese": "n. 烹饪", "example": "Enjoy cooking.", "category": "通用词汇"},
        {"english": "cool", "phonetic": "/kuːl/", "chinese": "adj. 凉爽的", "example": "Cool breeze.", "category": "通用词汇"},
        {"english": "cooperate", "phonetic": "/koʊˈɑːpəreɪt/", "chinese": "v. 合作", "example": "Cooperate well.", "category": "通用词汇"},
        {"english": "cooperation", "phonetic": "/koʊˌɑːpəˈreɪʃn/", "chinese": "n. 合作", "example": "Close cooperation.", "category": "通用词汇"},
        {"english": "coordinate", "phonetic": "/koʊˈɔːrdɪneɪt/", "chinese": "v. 协调", "example": "Coordinate project.", "category": "通用词汇"},
        {"english": "cop", "phonetic": "/kɑːp/", "chinese": "n. 警察", "example": "Call cop.", "category": "通用词汇"},
        {"english": "cope", "phonetic": "/koʊp/", "chinese": "v. 应对", "example": "Cope with stress.", "category": "通用词汇"},
        {"english": "copy", "phonetic": "/ˈkɑːpi/", "chinese": "v. 复制", "example": "Copy file.", "category": "通用词汇"},
        {"english": "copyright", "phonetic": "/ˈkɑːpiraɪt/", "chinese": "n. 版权", "example": "Copyright law.", "category": "通用词汇"},
        {"english": "core", "phonetic": "/kɔːr/", "chinese": "n. 核心", "example": "Core value.", "category": "通用词汇"},
        {"english": "corn", "phonetic": "/kɔːrn/", "chinese": "n. 玉米", "example": "Eat corn.", "category": "通用词汇"},
        {"english": "corner", "phonetic": "/ˈkɔːrnər/", "chinese": "n. 角落", "example": "In corner.", "category": "通用词汇"},
        {"english": "corporate", "phonetic": "/ˈkɔːrpərət/", "chinese": "adj. 企业的", "example": "Corporate world.", "category": "通用词汇"},
        {"english": "corporation", "phonetic": "/ˌkɔːrpəˈreɪʃn/", "chinese": "n. 公司", "example": "Large corporation.", "category": "通用词汇"},
        {"english": "correct", "phonetic": "/kəˈrekt/", "chinese": "adj. 正确的", "example": "Correct answer.", "category": "通用词汇"},
        {"english": "correction", "phonetic": "/kəˈrekʃn/", "chinese": "n. 改正", "example": "Make correction.", "category": "通用词汇"},
        {"english": "correspond", "phonetic": "/ˌkɔːrɪˈspɑːnd/", "chinese": "v. 通信", "example": "Correspond with.", "category": "通用词汇"},
        {"english": "corresponding", "phonetic": "/ˌkɔːrɪˈspɑːndɪŋ/", "chinese": "adj. 相应的", "example": "Corresponding period.", "category": "通用词汇"},
        {"english": "corridor", "phonetic": "/ˈkɔːrɪdɔːr/", "chinese": "n. 走廊", "example": "Long corridor.", "category": "通用词汇"},
        {"english": "cost", "phonetic": "/kɔːst/", "chinese": "n. 成本", "example": "Low cost.", "category": "通用词汇"},
        {"english": "costly", "phonetic": "/ˈkɔːstli/", "chinese": "adj. 昂贵的", "example": "Costly mistake.", "category": "通用词汇"},
        {"english": "costume", "phonetic": "/ˈkɑːstuːm/", "chinese": "n. 服装", "example": "Wear costume.", "category": "通用词汇"},
        {"english": "cottage", "phonetic": "/ˈkɑːtɪdʒ/", "chinese": "n. 小屋", "example": "Summer cottage.", "category": "通用词汇"},
        {"english": "cotton", "phonetic": "/ˈkɑːtn/", "chinese": "n. 棉花", "example": "Cotton shirt.", "category": "通用词汇"},
        {"english": "couch", "phonetic": "/kaʊtʃ/", "chinese": "n. 沙发", "example": "Sit on couch.", "category": "通用词汇"},
        {"english": "cough", "phonetic": "/kɔːf/", "chinese": "v. 咳嗽", "example": "Bad cough.", "category": "通用词汇"},
        {"english": "could", "phonetic": "/kʊd/", "chinese": "v. 能", "example": "Could help.", "category": "通用词汇"},
        {"english": "council", "phonetic": "/ˈkaʊnsəl/", "chinese": "n. 委员会", "example": "City council.", "category": "通用词汇"},
        {"english": "counsel", "phonetic": "/ˈkaʊnsəl/", "chinese": "n. 建议", "example": "Legal counsel.", "category": "通用词汇"},
        {"english": "count", "phonetic": "/kaʊnt/", "chinese": "v. 数", "example": "Count money.", "category": "通用词汇"},
        {"english": "counter", "phonetic": "/ˈkaʊntər/", "chinese": "n. 柜台", "example": "Kitchen counter.", "category": "通用词汇"},
        {"english": "country", "phonetic": "/ˈkʌntri/", "chinese": "n. 国家", "example": "My country.", "category": "通用词汇"},
        {"english": "countryside", "phonetic": "/ˈkʌntrisaɪd/", "chinese": "n. 乡村", "example": "Live in countryside.", "category": "通用词汇"},
        {"english": "county", "phonetic": "/ˈkaʊnti/", "chinese": "n. 县", "example": "Orange County.", "category": "通用词汇"},
        {"english": "couple", "phonetic": "/ˈkʌpl/", "chinese": "n. 夫妇", "example": "Young couple.", "category": "通用词汇"},
        {"english": "courage", "phonetic": "/ˈkɜːrɪdʒ/", "chinese": "n. 勇气", "example": "Show courage.", "category": "通用词汇"},
        {"english": "course", "phonetic": "/kɔːrs/", "chinese": "n. 课程", "example": "Take course.", "category": "通用词汇"},
        {"english": "court", "phonetic": "/kɔːrt/", "chinese": "n. 法院", "example": "Go to court.", "category": "通用词汇"},
        {"english": "courtesy", "phonetic": "/ˈkɜːrtəsi/", "chinese": "n. 礼貌", "example": "Show courtesy.", "category": "通用词汇"},
        {"english": "cousin", "phonetic": "/ˈkʌzn/", "chinese": "n. 堂兄弟", "example": "Visit cousin.", "category": "通用词汇"},
        {"english": "cover", "phonetic": "/ˈkʌvər/", "chinese": "v. 覆盖", "example": "Cover table.", "category": "通用词汇"},
        {"english": "cow", "phonetic": "/kaʊ/", "chinese": "n. 奶牛", "example": "Milk cow.", "category": "通用词汇"},
        {"english": "coward", "phonetic": "/ˈkaʊərd/", "chinese": "n. 懦夫", "example": "Act like coward.", "category": "通用词汇"},
        {"english": "crack", "phonetic": "/kræk/", "chinese": "n. 裂缝", "example": "Crack in wall.", "category": "通用词汇"},
        {"english": "craft", "phonetic": "/kræft/", "chinese": "n. 手工艺", "example": "Make craft.", "category": "通用词汇"},
        {"english": "crane", "phonetic": "/kreɪn/", "chinese": "n. 起重机", "example": "Use crane.", "category": "通用词汇"},
        {"english": "crash", "phonetic": "/kræʃ/", "chinese": "n. 崩溃", "example": "Stock market crash.", "category": "通用词汇"},
        {"english": "crazy", "phonetic": "/ˈkreɪzi/", "chinese": "adj. 疯狂的", "example": "Crazy idea.", "category": "通用词汇"},
        {"english": "cream", "phonetic": "/kriːm/", "chinese": "n. 奶油", "example": "Ice cream.", "category": "通用词汇"},
        {"english": "create", "phonetic": "/kriˈeɪt/", "chinese": "v. 创造", "example": "Create art.", "category": "通用词汇"},
        {"english": "creation", "phonetic": "/kriˈeɪʃn/", "chinese": "n. 创造", "example": "Artistic creation.", "category": "通用词汇"},
        {"english": "creative", "phonetic": "/kriˈeɪtɪv/", "chinese": "adj. 有创造力的", "example": "Creative mind.", "category": "通用词汇"},
        {"english": "creature", "phonetic": "/ˈkriːtʃər/", "chinese": "n. 生物", "example": "Strange creature.", "category": "通用词汇"},
        {"english": "credit", "phonetic": "/ˈkredɪt/", "chinese": "n. 信用", "example": "Good credit.", "category": "通用词汇"},
        {"english": "creep", "phonetic": "/kriːp/", "chinese": "v. 爬行", "example": "Creep forward.", "category": "通用词汇"},
        {"english": "crew", "phonetic": "/kruː/", "chinese": "n. 全体船员", "example": "Ship crew.", "category": "通用词汇"},
        {"english": "crime", "phonetic": "/kraɪm/", "chinese": "n. 犯罪", "example": "Commit crime.", "category": "通用词汇"},
        {"english": "criminal", "phonetic": "/ˈkrɪmɪnl/", "chinese": "n. 罪犯", "example": "Arrest criminal.", "category": "通用词汇"}
    ]
    
    added_count = 0
    for word in new_words:
        cursor.execute('''
            INSERT OR IGNORE INTO words (english, phonetic, chinese, example, category, subcategory)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (word['english'], word['phonetic'], word['chinese'], word['example'], word['category'], ''))
        
        if cursor.rowcount > 0:
            added_count += 1
    
    conn.commit()
    
    cursor.execute('SELECT COUNT(*) FROM words')
    total = cursor.fetchone()[0]
    
    print(f"成功添加 {added_count} 个新单词到数据库")
    print(f"数据库总单词数: {total}")
    
    conn.close()

if __name__ == "__main__":
    expand_to_5000_batch13()
