import sqlite3

def expand_to_5000_batch12():
    conn = sqlite3.connect('../words.db')
    cursor = conn.cursor()
    
    new_words = [
        {"english": "abandon", "phonetic": "/əˈbændən/", "chinese": "v. 放弃", "example": "Abandon project.", "category": "通用词汇"},
        {"english": "ability", "phonetic": "/əˈbɪləti/", "chinese": "n. 能力", "example": "Natural ability.", "category": "通用词汇"},
        {"english": "able", "phonetic": "/ˈeɪbl/", "chinese": "adj. 能够", "example": "Able to work.", "category": "通用词汇"},
        {"english": "about", "phonetic": "/əˈbaʊt/", "chinese": "prep. 关于", "example": "Talk about.", "category": "通用词汇"},
        {"english": "above", "phonetic": "/əˈbʌv/", "chinese": "prep. 在...之上", "example": "Above ground.", "category": "通用词汇"},
        {"english": "abroad", "phonetic": "/əˈbrɔːd/", "chinese": "adv. 在国外", "example": "Study abroad.", "category": "通用词汇"},
        {"english": "absence", "phonetic": "/ˈæbsəns/", "chinese": "n. 缺席", "example": "Absence notice.", "category": "通用词汇"},
        {"english": "absent", "phonetic": "/ˈæbsənt/", "chinese": "adj. 缺席的", "example": "Absent today.", "category": "通用词汇"},
        {"english": "absolute", "phonetic": "/ˈæbsəluːt/", "chinese": "adj. 绝对的", "example": "Absolute power.", "category": "通用词汇"},
        {"english": "absorb", "phonetic": "/əbˈzɔːrb/", "chinese": "v. 吸收", "example": "Absorb water.", "category": "通用词汇"},
        {"english": "abstract", "phonetic": "/ˈæbstrækt/", "chinese": "adj. 抽象的", "example": "Abstract art.", "category": "通用词汇"},
        {"english": "abundant", "phonetic": "/əˈbʌndənt/", "chinese": "adj. 丰富的", "example": "Abundant resources.", "category": "通用词汇"},
        {"english": "abuse", "phonetic": "/əˈbjuːs/", "chinese": "v. 滥用", "example": "Abuse power.", "category": "通用词汇"},
        {"english": "academic", "phonetic": "/ˌækəˈdemɪk/", "chinese": "adj. 学术的", "example": "Academic research.", "category": "通用词汇"},
        {"english": "academy", "phonetic": "/əˈkædəmi/", "chinese": "n. 学院", "example": "Military academy.", "category": "通用词汇"},
        {"english": "accelerate", "phonetic": "/əkˈseləreɪt/", "chinese": "v. 加速", "example": "Accelerate growth.", "category": "通用词汇"},
        {"english": "accent", "phonetic": "/ˈæksent/", "chinese": "n. 口音", "example": "Foreign accent.", "category": "通用词汇"},
        {"english": "accept", "phonetic": "/əkˈsept/", "chinese": "v. 接受", "example": "Accept offer.", "category": "通用词汇"},
        {"english": "access", "phonetic": "/ˈækses/", "chinese": "n. 访问", "example": "Internet access.", "category": "通用词汇"},
        {"english": "accident", "phonetic": "/ˈæksɪdənt/", "chinese": "n. 事故", "example": "Car accident.", "category": "通用词汇"},
        {"english": "accompany", "phonetic": "/əˈkʌmpəni/", "chinese": "v. 陪伴", "example": "Accompany friend.", "category": "通用词汇"},
        {"english": "accomplish", "phonetic": "/əˈkʌmplɪʃ/", "chinese": "v. 完成", "example": "Accomplish goal.", "category": "通用词汇"},
        {"english": "account", "phonetic": "/əˈkaʊnt/", "chinese": "n. 账户", "example": "Bank account.", "category": "通用词汇"},
        {"english": "accurate", "phonetic": "/ˈækjərət/", "chinese": "adj. 准确的", "example": "Accurate data.", "category": "通用词汇"},
        {"english": "accuse", "phonetic": "/əˈkjuːz/", "chinese": "v. 指责", "example": "Accuse someone.", "category": "通用词汇"},
        {"english": "achieve", "phonetic": "/əˈtʃiːv/", "chinese": "v. 实现", "example": "Achieve success.", "category": "通用词汇"},
        {"english": "acquire", "phonetic": "/əˈkwaɪər/", "chinese": "v. 获得", "example": "Acquire knowledge.", "category": "通用词汇"},
        {"english": "across", "phonetic": "/əˈkrɔːs/", "chinese": "prep. 穿过", "example": "Walk across.", "category": "通用词汇"},
        {"english": "action", "phonetic": "/ˈækʃn/", "chinese": "n. 行动", "example": "Take action.", "category": "通用词汇"},
        {"english": "active", "phonetic": "/ˈæktɪv/", "chinese": "adj. 积极的", "example": "Active member.", "category": "通用词汇"},
        {"english": "actual", "phonetic": "/ˈæktʃuəl/", "chinese": "adj. 实际的", "example": "Actual result.", "category": "通用词汇"},
        {"english": "adapt", "phonetic": "/əˈdæpt/", "chinese": "v. 适应", "example": "Adapt to change.", "category": "通用词汇"},
        {"english": "add", "phonetic": "/æd/", "chinese": "v. 添加", "example": "Add ingredient.", "category": "通用词汇"},
        {"english": "addition", "phonetic": "/əˈdɪʃn/", "chinese": "n. 添加", "example": "In addition.", "category": "通用词汇"},
        {"english": "additional", "phonetic": "/əˈdɪʃənl/", "chinese": "adj. 额外的", "example": "Additional cost.", "category": "通用词汇"},
        {"english": "address", "phonetic": "/əˈdres/", "chinese": "n. 地址", "example": "Home address.", "category": "通用词汇"},
        {"english": "adequate", "phonetic": "/ˈædɪkwət/", "chinese": "adj. 充足的", "example": "Adequate supply.", "category": "通用词汇"},
        {"english": "adjust", "phonetic": "/əˈdʒʌst/", "chinese": "v. 调整", "example": "Adjust settings.", "category": "通用词汇"},
        {"english": "administration", "phonetic": "/ədˌmɪnɪˈstreɪʃn/", "chinese": "n. 管理", "example": "Public administration.", "category": "通用词汇"},
        {"english": "admire", "phonetic": "/ədˈmaɪər/", "chinese": "v. 钦佩", "example": "Admire courage.", "category": "通用词汇"},
        {"english": "admit", "phonetic": "/ədˈmɪt/", "chinese": "v. 承认", "example": "Admit mistake.", "category": "通用词汇"},
        {"english": "adopt", "phonetic": "/əˈdɑːpt/", "chinese": "v. 采纳", "example": "Adopt policy.", "category": "通用词汇"},
        {"english": "adult", "phonetic": "/ˈædʌlt/", "chinese": "n. 成年人", "example": "Adult education.", "category": "通用词汇"},
        {"english": "advance", "phonetic": "/ədˈvæns/", "chinese": "v. 前进", "example": "Advance career.", "category": "通用词汇"},
        {"english": "advanced", "phonetic": "/ədˈvænst/", "chinese": "adj. 先进的", "example": "Advanced technology.", "category": "通用词汇"},
        {"english": "advantage", "phonetic": "/ədˈvæntɪdʒ/", "chinese": "n. 优势", "example": "Competitive advantage.", "category": "通用词汇"},
        {"english": "adventure", "phonetic": "/ədˈventʃər/", "chinese": "n. 冒险", "example": "Adventure story.", "category": "通用词汇"},
        {"english": "advertise", "phonetic": "/ˈædvərtaɪz/", "chinese": "v. 广告", "example": "Advertise product.", "category": "通用词汇"},
        {"english": "advice", "phonetic": "/ədˈvaɪs/", "chinese": "n. 建议", "example": "Give advice.", "category": "通用词汇"},
        {"english": "advise", "phonetic": "/ədˈvaɪz/", "chinese": "v. 建议", "example": "Advise client.", "category": "通用词汇"},
        {"english": "affair", "phonetic": "/əˈfer/", "chinese": "n. 事务", "example": "Public affair.", "category": "通用词汇"},
        {"english": "affect", "phonetic": "/əˈfekt/", "chinese": "v. 影响", "example": "Affect decision.", "category": "通用词汇"},
        {"english": "afford", "phonetic": "/əˈfɔːrd/", "chinese": "v. 负担得起", "example": "Afford house.", "category": "通用词汇"},
        {"english": "afraid", "phonetic": "/əˈfreɪd/", "chinese": "adj. 害怕的", "example": "Afraid of dark.", "category": "通用词汇"},
        {"english": "after", "phonetic": "/ˈæftər/", "chinese": "prep. 在...之后", "example": "After work.", "category": "通用词汇"},
        {"english": "afternoon", "phonetic": "/ˌæftərˈnuːn/", "chinese": "n. 下午", "example": "Afternoon tea.", "category": "通用词汇"},
        {"english": "afterward", "phonetic": "/ˈæftərwərd/", "chinese": "adv. 之后", "example": "Call afterward.", "category": "通用词汇"},
        {"english": "again", "phonetic": "/əˈɡen/", "chinese": "adv. 再次", "example": "Try again.", "category": "通用词汇"},
        {"english": "against", "phonetic": "/əˈɡenst/", "chinese": "prep. 反对", "example": "Against rule.", "category": "通用词汇"},
        {"english": "age", "phonetic": "/eɪdʒ/", "chinese": "n. 年龄", "example": "Middle age.", "category": "通用词汇"},
        {"english": "agency", "phonetic": "/ˈeɪdʒənsi/", "chinese": "n. 机构", "example": "Travel agency.", "category": "通用词汇"},
        {"english": "agent", "phonetic": "/ˈeɪdʒənt/", "chinese": "n. 代理人", "example": "Real estate agent.", "category": "通用词汇"},
        {"english": "aggressive", "phonetic": "/əˈɡresɪv/", "chinese": "adj. 侵略性的", "example": "Aggressive behavior.", "category": "通用词汇"},
        {"english": "ago", "phonetic": "/əˈɡoʊ/", "chinese": "adv. 以前", "example": "Long ago.", "category": "通用词汇"},
        {"english": "agree", "phonetic": "/əˈɡriː/", "chinese": "v. 同意", "example": "Agree with you.", "category": "通用词汇"},
        {"english": "agreement", "phonetic": "/əˈɡriːmənt/", "chinese": "n. 协议", "example": "Sign agreement.", "category": "通用词汇"},
        {"english": "agriculture", "phonetic": "/ˈæɡrɪkʌltʃər/", "chinese": "n. 农业", "example": "Modern agriculture.", "category": "通用词汇"},
        {"english": "ahead", "phonetic": "/əˈhed/", "chinese": "adv. 在前面", "example": "Look ahead.", "category": "通用词汇"},
        {"english": "aid", "phonetic": "/eɪd/", "chinese": "n. 援助", "example": "Financial aid.", "category": "通用词汇"},
        {"english": "aim", "phonetic": "/eɪm/", "chinese": "v. 目标", "example": "Aim high.", "category": "通用词汇"},
        {"english": "air", "phonetic": "/er/", "chinese": "n. 空气", "example": "Fresh air.", "category": "通用词汇"},
        {"english": "aircraft", "phonetic": "/ˈerkræft/", "chinese": "n. 飞机", "example": "Military aircraft.", "category": "通用词汇"},
        {"english": "airline", "phonetic": "/ˈerlaɪn/", "chinese": "n. 航空公司", "example": "International airline.", "category": "通用词汇"},
        {"english": "airport", "phonetic": "/ˈerpɔːrt/", "chinese": "n. 机场", "example": "Airport security.", "category": "通用词汇"},
        {"english": "alarm", "phonetic": "/əˈlɑːrm/", "chinese": "n. 警报", "example": "Fire alarm.", "category": "通用词汇"},
        {"english": "album", "phonetic": "/ˈælbəm/", "chinese": "n. 相册", "example": "Photo album.", "category": "通用词汇"},
        {"english": "alcohol", "phonetic": "/ˈælkəhɔːl/", "chinese": "n. 酒精", "example": "Alcohol content.", "category": "通用词汇"},
        {"english": "alert", "phonetic": "/əˈlɜːrt/", "chinese": "adj. 警觉的", "example": "Stay alert.", "category": "通用词汇"},
        {"english": "alien", "phonetic": "/ˈeɪliən/", "chinese": "n. 外星人", "example": "Alien invasion.", "category": "通用词汇"},
        {"english": "alike", "phonetic": "/əˈlaɪk/", "chinese": "adj. 相似的", "example": "Look alike.", "category": "通用词汇"},
        {"english": "alive", "phonetic": "/əˈlaɪv/", "chinese": "adj. 活着的", "example": "Stay alive.", "category": "通用词汇"},
        {"english": "all", "phonetic": "/ɔːl/", "chinese": "pron. 所有", "example": "All ready.", "category": "通用词汇"},
        {"english": "alliance", "phonetic": "/əˈlaɪəns/", "chinese": "n. 联盟", "example": "Military alliance.", "category": "通用词汇"},
        {"english": "allow", "phonetic": "/əˈlaʊ/", "chinese": "v. 允许", "example": "Allow entry.", "category": "通用词汇"},
        {"english": "almost", "phonetic": "/ˈɔːlmoʊst/", "chinese": "adv. 几乎", "example": "Almost finished.", "category": "通用词汇"},
        {"english": "alone", "phonetic": "/əˈloʊn/", "chinese": "adj. 独自的", "example": "Live alone.", "category": "通用词汇"},
        {"english": "along", "phonetic": "/əˈlɔːŋ/", "chinese": "prep. 沿着", "example": "Walk along.", "category": "通用词汇"},
        {"english": "already", "phonetic": "/ɔːlˈredi/", "chinese": "adv. 已经", "example": "Already done.", "category": "通用词汇"},
        {"english": "also", "phonetic": "/ˈɔːlsoʊ/", "chinese": "adv. 也", "example": "Also important.", "category": "通用词汇"},
        {"english": "alter", "phonetic": "/ˈɔːltər/", "chinese": "v. 改变", "example": "Alter plan.", "category": "通用词汇"},
        {"english": "alternative", "phonetic": "/ɔːlˈtɜːrnətɪv/", "chinese": "n. 替代方案", "example": "Alternative energy.", "category": "通用词汇"},
        {"english": "although", "phonetic": "/ɔːlˈðoʊ/", "chinese": "conj. 尽管", "example": "Although tired.", "category": "通用词汇"},
        {"english": "altogether", "phonetic": "/ˌɔːltəˈɡeðər/", "chinese": "adv. 总共", "example": "Altogether now.", "category": "通用词汇"},
        {"english": "always", "phonetic": "/ˈɔːlweɪz/", "chinese": "adv. 总是", "example": "Always late.", "category": "通用词汇"},
        {"english": "amazing", "phonetic": "/əˈmeɪzɪŋ/", "chinese": "adj. 惊人的", "example": "Amazing view.", "category": "通用词汇"},
        {"english": "ambition", "phonetic": "/æmˈbɪʃn/", "chinese": "n. 抱负", "example": "Career ambition.", "category": "通用词汇"},
        {"english": "ambulance", "phonetic": "/ˈæmbjələns/", "chinese": "n. 救护车", "example": "Call ambulance.", "category": "通用词汇"},
        {"english": "among", "phonetic": "/əˈmʌŋ/", "chinese": "prep. 在...之中", "example": "Among friends.", "category": "通用词汇"},
        {"english": "amount", "phonetic": "/əˈmaʊnt/", "chinese": "n. 数量", "example": "Large amount.", "category": "通用词汇"},
        {"english": "analyse", "phonetic": "/ˈænəlaɪz/", "chinese": "v. 分析", "example": "Analyse data.", "category": "通用词汇"},
        {"english": "analysis", "phonetic": "/əˈnæləsɪs/", "chinese": "n. 分析", "example": "Data analysis.", "category": "通用词汇"},
        {"english": "ancient", "phonetic": "/ˈeɪnʃənt/", "chinese": "adj. 古代的", "example": "Ancient history.", "category": "通用词汇"},
        {"english": "anger", "phonetic": "/ˈæŋɡər/", "chinese": "n. 愤怒", "example": "Show anger.", "category": "通用词汇"},
        {"english": "angle", "phonetic": "/ˈæŋɡl/", "chinese": "n. 角度", "example": "Right angle.", "category": "通用词汇"},
        {"english": "angry", "phonetic": "/ˈæŋɡri/", "chinese": "adj. 生气的", "example": "Get angry.", "category": "通用词汇"},
        {"english": "animal", "phonetic": "/ˈænɪml/", "chinese": "n. 动物", "example": "Wild animal.", "category": "通用词汇"},
        {"english": "ankle", "phonetic": "/ˈæŋkl/", "chinese": "n. 脚踝", "example": "Sprained ankle.", "category": "通用词汇"},
        {"english": "announce", "phonetic": "/əˈnaʊns/", "chinese": "v. 宣布", "example": "Announce winner.", "category": "通用词汇"},
        {"english": "annoy", "phonetic": "/əˈnɔɪ/", "chinese": "v. 使烦恼", "example": "Annoy neighbor.", "category": "通用词汇"},
        {"english": "annual", "phonetic": "/ˈænjuəl/", "chinese": "adj. 年度的", "example": "Annual report.", "category": "通用词汇"},
        {"english": "another", "phonetic": "/əˈnʌðər/", "chinese": "pron. 另一个", "example": "Another chance.", "category": "通用词汇"},
        {"english": "answer", "phonetic": "/ˈænsər/", "chinese": "v. 回答", "example": "Answer question.", "category": "通用词汇"},
        {"english": "anticipate", "phonetic": "/ænˈtɪsɪpeɪt/", "chinese": "v. 预期", "example": "Anticipate demand.", "category": "通用词汇"},
        {"english": "anxiety", "phonetic": "/æŋˈzaɪəti/", "chinese": "n. 焦虑", "example": "Social anxiety.", "category": "通用词汇"},
        {"english": "anxious", "phonetic": "/ˈæŋkʃəs/", "chinese": "adj. 焦虑的", "example": "Anxious about exam.", "category": "通用词汇"},
        {"english": "any", "phonetic": "/ˈeni/", "chinese": "pron. 任何", "example": "Any questions?", "category": "通用词汇"},
        {"english": "anybody", "phonetic": "/ˈenibɑːdi/", "chinese": "pron. 任何人", "example": "Anybody home?", "category": "通用词汇"},
        {"english": "anymore", "phonetic": "/ˌeniˈmɔːr/", "chinese": "adv. 不再", "example": "Not anymore.", "category": "通用词汇"},
        {"english": "anyone", "phonetic": "/ˈeniwʌn/", "chinese": "pron. 任何人", "example": "Anyone can join.", "category": "通用词汇"},
        {"english": "anything", "phonetic": "/ˈeniθɪŋ/", "chinese": "pron. 任何事", "example": "Anything else?", "category": "通用词汇"},
        {"english": "anyway", "phonetic": "/ˈeniweɪ/", "chinese": "adv. 无论如何", "example": "Anyway, let's go.", "category": "通用词汇"},
        {"english": "anywhere", "phonetic": "/ˈeniwer/", "chinese": "adv. 任何地方", "example": "Go anywhere.", "category": "通用词汇"},
        {"english": "apart", "phonetic": "/əˈpɑːrt/", "chinese": "adv. 分开", "example": "Live apart.", "category": "通用词汇"},
        {"english": "apartment", "phonetic": "/əˈpɑːrtmənt/", "chinese": "n. 公寓", "example": "Rent apartment.", "category": "通用词汇"},
        {"english": "apparent", "phonetic": "/əˈpærənt/", "chinese": "adj. 明显的", "example": "Apparent reason.", "category": "通用词汇"},
        {"english": "appeal", "phonetic": "/əˈpiːl/", "chinese": "v. 吸引", "example": "Appeal to public.", "category": "通用词汇"},
        {"english": "appear", "phonetic": "/əˈpɪr/", "chinese": "v. 出现", "example": "Appear suddenly.", "category": "通用词汇"},
        {"english": "appearance", "phonetic": "/əˈpɪrəns/", "chinese": "n. 外表", "example": "Physical appearance.", "category": "通用词汇"},
        {"english": "appetite", "phonetic": "/ˈæpɪtaɪt/", "chinese": "n. 胃口", "example": "Good appetite.", "category": "通用词汇"},
        {"english": "apple", "phonetic": "/ˈæpl/", "chinese": "n. 苹果", "example": "Apple pie.", "category": "通用词汇"},
        {"english": "application", "phonetic": "/ˌæplɪˈkeɪʃn/", "chinese": "n. 申请", "example": "Job application.", "category": "通用词汇"},
        {"english": "apply", "phonetic": "/əˈplaɪ/", "chinese": "v. 申请", "example": "Apply for job.", "category": "通用词汇"},
        {"english": "appoint", "phonetic": "/əˈpɔɪnt/", "chinese": "v. 任命", "example": "Appoint manager.", "category": "通用词汇"},
        {"english": "appreciate", "phonetic": "/əˈpriːʃieɪt/", "chinese": "v. 欣赏", "example": "Appreciate art.", "category": "通用词汇"},
        {"english": "approach", "phonetic": "/əˈproʊtʃ/", "chinese": "v. 接近", "example": "Approach problem.", "category": "通用词汇"},
        {"english": "appropriate", "phonetic": "/əˈproʊpriət/", "chinese": "adj. 适当的", "example": "Appropriate behavior.", "category": "通用词汇"},
        {"english": "approve", "phonetic": "/əˈpruːv/", "chinese": "v. 批准", "example": "Approve request.", "category": "通用词汇"},
        {"english": "approximately", "phonetic": "/əˈprɑːksɪmətli/", "chinese": "adv. 大约", "example": "Approximately 100.", "category": "通用词汇"},
        {"english": "architect", "phonetic": "/ˈɑːrkɪtekt/", "chinese": "n. 建筑师", "example": "Famous architect.", "category": "通用词汇"},
        {"english": "area", "phonetic": "/ˈeriə/", "chinese": "n. 区域", "example": "Local area.", "category": "通用词汇"},
        {"english": "argue", "phonetic": "/ˈɑːrɡjuː/", "chinese": "v. 争论", "example": "Argue about price.", "category": "通用词汇"},
        {"english": "argument", "phonetic": "/ˈɑːrɡjumənt/", "chinese": "n. 论点", "example": "Strong argument.", "category": "通用词汇"},
        {"english": "arise", "phonetic": "/əˈraɪz/", "chinese": "v. 出现", "example": "Problems arise.", "category": "通用词汇"},
        {"english": "arm", "phonetic": "/ɑːrm/", "chinese": "n. 手臂", "example": "Broken arm.", "category": "通用词汇"},
        {"english": "army", "phonetic": "/ˈɑːrmi/", "chinese": "n. 军队", "example": "Join army.", "category": "通用词汇"},
        {"english": "around", "phonetic": "/əˈraʊnd/", "chinese": "prep. 围绕", "example": "Around corner.", "category": "通用词汇"},
        {"english": "arrange", "phonetic": "/əˈreɪndʒ/", "chinese": "v. 安排", "example": "Arrange meeting.", "category": "通用词汇"},
        {"english": "arrest", "phonetic": "/əˈrest/", "chinese": "v. 逮捕", "example": "Arrest suspect.", "category": "通用词汇"},
        {"english": "arrival", "phonetic": "/əˈraɪvl/", "chinese": "n. 到达", "example": "Airport arrival.", "category": "通用词汇"},
        {"english": "arrive", "phonetic": "/əˈraɪv/", "chinese": "v. 到达", "example": "Arrive on time.", "category": "通用词汇"},
        {"english": "article", "phonetic": "/ˈɑːrtɪkl/", "chinese": "n. 文章", "example": "News article.", "category": "通用词汇"},
        {"english": "artist", "phonetic": "/ˈɑːrtɪst/", "chinese": "n. 艺术家", "example": "Talented artist.", "category": "通用词汇"},
        {"english": "as", "phonetic": "/æz/", "chinese": "conj. 当...时", "example": "As you wish.", "category": "通用词汇"},
        {"english": "aside", "phonetic": "/əˈsaɪd/", "chinese": "adv. 在旁边", "example": "Step aside.", "category": "通用词汇"},
        {"english": "ask", "phonetic": "/æsk/", "chinese": "v. 询问", "example": "Ask question.", "category": "通用词汇"},
        {"english": "asleep", "phonetic": "/əˈsliːp/", "chinese": "adj. 睡着的", "example": "Fall asleep.", "category": "通用词汇"},
        {"english": "aspect", "phonetic": "/ˈæspekt/", "chinese": "n. 方面", "example": "Positive aspect.", "category": "通用词汇"},
        {"english": "assess", "phonetic": "/əˈses/", "chinese": "v. 评估", "example": "Assess situation.", "category": "通用词汇"},
        {"english": "assignment", "phonetic": "/əˈsaɪnmənt/", "chinese": "n. 任务", "example": "Homework assignment.", "category": "通用词汇"},
        {"english": "assist", "phonetic": "/əˈsɪst/", "chinese": "v. 协助", "example": "Assist customer.", "category": "通用词汇"},
        {"english": "assistant", "phonetic": "/əˈsɪstənt/", "chinese": "n. 助手", "example": "Personal assistant.", "category": "通用词汇"},
        {"english": "associate", "phonetic": "/əˈsoʊʃieɪt/", "chinese": "v. 联系", "example": "Associate with.", "category": "通用词汇"},
        {"english": "association", "phonetic": "/əˌsoʊsiˈeɪʃn/", "chinese": "n. 协会", "example": "Trade association.", "category": "通用词汇"},
        {"english": "assume", "phonetic": "/əˈsuːm/", "chinese": "v. 假设", "example": "Assume responsibility.", "category": "通用词汇"},
        {"english": "assumption", "phonetic": "/əˈsʌmpʃn/", "chinese": "n. 假设", "example": "Wrong assumption.", "category": "通用词汇"},
        {"english": "assure", "phonetic": "/əˈʃʊr/", "chinese": "v. 保证", "example": "Assure quality.", "category": "通用词汇"},
        {"english": "atmosphere", "phonetic": "/ˈætməsfɪr/", "chinese": "n. 氛围", "example": "Relaxing atmosphere.", "category": "通用词汇"},
        {"english": "attach", "phonetic": "/əˈtætʃ/", "chinese": "v. 附加", "example": "Attach file.", "category": "通用词汇"},
        {"english": "attack", "phonetic": "/əˈtæk/", "chinese": "v. 攻击", "example": "Attack enemy.", "category": "通用词汇"},
        {"english": "attempt", "phonetic": "/əˈtempt/", "chinese": "v. 尝试", "example": "Attempt escape.", "category": "通用词汇"},
        {"english": "attend", "phonetic": "/əˈtend/", "chinese": "v. 参加", "example": "Attend meeting.", "category": "通用词汇"},
        {"english": "attention", "phonetic": "/əˈtenʃn/", "chinese": "n. 注意", "example": "Pay attention.", "category": "通用词汇"},
        {"english": "attitude", "phonetic": "/ˈætɪtuːd/", "chinese": "n. 态度", "example": "Positive attitude.", "category": "通用词汇"},
        {"english": "attract", "phonetic": "/əˈtrækt/", "chinese": "v. 吸引", "example": "Attract customers.", "category": "通用词汇"},
        {"english": "attraction", "phonetic": "/əˈtrækʃn/", "chinese": "n. 吸引", "example": "Tourist attraction.", "category": "通用词汇"},
        {"english": "attractive", "phonetic": "/əˈtræktɪv/", "chinese": "adj. 有吸引力的", "example": "Attractive offer.", "category": "通用词汇"},
        {"english": "audience", "phonetic": "/ˈɔːdiəns/", "chinese": "n. 观众", "example": "Large audience.", "category": "通用词汇"},
        {"english": "author", "phonetic": "/ˈɔːθər/", "chinese": "n. 作者", "example": "Famous author.", "category": "通用词汇"},
        {"english": "authority", "phonetic": "/əˈθɔːrəti/", "chinese": "n. 权威", "example": "Legal authority.", "category": "通用词汇"},
        {"english": "automatic", "phonetic": "/ˌɔːtəˈmætɪk/", "chinese": "adj. 自动的", "example": "Automatic door.", "category": "通用词汇"},
        {"english": "automobile", "phonetic": "/ˈɔːtəmoʊbiːl/", "chinese": "n. 汽车", "example": "Automobile industry.", "category": "通用词汇"},
        {"english": "available", "phonetic": "/əˈveɪləbl/", "chinese": "adj. 可用的", "example": "Available now.", "category": "通用词汇"},
        {"english": "average", "phonetic": "/ˈævərɪdʒ/", "chinese": "adj. 平均的", "example": "Average score.", "category": "通用词汇"},
        {"english": "avoid", "phonetic": "/əˈvɔɪd/", "chinese": "v. 避免", "example": "Avoid conflict.", "category": "通用词汇"},
        {"english": "awake", "phonetic": "/əˈweɪk/", "chinese": "adj. 醒着的", "example": "Stay awake.", "category": "通用词汇"},
        {"english": "award", "phonetic": "/əˈwɔːrd/", "chinese": "n. 奖项", "example": "Win award.", "category": "通用词汇"},
        {"english": "aware", "phonetic": "/əˈwer/", "chinese": "adj. 意识到的", "example": "Aware of risk.", "category": "通用词汇"},
        {"english": "away", "phonetic": "/əˈweɪ/", "chinese": "adv. 离开", "example": "Go away.", "category": "通用词汇"},
        {"english": "awful", "phonetic": "/ˈɔːfl/", "chinese": "adj. 糟糕的", "example": "Awful weather.", "category": "通用词汇"},
        {"english": "baby", "phonetic": "/ˈbeɪbi/", "chinese": "n. 婴儿", "example": "Newborn baby.", "category": "通用词汇"},
        {"english": "back", "phonetic": "/bæk/", "chinese": "n. 背部", "example": "Back pain.", "category": "通用词汇"},
        {"english": "background", "phonetic": "/ˈbækɡraʊnd/", "chinese": "n. 背景", "example": "Educational background.", "category": "通用词汇"},
        {"english": "backward", "phonetic": "/ˈbækwərd/", "chinese": "adv. 向后", "example": "Step backward.", "category": "通用词汇"},
        {"english": "bacteria", "phonetic": "/bækˈtɪriə/", "chinese": "n. 细菌", "example": "Harmful bacteria.", "category": "通用词汇"},
        {"english": "bad", "phonetic": "/bæd/", "chinese": "adj. 坏的", "example": "Bad habit.", "category": "通用词汇"},
        {"english": "badly", "phonetic": "/ˈbædli/", "chinese": "adv. 糟糕地", "example": "Behave badly.", "category": "通用词汇"},
        {"english": "bag", "phonetic": "/bæɡ/", "chinese": "n. 包", "example": "Shopping bag.", "category": "通用词汇"},
        {"english": "bake", "phonetic": "/beɪk/", "chinese": "v. 烘烤", "example": "Bake cake.", "category": "通用词汇"},
        {"english": "balance", "phonetic": "/ˈbæləns/", "chinese": "n. 平衡", "example": "Work-life balance.", "category": "通用词汇"},
        {"english": "ball", "phonetic": "/bɔːl/", "chinese": "n. 球", "example": "Play ball.", "category": "通用词汇"},
        {"english": "banana", "phonetic": "/bəˈnænə/", "chinese": "n. 香蕉", "example": "Yellow banana.", "category": "通用词汇"},
        {"english": "band", "phonetic": "/bænd/", "chinese": "n. 乐队", "example": "Rock band.", "category": "通用词汇"},
        {"english": "bank", "phonetic": "/bæŋk/", "chinese": "n. 银行", "example": "Go to bank.", "category": "通用词汇"},
        {"english": "bar", "phonetic": "/bɑːr/", "chinese": "n. 酒吧", "example": "Local bar.", "category": "通用词汇"},
        {"english": "bare", "phonetic": "/ber/", "chinese": "adj. 赤裸的", "example": "Bare feet.", "category": "通用词汇"},
        {"english": "bargain", "phonetic": "/ˈbɑːrɡən/", "chinese": "n. 便宜货", "example": "Good bargain.", "category": "通用词汇"},
        {"english": "base", "phonetic": "/beɪs/", "chinese": "n. 基础", "example": "Knowledge base.", "category": "通用词汇"},
        {"english": "baseball", "phonetic": "/ˈbeɪsbɔːl/", "chinese": "n. 棒球", "example": "Play baseball.", "category": "通用词汇"},
        {"english": "basic", "phonetic": "/ˈbeɪsɪk/", "chinese": "adj. 基本的", "example": "Basic needs.", "category": "通用词汇"},
        {"english": "basically", "phonetic": "/ˈbeɪsɪkli/", "chinese": "adv. 基本上", "example": "Basically correct.", "category": "通用词汇"},
        {"english": "basin", "phonetic": "/ˈbeɪsn/", "chinese": "n. 盆", "example": "Wash basin.", "category": "通用词汇"},
        {"english": "basis", "phonetic": "/ˈbeɪsɪs/", "chinese": "n. 基础", "example": "Regular basis.", "category": "通用词汇"},
        {"english": "basket", "phonetic": "/ˈbæskɪt/", "chinese": "n. 篮子", "example": "Shopping basket.", "category": "通用词汇"},
        {"english": "basketball", "phonetic": "/ˈbæskɪtbɔːl/", "chinese": "n. 篮球", "example": "Play basketball.", "category": "通用词汇"},
        {"english": "bat", "phonetic": "/bæt/", "chinese": "n. 蝙蝠", "example": "Baseball bat.", "category": "通用词汇"},
        {"english": "bath", "phonetic": "/bɑːθ/", "chinese": "n. 洗澡", "example": "Take bath.", "category": "通用词汇"},
        {"english": "bathroom", "phonetic": "/ˈbɑːθruːm/", "chinese": "n. 浴室", "example": "Clean bathroom.", "category": "通用词汇"},
        {"english": "battery", "phonetic": "/ˈbætəri/", "chinese": "n. 电池", "example": "Dead battery.", "category": "通用词汇"},
        {"english": "battle", "phonetic": "/ˈbætl/", "chinese": "n. 战斗", "example": "Win battle.", "category": "通用词汇"},
        {"english": "be", "phonetic": "/biː/", "chinese": "v. 是", "example": "Be happy.", "category": "通用词汇"},
        {"english": "beach", "phonetic": "/biːtʃ/", "chinese": "n. 海滩", "example": "Sandy beach.", "category": "通用词汇"},
        {"english": "bean", "phonetic": "/biːn/", "chinese": "n. 豆子", "example": "Green beans.", "category": "通用词汇"},
        {"english": "bear", "phonetic": "/ber/", "chinese": "v. 忍受", "example": "Bear pain.", "category": "通用词汇"},
        {"english": "beard", "phonetic": "/bɪrd/", "chinese": "n. 胡须", "example": "Grow beard.", "category": "通用词汇"},
        {"english": "beast", "phonetic": "/biːst/", "chinese": "n. 野兽", "example": "Wild beast.", "category": "通用词汇"},
        {"english": "beat", "phonetic": "/biːt/", "chinese": "v. 打败", "example": "Beat record.", "category": "通用词汇"},
        {"english": "beautiful", "phonetic": "/ˈbjuːtɪfl/", "chinese": "adj. 美丽的", "example": "Beautiful day.", "category": "通用词汇"},
        {"english": "beauty", "phonetic": "/ˈbjuːti/", "chinese": "n. 美丽", "example": "Natural beauty.", "category": "通用词汇"},
        {"english": "because", "phonetic": "/bɪˈkɔːz/", "chinese": "conj. 因为", "example": "Because of rain.", "category": "通用词汇"},
        {"english": "become", "phonetic": "/bɪˈkʌm/", "chinese": "v. 成为", "example": "Become famous.", "category": "通用词汇"},
        {"english": "bed", "phonetic": "/bed/", "chinese": "n. 床", "example": "Go to bed.", "category": "通用词汇"},
        {"english": "bedroom", "phonetic": "/ˈbedruːm/", "chinese": "n. 卧室", "example": "Master bedroom.", "category": "通用词汇"},
        {"english": "bee", "phonetic": "/biː/", "chinese": "n. 蜜蜂", "example": "Honey bee.", "category": "通用词汇"},
        {"english": "beef", "phonetic": "/biːf/", "chinese": "n. 牛肉", "example": "Grilled beef.", "category": "通用词汇"},
        {"english": "beer", "phonetic": "/bɪr/", "chinese": "n. 啤酒", "example": "Cold beer.", "category": "通用词汇"},
        {"english": "before", "phonetic": "/bɪˈfɔːr/", "chinese": "prep. 在...之前", "example": "Before dinner.", "category": "通用词汇"},
        {"english": "beg", "phonetic": "/beɡ/", "chinese": "v. 乞求", "example": "Beg for mercy.", "category": "通用词汇"},
        {"english": "begin", "phonetic": "/bɪˈɡɪn/", "chinese": "v. 开始", "example": "Begin work.", "category": "通用词汇"},
        {"english": "beginning", "phonetic": "/bɪˈɡɪnɪŋ/", "chinese": "n. 开始", "example": "New beginning.", "category": "通用词汇"},
        {"english": "behave", "phonetic": "/bɪˈheɪv/", "chinese": "v. 行为", "example": "Behave well.", "category": "通用词汇"},
        {"english": "behavior", "phonetic": "/bɪˈheɪvjər/", "chinese": "n. 行为", "example": "Good behavior.", "category": "通用词汇"},
        {"english": "behind", "phonetic": "/bɪˈhaɪnd/", "chinese": "prep. 在...后面", "example": "Behind schedule.", "category": "通用词汇"},
        {"english": "being", "phonetic": "/ˈbiːɪŋ/", "chinese": "n. 存在", "example": "Human being.", "category": "通用词汇"},
        {"english": "belief", "phonetic": "/bɪˈliːf/", "chinese": "n. 信念", "example": "Strong belief.", "category": "通用词汇"},
        {"english": "believe", "phonetic": "/bɪˈliːv/", "chinese": "v. 相信", "example": "Believe in yourself.", "category": "通用词汇"},
        {"english": "bell", "phonetic": "/bel/", "chinese": "n. 铃", "example": "Door bell.", "category": "通用词汇"},
        {"english": "belong", "phonetic": "/bɪˈlɔːŋ/", "chinese": "v. 属于", "example": "Belong to group.", "category": "通用词汇"},
        {"english": "below", "phonetic": "/bɪˈloʊ/", "chinese": "prep. 在...下面", "example": "Below average.", "category": "通用词汇"},
        {"english": "belt", "phonetic": "/belt/", "chinese": "n. 腰带", "example": "Seat belt.", "category": "通用词汇"},
        {"english": "bench", "phonetic": "/bentʃ/", "chinese": "n. 长凳", "example": "Park bench.", "category": "通用词汇"},
        {"english": "bend", "phonetic": "/bend/", "chinese": "v. 弯曲", "example": "Bend rules.", "category": "通用词汇"},
        {"english": "beneath", "phonetic": "/bɪˈniːθ/", "chinese": "prep. 在...之下", "example": "Beneath surface.", "category": "通用词汇"},
        {"english": "benefit", "phonetic": "/ˈbenɪfɪt/", "chinese": "n. 好处", "example": "Health benefit.", "category": "通用词汇"},
        {"english": "beside", "phonetic": "/bɪˈsaɪd/", "chinese": "prep. 在...旁边", "example": "Beside you.", "category": "通用词汇"},
        {"english": "besides", "phonetic": "/bɪˈsaɪdz/", "chinese": "adv. 此外", "example": "Besides, it's late.", "category": "通用词汇"},
        {"english": "best", "phonetic": "/best/", "chinese": "adj. 最好的", "example": "Best friend.", "category": "通用词汇"},
        {"english": "bet", "phonetic": "/bet/", "chinese": "v. 打赌", "example": "Bet money.", "category": "通用词汇"},
        {"english": "betray", "phonetic": "/bɪˈtreɪ/", "chinese": "v. 背叛", "example": "Betray trust.", "category": "通用词汇"},
        {"english": "better", "phonetic": "/ˈbetər/", "chinese": "adj. 更好的", "example": "Better option.", "category": "通用词汇"},
        {"english": "between", "phonetic": "/bɪˈtwiːn/", "chinese": "prep. 在...之间", "example": "Between us.", "category": "通用词汇"},
        {"english": "beyond", "phonetic": "/bɪˈjɑːnd/", "chinese": "prep. 超越", "example": "Beyond doubt.", "category": "通用词汇"},
        {"english": "bicycle", "phonetic": "/ˈbaɪsɪkl/", "chinese": "n. 自行车", "example": "Ride bicycle.", "category": "通用词汇"},
        {"english": "big", "phonetic": "/bɪɡ/", "chinese": "adj. 大的", "example": "Big house.", "category": "通用词汇"},
        {"english": "bike", "phonetic": "/baɪk/", "chinese": "n. 自行车", "example": "Mountain bike.", "category": "通用词汇"},
        {"english": "bill", "phonetic": "/bɪl/", "chinese": "n. 账单", "example": "Pay bill.", "category": "通用词汇"},
        {"english": "billion", "phonetic": "/ˈbɪljən/", "chinese": "n. 十亿", "example": "Cost billions.", "category": "通用词汇"},
        {"english": "bind", "phonetic": "/baɪnd/", "chinese": "v. 绑定", "example": "Bind together.", "category": "通用词汇"},
        {"english": "biology", "phonetic": "/baɪˈɑːlədʒi/", "chinese": "n. 生物学", "example": "Study biology.", "category": "通用词汇"},
        {"english": "bird", "phonetic": "/bɜːrd/", "chinese": "n. 鸟", "example": "Sing like bird.", "category": "通用词汇"},
        {"english": "birth", "phonetic": "/bɜːrθ/", "chinese": "n. 出生", "example": "Date of birth.", "category": "通用词汇"},
        {"english": "birthday", "phonetic": "/ˈbɜːrθdeɪ/", "chinese": "n. 生日", "example": "Happy birthday.", "category": "通用词汇"},
        {"english": "biscuit", "phonetic": "/ˈbɪskɪt/", "chinese": "n. 饼干", "example": "Chocolate biscuit.", "category": "通用词汇"},
        {"english": "bit", "phonetic": "/bɪt/", "chinese": "n. 一点", "example": "A bit tired.", "category": "通用词汇"},
        {"english": "bite", "phonetic": "/baɪt/", "chinese": "v. 咬", "example": "Bite food.", "category": "通用词汇"},
        {"english": "bitter", "phonetic": "/ˈbɪtər/", "chinese": "adj. 苦的", "example": "Bitter taste.", "category": "通用词汇"},
        {"english": "black", "phonetic": "/blæk/", "chinese": "adj. 黑色的", "example": "Black cat.", "category": "通用词汇"},
        {"english": "blade", "phonetic": "/bleɪd/", "chinese": "n. 刀片", "example": "Sharp blade.", "category": "通用词汇"},
        {"english": "blame", "phonetic": "/bleɪm/", "chinese": "v. 责备", "example": "Blame others.", "category": "通用词汇"},
        {"english": "blank", "phonetic": "/blæŋk/", "chinese": "adj. 空白的", "example": "Blank page.", "category": "通用词汇"},
        {"english": "blanket", "phonetic": "/ˈblæŋkɪt/", "chinese": "n. 毯子", "example": "Warm blanket.", "category": "通用词汇"},
        {"english": "blast", "phonetic": "/blæst/", "chinese": "n. 爆炸", "example": "Nuclear blast.", "category": "通用词汇"},
        {"english": "bleed", "phonetic": "/bliːd/", "chinese": "v. 流血", "example": "Bleed heavily.", "category": "通用词汇"},
        {"english": "blend", "phonetic": "/blend/", "chinese": "v. 混合", "example": "Blend colors.", "category": "通用词汇"},
        {"english": "bless", "phonetic": "/bles/", "chinese": "v. 祝福", "example": "Bless family.", "category": "通用词汇"},
        {"english": "blind", "phonetic": "/blaɪnd/", "chinese": "adj. 盲的", "example": "Blind person.", "category": "通用词汇"},
        {"english": "block", "phonetic": "/blɑːk/", "chinese": "n. 街区", "example": "Next block.", "category": "通用词汇"},
        {"english": "blood", "phonetic": "/blʌd/", "chinese": "n. 血液", "example": "Blood pressure.", "category": "通用词汇"},
        {"english": "blow", "phonetic": "/bloʊ/", "chinese": "v. 吹", "example": "Blow candle.", "category": "通用词汇"},
        {"english": "blue", "phonetic": "/bluː/", "chinese": "adj. 蓝色的", "example": "Blue sky.", "category": "通用词汇"},
        {"english": "board", "phonetic": "/bɔːrd/", "chinese": "n. 板", "example": "Notice board.", "category": "通用词汇"},
        {"english": "boast", "phonetic": "/boʊst/", "chinese": "v. 吹嘘", "example": "Boast about success.", "category": "通用词汇"},
        {"english": "boat", "phonetic": "/boʊt/", "chinese": "n. 船", "example": "Sail boat.", "category": "通用词汇"},
        {"english": "body", "phonetic": "/ˈbɑːdi/", "chinese": "n. 身体", "example": "Healthy body.", "category": "通用词汇"},
        {"english": "boil", "phonetic": "/bɔɪl/", "chinese": "v. 煮沸", "example": "Boil water.", "category": "通用词汇"},
        {"english": "bold", "phonetic": "/boʊld/", "chinese": "adj. 大胆的", "example": "Bold decision.", "category": "通用词汇"},
        {"english": "bomb", "phonetic": "/bɑːm/", "chinese": "n. 炸弹", "example": "Drop bomb.", "category": "通用词汇"},
        {"english": "bond", "phonetic": "/bɑːnd/", "chinese": "n. 债券", "example": "Government bond.", "category": "通用词汇"},
        {"english": "bone", "phonetic": "/boʊn/", "chinese": "n. 骨头", "example": "Broken bone.", "category": "通用词汇"},
        {"english": "book", "phonetic": "/bʊk/", "chinese": "n. 书", "example": "Read book.", "category": "通用词汇"},
        {"english": "boom", "phonetic": "/buːm/", "chinese": "n. 繁荣", "example": "Economic boom.", "category": "通用词汇"},
        {"english": "boot", "phonetic": "/buːt/", "chinese": "n. 靴子", "example": "Winter boot.", "category": "通用词汇"},
        {"english": "border", "phonetic": "/ˈbɔːrdər/", "chinese": "n. 边界", "example": "Cross border.", "category": "通用词汇"},
        {"english": "bore", "phonetic": "/bɔːr/", "chinese": "v. 使厌烦", "example": "Bore to death.", "category": "通用词汇"},
        {"english": "born", "phonetic": "/bɔːrn/", "chinese": "adj. 出生的", "example": "Born in 1990.", "category": "通用词汇"},
        {"english": "borrow", "phonetic": "/ˈbɑːroʊ/", "chinese": "v. 借", "example": "Borrow money.", "category": "通用词汇"},
        {"english": "boss", "phonetic": "/bɔːs/", "chinese": "n. 老板", "example": "Meet boss.", "category": "通用词汇"},
        {"english": "both", "phonetic": "/boʊθ/", "chinese": "pron. 两者都", "example": "Both sides.", "category": "通用词汇"},
        {"english": "bother", "phonetic": "/ˈbɑːðər/", "chinese": "v. 打扰", "example": "Bother neighbor.", "category": "通用词汇"},
        {"english": "bottle", "phonetic": "/ˈbɑːtl/", "chinese": "n. 瓶子", "example": "Water bottle.", "category": "通用词汇"},
        {"english": "bottom", "phonetic": "/ˈbɑːtəm/", "chinese": "n. 底部", "example": "At bottom.", "category": "通用词汇"},
        {"english": "bound", "phonetic": "/baʊnd/", "chinese": "adj. 必然的", "example": "Bound to succeed.", "category": "通用词汇"},
        {"english": "boundary", "phonetic": "/ˈbaʊndri/", "chinese": "n. 边界", "example": "Set boundary.", "category": "通用词汇"},
        {"english": "bow", "phonetic": "/boʊ/", "chinese": "v. 鞠躬", "example": "Bow to audience.", "category": "通用词汇"},
        {"english": "bowl", "phonetic": "/boʊl/", "chinese": "n. 碗", "example": "Rice bowl.", "category": "通用词汇"},
        {"english": "box", "phonetic": "/bɑːks/", "chinese": "n. 盒子", "example": "Gift box.", "category": "通用词汇"},
        {"english": "boy", "phonetic": "/bɔɪ/", "chinese": "n. 男孩", "example": "Young boy.", "category": "通用词汇"},
        {"english": "brain", "phonetic": "/breɪn/", "chinese": "n. 大脑", "example": "Human brain.", "category": "通用词汇"},
        {"english": "branch", "phonetic": "/bræntʃ/", "chinese": "n. 分支", "example": "Tree branch.", "category": "通用词汇"},
        {"english": "brand", "phonetic": "/brænd/", "chinese": "n. 品牌", "example": "Famous brand.", "category": "通用词汇"},
        {"english": "brave", "phonetic": "/breɪv/", "chinese": "adj. 勇敢的", "example": "Brave soldier.", "category": "通用词汇"},
        {"english": "bread", "phonetic": "/bred/", "chinese": "n. 面包", "example": "Fresh bread.", "category": "通用词汇"},
        {"english": "break", "phonetic": "/breɪk/", "chinese": "v. 打破", "example": "Break record.", "category": "通用词汇"},
        {"english": "breakfast", "phonetic": "/ˈbrekfəst/", "chinese": "n. 早餐", "example": "Eat breakfast.", "category": "通用词汇"},
        {"english": "breast", "phonetic": "/brest/", "chinese": "n. 胸部", "example": "Chicken breast.", "category": "通用词汇"},
        {"english": "breath", "phonetic": "/breθ/", "chinese": "n. 呼吸", "example": "Deep breath.", "category": "通用词汇"},
        {"english": "breathe", "phonetic": "/briːð/", "chinese": "v. 呼吸", "example": "Breathe deeply.", "category": "通用词汇"},
        {"english": "breed", "phonetic": "/briːd/", "chinese": "v. 繁殖", "example": "Breed animals.", "category": "通用词汇"},
        {"english": "brick", "phonetic": "/brɪk/", "chinese": "n. 砖块", "example": "Red brick.", "category": "通用词汇"},
        {"english": "bride", "phonetic": "/braɪd/", "chinese": "n. 新娘", "example": "Beautiful bride.", "category": "通用词汇"},
        {"english": "bridge", "phonetic": "/brɪdʒ/", "chinese": "n. 桥", "example": "Cross bridge.", "category": "通用词汇"},
        {"english": "brief", "phonetic": "/briːf/", "chinese": "adj. 简短的", "example": "Brief meeting.", "category": "通用词汇"},
        {"english": "bright", "phonetic": "/braɪt/", "chinese": "adj. 明亮的", "example": "Bright future.", "category": "通用词汇"},
        {"english": "bring", "phonetic": "/brɪŋ/", "chinese": "v. 带来", "example": "Bring lunch.", "category": "通用词汇"},
        {"english": "broad", "phonetic": "/brɔːd/", "chinese": "adj. 宽广的", "example": "Broad shoulders.", "category": "通用词汇"},
        {"english": "broadcast", "phonetic": "/ˈbrɔːdkæst/", "chinese": "v. 广播", "example": "Broadcast news.", "category": "通用词汇"},
        {"english": "broken", "phonetic": "/ˈbroʊkən/", "chinese": "adj. 破碎的", "example": "Broken window.", "category": "通用词汇"},
        {"english": "brother", "phonetic": "/ˈbrʌðər/", "chinese": "n. 兄弟", "example": "Elder brother.", "category": "通用词汇"},
        {"english": "brown", "phonetic": "/braʊn/", "chinese": "adj. 棕色的", "example": "Brown hair.", "category": "通用词汇"},
        {"english": "brush", "phonetic": "/brʌʃ/", "chinese": "n. 刷子", "example": "Tooth brush.", "category": "通用词汇"},
        {"english": "budget", "phonetic": "/ˈbʌdʒɪt/", "chinese": "n. 预算", "example": "Annual budget.", "category": "通用词汇"},
        {"english": "build", "phonetic": "/bɪld/", "chinese": "v. 建造", "example": "Build house.", "category": "通用词汇"},
        {"english": "building", "phonetic": "/ˈbɪldɪŋ/", "chinese": "n. 建筑", "example": "Tall building.", "category": "通用词汇"},
        {"english": "bunch", "phonetic": "/bʌntʃ/", "chinese": "n. 一束", "example": "Bunch of flowers.", "category": "通用词汇"},
        {"english": "burden", "phonetic": "/ˈbɜːrdn/", "chinese": "n. 负担", "example": "Heavy burden.", "category": "通用词汇"},
        {"english": "bureau", "phonetic": "/ˈbjʊroʊ/", "chinese": "n. 局", "example": "Information bureau.", "category": "通用词汇"},
        {"english": "burn", "phonetic": "/bɜːrn/", "chinese": "v. 燃烧", "example": "Burn calories.", "category": "通用词汇"},
        {"english": "burst", "phonetic": "/bɜːrst/", "chinese": "v. 爆裂", "example": "Burst balloon.", "category": "通用词汇"},
        {"english": "bury", "phonetic": "/ˈberi/", "chinese": "v. 埋葬", "example": "Bury treasure.", "category": "通用词汇"},
        {"english": "bus", "phonetic": "/bʌs/", "chinese": "n. 公共汽车", "example": "Take bus.", "category": "通用词汇"},
        {"english": "business", "phonetic": "/ˈbɪznəs/", "chinese": "n. 商业", "example": "Small business.", "category": "通用词汇"},
        {"english": "busy", "phonetic": "/ˈbɪzi/", "chinese": "adj. 忙碌的", "example": "Busy day.", "category": "通用词汇"},
        {"english": "but", "phonetic": "/bʌt/", "chinese": "conj. 但是", "example": "But wait.", "category": "通用词汇"},
        {"english": "butter", "phonetic": "/ˈbʌtər/", "chinese": "n. 黄油", "example": "Butter bread.", "category": "通用词汇"},
        {"english": "button", "phonetic": "/ˈbʌtn/", "chinese": "n. 按钮", "example": "Press button.", "category": "通用词汇"},
        {"english": "buy", "phonetic": "/baɪ/", "chinese": "v. 购买", "example": "Buy groceries.", "category": "通用词汇"},
        {"english": "by", "phonetic": "/baɪ/", "chinese": "prep. 通过", "example": "By bus.", "category": "通用词汇"}
    ]
    
    added_count = 0
    for word in new_words:
        cursor.execute('''
            INSERT OR IGNORE INTO words (english, phonetic, chinese, example, category, subcategory)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (word['english'], word['phonetic'], word['chinese'], word['example'], word['category'], ''))
        
        if cursor.rowcount > 0:
            added_count += 1
    
    conn.commit()
    
    cursor.execute('SELECT COUNT(*) FROM words')
    total = cursor.fetchone()[0]
    
    print(f"成功添加 {added_count} 个新单词到数据库")
    print(f"数据库总单词数: {total}")
    
    conn.close()

if __name__ == "__main__":
    expand_to_5000_batch12()