import sqlite3

def expand_to_5000_final():
    conn = sqlite3.connect('../words.db')
    cursor = conn.cursor()
    
    new_words = [
        # 科技与互联网词汇
        ("algorithm", "/ˈælɡərɪðəm/", "算法", "The algorithm is efficient.", "名词"),
        ("application", "/ˌæplɪˈkeɪʃn/", "应用程序", "Mobile application.", "名词"),
        ("bandwidth", "/ˈbændwɪdθ/", "带宽", "High bandwidth.", "名词"),
        ("browser", "/ˈbraʊzər/", "浏览器", "Web browser.", "名词"),
        ("cache", "/kæʃ/", "缓存", "Clear the cache.", "名词"),
        ("cloud", "/klaʊd/", "云", "Cloud computing.", "名词"),
        ("code", "/koʊd/", "代码", "Source code.", "名词"),
        ("database", "/ˈdeɪtəbeɪs/", "数据库", "Relational database.", "名词"),
        ("debug", "/diːˈbʌɡ/", "调试", "Debug the program.", "动词"),
        ("digital", "/ˈdɪdʒɪtl/", "数字的", "Digital transformation.", "形容词"),
        ("download", "/ˈdaʊnloʊd/", "下载", "Download the file.", "动词"),
        ("encryption", "/ɪnˈkrɪpʃn/", "加密", "Data encryption.", "名词"),
        ("firewall", "/ˈfaɪərwɔːl/", "防火墙", "Network firewall.", "名词"),
        ("hardware", "/ˈhɑːrdwer/", "硬件", "Computer hardware.", "名词"),
        ("interface", "/ˈɪntərfeɪs/", "接口", "User interface.", "名词"),
        ("malware", "/ˈmælwer/", "恶意软件", "Malware protection.", "名词"),
        ("network", "/ˈnetwɜːrk/", "网络", "Social network.", "名词"),
        ("password", "/ˈpæswɜːrd/", "密码", "Strong password.", "名词"),
        ("platform", "/ˈplætfɔːrm/", "平台", "Online platform.", "名词"),
        ("program", "/ˈproʊɡræm/", "程序", "Computer program.", "名词"),
        ("server", "/ˈsɜːrvər/", "服务器", "Web server.", "名词"),
        ("software", "/ˈsɔːftwer/", "软件", "Application software.", "名词"),
        ("upload", "/ʌpˈloʊd/", "上传", "Upload the document.", "动词"),
        ("virus", "/ˈvaɪrəs/", "病毒", "Computer virus.", "名词"),
        ("wireless", "/ˈwaɪərləs/", "无线的", "Wireless connection.", "形容词"),
        
        # 商业与经济词汇
        ("account", "/əˈkaʊnt/", "账户", "Bank account.", "名词"),
        ("asset", "/ˈæset/", "资产", "Financial asset.", "名词"),
        ("audit", "/ˈɔːdɪt/", "审计", "Financial audit.", "名词"),
        ("budget", "/ˈbʌdʒɪt/", "预算", "Annual budget.", "名词"),
        ("capital", "/ˈkæpɪtl/", "资本", "Human capital.", "名词"),
        ("client", "/ˈklaɪənt/", "客户", "Important client.", "名词"),
        ("contract", "/ˈkɒntrækt/", "合同", "Sign the contract.", "名词"),
        ("corporate", "/ˈkɔːrpərət/", "企业的", "Corporate strategy.", "形容词"),
        ("credit", "/ˈkredɪt/", "信用", "Credit score.", "名词"),
        ("currency", "/ˈkʌrənsi/", "货币", "Foreign currency.", "名词"),
        ("customer", "/ˈkʌstəmər/", "顾客", "Customer service.", "名词"),
        ("debt", "/det/", "债务", "National debt.", "名词"),
        ("dividend", "/ˈdɪvɪdend/", "股息", "Pay dividend.", "名词"),
        ("economy", "/ɪˈkɒnəmi/", "经济", "Global economy.", "名词"),
        ("enterprise", "/ˈentərpraɪz/", "企业", "Large enterprise.", "名词"),
        ("equity", "/ˈekwəti/", "股权", "Home equity.", "名词"),
        ("finance", "/ˈfaɪnæns/", "金融", "Personal finance.", "名词"),
        ("franchise", "/ˈfræntʃaɪz/", "特许经营", "Buy a franchise.", "名词"),
        ("gross", "/ɡroʊs/", "总的", "Gross income.", "形容词"),
        ("income", "/ˈɪnkʌm/", "收入", "Annual income.", "名词"),
        ("inflation", "/ɪnˈfleɪʃn/", "通货膨胀", "Control inflation.", "名词"),
        ("investment", "/ɪnˈvestmənt/", "投资", "Smart investment.", "名词"),
        ("liability", "/ˌlaɪəˈbɪləti/", "负债", "Legal liability.", "名词"),
        ("market", "/ˈmɑːrkɪt/", "市场", "Stock market.", "名词"),
        ("merger", "/ˈmɜːrdʒər/", "合并", "Company merger.", "名词"),
        ("net", "/net/", "净的", "Net profit.", "形容词"),
        ("profit", "/ˈprɒfɪt/", "利润", "Maximize profit.", "名词"),
        ("revenue", "/ˈrevənuː/", "收入", "Annual revenue.", "名词"),
        ("share", "/ʃer/", "股份", "Buy shares.", "名词"),
        ("stock", "/stɒk/", "股票", "Stock market.", "名词"),
        ("tax", "/tæks/", "税收", "Pay taxes.", "名词"),
        ("venture", "/ˈventʃər/", "风险投资", "Joint venture.", "名词"),
        
        # 教育与学术词汇
        ("academic", "/ˌækəˈdemɪk/", "学术的", "Academic year.", "形容词"),
        ("assignment", "/əˈsaɪnmənt/", "作业", "Complete the assignment.", "名词"),
        ("campus", "/ˈkæmpəs/", "校园", "University campus.", "名词"),
        ("curriculum", "/kəˈrɪkjələm/", "课程", "School curriculum.", "名词"),
        ("degree", "/dɪˈɡriː/", "学位", "Bachelor's degree.", "名词"),
        ("diploma", "/dɪˈploʊmə/", "文凭", "High school diploma.", "名词"),
        ("education", "/ˌedʒuˈkeɪʃn/", "教育", "Higher education.", "名词"),
        ("enrollment", "/ɪnˈroʊlmənt/", "入学", "Student enrollment.", "名词"),
        ("faculty", "/ˈfæklti/", "教职员工", "Faculty members.", "名词"),
        ("graduate", "/ˈɡrædʒuət/", "毕业生", "Recent graduate.", "名词"),
        ("institution", "/ˌɪnstɪˈtuːʃn/", "机构", "Educational institution.", "名词"),
        ("lecture", "/ˈlektʃər/", "讲座", "Attend a lecture.", "名词"),
        ("professor", "/prəˈfesər/", "教授", "University professor.", "名词"),
        ("scholarship", "/ˈskɑːlərʃɪp/", "奖学金", "Academic scholarship.", "名词"),
        ("semester", "/sɪˈmestər/", "学期", "Fall semester.", "名词"),
        ("student", "/ˈstuːdnt/", "学生", "International student.", "名词"),
        ("tuition", "/tuːˈɪʃn/", "学费", "Tuition fee.", "名词"),
        ("university", "/ˌjuːnɪˈvɜːrsəti/", "大学", "Prestigious university.", "名词"),
        
        # 医疗与健康词汇
        ("allergy", "/ˈælərdʒi/", "过敏", "Food allergy.", "名词"),
        ("antibiotic", "/ˌæntibaɪˈɒtɪk/", "抗生素", "Take antibiotic.", "名词"),
        ("bacteria", "/bækˈtɪriə/", "细菌", "Harmful bacteria.", "名词"),
        ("clinic", "/ˈklɪnɪk/", "诊所", "Medical clinic.", "名词"),
        ("diagnosis", "/ˌdaɪəɡˈnoʊsɪs/", "诊断", "Medical diagnosis.", "名词"),
        ("disease", "/dɪˈziːz/", "疾病", "Chronic disease.", "名词"),
        ("doctor", "/ˈdɑːktər/", "医生", "Visit the doctor.", "名词"),
        ("hospital", "/ˈhɑːspɪtl/", "医院", "Local hospital.", "名词"),
        ("infection", "/ɪnˈfekʃn/", "感染", "Viral infection.", "名词"),
        ("medication", "/ˌmedɪˈkeɪʃn/", "药物", "Prescription medication.", "名词"),
        ("medicine", "/ˈmedɪsn/", "医学", "Modern medicine.", "名词"),
        ("nurse", "/nɜːrs/", "护士", "Registered nurse.", "名词"),
        ("patient", "/ˈpeɪʃnt/", "病人", "Patient care.", "名词"),
        ("pharmacy", "/ˈfɑːrməsi/", "药房", "Local pharmacy.", "名词"),
        ("prescription", "/prɪˈskrɪpʃn/", "处方", "Fill prescription.", "名词"),
        ("recovery", "/rɪˈkʌvəri/", "康复", "Speedy recovery.", "名词"),
        ("symptom", "/ˈsɪmptəm/", "症状", "Common symptom.", "名词"),
        ("treatment", "/ˈtriːtmənt/", "治疗", "Medical treatment.", "名词"),
        ("vaccine", "/vækˈsiːn/", "疫苗", "COVID-19 vaccine.", "名词"),
        ("virus", "/ˈvaɪrəs/", "病毒", "Flu virus.", "名词"),
        
        # 环境与自然词汇
        ("atmosphere", "/ˈætməsfɪr/", "大气层", "Earth's atmosphere.", "名词"),
        ("carbon", "/ˈkɑːrbən/", "碳", "Carbon footprint.", "名词"),
        ("climate", "/ˈklaɪmət/", "气候", "Global climate.", "名词"),
        ("conservation", "/ˌkɑːnsərˈveɪʃn/", "保护", "Wildlife conservation.", "名词"),
        ("disaster", "/dɪˈzæstər/", "灾难", "Natural disaster.", "名词"),
        ("ecosystem", "/ˈiːkoʊsɪstəm/", "生态系统", "Marine ecosystem.", "名词"),
        ("emission", "/iˈmɪʃn/", "排放", "Carbon emission.", "名词"),
        ("energy", "/ˈenərdʒi/", "能源", "Renewable energy.", "名词"),
        ("environment", "/ɪnˈvaɪrənmənt/", "环境", "Protect environment.", "名词"),
        ("extinction", "/ɪkˈstɪŋkʃn/", "灭绝", "Species extinction.", "名词"),
        ("flood", "/flʌd/", "洪水", "Flash flood.", "名词"),
        ("forest", "/ˈfɔːrɪst/", "森林", "Tropical forest.", "名词"),
        ("global", "/ˈɡloʊbl/", "全球的", "Global warming.", "形容词"),
        ("habitat", "/ˈhæbɪtæt/", "栖息地", "Natural habitat.", "名词"),
        ("hurricane", "/ˈhʌrɪkeɪn/", "飓风", "Category 5 hurricane.", "名词"),
        ("ocean", "/ˈoʊʃn/", "海洋", "Pacific ocean.", "名词"),
        ("pollution", "/pəˈluːʃn/", "污染", "Air pollution.", "名词"),
        ("recycle", "/riːˈsaɪkl/", "回收", "Recycle paper.", "动词"),
        ("renewable", "/rɪˈnuːəbl/", "可再生的", "Renewable energy.", "形容词"),
        ("resource", "/ˈriːsɔːrs/", "资源", "Natural resource.", "名词"),
        ("solar", "/ˈsoʊlər/", "太阳的", "Solar power.", "形容词"),
        ("species", "/ˈspiːʃiːz/", "物种", "Endangered species.", "名词"),
        ("sustainability", "/səˌsteɪnəˈbɪləti/", "可持续性", "Environmental sustainability.", "名词"),
        ("temperature", "/ˈtemprətʃər/", "温度", "Global temperature.", "名词"),
        ("tsunami", "/tsuːˈnɑːmi/", "海啸", "Tsunami warning.", "名词"),
        ("waste", "/weɪst/", "废物", "Nuclear waste.", "名词"),
        ("wildlife", "/ˈwaɪldlaɪf/", "野生动物", "Protect wildlife.", "名词"),
        ("wind", "/wɪnd/", "风", "Wind energy.", "名词"),
        
        # 法律与政治词汇
        ("amendment", "/əˈmendmənt/", "修正案", "Constitutional amendment.", "名词"),
        ("campaign", "/kæmˈpeɪn/", "竞选", "Political campaign.", "名词"),
        ("candidate", "/ˈkændɪdeɪt/", "候选人", "Presidential candidate.", "名词"),
        ("citizen", "/ˈsɪtɪzn/", "公民", "Responsible citizen.", "名词"),
        ("congress", "/ˈkɑːŋɡres/", "国会", "US Congress.", "名词"),
        ("constitution", "/ˌkɑːnstɪˈtuːʃn/", "宪法", "National constitution.", "名词"),
        ("court", "/kɔːrt/", "法庭", "Supreme court.", "名词"),
        ("crime", "/kraɪm/", "犯罪", "Violent crime.", "名词"),
        ("democracy", "/dɪˈmɒkrəsi/", "民主", "Direct democracy.", "名词"),
        ("election", "/ɪˈlekʃn/", "选举", "General election.", "名词"),
        ("government", "/ˈɡʌvərnmənt/", "政府", "Federal government.", "名词"),
        ("judge", "/dʒʌdʒ/", "法官", "Federal judge.", "名词"),
        ("justice", "/ˈdʒʌstɪs/", "正义", "Social justice.", "名词"),
        ("law", "/lɔː/", "法律", "International law.", "名词"),
        ("legislation", "/ˌledʒɪsˈleɪʃn/", "立法", "New legislation.", "名词"),
        ("policy", "/ˈpɑːləsi/", "政策", "Foreign policy.", "名词"),
        ("politics", "/ˈpɑːlətɪks/", "政治", "Study politics.", "名词"),
        ("president", "/ˈprezɪdənt/", "总统", "Elected president.", "名词"),
        ("regulation", "/ˌreɡjuˈleɪʃn/", "法规", "Safety regulation.", "名词"),
        ("rights", "/raɪts/", "权利", "Human rights.", "名词"),
        ("senate", "/ˈsenət/", "参议院", "Senate hearing.", "名词"),
        ("tax", "/tæks/", "税收", "Income tax.", "名词"),
        ("treaty", "/ˈtriːti/", "条约", "International treaty.", "名词"),
        ("vote", "/voʊt/", "投票", "Cast a vote.", "动词"),
        ("voter", "/ˈvoʊtər/", "选民", "Registered voter.", "名词"),
        
        # 旅行与交通词汇
        ("airline", "/ˈerlaɪn/", "航空公司", "Major airline.", "名词"),
        ("airport", "/ˈerpɔːrt/", "机场", "International airport.", "名词"),
        ("cargo", "/ˈkɑːrɡoʊ/", "货物", "Cargo ship.", "名词"),
        ("commute", "/kəˈmjuːt/", "通勤", "Daily commute.", "动词"),
        ("destination", "/ˌdestɪˈneɪʃn/", "目的地", "Popular destination.", "名词"),
        ("flight", "/flaɪt/", "航班", "Book a flight.", "名词"),
        ("highway", "/ˈhaɪweɪ/", "高速公路", "Interstate highway.", "名词"),
        ("itinerary", "/aɪˈtɪnəreri/", "行程", "Travel itinerary.", "名词"),
        ("journey", "/ˈdʒɜːrni/", "旅程", "Long journey.", "名词"),
        ("luggage", "/ˈlʌɡɪdʒ/", "行李", "Check luggage.", "名词"),
        ("passport", "/ˈpæspɔːrt/", "护照", "Renew passport.", "名词"),
        ("railway", "/ˈreɪlweɪ/", "铁路", "Railway station.", "名词"),
        ("reservation", "/ˌrezərˈveɪʃn/", "预订", "Make reservation.", "名词"),
        ("route", "/ruːt/", "路线", "Bus route.", "名词"),
        ("schedule", "/ˈskedʒuːl/", "时间表", "Flight schedule.", "名词"),
        ("ticket", "/ˈtɪkɪt/", "票", "Buy ticket.", "名词"),
        ("traffic", "/ˈtræfɪk/", "交通", "Heavy traffic.", "名词"),
        ("transportation", "/ˌtrænspɔːrˈteɪʃn/", "交通", "Public transportation.", "名词"),
        ("trip", "/trɪp/", "旅行", "Business trip.", "名词"),
        ("vacation", "/veɪˈkeɪʃn/", "假期", "Summer vacation.", "名词"),
        ("vehicle", "/ˈviːɪkl/", "车辆", "Electric vehicle.", "名词"),
        ("visa", "/ˈviːzə/", "签证", "Apply for visa.", "名词"),
        
        # 食物与烹饪词汇
        ("appetite", "/ˈæpɪtaɪt/", "食欲", "Good appetite.", "名词"),
        ("bake", "/beɪk/", "烘烤", "Bake a cake.", "动词"),
        ("barbecue", "/ˈbɑːrbɪkjuː/", "烧烤", "Summer barbecue.", "名词"),
        ("beverage", "/ˈbevərɪdʒ/", "饮料", "Alcoholic beverage.", "名词"),
        ("boil", "/bɔɪl/", "煮沸", "Boil water.", "动词"),
        ("breakfast", "/ˈbrekfəst/", "早餐", "Healthy breakfast.", "名词"),
        ("cuisine", "/kwɪˈziːn/", "烹饪", "French cuisine.", "名词"),
        ("delicious", "/dɪˈlɪʃəs/", "美味的", "Delicious meal.", "形容词"),
        ("dinner", "/ˈdɪnər/", "晚餐", "Family dinner.", "名词"),
        ("dish", "/dɪʃ/", "菜肴", "Traditional dish.", "名词"),
        ("flavor", "/ˈfleɪvər/", "味道", "Rich flavor.", "名词"),
        ("fry", "/fraɪ/", "油炸", "Fry chicken.", "动词"),
        ("grill", "/ɡrɪl/", "烧烤", "Grill steak.", "动词"),
        ("ingredient", "/ɪnˈɡriːdiənt/", "配料", "Fresh ingredient.", "名词"),
        ("lunch", "/lʌntʃ/", "午餐", "Business lunch.", "名词"),
        ("meal", "/miːl/", "一餐", "Balanced meal.", "名词"),
        ("menu", "/ˈmenjuː/", "菜单", "Restaurant menu.", "名词"),
        ("recipe", "/ˈresəpi/", "食谱", "Follow recipe.", "名词"),
        ("restaurant", "/ˈrestərɑːnt/", "餐厅", "Fine restaurant.", "名词"),
        ("snack", "/snæk/", "零食", "Healthy snack.", "名词"),
        ("spice", "/spaɪs/", "香料", "Exotic spice.", "名词"),
        ("taste", "/teɪst/", "味道", "Sweet taste.", "名词"),
        ("tasty", "/ˈteɪsti/", "好吃的", "Tasty food.", "形容词"),
        
        # 情感与心理词汇
        ("anxiety", "/æŋˈzaɪəti/", "焦虑", "Social anxiety.", "名词"),
        ("attitude", "/ˈætɪtuːd/", "态度", "Positive attitude.", "名词"),
        ("behavior", "/bɪˈheɪvjər/", "行为", "Human behavior.", "名词"),
        ("confident", "/ˈkɒnfɪdənt/", "自信的", "Feel confident.", "形容词"),
        ("confused", "/kənˈfjuːzd/", "困惑的", "Get confused.", "形容词"),
        ("curious", "/ˈkjʊriəs/", "好奇的", "Be curious.", "形容词"),
        ("depressed", "/dɪˈprest/", "抑郁的", "Feel depressed.", "形容词"),
        ("emotion", "/ɪˈmoʊʃn/", "情感", "Express emotion.", "名词"),
        ("excited", "/ɪkˈsaɪtɪd/", "兴奋的", "Feel excited.", "形容词"),
        ("fear", "/fɪr/", "恐惧", "Overcome fear.", "名词"),
        ("frustrated", "/ˈfrʌstreɪtɪd/", "沮丧的", "Feel frustrated.", "形容词"),
        ("happy", "/ˈhæpi/", "快乐的", "Be happy.", "形容词"),
        ("hope", "/hoʊp/", "希望", "Lose hope.", "名词"),
        ("jealous", "/ˈdʒeləs/", "嫉妒的", "Get jealous.", "形容词"),
        ("lonely", "/ˈloʊnli/", "孤独的", "Feel lonely.", "形容词"),
        ("love", "/lʌv/", "爱", "Fall in love.", "名词"),
        ("mood", "/muːd/", "情绪", "Good mood.", "名词"),
        ("nervous", "/ˈnɜːrvəs/", "紧张的", "Feel nervous.", "形容词"),
        ("optimistic", "/ˌɒptɪˈmɪstɪk/", "乐观的", "Be optimistic.", "形容词"),
        ("pessimistic", "/ˌpesɪˈmɪstɪk/", "悲观的", "Be pessimistic.", "形容词"),
        ("proud", "/praʊd/", "骄傲的", "Feel proud.", "形容词"),
        ("sad", "/sæd/", "悲伤的", "Feel sad.", "形容词"),
        ("scared", "/skerd/", "害怕的", "Get scared.", "形容词"),
        ("shy", "/ʃaɪ/", "害羞的", "Be shy.", "形容词"),
        ("stress", "/stres/", "压力", "Reduce stress.", "名词"),
        ("surprised", "/sərˈpraɪzd/", "惊讶的", "Feel surprised.", "形容词"),
        ("worried", "/ˈwɜːrid/", "担心的", "Feel worried.", "形容词"),
        
        # 常见动词
        ("accept", "/əkˈsept/", "接受", "Accept the offer.", "动词"),
        ("achieve", "/əˈtʃiːv/", "实现", "Achieve goals.", "动词"),
        ("act", "/ækt/", "行动", "Act quickly.", "动词"),
        ("add", "/æd/", "添加", "Add details.", "动词"),
        ("admire", "/ədˈmaɪər/", "钦佩", "Admire courage.", "动词"),
        ("advise", "/ədˈvaɪz/", "建议", "Advise caution.", "动词"),
        ("afford", "/əˈfɔːrd/", "负担得起", "Can afford.", "动词"),
        ("agree", "/əˈɡriː/", "同意", "Agree with.", "动词"),
        ("allow", "/əˈlaʊ/", "允许", "Allow access.", "动词"),
        ("answer", "/ˈænsər/", "回答", "Answer questions.", "动词"),
        ("appear", "/əˈpɪr/", "出现", "Appear suddenly.", "动词"),
        ("apply", "/əˈplaɪ/", "申请", "Apply for job.", "动词"),
        ("argue", "/ˈɑːrɡjuː/", "争论", "Argue about.", "动词"),
        ("arrange", "/əˈreɪndʒ/", "安排", "Arrange meeting.", "动词"),
        ("arrive", "/əˈraɪv/", "到达", "Arrive safely.", "动词"),
        ("ask", "/æsk/", "询问", "Ask questions.", "动词"),
        ("attack", "/əˈtæk/", "攻击", "Attack the enemy.", "动词"),
        ("avoid", "/əˈvɔɪd/", "避免", "Avoid mistakes.", "动词"),
        ("beat", "/biːt/", "击败", "Beat the record.", "动词"),
        ("become", "/bɪˈkʌm/", "变成", "Become successful.", "动词"),
        ("begin", "/bɪˈɡɪn/", "开始", "Begin now.", "动词"),
        ("believe", "/bɪˈliːv/", "相信", "Believe in.", "动词"),
        ("break", "/breɪk/", "打破", "Break rules.", "动词"),
        ("bring", "/brɪŋ/", "带来", "Bring changes.", "动词"),
        ("build", "/bɪld/", "建立", "Build trust.", "动词"),
        ("buy", "/baɪ/", "购买", "Buy a house.", "动词"),
        ("call", "/kɔːl/", "打电话", "Call me.", "动词"),
        ("care", "/ker/", "关心", "Care about.", "动词"),
        ("carry", "/ˈkæri/", "携带", "Carry luggage.", "动词"),
        ("catch", "/kætʃ/", "抓住", "Catch the bus.", "动词"),
        ("cause", "/kɔːz/", "导致", "Cause problems.", "动词"),
        ("change", "/tʃeɪndʒ/", "改变", "Change plans.", "动词"),
        ("check", "/tʃek/", "检查", "Check email.", "动词"),
        ("choose", "/tʃuːz/", "选择", "Choose wisely.", "动词"),
        ("claim", "/kleɪm/", "声称", "Claim responsibility.", "动词"),
        ("clean", "/kliːn/", "打扫", "Clean the room.", "动词"),
        ("clear", "/klɪr/", "清除", "Clear the desk.", "动词"),
        ("climb", "/klaɪm/", "攀登", "Climb mountains.", "动词"),
        ("close", "/kloʊz/", "关闭", "Close the door.", "动词"),
        ("collect", "/kəˈlekt/", "收集", "Collect data.", "动词"),
        ("come", "/kʌm/", "来", "Come here.", "动词"),
        ("compare", "/kəmˈper/", "比较", "Compare prices.", "动词"),
        ("complete", "/kəmˈpliːt/", "完成", "Complete task.", "动词"),
        ("connect", "/kəˈnekt/", "连接", "Connect to wifi.", "动词"),
        ("consider", "/kənˈsɪdər/", "考虑", "Consider options.", "动词"),
        ("contain", "/kənˈteɪn/", "包含", "Contain information.", "动词"),
        ("continue", "/kənˈtɪnjuː/", "继续", "Continue working.", "动词"),
        ("control", "/kənˈtroʊl/", "控制", "Control emotions.", "动词"),
        ("cook", "/kʊk/", "烹饪", "Cook dinner.", "动词"),
        ("copy", "/ˈkɑːpi/", "复制", "Copy files.", "动词"),
        ("correct", "/kəˈrekt/", "纠正", "Correct mistakes.", "动词"),
        ("cost", "/kɔːst/", "花费", "Cost money.", "动词"),
        ("count", "/kaʊnt/", "数数", "Count the items.", "动词"),
        ("cover", "/ˈkʌvər/", "覆盖", "Cover the topic.", "动词"),
        ("create", "/kriˈeɪt/", "创造", "Create value.", "动词"),
        ("cross", "/krɔːs/", "穿过", "Cross the street.", "动词"),
        ("cry", "/kraɪ/", "哭泣", "Cry for help.", "动词"),
        ("cut", "/kʌt/", "切割", "Cut the paper.", "动词"),
        ("dance", "/dæns/", "跳舞", "Dance together.", "动词"),
        ("decide", "/dɪˈsaɪd/", "决定", "Decide quickly.", "动词"),
        ("describe", "/dɪˈskraɪb/", "描述", "Describe the scene.", "动词"),
        ("design", "/dɪˈzaɪn/", "设计", "Design system.", "动词"),
        ("develop", "/dɪˈveləp/", "开发", "Develop skills.", "动词"),
        ("die", "/daɪ/", "死亡", "Die young.", "动词"),
        ("discuss", "/dɪˈskʌs/", "讨论", "Discuss plans.", "动词"),
        ("divide", "/dɪˈvaɪd/", "分割", "Divide tasks.", "动词"),
        ("do", "/duː/", "做", "Do your best.", "动词"),
        ("draw", "/drɔː/", "画", "Draw a picture.", "动词"),
        ("drink", "/drɪŋk/", "喝", "Drink water.", "动词"),
        ("drive", "/draɪv/", "驾驶", "Drive carefully.", "动词"),
        ("eat", "/iːt/", "吃", "Eat healthy.", "动词"),
        ("enjoy", "/ɪnˈdʒɔɪ/", "享受", "Enjoy life.", "动词"),
        ("enter", "/ˈentər/", "进入", "Enter the room.", "动词"),
        ("escape", "/ɪˈskeɪp/", "逃跑", "Escape danger.", "动词"),
        ("explain", "/ɪkˈspleɪn/", "解释", "Explain clearly.", "动词"),
        ("express", "/ɪkˈspres/", "表达", "Express feelings.", "动词"),
        ("face", "/feɪs/", "面对", "Face challenges.", "动词"),
        ("fail", "/feɪl/", "失败", "Fail to.", "动词"),
        ("fall", "/fɔːl/", "落下", "Fall asleep.", "动词"),
        ("feel", "/fiːl/", "感觉", "Feel better.", "动词"),
        ("fight", "/faɪt/", "战斗", "Fight for.", "动词"),
        ("find", "/faɪnd/", "找到", "Find solution.", "动词"),
        ("finish", "/ˈfɪnɪʃ/", "完成", "Finish work.", "动词"),
        ("fit", "/fɪt/", "适合", "Fit well.", "动词"),
        ("fly", "/flaɪ/", "飞行", "Fly high.", "动词"),
        ("forget", "/fərˈɡet/", "忘记", "Forget password.", "动词"),
        ("forgive", "/fərˈɡɪv/", "原谅", "Forgive mistakes.", "动词"),
        ("get", "/ɡet/", "得到", "Get ready.", "动词"),
        ("give", "/ɡɪv/", "给予", "Give up.", "动词"),
        ("go", "/ɡoʊ/", "去", "Go home.", "动词"),
        ("grow", "/ɡroʊ/", "成长", "Grow fast.", "动词"),
        ("handle", "/ˈhændl/", "处理", "Handle stress.", "动词"),
        ("happen", "/ˈhæpən/", "发生", "Happen suddenly.", "动词"),
        ("have", "/hæv/", "有", "Have fun.", "动词"),
        ("hear", "/hɪr/", "听到", "Hear music.", "动词"),
        ("help", "/help/", "帮助", "Help others.", "动词"),
        ("hide", "/haɪd/", "隐藏", "Hide feelings.", "动词"),
        ("hit", "/hɪt/", "击打", "Hit the target.", "动词"),
        ("hold", "/hoʊld/", "握住", "Hold on.", "动词"),
        ("hope", "/hoʊp/", "希望", "Hope for.", "动词"),
        ("imagine", "/ɪˈmædʒɪn/", "想象", "Imagine that.", "动词"),
        ("improve", "/ɪmˈpruːv/", "改善", "Improve skills.", "动词"),
        ("include", "/ɪnˈkluːd/", "包括", "Include details.", "动词"),
        ("increase", "/ɪnˈkriːs/", "增加", "Increase sales.", "动词"),
        ("keep", "/kiːp/", "保持", "Keep calm.", "动词"),
        ("kill", "/kɪl/", "杀死", "Kill time.", "动词"),
        ("know", "/noʊ/", "知道", "Know the answer.", "动词"),
        ("laugh", "/læf/", "笑", "Laugh loudly.", "动词"),
        ("lead", "/liːd/", "领导", "Lead team.", "动词"),
        ("learn", "/lɜːrn/", "学习", "Learn quickly.", "动词"),
        ("leave", "/liːv/", "离开", "Leave now.", "动词"),
        ("let", "/let/", "让", "Let go.", "动词"),
        ("lie", "/laɪ/", "躺", "Lie down.", "动词"),
        ("like", "/laɪk/", "喜欢", "Like it.", "动词"),
        ("listen", "/ˈlɪsn/", "听", "Listen carefully.", "动词"),
        ("live", "/lɪv/", "居住", "Live well.", "动词"),
        ("look", "/lʊk/", "看", "Look around.", "动词"),
        ("lose", "/luːz/", "失去", "Lose weight.", "动词"),
        ("love", "/lʌv/", "爱", "Love yourself.", "动词"),
        ("make", "/meɪk/", "制作", "Make progress.", "动词"),
        ("manage", "/ˈmænɪdʒ/", "管理", "Manage time.", "动词"),
        ("mean", "/miːn/", "意思是", "Mean well.", "动词"),
        ("meet", "/miːt/", "见面", "Meet friends.", "动词"),
        ("move", "/muːv/", "移动", "Move forward.", "动词"),
        ("need", "/niːd/", "需要", "Need help.", "动词"),
        ("open", "/ˈoʊpən/", "打开", "Open the door.", "动词"),
        ("pay", "/peɪ/", "支付", "Pay attention.", "动词"),
        ("play", "/pleɪ/", "玩", "Play games.", "动词"),
        ("point", "/pɔɪnt/", "指向", "Point out.", "动词"),
        ("prefer", "/prɪˈfɜːr/", "更喜欢", "Prefer tea.", "动词"),
        ("prepare", "/prɪˈper/", "准备", "Prepare well.", "动词"),
        ("produce", "/prəˈduːs/", "生产", "Produce results.", "动词"),
        ("promise", "/ˈprɑːmɪs/", "承诺", "Promise to.", "动词"),
        ("protect", "/prəˈtekt/", "保护", "Protect environment.", "动词"),
        ("provide", "/prəˈvaɪd/", "提供", "Provide service.", "动词"),
        ("pull", "/pʊl/", "拉", "Pull hard.", "动词"),
        ("push", "/pʊʃ/", "推", "Push through.", "动词"),
        ("put", "/pʊt/", "放", "Put away.", "动词"),
        ("read", "/riːd/", "阅读", "Read books.", "动词"),
        ("realize", "/ˈriːəlaɪz/", "意识到", "Realize dreams.", "动词"),
        ("receive", "/rɪˈsiːv/", "接收", "Receive email.", "动词"),
        ("reduce", "/rɪˈduːs/", "减少", "Reduce costs.", "动词"),
        ("refuse", "/rɪˈfjuːz/", "拒绝", "Refuse to.", "动词"),
        ("remember", "/rɪˈmembər/", "记住", "Remember me.", "动词"),
        ("repeat", "/rɪˈpiːt/", "重复", "Repeat after.", "动词"),
        ("report", "/rɪˈpɔːrt/", "报告", "Report issues.", "动词"),
        ("require", "/rɪˈkwaɪər/", "需要", "Require attention.", "动词"),
        ("return", "/rɪˈtɜːrn/", "返回", "Return home.", "动词"),
        ("run", "/rʌn/", "跑", "Run fast.", "动词"),
        ("save", "/seɪv/", "保存", "Save money.", "动词"),
        ("say", "/seɪ/", "说", "Say hello.", "动词"),
        ("see", "/siː/", "看见", "See clearly.", "动词"),
        ("sell", "/sel/", "卖", "Sell products.", "动词"),
        ("send", "/send/", "发送", "Send message.", "动词"),
        ("serve", "/sɜːrv/", "服务", "Serve people.", "动词"),
        ("set", "/set/", "设置", "Set goals.", "动词"),
        ("shake", "/ʃeɪk/", "摇动", "Shake hands.", "动词"),
        ("share", "/ʃer/", "分享", "Share ideas.", "动词"),
        ("shoot", "/ʃuːt/", "射击", "Shoot photos.", "动词"),
        ("show", "/ʃoʊ/", "展示", "Show respect.", "动词"),
        ("sit", "/sɪt/", "坐", "Sit down.", "动词"),
        ("speak", "/spiːk/", "说话", "Speak up.", "动词"),
        ("stand", "/stænd/", "站立", "Stand tall.", "动词"),
        ("start", "/stɑːrt/", "开始", "Start now.", "动词"),
        ("stay", "/steɪ/", "停留", "Stay safe.", "动词"),
        ("stop", "/stɑːp/", "停止", "Stop talking.", "动词"),
        ("study", "/ˈstʌdi/", "学习", "Study hard.", "动词"),
        ("succeed", "/səkˈsiːd/", "成功", "Succeed in.", "动词"),
        ("suggest", "/səˈdʒest/", "建议", "Suggest ideas.", "动词"),
        ("suppose", "/səˈpoʊz/", "假设", "Suppose that.", "动词"),
        ("take", "/teɪk/", "拿", "Take action.", "动词"),
        ("talk", "/tɔːk/", "谈话", "Talk to.", "动词"),
        ("teach", "/tiːtʃ/", "教", "Teach well.", "动词"),
        ("tell", "/tel/", "告诉", "Tell the truth.", "动词"),
        ("thank", "/θæŋk/", "感谢", "Thank you.", "动词"),
        ("think", "/θɪŋk/", "思考", "Think about.", "动词"),
        ("throw", "/θroʊ/", "扔", "Throw away.", "动词"),
        ("touch", "/tʌtʃ/", "触摸", "Touch screen.", "动词"),
        ("try", "/traɪ/", "尝试", "Try again.", "动词"),
        ("turn", "/tɜːrn/", "转动", "Turn around.", "动词"),
        ("understand", "/ˌʌndərˈstænd/", "理解", "Understand clearly.", "动词"),
        ("use", "/juːz/", "使用", "Use wisely.", "动词"),
        ("visit", "/ˈvɪzɪt/", "拜访", "Visit often.", "动词"),
        ("wait", "/weɪt/", "等待", "Wait here.", "动词"),
        ("walk", "/wɔːk/", "走路", "Walk fast.", "动词"),
        ("want", "/wɑːnt/", "想要", "Want to.", "动词"),
        ("watch", "/wɑːtʃ/", "观看", "Watch TV.", "动词"),
        ("win", "/wɪn/", "赢得", "Win the game.", "动词"),
        ("wish", "/wɪʃ/", "希望", "Wish you luck.", "动词"),
        ("work", "/wɜːrk/", "工作", "Work hard.", "动词"),
        ("write", "/raɪt/", "写", "Write down.", "动词"),
        ("yield", "/jiːld/", "产生", "Yield results.", "动词"),
    ]
    
    added_count = 0
    skipped_count = 0
    
    for word in new_words:
        cursor.execute('SELECT COUNT(*) FROM words WHERE english = ?', (word[0],))
        if cursor.fetchone()[0] == 0:
            cursor.execute('INSERT INTO words (english, phonetic, chinese, example, category) VALUES (?, ?, ?, ?, ?)', word)
            added_count += 1
        else:
            skipped_count += 1
    
    conn.commit()
    
    cursor.execute('SELECT COUNT(*) FROM words')
    total_count = cursor.fetchone()[0]
    
    print(f'添加了 {added_count} 个新单词')
    print(f'跳过了 {skipped_count} 个已存在的单词')
    print(f'数据库总单词数: {total_count}')
    
    conn.close()

if __name__ == '__main__':
    expand_to_5000_final()