#!/usr/bin/env python3
import sqlite3

def expand_common_words():
    conn = sqlite3.connect('../words.db')
    cursor = conn.cursor()
    
    new_words = [
        ("able", "/əˈbɪl/", "能够的", "Able to help.", "形容词"),
        ("actual", "/ˈæktʃuəl/", "实际的", "Actual result.", "形容词"),
        ("additional", "/əˈdɪʃənl/", "额外的", "Additional cost.", "形容词"),
        ("advanced", "/ədˈvɑːnst/", "先进的", "Advanced level.", "形容词"),
        ("afraid", "/əˈfreɪd/", "害怕的", "Don't be afraid.", "形容词"),
        ("aggressive", "/əˈɡresɪv/", "侵略的", "Aggressive style.", "形容词"),
        ("alert", "/əˈlɜːt/", "警觉的", "Stay alert.", "形容词"),
        ("alive", "/əˈlaɪv/", "活着的", "Stay alive.", "形容词"),
        ("alone", "/əˈləʊn/", "独自的", "Not alone.", "形容词"),
        ("amazing", "/əˈmeɪzɪŋ/", "惊人的", "Amazing work.", "形容词"),
        ("angry", "/ˈæŋɡri/", "生气的", "Don't be angry.", "形容词"),
        ("annual", "/ˈænjuəl/", "每年的", "Annual report.", "形容词"),
        ("anxious", "/ˈæŋkʃəs/", "焦虑的", "Feel anxious.", "形容词"),
        ("appropriate", "/əˈprəʊpriət/", "适当的", "Appropriate action.", "形容词"),
        ("arbitrary", "/ˈɑːbɪtrəri/", "任意的", "Arbitrary choice.", "形容词"),
        ("artistic", "/ɑːˈtɪstɪk/", "艺术的", "Artistic talent.", "形容词"),
        ("ashamed", "/əˈʃeɪmd/", "羞耻的", "Don't be ashamed.", "形容词"),
        ("asleep", "/əˈsliːp/", "睡着的", "Fall asleep.", "形容词"),
        ("assistant", "/əˈsɪstənt/", "助理的", "Assistant role.", "形容词"),
        ("attached", "/əˈtætʃt/", "附着的", "Attached file.", "形容词"),
        ("automatic", "/ˌɔːtəˈmætɪk/", "自动的", "Automatic system.", "形容词"),
        ("available", "/əˈveɪləbl/", "可用的", "Not available.", "形容词"),
        ("aware", "/əˈweə(r)/", "意识到的", "Be aware.", "形容词"),
        ("awful", "/ˈɔːfl/", "糟糕的", "Awful weather.", "形容词"),
        ("awkward", "/ˈɔːkwəd/", "尴尬的", "Awkward moment.", "形容词"),
        ("back", "/bæk/", "后面的", "Go back.", "形容词"),
        ("bad", "/bæd/", "坏的", "Not bad.", "形容词"),
        ("basic", "/ˈbeɪsɪk/", "基本的", "Basic needs.", "形容词"),
        ("beautiful", "/ˈbjuːtɪfl/", "美丽的", "Beautiful day.", "形容词"),
        ("beneficial", "/ˌbenɪˈfɪʃl/", "有益的", "Beneficial effect.", "形容词"),
        ("best", "/best/", "最好的", "Best friend.", "形容词"),
        ("better", "/ˈbetə(r)/", "更好的", "Better late.", "形容词"),
        ("bitter", "/ˈbɪtə(r)/", "苦涩的", "Bitter taste.", "形容词"),
        ("blank", "/blæŋk/", "空白的", "Blank page.", "形容词"),
        ("blind", "/blaɪnd/", "盲目的", "Blind faith.", "形容词"),
        ("blue", "/bluː/", "蓝色的", "Blue sky.", "形容词"),
        ("bold", "/bəʊld/", "大胆的", "Bold decision.", "形容词"),
        ("boring", "/ˈbɔːrɪŋ/", "无聊的", "Not boring.", "形容词"),
        ("brave", "/breɪv/", "勇敢的", "Be brave.", "形容词"),
        ("bright", "/braɪt/", "明亮的", "Bright future.", "形容词"),
        ("broad", "/brɔːd/", "宽广的", "Broad shoulders.", "形容词"),
        ("broken", "/ˈbrəʊkən/", "破碎的", "Broken heart.", "形容词"),
        ("busy", "/ˈbɪzi/", "忙碌的", "Too busy.", "形容词"),
        ("calm", "/kɑːm/", "平静的", "Stay calm.", "形容词"),
        ("capable", "/ˈkeɪpəbl/", "有能力的", "Capable hands.", "形容词"),
        ("careful", "/ˈkeəfl/", "小心的", "Be careful.", "形容词"),
        ("casual", "/ˈkæʒuəl/", "随意的", "Casual dress.", "形容词"),
        ("certain", "/ˈsɜːtn/", "确定的", "Certain success.", "形容词"),
        ("cheap", "/tʃiːp/", "便宜的", "Cheap price.", "形容词"),
        ("cheerful", "/ˈtʃɪəfl/", "快乐的", "Cheerful mood.", "形容词"),
        ("chemical", "/ˈkemɪkl/", "化学的", "Chemical reaction.", "形容词"),
        ("chief", "/tʃiːf/", "主要的", "Chief concern.", "形容词"),
        ("civil", "/ˈsɪvl/", "公民的", "Civil society.", "形容词"),
        ("clean", "/kliːn/", "清洁的", "Clean room.", "形容词"),
        ("clear", "/klɪə(r)/", "清楚的", "Clear mind.", "形容词"),
        ("clever", "/ˈklevə(r)/", "聪明的", "Clever idea.", "形容词"),
        ("close", "/kləʊs/", "亲密的", "Close friend.", "形容词"),
        ("cloudy", "/ˈklaʊdi/", "多云的", "Cloudy day.", "形容词"),
        ("cold", "/kəʊld/", "寒冷的", "Cold water.", "形容词"),
        ("collective", "/kəˈlektɪv/", "集体的", "Collective effort.", "形容词"),
        ("comfortable", "/ˈkʌmftəbl/", "舒适的", "Comfortable life.", "形容词"),
        ("common", "/ˈkɒmən/", "普通的", "Common ground.", "形容词"),
        ("complex", "/ˈkɒmpleks/", "复杂的", "Complex issue.", "形容词"),
        ("confident", "/ˈkɒnfɪdənt/", "自信的", "Confident smile.", "形容词"),
        ("confused", "/kənˈfjuːzd/", "困惑的", "Confused state.", "形容词"),
        ("conscious", "/ˈkɒnʃəs/", "有意识的", "Conscious choice.", "形容词"),
        ("consistent", "/kənˈsɪstənt/", "一致的", "Consistent effort.", "形容词"),
        ("constant", "/ˈkɒnstənt/", "持续的", "Constant love.", "形容词"),
        ("content", "/kənˈtent/", "满足的", "Content life.", "形容词"),
        ("convenient", "/kənˈviːniənt/", "方便的", "Convenient time.", "形容词"),
        ("cool", "/kuːl/", "凉爽的", "Cool breeze.", "形容词"),
        ("correct", "/kəˈrekt/", "正确的", "Correct answer.", "形容词"),
        ("crazy", "/ˈkreɪzi/", "疯狂的", "Crazy idea.", "形容词"),
        ("creative", "/kriˈeɪtɪv/", "有创造力的", "Creative mind.", "形容词"),
        ("critical", "/ˈkrɪtɪkl/", "关键的", "Critical thinking.", "形容词"),
        ("cruel", "/ˈkruːəl/", "残酷的", "Cruel fate.", "形容词"),
        ("cultural", "/ˈkʌltʃərəl/", "文化的", "Cultural heritage.", "形容词"),
        ("curious", "/ˈkjʊəriəs/", "好奇的", "Curious mind.", "形容词"),
        ("current", "/ˈkʌrənt/", "当前的", "Current events.", "形容词"),
        ("daily", "/ˈdeɪli/", "每天的", "Daily routine.", "形容词"),
        ("dangerous", "/ˈdeɪndʒərəs/", "危险的", "Dangerous path.", "形容词"),
        ("dark", "/dɑːk/", "黑暗的", "Dark night.", "形容词"),
        ("dead", "/ded/", "死的", "Dead end.", "形容词"),
        ("deaf", "/def/", "聋的", "Deaf to reason.", "形容词"),
        ("dear", "/dɪə(r)/", "亲爱的", "Dear friend.", "形容词"),
        ("decent", "/ˈdiːsnt/", "体面的", "Decent living.", "形容词"),
        ("deep", "/diːp/", "深的", "Deep thought.", "形容词"),
        ("defensive", "/dɪˈfensɪv/", "防御的", "Defensive play.", "形容词"),
        ("delicate", "/ˈdelɪkət/", "精致的", "Delicate touch.", "形容词"),
        ("delicious", "/dɪˈlɪʃəs/", "美味的", "Delicious food.", "形容词"),
        ("dependent", "/dɪˈpendənt/", "依赖的", "Dependent on.", "形容词"),
        ("desperate", "/ˈdespərət/", "绝望的", "Desperate need.", "形容词"),
        ("detailed", "/ˈdiːteɪld/", "详细的", "Detailed plan.", "形容词"),
        ("determined", "/dɪˈtɜːmɪnd/", "坚决的", "Determined effort.", "形容词"),
        ("different", "/ˈdɪfrənt/", "不同的", "Different view.", "形容词"),
        ("difficult", "/ˈdɪfɪkəlt/", "困难的", "Difficult task.", "形容词"),
        ("digital", "/ˈdɪdʒɪtl/", "数字的", "Digital age.", "形容词"),
        ("dirty", "/ˈdɜːti/", "脏的", "Dirty hands.", "形容词"),
        ("direct", "/dɪˈrekt/", "直接的", "Direct approach.", "形容词"),
        ("distinct", "/dɪˈstɪŋkt/", "独特的", "Distinct style.", "形容词"),
        ("distant", "/ˈdɪstənt/", "遥远的", "Distant dream.", "形容词"),
        ("diverse", "/daɪˈvɜːs/", "多样的", "Diverse skills.", "形容词"),
        ("double", "/ˈdʌbl/", "双重的", "Double check.", "形容词"),
        ("doubtful", "/ˈdaʊtfl/", "怀疑的", "Doubtful mind.", "形容词"),
        ("dramatic", "/drəˈmætɪk/", "戏剧性的", "Dramatic change.", "形容词"),
        ("drunk", "/drʌŋk/", "喝醉的", "Get drunk.", "形容词"),
        ("dry", "/draɪ/", "干燥的", "Dry season.", "形容词"),
        ("due", "/djuː/", "到期的", "Due date.", "形容词"),
        ("dull", "/dʌl/", "枯燥的", "Dull moment.", "形容词"),
        ("dumb", "/dʌm/", "愚蠢的", "Dumb question.", "形容词"),
        ("dynamic", "/daɪˈnæmɪk/", "动态的", "Dynamic team.", "形容词"),
        ("eager", "/ˈiːɡə(r)/", "渴望的", "Eager to learn.", "形容词"),
        ("early", "/ˈɜːli/", "早的", "Early bird.", "形容词"),
        ("earnest", "/ˈɜːnɪst/", "认真的", "Earnest effort.", "形容词"),
        ("east", "/iːst/", "东方的", "East side.", "形容词"),
        ("economic", "/ˌiːkəˈnɒmɪk/", "经济的", "Economic growth.", "形容词"),
        ("educational", "/ˌedʒuˈkeɪʃənl/", "教育的", "Educational value.", "形容词"),
        ("effective", "/ɪˈfektɪv/", "有效的", "Effective method.", "形容词"),
        ("efficient", "/ɪˈfɪʃnt/", "高效的", "Efficient work.", "形容词"),
        ("elaborate", "/ɪˈlæbərət/", "精心制作的", "Elaborate plan.", "形容词"),
        ("elderly", "/ˈeldəli/", "年长的", "Elderly care.", "形容词"),
        ("electric", "/ɪˈlektrɪk/", "电的", "Electric power.", "形容词"),
        ("elegant", "/ˈelɪɡənt/", "优雅的", "Elegant style.", "形容词"),
        ("elementary", "/ˌelɪˈmentri/", "基本的", "Elementary school.", "形容词"),
        ("eligible", "/ˈelɪdʒəbl/", "有资格的", "Eligible voters.", "形容词"),
        ("embarrassed", "/ɪmˈbærəst/", "尴尬的", "Embarrassed face.", "形容词"),
        ("emotional", "/ɪˈməʊʃənl/", "情感的", "Emotional support.", "形容词"),
        ("empty", "/ˈempti/", "空的", "Empty promise.", "形容词"),
        ("encouraging", "/ɪnˈkʌrɪdʒɪŋ/", "鼓舞人心的", "Encouraging words.", "形容词"),
        ("energetic", "/ˌenəˈdʒetɪk/", "精力充沛的", "Energetic person.", "形容词"),
        ("engaged", "/ɪnˈɡeɪdʒd/", "忙碌的", "Engaged signal.", "形容词"),
        ("enormous", "/ɪˈnɔːməs/", "巨大的", "Enormous impact.", "形容词"),
        ("entire", "/ɪnˈtaɪə(r)/", "整个的", "Entire family.", "形容词"),
        ("enthusiastic", "/ɪnˌθjuːziˈæstɪk/", "热情的", "Enthusiastic support.", "形容词"),
        ("equal", "/ˈiːkwəl/", "相等的", "Equal rights.", "形容词"),
        ("essential", "/ɪˈsenʃl/", "基本的", "Essential needs.", "形容词"),
        ("eternal", "/ɪˈtɜːnl/", "永恒的", "Eternal love.", "形容词"),
        ("ethical", "/ˈeθɪkl/", "道德的", "Ethical choice.", "形容词"),
        ("ethnic", "/ˈeθnɪk/", "种族的", "Ethnic diversity.", "形容词"),
        ("exact", "/ɪɡˈzækt/", "精确的", "Exact amount.", "形容词"),
        ("excellent", "/ˈeksələnt/", "优秀的", "Excellent work.", "形容词"),
        ("excited", "/ɪkˈsaɪtɪd/", "兴奋的", "Excited mood.", "形容词"),
        ("exclusive", "/ɪkˈskluːsɪv/", "独有的", "Exclusive offer.", "形容词"),
        ("exhausted", "/ɪɡˈzɔːstɪd/", "精疲力竭的", "Exhausted body.", "形容词"),
        ("expensive", "/ɪkˈspensɪv/", "昂贵的", "Expensive taste.", "形容词"),
        ("expert", "/ˈekspɜːt/", "专家的", "Expert advice.", "形容词"),
        ("explicit", "/ɪkˈsplɪsɪt/", "明确的", "Explicit instruction.", "形容词"),
        ("external", "/ɪkˈstɜːnl/", "外部的", "External factor.", "形容词"),
        ("extreme", "/ɪkˈstriːm/", "极端的", "Extreme weather.", "形容词"),
        ("fabulous", "/ˈfæbjələs/", "极好的", "Fabulous news.", "形容词"),
        ("fair", "/feə(r)/", "公平的", "Fair play.", "形容词"),
        ("faithful", "/ˈfeɪθfl/", "忠诚的", "Faithful friend.", "形容词"),
        ("false", "/fɔːls/", "错误的", "False claim.", "形容词"),
        ("familiar", "/fəˈmɪliə(r)/", "熟悉的", "Familiar face.", "形容词"),
        ("famous", "/ˈfeɪməs/", "著名的", "Famous landmark.", "形容词"),
        ("fancy", "/ˈfænsi/", "花哨的", "Fancy dress.", "形容词"),
        ("fantastic", "/fænˈtæstɪk/", "极好的", "Fantastic idea.", "形容词"),
        ("far", "/fɑː(r)/", "远的", "Far away.", "形容词"),
        ("fatal", "/ˈfeɪtl/", "致命的", "Fatal error.", "形容词"),
        ("favorite", "/ˈfeɪvərɪt/", "最喜欢的", "Favorite song.", "形容词"),
        ("fearful", "/ˈfɪəfl/", "恐惧的", "Fearful heart.", "形容词"),
        ("feasible", "/ˈfiːzəbl/", "可行的", "Feasible plan.", "形容词"),
        ("federal", "/ˈfedərəl/", "联邦的", "Federal law.", "形容词"),
        ("female", "/ˈfiːmeɪl/", "女性的", "Female voice.", "形容词"),
        ("fertile", "/ˈfɜːtaɪl/", "肥沃的", "Fertile land.", "形容词"),
        ("fierce", "/fɪəs/", "凶猛的", "Fierce competition.", "形容词"),
        ("final", "/ˈfaɪnl/", "最后的", "Final decision.", "形容词"),
        ("financial", "/faɪˈnænʃl/", "财政的", "Financial plan.", "形容词"),
        ("fine", "/faɪn/", "好的", "I'm fine.", "形容词"),
        ("firm", "/fɜːm/", "坚定的", "Firm belief.", "形容词"),
        ("first", "/fɜːst/", "第一的", "First place.", "形容词"),
        ("fit", "/fɪt/", "健康的", "Fit body.", "形容词"),
        ("fixed", "/fɪkst/", "固定的", "Fixed price.", "形容词"),
        ("flawed", "/flɔːd/", "有缺陷的", "Flawed logic.", "形容词"),
        ("flexible", "/ˈfleksəbl/", "灵活的", "Flexible schedule.", "形容词"),
        ("fluent", "/ˈfluːənt/", "流利的", "Fluent speech.", "形容词"),
        ("fond", "/fɒnd/", "喜欢的", "Fond of music.", "形容词"),
        ("foolish", "/ˈfuːlɪʃ/", "愚蠢的", "Foolish mistake.", "形容词"),
        ("foreign", "/ˈfɒrən/", "外国的", "Foreign language.", "形容词"),
        ("formal", "/ˈfɔːml/", "正式的", "Formal event.", "形容词"),
        ("former", "/ˈfɔːmə(r)/", "以前的", "Former president.", "形容词"),
        ("fortunate", "/ˈfɔːtʃənət/", "幸运的", "Fortunate life.", "形容词"),
        ("fragile", "/ˈfrædʒaɪl/", "脆弱的", "Fragile item.", "形容词"),
        ("free", "/friː/", "自由的", "Free mind.", "形容词"),
        ("frequent", "/ˈfriːkwənt/", "频繁的", "Frequent visits.", "形容词"),
        ("fresh", "/freʃ/", "新鲜的", "Fresh air.", "形容词"),
        ("friendly", "/ˈfrendli/", "友好的", "Friendly smile.", "形容词"),
        ("frightened", "/ˈfraɪtnd/", "受惊的", "Frightened cat.", "形容词"),
        ("full", "/fʊl/", "满的", "Full heart.", "形容词"),
        ("fundamental", "/ˌfʌndəˈmentl/", "根本的", "Fundamental right.", "形容词"),
        ("funny", "/ˈfʌni/", "有趣的", "Funny story.", "形容词"),
        ("furious", "/ˈfjʊəriəs/", "暴怒的", "Furious reaction.", "形容词"),
        ("future", "/ˈfjuːtʃə(r)/", "未来的", "Future goals.", "形容词"),
        ("gentle", "/ˈdʒentl/", "温柔的", "Gentle touch.", "形容词"),
        ("genuine", "/ˈdʒenjuɪn/", "真诚的", "Genuine care.", "形容词"),
        ("glad", "/ɡlæd/", "高兴的", "Glad to help.", "形容词"),
        ("global", "/ˈɡləʊbl/", "全球的", "Global issue.", "形容词"),
        ("golden", "/ˈɡəʊldən/", "金色的", "Golden opportunity.", "形容词"),
        ("good", "/ɡʊd/", "好的", "Good job.", "形容词"),
        ("grateful", "/ˈɡreɪtfl/", "感激的", "Grateful heart.", "形容词"),
        ("great", "/ɡreɪt/", "伟大的", "Great news.", "形容词"),
        ("gross", "/ɡrəʊs/", "严重的", "Gross error.", "形容词"),
        ("guilty", "/ˈɡɪlti/", "内疚的", "Guilty conscience.", "形容词"),
        ("happy", "/ˈhæpi/", "快乐的", "Happy life.", "形容词"),
        ("harsh", "/hɑːʃ/", "严厉的", "Harsh reality.", "形容词"),
        ("healthy", "/ˈhelθi/", "健康的", "Healthy body.", "形容词"),
        ("heavy", "/ˈhevi/", "沉重的", "Heavy load.", "形容词"),
        ("helpful", "/ˈhelpfl/", "有帮助的", "Helpful advice.", "形容词"),
        ("hidden", "/ˈhɪdn/", "隐藏的", "Hidden talent.", "形容词"),
        ("high", "/haɪ/", "高的", "High standards.", "形容词"),
        ("hollow", "/ˈhɒləʊ/", "空的", "Hollow promise.", "形容词"),
        ("honest", "/ˈɒnɪst/", "诚实的", "Honest person.", "形容词"),
        ("hopeful", "/ˈhəʊpfl/", "充满希望的", "Hopeful future.", "形容词"),
        ("horrible", "/ˈhɒrəbl/", "可怕的", "Horrible dream.", "形容词"),
        ("hot", "/hɒt/", "热的", "Hot weather.", "形容词"),
        ("huge", "/hjuːdʒ/", "巨大的", "Huge success.", "形容词"),
        ("human", "/ˈhjuːmən/", "人类的", "Human rights.", "形容词"),
        ("humble", "/ˈhʌmbl/", "谦逊的", "Humble attitude.", "形容词"),
        ("hungry", "/ˈhʌŋɡri/", "饥饿的", "Hungry stomach.", "形容词"),
        ("ideal", "/aɪˈdiːəl/", "理想的", "Ideal world.", "形容词"),
        ("identical", "/aɪˈdentɪkl/", "完全相同的", "Identical twins.", "形容词"),
        ("idle", "/ˈaɪdl/", "空闲的", "Idle time.", "形容词"),
        ("ignorant", "/ˈɪɡnərənt/", "无知的", "Ignorant claim.", "形容词"),
        ("illegal", "/ɪˈliːɡl/", "非法的", "Illegal act.", "形容词"),
        ("illiterate", "/ɪˈlɪtərət/", "不识字的", "Illiterate population.", "形容词"),
        ("imaginary", "/ɪˈmædʒɪnəri/", "想象的", "Imaginary friend.", "形容词"),
        ("immediate", "/ɪˈmiːdiət/", "立即的", "Immediate action.", "形容词"),
        ("immune", "/ɪˈmjuːn/", "免疫的", "Immune system.", "形容词"),
        ("impatient", "/ɪmˈpeɪʃnt/", "不耐烦的", "Impatient mood.", "形容词"),
        ("implicit", "/ɪmˈplɪsɪt/", "含蓄的", "Implicit meaning.", "形容词"),
        ("impossible", "/ɪmˈpɒsəbl/", "不可能的", "Impossible dream.", "形容词"),
        ("impressed", "/ɪmˈprest/", "印象深刻的", "Impressed by.", "形容词"),
        ("improper", "/ɪmˈprɒpə(r)/", "不恰当的", "Improper conduct.", "形容词"),
        ("inaccurate", "/ɪnˈækjərət/", "不准确的", "Inaccurate data.", "形容词"),
        ("inactive", "/ɪnˈæktɪv/", "不活跃的", "Inactive account.", "形容词"),
        ("inadequate", "/ɪnˈædɪkwət/", "不充分的", "Inadequate supply.", "形容词"),
        ("inappropriate", "/ˌɪnəˈprəʊpriət/", "不当的", "Inappropriate behavior.", "形容词"),
        ("incapable", "/ɪnˈkeɪpəbl/", "无能力的", "Incapable of.", "形容词"),
        ("inclined", "/ɪnˈklaɪnd/", "倾向于", "Inclined to.", "形容词"),
        ("incomplete", "/ˌɪnkəmˈpliːt/", "不完整的", "Incomplete task.", "形容词"),
        ("incredible", "/ɪnˈkredəbl/", "难以置信的", "Incredible story.", "形容词"),
        ("independent", "/ˌɪndɪˈpendənt/", "独立的", "Independent thinker.", "形容词"),
        ("indifferent", "/ɪnˈdɪfrənt/", "冷漠的", "Indifferent attitude.", "形容词"),
        ("indirect", "/ˌɪndɪˈrekt/", "间接的", "Indirect approach.", "形容词"),
        ("indispensable", "/ˌɪndɪˈspensəbl/", "不可或缺的", "Indispensable tool.", "形容词"),
        ("individual", "/ˌɪndɪˈvɪdʒuəl/", "个人的", "Individual rights.", "形容词"),
        ("industrial", "/ɪnˈdʌstriəl/", "工业的", "Industrial area.", "形容词"),
    ]
    
    added_count = 0
    skipped_count = 0
    
    for word in new_words:
        cursor.execute('SELECT COUNT(*) FROM words WHERE english = ?', (word[0],))
        if cursor.fetchone()[0] == 0:
            cursor.execute('INSERT INTO words (english, phonetic, chinese, example, category) VALUES (?, ?, ?, ?, ?)', word)
            added_count += 1
        else:
            skipped_count += 1
    
    conn.commit()
    
    cursor.execute('SELECT COUNT(*) FROM words')
    total_count = cursor.fetchone()[0]
    
    print(f'添加了 {added_count} 个新单词')
    print(f'跳过了 {skipped_count} 个已存在的单词')
    print(f'数据库总单词数: {total_count}')
    
    conn.close()

if __name__ == '__main__':
    expand_common_words()
