#!/usr/bin/env python3
import json
import sqlite3
from pathlib import Path

def expand_vocabulary_massive():
    """大规模扩展词汇到5000+单词"""
    
    expanded_words = []
    
    # 更多动词 - 高级和常用 (800+)
    more_verbs = [
        ("accommodate", "/əˈkɒmədeɪt/", "容纳", "Accommodate guests.", "动词", "高级动词"),
        ("accompany", "/əˈkʌmpəni/", "陪伴", "Accompany me.", "动词", "高级动词"),
        ("account", "/əˈkaʊnt/", "解释", "Account for this.", "动词", "高级动词"),
        ("accuse", "/əˈkjuːz/", "指责", "Don't accuse me.", "动词", "高级动词"),
        ("achieve", "/əˈtʃiːv/", "实现", "Achieve dreams.", "动词", "高级动词"),
        ("acquire", "/əˈkwaɪər/", "获得", "Acquire skills.", "动词", "高级动词"),
        ("act", "/ækt/", "行动", "Act now.", "动词", "常用动词"),
        ("activate", "/ˈæktɪveɪt/", "激活", "Activate system.", "动词", "高级动词"),
        ("adapt", "/əˈdæpt/", "适应", "Adapt to change.", "动词", "高级动词"),
        ("add", "/æd/", "添加", "Add more words.", "动词", "常用动词"),
        ("address", "/əˈdres/", "处理", "Address issue.", "动词", "高级动词"),
        ("adjust", "/əˈdʒʌst/", "调整", "Adjust settings.", "动词", "高级动词"),
        ("administer", "/ədˈmɪnɪstər/", "管理", "Administer test.", "动词", "高级动词"),
        ("admire", "/ədˈmaɪər/", "钦佩", "I admire you.", "动词", "高级动词"),
        ("admit", "/ədˈmɪt/", "承认", "Admit your mistake.", "动词", "高级动词"),
        ("adopt", "/əˈdɒpt/", "采用", "Adopt a new approach.", "动词", "高级动词"),
        ("advance", "/ədˈvæns/", "前进", "Advance your career.", "动词", "高级动词"),
        ("advise", "/ədˈvaɪz/", "建议", "Advise wisely.", "动词", "高级动词"),
        ("advocate", "/ˈædvəkeɪt/", "提倡", "Advocate for change.", "动词", "高级动词"),
        ("affect", "/əˈfekt/", "影响", "Affect outcome.", "动词", "高级动词"),
        ("afford", "/əˈfɔːd/", "负担得起", "I can afford it.", "动词", "高级动词"),
        ("age", "/eɪdʒ/", "变老", "Wine ages well.", "动词", "常用动词"),
        ("agree", "/əˈɡriː/", "同意", "I agree with you.", "动词", "常用动词"),
        ("aid", "/eɪd/", "援助", "Aid victims.", "动词", "高级动词"),
        ("aim", "/eɪm/", "瞄准", "Aim for success.", "动词", "常用动词"),
        ("allow", "/əˈlaʊ/", "允许", "Allow me to help.", "动词", "常用动词"),
        ("alter", "/ˈɔːltər/", "改变", "Alter plan.", "动词", "高级动词"),
        ("amaze", "/əˈmeɪz/", "使惊讶", "You amaze me.", "动词", "高级动词"),
        ("amuse", "/əˈmjuːz/", "逗乐", "Amuse children.", "动词", "高级动词"),
        ("analyze", "/ˈænəlaɪz/", "分析", "Analyze data.", "动词", "高级动词"),
        ("announce", "/əˈnaʊns/", "宣布", "Announce news.", "动词", "高级动词"),
        ("annoy", "/əˈnɔɪ/", "使烦恼", "Don't annoy me.", "动词", "高级动词"),
        ("answer", "/ˈænsər/", "回答", "Answer question.", "动词", "常用动词"),
        ("anticipate", "/ænˈtɪsɪpeɪt/", "预期", "Anticipate problems.", "动词", "高级动词"),
        ("apologize", "/əˈpɒlədʒaɪz/", "道歉", "Apologize sincerely.", "动词", "高级动词"),
        ("appear", "/əˈpɪər/", "出现", "Problems appear.", "动词", "常用动词"),
        ("applaud", "/əˈplɔːd/", "鼓掌", "Applaud loudly.", "动词", "高级动词"),
        ("apply", "/əˈplaɪ/", "申请", "Apply for job.", "动词", "常用动词"),
        ("appoint", "/əˈpɔɪnt/", "任命", "Appoint a leader.", "动词", "高级动词"),
        ("appreciate", "/əˈpriːʃieɪt/", "感激", "I appreciate it.", "动词", "高级动词"),
        ("approach", "/əˈprəʊtʃ/", "接近", "Approach carefully.", "动词", "高级动词"),
        ("approve", "/əˈpruːv/", "批准", "Approve request.", "动词", "高级动词"),
        ("argue", "/ˈɑːɡjuː/", "争论", "Don't argue.", "动词", "常用动词"),
        ("arise", "/əˈraɪz/", "出现", "Problems arise.", "动词", "高级动词"),
        ("arrange", "/əˈreɪndʒ/", "安排", "Arrange a meeting.", "动词", "常用动词"),
        ("arrest", "/əˈrest/", "逮捕", "Arrest suspect.", "动词", "高级动词"),
        ("arrive", "/əˈraɪv/", "到达", "Arrive on time.", "动词", "常用动词"),
        ("ask", "/æsk/", "询问", "Ask questions.", "动词", "常用动词"),
        ("assemble", "/əˈsembl/", "组装", "Assemble team.", "动词", "高级动词"),
        ("assert", "/əˈsɜːt/", "断言", "Assert your rights.", "动词", "高级动词"),
        ("assess", "/əˈses/", "评估", "Assess damage.", "动词", "高级动词"),
        ("assist", "/əˈsɪst/", "协助", "Assist your colleagues.", "动词", "高级动词"),
        ("assume", "/əˈsjuːm/", "假设", "Don't assume.", "动词", "高级动词"),
        ("assure", "/əˈʃʊər/", "保证", "I assure you.", "动词", "高级动词"),
        ("attach", "/əˈtætʃ/", "附加", "Attach file.", "动词", "高级动词"),
        ("attack", "/əˈtæk/", "攻击", "Attack problem.", "动词", "高级动词"),
        ("attempt", "/əˈtempt/", "尝试", "Attempt task.", "动词", "高级动词"),
        ("attend", "/əˈtend/", "参加", "Attend class.", "动词", "常用动词"),
        ("attract", "/əˈtrækt/", "吸引", "Attract attention.", "动词", "高级动词"),
        ("attribute", "/əˈtrɪbjuːt/", "归因", "Attribute success to hard work.", "动词", "高级动词"),
        ("auction", "/ˈɔːkʃn/", "拍卖", "Auction item.", "动词", "高级动词"),
        ("avoid", "/əˈvɔɪd/", "避免", "Avoid mistakes.", "动词", "常用动词"),
        ("await", "/əˈweɪt/", "等待", "Await my return.", "动词", "高级动词"),
        ("award", "/əˈwɔːd/", "授予", "Award prize.", "动词", "高级动词"),
        ("back", "/bæk/", "支持", "Back me up.", "动词", "常用动词"),
        ("bake", "/beɪk/", "烘烤", "Bake a cake.", "动词", "常用动词"),
        ("balance", "/ˈbæləns/", "平衡", "Balance your life.", "动词", "高级动词"),
        ("ban", "/bæn/", "禁止", "Ban smoking.", "动词", "高级动词"),
        ("bang", "/bæŋ/", "猛击", "Don't bang door.", "动词", "常用动词"),
        ("bar", "/bɑːr/", "阻挡", "Bar entrance.", "动词", "高级动词"),
        ("bargain", "/ˈbɑːɡɪn/", "讨价还价", "Bargain hard.", "动词", "高级动词"),
        ("bark", "/bɑːrk/", "吠叫", "The dog barks.", "动词", "常用动词"),
        ("base", "/beɪs/", "基于", "Base on facts.", "动词", "高级动词"),
        ("bathe", "/beɪð/", "洗澡", "Bathe regularly.", "动词", "常用动词"),
        ("beam", "/biːm/", "微笑", "Beam with joy.", "动词", "高级动词"),
        ("bear", "/beər/", "忍受", "Bear with me.", "动词", "常用动词"),
        ("beat", "/biːt/", "击败", "Beat record.", "动词", "常用动词"),
        ("become", "/bɪˈkʌm/", "变成", "Become successful.", "动词", "常用动词"),
        ("beg", "/beɡ/", "乞求", "Don't beg.", "动词", "常用动词"),
        ("begin", "/bɪˈɡɪn/", "开始", "Begin now.", "动词", "常用动词"),
        ("behave", "/bɪˈheɪv/", "表现", "Behave well.", "动词", "常用动词"),
        ("belong", "/bɪˈlɒŋ/", "属于", "Belong to us.", "动词", "常用动词"),
        ("bend", "/bend/", "弯曲", "Bend rules.", "动词", "常用动词"),
        ("bet", "/bet/", "打赌", "Bet on winner.", "动词", "常用动词"),
        ("bind", "/baɪnd/", "捆绑", "Bind books.", "动词", "高级动词"),
        ("bite", "/baɪt/", "咬", "Don't bite.", "动词", "常用动词"),
        ("blame", "/bleɪm/", "责怪", "Don't blame others.", "动词", "常用动词"),
        ("bless", "/bles/", "保佑", "God bless you.", "动词", "高级动词"),
        ("blind", "/blaɪnd/", "使失明", "The light blinded me.", "动词", "高级动词"),
        ("blink", "/blɪŋk/", "眨眼", "Blink your eyes.", "动词", "常用动词"),
        ("block", "/blɒk/", "阻挡", "Block view.", "动词", "常用动词"),
        ("bloom", "/bluːm/", "开花", "Flowers bloom.", "动词", "高级动词"),
        ("blow", "/bləʊ/", "吹", "Blow candle.", "动词", "常用动词"),
        ("board", "/bɔːd/", "登机", "Board plane.", "动词", "常用动词"),
        ("boast", "/bəʊst/", "吹嘘", "Don't boast.", "动词", "高级动词"),
        ("boil", "/bɔɪl/", "煮沸", "Boil water.", "动词", "常用动词"),
        ("bomb", "/bɒm/", "轰炸", "Bomb target.", "动词", "高级动词"),
        ("book", "/bʊk/", "预订", "Book a hotel.", "动词", "常用动词"),
        ("boost", "/buːst/", "促进", "Boost morale.", "动词", "高级动词"),
        ("border", "/ˈbɔːdər/", "接壤", "Border country.", "动词", "高级动词"),
        ("bore", "/bɔːr/", "使厌烦", "Don't bore me.", "动词", "高级动词"),
        ("borrow", "/ˈbɒrəʊ/", "借入", "Borrow some money.", "动词", "常用动词"),
        ("bounce", "/baʊns/", "弹跳", "Bounce ball.", "动词", "常用动词"),
        ("bow", "/baʊ/", "鞠躬", "Bow to queen.", "动词", "常用动词"),
        ("box", "/bɒks/", "拳击", "Box cleverly.", "动词", "常用动词"),
        ("brake", "/breɪk/", "刹车", "Brake car.", "动词", "常用动词"),
        ("branch", "/bræntʃ/", "分支", "Branch out.", "动词", "高级动词"),
        ("break", "/breɪk/", "打破", "Break record.", "动词", "常用动词"),
        ("breathe", "/briːð/", "呼吸", "Breathe deeply.", "动词", "常用动词"),
        ("breed", "/briːd/", "繁殖", "Breed animals.", "动词", "高级动词"),
        ("brew", "/bruː/", "酿造", "Brew coffee.", "动词", "高级动词"),
        ("bring", "/brɪŋ/", "带来", "Bring good news.", "动词", "常用动词"),
        ("broadcast", "/ˈbrɔːdkæst/", "广播", "Broadcast live.", "动词", "高级动词"),
        ("bruise", "/bruːz/", "淤青", "Don't bruise easily.", "动词", "高级动词"),
        ("brush", "/brʌʃ/", "刷", "Brush your teeth.", "动词", "常用动词"),
        ("bubble", "/ˈbʌbl/", "冒泡", "Bubbles rise.", "动词", "高级动词"),
        ("build", "/bɪld/", "建造", "Build a house.", "动词", "常用动词"),
        ("bump", "/bʌmp/", "碰撞", "Bump into someone.", "动词", "常用动词"),
        ("burn", "/bɜːn/", "燃烧", "Burn calories.", "动词", "常用动词"),
        ("burst", "/bɜːst/", "爆发", "Burst into laughter.", "动词", "高级动词"),
        ("bury", "/ˈberi/", "埋葬", "Bury past.", "动词", "高级动词"),
        ("buy", "/baɪ/", "购买", "Buy quality.", "动词", "常用动词"),
        ("buzz", "/bʌz/", "嗡嗡", "Bees buzz.", "动词", "常用动词"),
        ("calculate", "/ˈkælkjʊleɪt/", "计算", "Calculate cost.", "动词", "高级动词"),
        ("call", "/kɔːl/", "打电话", "Call me later.", "动词", "常用动词"),
        ("calm", "/kɑːm/", "使平静", "Calm down.", "动词", "常用动词"),
        ("camp", "/kæmp/", "露营", "Camp overnight.", "动词", "常用动词"),
        ("cancel", "/ˈkænsəl/", "取消", "Cancel meeting.", "动词", "常用动词"),
        ("capture", "/ˈkæptʃər/", "捕捉", "Capture moment.", "动词", "高级动词"),
        ("care", "/keər/", "关心", "Care for others.", "动词", "常用动词"),
        ("carry", "/ˈkæri/", "携带", "Carry load.", "动词", "常用动词"),
        ("carve", "/kɑːrv/", "雕刻", "Carve statue.", "动词", "高级动词"),
        ("cast", "/kæst/", "投掷", "Cast a vote.", "动词", "高级动词"),
        ("catalog", "/ˈkætəlɒɡ/", "编目", "Catalog items.", "动词", "高级动词"),
        ("catch", "/kætʃ/", "抓住", "Catch bus.", "动词", "常用动词"),
        ("cause", "/kɔːz/", "导致", "Cause and effect.", "动词", "常用动词"),
        ("caution", "/ˈkɔːʃn/", "警告", "Caution advised.", "动词", "高级动词"),
        ("cease", "/siːs/", "停止", "Cease fire.", "动词", "高级动词"),
        ("celebrate", "/ˈselɪbreɪt/", "庆祝", "Celebrate success.", "动词", "高级动词"),
        ("challenge", "/ˈtʃælɪndʒ/", "挑战", "Challenge yourself.", "动词", "高级动词"),
        ("change", "/tʃeɪndʒ/", "改变", "Change world.", "动词", "常用动词"),
        ("charge", "/tʃɑːrdʒ/", "收费", "Charge phone.", "动词", "常用动词"),
        ("chase", "/tʃeɪs/", "追逐", "Chase your dreams.", "动词", "常用动词"),
        ("chat", "/tʃæt/", "聊天", "Chat with friends.", "动词", "常用动词"),
        ("cheat", "/tʃiːt/", "作弊", "Don't cheat.", "动词", "常用动词"),
        ("check", "/tʃek/", "检查", "Check your work.", "动词", "常用动词"),
        ("cheer", "/tʃɪər/", "欢呼", "Cheer for team.", "动词", "高级动词"),
        ("chew", "/tʃuː/", "咀嚼", "Chew slowly.", "动词", "常用动词"),
        ("choke", "/tʃəʊk/", "窒息", "Don't choke.", "动词", "常用动词"),
        ("choose", "/tʃuːz/", "选择", "Choose wisely.", "动词", "常用动词"),
        ("chop", "/tʃɒp/", "砍", "Chop wood.", "动词", "常用动词"),
        ("claim", "/kleɪm/", "声称", "Claim your rights.", "动词", "高级动词"),
        ("clap", "/klæp/", "鼓掌", "Clap your hands.", "动词", "常用动词"),
        ("clarify", "/ˈklærəfaɪ/", "澄清", "Clarify point.", "动词", "高级动词"),
        ("clash", "/klæʃ/", "冲突", "Clash of opinions.", "动词", "高级动词"),
        ("class", "/klæs/", "分类", "Class items.", "动词", "高级动词"),
        ("clean", "/kliːn/", "打扫", "Clean your room.", "动词", "常用动词"),
        ("clear", "/klɪər/", "清除", "Clear desk.", "动词", "常用动词"),
        ("climb", "/klaɪm/", "攀登", "Climb mountain.", "动词", "常用动词"),
        ("cling", "/klɪŋ/", "依附", "Cling to hope.", "动词", "高级动词"),
        ("clip", "/klɪp/", "剪裁", "Clip coupon.", "动词", "常用动词"),
        ("close", "/kləʊz/", "关闭", "Close door.", "动词", "常用动词"),
        ("clothe", "/kləʊð/", "给...穿衣", "Clothe poor.", "动词", "高级动词"),
        ("cluster", "/ˈklʌstər/", "聚集", "Stars cluster.", "动词", "高级动词"),
        ("coach", "/kəʊtʃ/", "教练", "Coach team.", "动词", "高级动词"),
        ("coil", "/kɔɪl/", "卷", "Coil rope.", "动词", "高级动词"),
        ("collect", "/kəˈlekt/", "收集", "Collect stamps.", "动词", "常用动词"),
        ("collide", "/kəˈlaɪd/", "碰撞", "Cars collide.", "动词", "高级动词"),
        ("combine", "/kəmˈbaɪn/", "结合", "Combine efforts.", "动词", "高级动词"),
        ("come", "/kʌm/", "来", "Come here.", "动词", "常用动词"),
        ("command", "/kəˈmænd/", "命令", "Command respect.", "动词", "高级动词"),
        ("commit", "/kəˈmɪt/", "承诺", "Commit to excellence.", "动词", "高级动词"),
        ("communicate", "/kəˈmjuːnɪkeɪt/", "交流", "Communicate well.", "动词", "高级动词"),
        ("compare", "/kəmˈpeər/", "比较", "Compare prices.", "动词", "常用动词"),
        ("compete", "/kəmˈpiːt/", "竞争", "Compete fairly.", "动词", "高级动词"),
        ("compile", "/kəmˈpaɪl/", "编译", "Compile code.", "动词", "高级动词"),
        ("complain", "/kəmˈpleɪn/", "抱怨", "Don't complain.", "动词", "常用动词"),
        ("complete", "/kəmˈpliːt/", "完成", "Complete task.", "动词", "常用动词"),
        ("compose", "/kəmˈpəʊz/", "组成", "Compose music.", "动词", "高级动词"),
        ("compress", "/kəmˈpres/", "压缩", "Compress file.", "动词", "高级动词"),
        ("compromise", "/ˈkɒmprəmaɪz/", "妥协", "Compromise when needed.", "动词", "高级动词"),
        ("compute", "/kəmˈpjuːt/", "计算", "Compute result.", "动词", "高级动词"),
        ("conceal", "/kənˈsiːl/", "隐藏", "Conceal truth.", "动词", "高级动词"),
        ("concentrate", "/ˈkɒnsntreɪt/", "集中", "Concentrate on work.", "动词", "高级动词"),
        ("conclude", "/kənˈkluːd/", "结束", "Conclude meeting.", "动词", "高级动词"),
        ("condemn", "/kənˈdem/", "谴责", "Condemn violence.", "动词", "高级动词"),
        ("condition", "/kənˈdɪʃn/", "conditioning", "Condition your mind.", "动词", "高级动词"),
        ("conduct", "/kənˈdʌkt/", "进行", "Conduct research.", "动词", "高级动词"),
        ("confess", "/kənˈfes/", "坦白", "Confess your sins.", "动词", "高级动词"),
        ("confirm", "/kənˈfɜːm/", "确认", "Confirm details.", "动词", "高级动词"),
        ("conflict", "/kənˈflɪkt/", "冲突", "Conflict arises.", "动词", "高级动词"),
        ("conform", "/kənˈfɔːm/", "遵从", "Conform to rules.", "动词", "高级动词"),
        ("confront", "/kənˈfrʌnt/", "面对", "Confront problem.", "动词", "高级动词"),
        ("confuse", "/kənˈfjuːz/", "使困惑", "Don't confuse me.", "动词", "常用动词"),
        ("connect", "/kəˈnekt/", "连接", "Connect to WiFi.", "动词", "常用动词"),
        ("conquer", "/ˈkɒŋkər/", "征服", "Conquer your fears.", "动词", "高级动词"),
        ("consent", "/kənˈsent/", "同意", "Give your consent.", "动词", "高级动词"),
        ("consider", "/kənˈsɪdər/", "考虑", "Consider all options.", "动词", "常用动词"),
        ("consist", "/kənˈsɪst/", "由...组成", "Consist of facts.", "动词", "高级动词"),
        ("console", "/kənˈsəʊl/", "安慰", "Console grieving.", "动词", "高级动词"),
        ("consolidate", "/kənˈsɒlɪdeɪt/", "巩固", "Consolidate power.", "动词", "高级动词"),
        ("construct", "/kənˈstrʌkt/", "建造", "Construct a building.", "动词", "高级动词"),
        ("consult", "/kənˈsʌlt/", "咨询", "Consult an expert.", "动词", "高级动词"),
        ("consume", "/kənˈsuːm/", "消耗", "Consume energy.", "动词", "高级动词"),
        ("contact", "/ˈkɒntækt/", "联系", "Contact me soon.", "动词", "常用动词"),
        ("contain", "/kənˈteɪn/", "包含", "Contain virus.", "动词", "常用动词"),
        ("contaminate", "/kənˈtæmɪneɪt/", "污染", "Don't contaminate.", "动词", "高级动词"),
        ("contemplate", "/ˈkɒntəmpleɪt/", "沉思", "Contemplate deeply.", "动词", "高级动词"),
        ("continue", "/kənˈtɪnjuː/", "继续", "Continue working.", "动词", "常用动词"),
        ("contract", "/kənˈtrækt/", "收缩", "Contract muscles.", "动词", "高级动词"),
        ("contradict", "/ˌkɒntrəˈdɪkt/", "矛盾", "Don't contradict.", "动词", "高级动词"),
        ("contrast", "/kənˈtræst/", "对比", "Contrast styles.", "动词", "高级动词"),
        ("contribute", "/kənˈtrɪbjuːt/", "贡献", "Contribute to society.", "动词", "高级动词"),
        ("control", "/kənˈtrəʊl/", "控制", "Control your temper.", "动词", "常用动词"),
        ("convert", "/kənˈvɜːt/", "转换", "Convert to PDF.", "动词", "高级动词"),
        ("convict", "/kənˈvɪkt/", "定罪", "Convict criminal.", "动词", "高级动词"),
        ("convince", "/kənˈvɪns/", "说服", "Convince them.", "动词", "高级动词"),
        ("cook", "/kʊk/", "烹饪", "Cook dinner.", "动词", "常用动词"),
        ("cool", "/kuːl/", "冷却", "Cool down.", "动词", "常用动词"),
        ("cooperate", "/kəʊˈɒpəreɪt/", "合作", "Cooperate with others.", "动词", "高级动词"),
        ("coordinate", "/kəʊˈɔːrdɪneɪt/", "协调", "Coordinate team.", "动词", "高级动词"),
        ("copy", "/ˈkɒpi/", "复制", "Copy file.", "动词", "常用动词"),
        ("correct", "/kəˈrekt/", "改正", "Correct errors.", "动词", "常用动词"),
        ("correspond", "/ˌkɒrɪˈspɒnd/", "通信", "Correspond regularly.", "动词", "高级动词"),
        ("corrode", "/kəˈrəʊd/", "腐蚀", "Acid corrodes metal.", "动词", "高级动词"),
        ("corrupt", "/kəˈrʌpt/", "腐蚀", "Don't corrupt.", "动词", "高级动词"),
        ("cost", "/kɒst/", "花费", "It costs money.", "动词", "常用动词"),
        ("cough", "/kɒf/", "咳嗽", "Don't cough.", "动词", "常用动词"),
        ("counsel", "/ˈkaʊnsəl/", "建议", "Counsel client.", "动词", "高级动词"),
        ("count", "/kaʊnt/", "数数", "Count to ten.", "动词", "常用动词"),
        ("cover", "/ˈkʌvər/", "覆盖", "Cover expenses.", "动词", "常用动词"),
        ("crack", "/kræk/", "破裂", "Don't crack.", "动词", "常用动词"),
        ("crash", "/kræʃ/", "坠毁", "The car crashed.", "动词", "常用动词"),
        ("crawl", "/krɔːl/", "爬行", "Babies crawl.", "动词", "常用动词"),
        ("crazy", "/ˈkreɪzi/", "发疯", "Don't go crazy.", "动词", "常用动词"),
        ("create", "/kriˈeɪt/", "创造", "Create value.", "动词", "常用动词"),
        ("creep", "/kriːp/", "爬行", "Creep slowly.", "动词", "高级动词"),
        ("criticize", "/ˈkrɪtɪsaɪz/", "批评", "Criticize constructively.", "动词", "高级动词"),
        ("cross", "/krɒs/", "穿过", "Cross street.", "动词", "常用动词"),
        ("crowd", "/kraʊd/", "拥挤", "Don't crowd.", "动词", "常用动词"),
        ("crush", "/krʌʃ/", "压碎", "Crush can.", "动词", "常用动词"),
        ("cry", "/kraɪ/", "哭", "Don't cry.", "动词", "常用动词"),
        ("cultivate", "/ˈkʌltɪveɪt/", "培养", "Cultivate habits.", "动词", "高级动词"),
        ("cure", "/kjʊər/", "治愈", "Cure disease.", "动词", "高级动词"),
        ("curl", "/kɜːl/", "卷曲", "Curl your hair.", "动词", "常用动词"),
        ("curse", "/kɜːs/", "诅咒", "Don't curse.", "动词", "常用动词"),
        ("curve", "/kɜːv/", "弯曲", "Curve road.", "动词", "高级动词"),
        ("cushion", "/ˈkʊʃn/", "缓冲", "Cushion blow.", "动词", "高级动词"),
        ("custom", "/ˈkʌstəm/", "定制", "Customize it.", "动词", "高级动词"),
        ("cut", "/kʌt/", "切", "Cut cake.", "动词", "常用动词"),
        ("cycle", "/ˈsaɪkl/", "循环", "Cycle through.", "动词", "高级动词"),
        ("damage", "/ˈdæmɪdʒ/", "损坏", "Damage car.", "动词", "高级动词"),
        ("dance", "/dæns/", "跳舞", "Dance with joy.", "动词", "常用动词"),
        ("dare", "/deər/", "敢于", "Dare to dream.", "动词", "常用动词"),
        ("deal", "/diːl/", "处理", "Deal with it.", "动词", "常用动词"),
        ("debate", "/dɪˈbeɪt/", "辩论", "Debate issue.", "动词", "高级动词"),
        ("decay", "/dɪˈkeɪ/", "腐烂", "The fruit decayed.", "动词", "高级动词"),
        ("deceive", "/dɪˈsiːv/", "欺骗", "Don't deceive me.", "动词", "高级动词"),
        ("decide", "/dɪˈsaɪd/", "决定", "Decide now.", "动词", "常用动词"),
        ("declare", "/dɪˈkleər/", "宣布", "Declare independence.", "动词", "高级动词"),
        ("decline", "/dɪˈklaɪn/", "拒绝", "Decline offer.", "动词", "高级动词"),
        ("decorate", "/ˈdekəreɪt/", "装饰", "Decorate room.", "动词", "高级动词"),
        ("decrease", "/dɪˈkriːs/", "减少", "Decrease volume.", "动词", "高级动词"),
        ("dedicate", "/ˈdedɪkeɪt/", "奉献", "Dedicate your life.", "动词", "高级动词"),
        ("defeat", "/dɪˈfiːt/", "击败", "Defeat enemy.", "动词", "高级动词"),
        ("defend", "/dɪˈfend/", "防守", "Defend your position.", "动词", "高级动词"),
        ("define", "/dɪˈfaɪn/", "定义", "Define terms.", "动词", "高级动词"),
        ("deflect", "/dɪˈflekt/", "偏转", "Deflect blame.", "动词", "高级动词"),
        ("delay", "/dɪˈleɪ/", "推迟", "Delay flight.", "动词", "常用动词"),
        ("delete", "/dɪˈliːt/", "删除", "Delete file.", "动词", "常用动词"),
        ("deliberate", "/dɪˈlɪbəreɪt/", "深思熟虑", "Deliberate carefully.", "动词", "高级动词"),
        ("delicate", "/ˈdelɪkət/", "使精致", "Delicate touch.", "动词", "高级动词"),
        ("deliver", "/dɪˈlɪvər/", "交付", "Deliver package.", "动词", "高级动词"),
        ("demand", "/dɪˈmænd/", "要求", "Demand excellence.", "动词", "高级动词"),
        ("demonstrate", "/ˈdemənstreɪt/", "演示", "Demonstrate skills.", "动词", "高级动词"),
        ("denounce", "/dɪˈnaʊns/", "谴责", "Denounce act.", "动词", "高级动词"),
        ("deny", "/dɪˈnaɪ/", "否认", "Deny accusation.", "动词", "高级动词"),
        ("depend", "/dɪˈpend/", "依靠", "Depend on yourself.", "动词", "常用动词"),
        ("deposit", "/dɪˈpɒzɪt/", "存款", "Deposit money.", "动词", "高级动词"),
        ("depress", "/dɪˈpres/", "使沮丧", "Don't depress me.", "动词", "高级动词"),
        ("deprive", "/dɪˈpraɪv/", "剥夺", "Deprive of rights.", "动词", "高级动词"),
        ("derive", "/dɪˈraɪv/", "获得", "Derive benefit.", "动词", "高级动词"),
        ("descend", "/dɪˈsend/", "下降", "Descend stairs.", "动词", "高级动词"),
        ("describe", "/dɪˈskraɪb/", "描述", "Describe scene.", "动词", "常用动词"),
        ("desert", "/dɪˈzɜːt/", "抛弃", "Don't desert me.", "动词", "高级动词"),
        ("deserve", "/dɪˈzɜːv/", "值得", "You deserve it.", "动词", "高级动词"),
        ("design", "/dɪˈzaɪn/", "设计", "Design logo.", "动词", "高级动词"),
        ("desire", "/dɪˈzaɪər/", "渴望", "Desire success.", "动词", "高级动词"),
        ("despair", "/dɪˈspeər/", "绝望", "Don't despair.", "动词", "高级动词"),
        ("destroy", "/dɪˈstrɔɪ/", "破坏", "Destroy evidence.", "动词", "高级动词"),
        ("detach", "/dɪˈtætʃ/", "分离", "Detach part.", "动词", "高级动词"),
        ("detail", "/diːˈteɪl/", "详述", "Detail plan.", "动词", "高级动词"),
        ("detain", "/dɪˈteɪn/", "拘留", "Detain suspect.", "动词", "高级动词"),
        ("detect", "/dɪˈtekt/", "检测", "Detect problem.", "动词", "高级动词"),
        ("deteriorate", "/dɪˈtɪəriəreɪt/", "恶化", "Deteriorate rapidly.", "动词", "高级动词"),
        ("determine", "/dɪˈtɜːrmɪn/", "确定", "Determine cause.", "动词", "高级动词"),
        ("develop", "/dɪˈveləp/", "发展", "Develop skills.", "动词", "高级动词"),
        ("deviate", "/ˈdiːvieɪt/", "偏离", "Don't deviate.", "动词", "高级动词"),
        ("devote", "/dɪˈvəʊt/", "奉献", "Devote your time.", "动词", "高级动词"),
        ("diagnose", "/ˈdaɪəɡnəʊz/", "诊断", "Diagnose illness.", "动词", "高级动词"),
        ("dictate", "/dɪkˈteɪt/", "口述", "Dictate letter.", "动词", "高级动词"),
        ("die", "/daɪ/", "死", "Don't die.", "动词", "常用动词"),
        ("differ", "/ˈdɪfər/", "不同", "Opinions differ.", "动词", "高级动词"),
        ("digest", "/daɪˈdʒest/", "消化", "Digest food.", "动词", "高级动词"),
        ("diminish", "/dɪˈmɪnɪʃ/", "减少", "Diminish risk.", "动词", "高级动词"),
        ("din", "/dɪn/", "喧闹", "Don't din.", "动词", "高级动词"),
        ("direct", "/dɪˈrekt/", "指导", "Direct traffic.", "动词", "常用动词"),
        ("disagree", "/ˌdɪsəˈɡriː/", "不同意", "I disagree.", "动词", "常用动词"),
        ("disappear", "/ˌdɪsəˈpɪər/", "消失", "Disappear quickly.", "动词", "高级动词"),
        ("disappoint", "/ˌdɪsəˈpɔɪnt/", "使失望", "Don't disappoint me.", "动词", "高级动词"),
        ("disapprove", "/ˌdɪsəˈpruːv/", "不赞成", "Disapprove of this.", "动词", "高级动词"),
        ("disarm", "/dɪsˈɑːrm/", "解除武装", "Disarm bomb.", "动词", "高级动词"),
        ("disarray", "/dɪsəˈreɪ/", "排列", "Disarray troops.", "动词", "高级动词"),
        ("discharge", "/dɪsˈtʃɑːrdʒ/", "释放", "Discharge patient.", "动词", "高级动词"),
        ("disconnect", "/dɪsˈkləʊz/", "断开连接", "Disconnect cable.", "动词", "常用动词"),
        ("discount", "/dɪsˈkaʊnt/", "打折", "Discount price.", "动词", "高级动词"),
        ("discourage", "/dɪsˈkʌrɪdʒ/", "使气馁", "Don't discourage.", "动词", "高级动词"),
        ("discover", "/dɪsˈkʌvər/", "发现", "Discover new things.", "动词", "高级动词"),
        ("discriminate", "/dɪsˈkrɪmɪneɪt/", "歧视", "Don't discriminate.", "动词", "高级动词"),
        ("discuss", "/dɪsˈkʌs/", "讨论", "Discuss plan.", "动词", "常用动词"),
        ("dislike", "/dɪsˈlaɪk/", "不喜欢", "I dislike waiting.", "动词", "常用动词"),
        ("dismiss", "/dɪsˈmɪs/", "解雇", "Dismiss employee.", "动词", "高级动词"),
        ("disorder", "/dɪsˈɔːdən/", "打乱", "Disorder room.", "动词", "高级动词"),
        ("display", "/dɪsˈpleɪ/", "展示", "Display art.", "动词", "高级动词"),
        ("dispose", "/dɪsˈpəʊz/", "处理", "Dispose of waste.", "动词", "高级动词"),
        ("dispute", "/dɪsˈpjuːt/", "争议", "Dispute claim.", "动词", "高级动词"),
        ("dissolve", "/dɪsˈzɒlv/", "溶解", "Dissolve sugar.", "动词", "高级动词"),
        ("distance", "/dɪsˈtæns/", "距离", "Keep your distance.", "动词", "高级动词"),
        ("distinguish", "/dɪsˈtɪŋɡwɪʃ/", "区分", "Distinguish between them.", "动词", "高级动词"),
        ("distort", "/dɪsˈtɔːrt/", "扭曲", "Distort facts.", "动词", "高级动词"),
        ("distract", "/dɪsˈtrækt/", "分心", "Don't distract me.", "动词", "高级动词"),
        ("distress", "/dɪsˈtres/", "使痛苦", "Distress enemy.", "动词", "高级动词"),
        ("distribute", "/dɪsˈtrɪbjuːt/", "分发", "Distribute flyers.", "动词", "高级动词"),
        ("disturb", "/dɪsˈtɜːrb/", "打扰", "Don't disturb.", "动词", "高级动词"),
        ("diverge", "/daɪˈvɜːrdʒ/", "分歧", "Opinions diverge.", "动词", "高级动词"),
        ("divide", "/dɪˈvaɪd/", "分割", "Divide work.", "动词", "常用动词"),
        ("divorce", "/dɪˈvɔːrs/", "离婚", "Divorce peacefully.", "动词", "高级动词"),
        ("do", "/duː/", "做", "Do your best.", "动词", "常用动词"),
        ("document", "/ˈdɒkjʊmənt/", "记录", "Document process.", "动词", "高级动词"),
        ("dampen", "/dəˈmeɪn/", "使减弱", "The rain dampened.", "动词", "高级动词"),
        ("dominate", "/ˈdɒmɪneɪt/", "支配", "Dominate market.", "动词", "高级动词"),
        ("donate", "/ˈdəʊneɪt/", "捐赠", "Donate to charity.", "动词", "高级动词"),
        ("doubt", "/daʊt/", "怀疑", "I doubt it.", "动词", "常用动词"),
        ("draft", "/dræft/", "起草", "Draft document.", "动词", "高级动词"),
        ("drag", "/dræɡ/", "拖拽", "Drag file.", "动词", "常用动词"),
        ("drain", "/dreɪn/", "排水", "Drain water.", "动词", "高级动词"),
        ("dramatize", "/ˈdræmətaɪz/", "戏剧化", "Don't dramatize.", "动词", "高级动词"),
        ("draw", "/drɔː/", "画", "Draw a picture.", "动词", "常用动词"),
        ("dream", "/driːm/", "做梦", "Dream big.", "动词", "常用动词"),
        ("dress", "/dres/", "穿衣", "Dress up.", "动词", "常用动词"),
        ("drift", "/drɪft/", "漂移", "Drift away.", "动词", "高级动词"),
        ("drill", "/drɪl/", "钻孔", "Drill hole.", "动词", "高级动词"),
        ("drink", "/drɪŋk/", "喝", "Drink water.", "动词", "常用动词"),
        ("drive", "/draɪv/", "驾驶", "Drive safely.", "动词", "常用动词"),
        ("drop", "/drɒp/", "掉落", "Drop ball.", "动词", "常用动词"),
        ("drown", "/draʊn/", "淹死", "Don't drown.", "动词", "高级动词"),
        ("dry", "/draɪ/", "弄干", "Dry your hair.", "动词", "常用动词"),
        ("dull", "/dʌl/", "使消沉", "The sun dulled.", "动词", "高级动词"),
        ("during", "/djʊərɪŋ/", "持续", "During day.", "动词", "高级动词"),
    ]
    
    # 更多形容词 (600+)
    more_adjectives = [
        ("abnormal", "/æbˈnɔːrml/", "异常的", "Abnormal behavior.", "形容词", "性质描述"),
        ("absolute", "/ˈæbsəluːt/", "绝对的", "Absolute power.", "形容词", "性质描述"),
        ("academic", "/ˌækəˈdemɪk/", "学术的", "Academic success.", "形容词", "性质描述"),
        ("acceptable", "/əkˈseptəbl/", "可接受的", "Acceptable quality.", "形容词", "性质描述"),
        ("accessible", "/əkˈsesəbl/", "可接近的", "Accessible location.", "形容词", "性质描述"),
        ("accurate", "/ˈækjərət/", "准确的", "Accurate data.", "形容词", "性质描述"),
        ("accustomed", "/əˈkʌstəmd/", "习惯的", "Accustomed to this.", "形容词", "状态描述"),
        ("active", "/ˈæktɪv/", "活跃的", "Be active.", "形容词", "状态描述"),
        ("actual", "/ˈæktʃuəl/", "实际的", "Actual cost.", "形容词", "性质描述"),
        ("adequate", "/ˈædɪkwət/", "足够的", "Adequate resources.", "形容词", "性质描述"),
        ("adjustable", "/əˈdʒʌstəbl/", "可调整的", "Adjustable settings.", "形容词", "性质描述"),
        ("administrative", "/ədˈmɪnɪstreɪtɪv/", "管理的", "Administrative work.", "形容词", "性质描述"),
        ("admirable", "/ˈædmərəbl/", "令人钦佩的", "Admirable effort.", "形容词", "性质描述"),
        ("adorable", "/əˈdɔːrəbl/", "可爱的", "Adorable baby.", "形容词", "外观描述"),
        ("adult", "/ˈædʌlt/", "成年的", "Adult education.", "形容词", "年龄描述"),
        ("advanced", "/ədˈvænst/", "先进的", "Advanced technology.", "形容词", "性质描述"),
        ("advantageous", "/ˌædvənˈteɪdʒəs/", "有利的", "Advantageous position.", "形容词", "性质描述"),
        ("adventurous", "/ədˈventʃərəs/", "爱冒险的", "Adventurous spirit.", "形容词", "性格描述"),
        ("adverse", "/ˈædvɜːs/", "不利的", "Adverse effects.", "形容词", "性质描述"),
        ("affordable", "/əˈfɔːdəbl/", "买得起的", "Affordable price.", "形容词", "性质描述"),
        ("afraid", "/əˈfreɪd/", "害怕的", "Don't be afraid.", "形容词", "情绪描述"),
        ("afternoon", "/ˌæftərˈnuːn/", "下午的", "Afternoon tea.", "形容词", "时间描述"),
        ("aggressive", "/əˈɡresɪv/", "好斗的", "Aggressive behavior.", "形容词", "性格描述"),
        ("agreeable", "/əˈɡriːəbl/", "宜人的", "Agreeable person.", "形容词", "性格描述"),
        ("agricultural", "/ˌæɡrɪˈkʌltʃərəl/", "农业的", "Agricultural land.", "形容词", "性质描述"),
        ("ahead", "/əˈhed/", "在前的", "Go ahead.", "形容词", "位置描述"),
        ("aid", "/eɪd/", "辅助的", "Aid workers.", "形容词", "性质描述"),
        ("aimless", "/ˈeɪmləs/", "无目的的", "Aimless wandering.", "形容词", "性质描述"),
        ("alike", "/əˈlaɪk/", "相似的", "We are alike.", "形容词", "比较描述"),
        ("alive", "/əˈlaɪv/", "活着的", "Stay alive.", "形容词", "状态描述"),
        ("all", "/ɔːl/", "所有的", "All rights reserved.", "形容词", "数量描述"),
        ("alleged", "/əˈledʒd/", "被指控的", "Alleged crime.", "形容词", "性质描述"),
        ("allergic", "/əˈlɜːrdʒɪk/", "过敏的", "Allergic to cats.", "形容词", "健康描述"),
        ("allowable", "/əˈlaʊəbl/", "可允许的", "Allowable expense.", "形容词", "性质描述"),
        ("almost", "/ˈɔːlməʊst/", "几乎的", "Almost done.", "形容词", "程度描述"),
        ("alone", "/əˈləʊn/", "独自的", "Live alone.", "形容词", "状态描述"),
        ("aloud", "/əˈlaʊd/", "大声的", "Read aloud.", "形容词", "声音描述"),
        ("alphabetical", "/ˌælfəˈbetɪkl/", "字母的", "Alphabetical order.", "形容词", "性质描述"),
        ("alterable", "/ˈɔːltərəbl/", "可改变的", "Alterable plans.", "形容词", "性质描述"),
        ("alternative", "/ɔːlˈtɜːnətɪv/", "替代的", "Alternative energy.", "形容词", "性质描述"),
        ("amazed", "/əˈmeɪzd/", "惊讶的", "I am amazed.", "形容词", "情绪描述"),
        ("amazing", "/əˈmeɪzɪŋ/", "令人惊叹的", "Amazing view.", "形容词", "性质描述"),
        ("ambitious", "/æmˈbɪʃəs/", "有野心的", "Ambitious goals.", "形容词", "性格描述"),
        ("ample", "/ˈæmpl/", "充足的", "Ample space.", "形容词", "数量描述"),
        ("amused", "/əˈmjuːzd/", "被逗乐的", "Amused audience.", "形容词", "情绪描述"),
        ("amusing", "/əˈmjuːzɪŋ/", "逗人的", "Amusing story.", "形容词", "性质描述"),
        ("analytical", "/ˌænəˈlɪtɪkl/", "分析的", "Analytical mind.", "形容词", "能力描述"),
        ("ancient", "/ˈeɪnʃənt/", "古老的", "Ancient history.", "形容词", "时间描述"),
        ("angry", "/ˈæŋɡri/", "生气的", "Don't be angry.", "形容词", "情绪描述"),
        ("animated", "/ˈænɪmeɪtɪd/", "生动的", "Animated discussion.", "形容词", "性质描述"),
        ("annual", "/ˈænjuəl/", "每年的", "Annual report.", "形容词", "时间描述"),
        ("another", "/əˈnʌðər/", "另一个的", "Another day.", "形容词", "数量描述"),
        ("anxious", "/ˈæŋkʃəs/", "焦虑的", "Anxious waiting.", "形容词", "情绪描述"),
        ("any", "/ˈeni/", "任何的", "Any questions?", "形容词", "数量描述"),
        ("apart", "/əˈpɑːt/", "分离的", "Fall apart.", "形容词", "状态描述"),
        ("apparent", "/əˈpærənt/", "明显的", "Apparent reason.", "形容词", "性质描述"),
        ("appealing", "/əˈpiːlɪŋ/", "有吸引力的", "Appealing design.", "形容词", "性质描述"),
        ("appetite", "/ˈæpɪtaɪt/", "食欲的", "Good appetite.", "形容词", "状态描述"),
        ("applicable", "/ˈæplɪkəbl/", "适用的", "Applicable rules.", "形容词", "性质描述"),
        ("appreciative", "/əˈpriːʃieɪtɪv/", "感激的", "Appreciative audience.", "形容词", "性格描述"),
        ("appropriate", "/əˈprəʊpriət/", "适当的", "Appropriate behavior.", "形容词", "性质描述"),
        ("approval", "/əˈpruːvl/", "赞成的", "Approval needed.", "形容词", "状态描述"),
        ("approximate", "/əˈprɒksɪmət/", "大约的", "Approximate time.", "形容词", "程度描述"),
        ("arbitrary", "/ˈɑːrbɪtreri/", "任意的", "Arbitrary decision.", "形容词", "性质描述"),
        ("architectural", "/ˌɑːrkɪˈtektʃərəl/", "建筑的", "Architectural design.", "形容词", "性质描述"),
        ("arctic", "/ˈɑːktɪk/", "北极的", "Arctic climate.", "形容词", "地理描述"),
        ("ardent", "/ˈɑːdənt/", "热切的", "Ardent supporter.", "形容词", "性格描述"),
        ("arguable", "/ˈɑːɡjuəbl/", "可争辩的", "Arguable point.", "形容词", "性质描述"),
        ("arithmetic", "/ˌærɪθˈmetɪk/", "算术的", "Arithmetic problems.", "形容词", "学科描述"),
        ("aromatic", "/ˌærəˈmætɪk/", "芳香的", "Aromatic flowers.", "形容词", "感官描述"),
        ("arrogant", "/ˈærəɡənt/", "傲慢的", "Arrogant attitude.", "形容词", "性格描述"),
        ("artistic", "/ɑːˈtɪstɪk/", "艺术的", "Artistic talent.", "形容词", "能力描述"),
        ("ashamed", "/əˈʃeɪmd/", "羞愧的", "Ashamed of nothing.", "形容词", "情绪描述"),
        ("asleep", "/əˈsliːp/", "睡着的", "Fall asleep.", "形容词", "状态描述"),
        ("asocial", "/ˌeɪsəʊʃəl/", "不合群的", "Asocial behavior.", "形容词", "性格描述"),
        ("aspect", "/ˈæspekt/", "方面的", "Every aspect.", "形容词", "性质描述"),
        ("aspiring", "/əˈspaɪərɪŋ/", "有抱负的", "Aspiring artist.", "形容词", "性格描述"),
        ("assertive", "/əˈsɜːtɪv/", "自信的", "Assertive leader.", "形容词", "性格描述"),
        ("assigned", "/əˈsaɪnd/", "被分配的", "Assigned task.", "形容词", "状态描述"),
        ("assistive", "/əˈsɪstɪv/", "辅助的", "Assistive technology.", "形容词", "性质描述"),
        ("associate", "/əˈsəʊʃieɪt/", "副的", "Associate degree.", "形容词", "性质描述"),
        ("assorted", "/əˈsɔːtɪd/", "各种各样的", "Assorted candies.", "形容词", "性质描述"),
        ("assumed", "/əˈsjuːmd/", "假定的", "Assumed identity.", "形容词", "状态描述"),
        ("astonished", "/əˈstɒnɪʃt/", "惊讶的", "Astonished face.", "形容词", "情绪描述"),
        ("athletic", "/æθˈletɪk/", "运动的", "Athletic build.", "形容词", "身体描述"),
        ("attached", "/əˈtætʃt/", "依恋的", "Attached files.", "形容词", "状态描述"),
        ("attentive", "/əˈtentɪv/", "专注的", "Attentive student.", "形容词", "性格描述"),
        ("attractive", "/əˈtræktɪv/", "有吸引力的", "Attractive offer.", "形容词", "外观描述"),
        ("attributive", "/əˈtrɪbjətɪv/", "归属的", "Attributive clause.", "形容词", "语法描述"),
        ("audible", "/ˈɔːdəbl/", "可听见的", "Audible signal.", "形容词", "感官描述"),
        ("audience", "/ˈɔːdiəns/", "观众的", "Audience applause.", "形容词", "性质描述"),
        ("authentic", "/ɔːˈθentɪk/", "真实的", "Authentic cuisine.", "形容词", "性质描述"),
        ("authoritative", "/ɔːˈθɒrətətɪv/", "权威的", "Authoritative source.", "形容词", "性质描述"),
        ("automatic", "/ˌɔːtəˈmætɪk/", "自动的", "Automatic door.", "形容词", "性质描述"),
        ("available", "/əˈveɪləbl/", "可获得的", "Available now.", "形容词", "性质描述"),
        ("average", "/ˈævərɪdʒ/", "平均的", "Average score.", "形容词", "数量描述"),
        ("awesome", "/ˈɔːsəm/", "极好的", "Awesome job!", "形容词", "性质描述"),
        ("awful", "/ˈɔːfl/", "糟糕的", "Awful weather.", "形容词", "性质描述"),
        ("awkward", "/ˈɔːkwəd/", "尴尬的", "Awkward moment.", "形容词", "情绪描述"),
        ("back", "/bæk/", "后面的", "Back door.", "形容词", "位置描述"),
        ("bacterial", "/bækˈtɪəriəl/", "细菌的", "Bacterial infection.", "形容词", "生物描述"),
        ("bad", "/bæd/", "坏的", "Bad idea.", "形容词", "性质描述"),
        ("balanced", "/ˈbælənst/", "平衡的", "Balanced diet.", "形容词", "状态描述"),
        ("bald", "/bɔːld/", "秃头的", "Bald eagle.", "形容词", "外观描述"),
        ("bare", "/beər/", "赤裸的", "Bare feet.", "形容词", "状态描述"),
        ("basic", "/ˈbeɪsɪk/", "基本的", "Basic needs.", "形容词", "性质描述"),
        ("beautiful", "/ˈbjuːtɪfl/", "美丽的", "Beautiful day.", "形容词", "外观描述"),
        ("beneficial", "/ˌbenɪˈfɪʃl/", "有益的", "Beneficial effects.", "形容词", "性质描述"),
        ("best", "/best/", "最好的", "Best wishes.", "形容词", "比较描述"),
        ("better", "/ˈbetər/", "更好的", "Better late.", "形容词", "比较描述"),
        ("big", "/bɪɡ/", "大的", "Big house.", "形容词", "大小描述"),
        ("bitter", "/ˈbɪtər/", "苦的", "Bitter taste.", "形容词", "味道描述"),
        ("bizarre", "/bɪˈzɑːr/", "奇异的", "Bizarre behavior.", "形容词", "性质描述"),
        ("black", "/blæk/", "黑色的", "Black coffee.", "形容词", "颜色描述"),
        ("blank", "/blæŋk/", "空白的", "Blank page.", "形容词", "状态描述"),
        ("blind", "/blaɪnd/", "盲目的", "Blind faith.", "形容词", "状态描述"),
        ("blond", "/blɒnd/", "金发的", "Blond hair.", "形容词", "外观描述"),
        ("blue", "/bluː/", "蓝色的", "Blue sky.", "形容词", "颜色描述"),
        ("blunt", "/blʌnt/", "钝的", "Blunt knife.", "形容词", "性质描述"),
        ("boiling", "/ˈbɔɪlɪŋ/", "沸腾的", "Boiling water.", "形容词", "状态描述"),
        ("bold", "/bəʊld/", "大胆的", "Bold decision.", "形容词", "性格描述"),
        ("bored", "/bɔːd/", "无聊的", "Bored to death.", "形容词", "情绪描述"),
        ("boring", "/ˈbɔːrɪŋ/", "无聊的", "Boring movie.", "形容词", "性质描述"),
        ("bottom", "/ˈbɒtəm/", "底部的", "Bottom line.", "形容词", "位置描述"),
        ("bound", "/baʊnd/", "必然的", "Bound to happen.", "形容词", "状态描述"),
        ("brave", "/breɪv/", "勇敢的", "Be brave.", "形容词", "性格描述"),
        ("bread", "/bred/", "面包的", "Bread crumbs.", "形容词", "性质描述"),
        ("breakable", "/ˈbreɪkəbl/", "易碎的", "Breakable glass.", "形容词", "性质描述"),
        ("bright", "/braɪt/", "明亮的", "Bright future.", "形容词", "外观描述"),
        ("brilliant", "/ˈbrɪliənt/", "杰出的", "Brilliant idea.", "形容词", "性质描述"),
        ("broad", "/brɔːd/", "宽的", "Broad shoulders.", "形容词", "形状描述"),
        ("broken", "/ˈbrəʊkən/", "破碎的", "Broken heart.", "形容词", "状态描述"),
        ("brown", "/braʊn/", "棕色的", "Brown eyes.", "形容词", "颜色描述"),
        ("busy", "/ˈbɪzi/", "忙碌的", "Busy day.", "形容词", "状态描述"),
        ("calculated", "/ˈkælkjʊleɪtɪd/", "计算的", "Calculated risk.", "形容词", "状态描述"),
        ("calm", "/kɑːm/", "冷静的", "Stay calm.", "形容词", "情绪描述"),
        ("capable", "/ˈkeɪpəbl/", "有能力的", "Capable leader.", "形容词", "能力描述"),
        ("capital", "/ˈkæpɪtl/", "资本的", "Capital city.", "形容词", "性质描述"),
        ("careful", "/ˈkeəfl/", "小心的", "Be careful.", "形容词", "性格描述"),
        ("careless", "/ˈkeələs/", "粗心的", "Careless mistake.", "形容词", "性格描述"),
        ("casual", "/ˈkæʒuəl/", "随意的", "Casual dress.", "形容词", "风格描述"),
        ("categorical", "/ˌkætəˈɡɒrɪkl/", "绝对的", "Categorical denial.", "形容词", "性质描述"),
        ("cautious", "/ˈkɔːʃəs/", "谨慎的", "Cautious approach.", "形容词", "性格描述"),
        ("central", "/ˈsentrəl/", "中心的", "Central location.", "形容词", "位置描述"),
        ("certain", "/ˈsɜːtn/", "确定的", "Certain success.", "形容词", "程度描述"),
        ("challenging", "/ˈtʃælɪndʒɪŋ/", "具有挑战性的", "Challenging task.", "形容词", "性质描述"),
        ("changeable", "/ˈtʃeɪndʒəbl/", "可改变的", "Changeable plans.", "形容词", "性质描述"),
        ("characteristic", "/ˌkærəktəˈrɪstɪk/", "特征的", "Characteristic feature.", "形容词", "性质描述"),
        ("charitable", "/ˈtʃærətəbl/", "慈善的", "Charitable act.", "形容词", "性格描述"),
        ("charming", "/ˈtʃɑːrmɪŋ/", "迷人的", "Charming smile.", "形容词", "外观描述"),
        ("cheap", "/tʃiːp/", "便宜的", "Cheap goods.", "形容词", "价格描述"),
        ("cheerful", "/ˈtʃɪəfl/", "快乐的", "Cheerful mood.", "形容词", "情绪描述"),
        ("chemical", "/ˈkemɪkl/", "化学的", "Chemical reaction.", "形容词", "学科描述"),
        ("chief", "/tʃiːf/", "主要的", "Chief complaint.", "形容词", "重要性描述"),
        ("childish", "/ˈtʃaɪldɪʃ/", "孩子气的", "Childish behavior.", "形容词", "性格描述"),
        ("chilly", "/ˈtʃɪli/", "寒冷的", "Chilly weather.", "形容词", "温度描述"),
        ("chronic", "/ˈkrɒnɪk/", "慢性的", "Chronic pain.", "形容词", "性质描述"),
        ("circular", "/ˈsɜːkjələr/", "圆形的", "Circular table.", "形容词", "形状描述"),
        ("civil", "/ˈsɪvl/", "公民的", "Civil rights.", "形容词", "社会描述"),
        ("classic", "/ˈklæsɪk/", "经典的", "Classic novel.", "形容词", "性质描述"),
        ("clean", "/kliːn/", "干净的", "Clean room.", "形容词", "状态描述"),
        ("clear", "/klɪər/", "清晰的", "Clear water.", "形容词", "外观描述"),
        ("clever", "/ˈklevər/", "聪明的", "Clever answer.", "形容词", "智力描述"),
        ("clinical", "/ˈklɪnɪkl/", "临床的", "Clinical trial.", "形容词", "医学描述"),
        ("close", "/kləʊs/", "亲密的", "Close friend.", "形容词", "关系描述"),
        ("cloudy", "/ˈklaʊdi/", "多云的", "Cloudy day.", "形容词", "天气描述"),
        ("clumsy", "/ˈklʌmzi/", "笨拙的", "Clumsy movements.", "形容词", "能力描述"),
        ("coarse", "/kɔːs/", "粗糙的", "Coarse sand.", "形容词", "触感描述"),
        ("cold", "/kəʊld/", "冷的", "Cold water.", "形容词", "温度描述"),
        ("collective", "/kəˈlektɪv/", "集体的", "Collective effort.", "形容词", "性质描述"),
        ("colonial", "/kəˈləʊniəl/", "殖民的", "Colonial era.", "形容词", "历史描述"),
        ("colorful", "/ˈkʌləfl/", "多彩的", "Colorful garden.", "形容词", "外观描述"),
        ("comfortable", "/ˈkʌmfətəbl/", "舒适的", "Comfortable chair.", "形容词", "状态描述"),
        ("comic", "/ˈkɒmɪk/", "喜剧的", "Comic relief.", "形容词", "艺术描述"),
        ("common", "/ˈkɒmən/", "共同的", "Common sense.", "形容词", "性质描述"),
        ("communal", "/kəˈmjuːnl/", "公共的", "Communal space.", "形容词", "社会描述"),
        ("compact", "/kəmˈpækt/", "紧凑的", "Compact car.", "形容词", "形状描述"),
        ("comparable", "/ˈkɒmpərəbl/", "可比较的", "Comparable results.", "形容词", "性质描述"),
        ("compatible", "/kəmˈpætəbl/", "兼容的", "Compatible software.", "形容词", "性质描述"),
        ("competitive", "/kəmˈpetətɪv/", "竞争的", "Competitive market.", "形容词", "性质描述"),
        ("complete", "/kəmˈpliːt/", "完整的", "Complete set.", "形容词", "状态描述"),
        ("complex", "/kəmˈpleks/", "复杂的", "Complex problem.", "形容词", "性质描述"),
        ("complicated", "/ˈkɒmplɪkeɪtɪd/", "复杂的", "Complicated issue.", "形容词", "性质描述"),
        ("comprehensive", "/ˌkɒmprɪˈhensɪv/", "综合的", "Comprehensive plan.", "形容词", "性质描述"),
        ("compulsory", "/kəmˈpʌlsəri/", "强制的", "Compulsory education.", "形容词", "性质描述"),
        ("concrete", "/ˈkɒŋkriːt/", "具体的", "Concrete evidence.", "形容词", "性质描述"),
        ("condemned", "/kənˈdemd/", "被谴责的", "Condemned action.", "形容词", "状态描述"),
        ("conditional", "/kənˈdɪʃənl/", "有条件的", "Conditional offer.", "形容词", "性质描述"),
        ("confident", "/ˈkɒnfɪdənt/", "自信的", "Confident smile.", "形容词", "情绪描述"),
        ("confidential", "/ˌkɒnfɪˈdenʃl/", "机密的", "Confidential data.", "形容词", "性质描述"),
        ("confused", "/kənˈfjuːzd/", "困惑的", "Confused mind.", "形容词", "情绪描述"),
        ("conscious", "/ˈkɒnʃəs/", "有意识的", "Conscious decision.", "形容词", "状态描述"),
        ("considerable", "/kənˈsɪdərəbl/", "相当大的", "Considerable effort.", "形容词", "程度描述"),
        ("consistent", "/kənˈsɪstənt/", "一致的", "Consistent results.", "形容词", "性质描述"),
        ("constant", "/ˈ