#!/usr/bin/env python3
import sqlite3

def expand_vocabulary_to_5000():
    conn = sqlite3.connect('../words.db')
    cursor = conn.cursor()
    
    new_words = [
        # 高级形容词 (100+)
        ("abundant", "/əˈbʌndənt/", "丰富的", "The forest has abundant wildlife.", "形容词"),
        ("adequate", "/ˈædɪkwət/", "足够的", "The supply is adequate.", "形容词"),
        ("ambiguous", "/æmˈbɪɡjuəs/", "模棱两可的", "The message was ambiguous.", "形容词"),
        ("authentic", "/ɔːˈθentɪk/", "真实的", "This is an authentic document.", "形容词"),
        ("benevolent", "/bəˈnevələnt/", "仁慈的", "A benevolent leader.", "形容词"),
        ("candid", "/ˈkændɪd/", "坦率的", "Give me a candid opinion.", "形容词"),
        ("coherent", "/kəʊˈhɪərənt/", "连贯的", "A coherent argument.", "形容词"),
        ("compelling", "/kəmˈpelɪŋ/", "引人入胜的", "A compelling story.", "形容词"),
        ("conspicuous", "/kənˈspɪkjuəs/", "显著的", "A conspicuous absence.", "形容词"),
        ("controversial", "/ˌkɒntrəˈvɜːʃl/", "有争议的", "A controversial decision.", "形容词"),
        ("diligent", "/ˈdɪlɪdʒənt/", "勤奋的", "A diligent student.", "形容词"),
        ("eccentric", "/ɪkˈsentrɪk/", "古怪的", "An eccentric artist.", "形容词"),
        ("eloquent", "/ˈeləkwənt/", "雄辩的", "An eloquent speaker.", "形容词"),
        ("eminent", "/ˈemɪnənt/", "杰出的", "An eminent scientist.", "形容词"),
        ("exquisite", "/ɪkˈskwɪzɪt/", "精致的", "Exquisite craftsmanship.", "形容词"),
        ("feasible", "/ˈfiːzəbl/", "可行的", "A feasible plan.", "形容词"),
        ("genuine", "/ˈdʒenjuɪn/", "真正的", "Genuine leather.", "形容词"),
        ("hazardous", "/ˈhæzədəs/", "危险的", "Hazardous materials.", "形容词"),
        ("impeccable", "/ɪmˈpekəbl/", "无懈可击的", "Impeccable manners.", "形容词"),
        ("ingenious", "/ɪnˈdʒiːniəs/", "独创的", "An ingenious solution.", "形容词"),
        ("intricate", "/ˈɪntrɪkət/", "复杂的", "Intricate patterns.", "形容词"),
        ("meticulous", "/məˈtɪkjələs/", "一丝不苟的", "Meticulous planning.", "形容词"),
        ("notorious", "/nəʊˈtɔːriəs/", "臭名昭著的", "A notorious criminal.", "形容词"),
        ("obscure", "/əbˈskjʊə(r)/", "晦涩的", "An obscure reference.", "形容词"),
        ("optimal", "/ˈɒptɪməl/", "最佳的", "Optimal conditions.", "形容词"),
        ("plausible", "/ˈplɔːzəbl/", "看似合理的", "A plausible explanation.", "形容词"),
        ("pragmatic", "/præɡˈmætɪk/", "务实的", "A pragmatic approach.", "形容词"),
        ("profound", "/prəˈfaʊnd/", "深刻的", "Profound wisdom.", "形容词"),
        ("prudent", "/ˈpruːdnt/", "审慎的", "A prudent decision.", "形容词"),
        ("radiant", "/ˈreɪdiənt/", "光芒四射的", "A radiant smile.", "形容词"),
        ("relentless", "/rɪˈlentləs/", "不懈的", "Relentless pursuit.", "形容词"),
        ("resilient", "/rɪˈzɪliənt/", "有韧性的", "Resilient people.", "形容词"),
        ("skeptical", "/ˈskeptɪkl/", "怀疑的", "Skeptical about the claims.", "形容词"),
        ("spontaneous", "/spɒnˈteɪniəs/", "自发的", "A spontaneous decision.", "形容词"),
        ("subtle", "/ˈsʌtl/", "微妙的", "A subtle change.", "形容词"),
        ("superficial", "/ˌsuːpəˈfɪʃl/", "表面的", "Superficial similarities.", "形容词"),
        ("tangible", "/ˈtændʒəbl/", "有形的", "Tangible results.", "形容词"),
        ("tedious", "/ˈtiːdiəs/", "单调乏味的", "Tedious work.", "形容词"),
        ("versatile", "/ˈvɜːsətaɪl/", "多才多艺的", "A versatile actor.", "形容词"),
        ("vibrant", "/ˈvaɪbrənt/", "充满活力的", "Vibrant colors.", "形容词"),
        ("vigorous", "/ˈvɪɡərəs/", "有力的", "Vigorous exercise.", "形容词"),
        ("vulnerable", "/ˈvʌlnərəbl/", "脆弱的", "Vulnerable populations.", "形容词"),
        ("witty", "/ˈwɪti/", "机智的", "A witty remark.", "形容词"),
        ("zealous", "/ˈzeləs/", "热情的", "A zealous supporter.", "形容词"),
        
        # 学术/教育词汇 (50+)
        ("academic", "/ˌækəˈdemɪk/", "学术的", "Academic research.", "名词"),
        ("curriculum", "/kəˈrɪkjələm/", "课程", "School curriculum.", "名词"),
        ("dissertation", "/ˌdɪsəˈteɪʃn/", "学位论文", "Writing a dissertation.", "名词"),
        ("hypothesis", "/haɪˈpɒθəsɪs/", "假设", "Test the hypothesis.", "名词"),
        ("methodology", "/ˌmeθəˈdɒlədʒi/", "方法论", "Research methodology.", "名词"),
        ("pedagogy", "/ˈpedəɡɒdʒi/", "教学法", "Modern pedagogy.", "名词"),
        ("scholarship", "/ˈskɒləʃɪp/", "奖学金", "Apply for scholarship.", "名词"),
        ("thesis", "/ˈθiːsɪs/", "论文", "Defend your thesis.", "名词"),
        ("tuition", "/tjuˈɪʃn/", "学费", "Pay tuition fees.", "名词"),
        ("undergraduate", "/ˌʌndəˈɡrædʒuət/", "本科生", "An undergraduate student.", "名词"),
        ("graduate", "/ˈɡrædʒuət/", "研究生", "Graduate studies.", "名词"),
        ("professor", "/prəˈfesə(r)/", "教授", "The professor lectured.", "名词"),
        ("lecture", "/ˈlektʃə(r)/", "讲座", "Attend a lecture.", "名词"),
        ("seminar", "/ˈsemɪnɑː(r)/", "研讨会", "Join the seminar.", "名词"),
        ("assignment", "/əˈsaɪnmənt/", "作业", "Complete the assignment.", "名词"),
        ("examination", "/ɪɡˌzæmɪˈneɪʃn/", "考试", "Pass the examination.", "名词"),
        ("qualification", "/ˌkwɒlɪfɪˈkeɪʃn/", "资格", "Professional qualification.", "名词"),
        ("certification", "/ˌsɜːtɪfɪˈkeɪʃn/", "认证", "Get certification.", "名词"),
        ("diploma", "/dɪˈpləʊmə/", "文凭", "Earn a diploma.", "名词"),
        ("degree", "/dɪˈɡriː/", "学位", "Bachelor's degree.", "名词"),
        ("faculty", "/ˈfæklti/", "全体教员", "Faculty meeting.", "名词"),
        ("alumni", "/əˈlʌmnaɪ/", "校友", "Alumni association.", "名词"),
        ("campus", "/ˈkæmpəs/", "校园", "Campus life.", "名词"),
        ("library", "/ˈlaɪbrəri/", "图书馆", "Study in the library.", "名词"),
        ("laboratory", "/ləˈbɒrətri/", "实验室", "Chemistry laboratory.", "名词"),
        ("research", "/rɪˈsɜːtʃ/", "研究", "Conduct research.", "名词"),
        ("publication", "/ˌpʌblɪˈkeɪʃn/", "出版物", "Scientific publication.", "名词"),
        ("citation", "/saɪˈteɪʃn/", "引用", "Add citation.", "名词"),
        ("bibliography", "/ˌbɪbliˈɒɡrəfi/", "参考文献", "Check bibliography.", "名词"),
        ("abstract", "/ˈæbstrækt/", "摘要", "Read the abstract.", "名词"),
        ("appendix", "/əˈpendɪks/", "附录", "See the appendix.", "名词"),
        ("index", "/ˈɪndeks/", "索引", "Check the index.", "名词"),
        ("glossary", "/ˈɡlɒsəri/", "术语表", "Consult the glossary.", "名词"),
        ("encyclopedia", "/ɪnˌsaɪkləˈpiːdiə/", "百科全书", "Use encyclopedia.", "名词"),
        ("journal", "/ˈdʒɜːnl/", "期刊", "Academic journal.", "名词"),
        ("periodical", "/ˌpɪəriˈɒdɪkl/", "期刊", "Read periodicals.", "名词"),
        ("subscription", "/səbˈskrɪpʃn/", "订阅", "Magazine subscription.", "名词"),
        ("institution", "/ˌɪnstɪˈtjuːʃn/", "机构", "Educational institution.", "名词"),
        ("university", "/ˌjuːnɪˈvɜːsəti/", "大学", "Top university.", "名词"),
        ("college", "/ˈkɒlɪdʒ/", "学院", "Business college.", "名词"),
        ("department", "/dɪˈpɑːtmənt/", "系", "Mathematics department.", "名词"),
        ("major", "/ˈmeɪdʒə(r)/", "专业", "Choose your major.", "名词"),
        ("minor", "/ˈmaɪnə(r)/", "辅修专业", "Minor in history.", "名词"),
        
        # 商业/职场词汇 (80+)
        ("acquisition", "/ˌækwɪˈzɪʃn/", "收购", "Company acquisition.", "名词"),
        ("audit", "/ˈɔːdɪt/", "审计", "Financial audit.", "名词"),
        ("bankruptcy", "/ˈbæŋkrʌptsi/", "破产", "File for bankruptcy.", "名词"),
        ("benchmark", "/ˈbentʃmɑːk/", "基准", "Performance benchmark.", "名词"),
        ("budget", "/ˈbʌdʒɪt/", "预算", "Annual budget.", "名词"),
        ("capital", "/ˈkæpɪtl/", "资本", "Invest capital.", "名词"),
        ("collaboration", "/kəˌlæbəˈreɪʃn/", "合作", "Team collaboration.", "名词"),
        ("competition", "/ˌkɒmpəˈtɪʃn/", "竞争", "Market competition.", "名词"),
        ("compliance", "/kəmˈplaɪəns/", "合规", "Regulatory compliance.", "名词"),
        ("consultancy", "/kənˈsʌltənsi/", "咨询", "Management consultancy.", "名词"),
        ("contract", "/ˈkɒntrækt/", "合同", "Sign the contract.", "名词"),
        ("corporate", "/ˈkɔːpərət/", "公司的", "Corporate strategy.", "形容词"),
        ("delegation", "/ˌdelɪˈɡeɪʃn/", "授权", "Task delegation.", "名词"),
        ("dividend", "/ˈdɪvɪdend/", "股息", "Pay dividends.", "名词"),
        ("economics", "/ˌiːkəˈnɒmɪks/", "经济学", "Study economics.", "名词"),
        ("enterprise", "/ˈentəpraɪz/", "企业", "Large enterprise.", "名词"),
        ("entrepreneur", "/ˌɒntrəprəˈnɜː(r)/", "企业家", "Successful entrepreneur.", "名词"),
        ("equity", "/ˈekwəti/", "股权", "Home equity.", "名词"),
        ("expenditure", "/ɪkˈspendɪtʃə(r)/", "支出", "Public expenditure.", "名词"),
        ("franchise", "/ˈfræntʃaɪz/", "特许经营", "Buy a franchise.", "名词"),
        ("governance", "/ˈɡʌvənəns/", "治理", "Corporate governance.", "名词"),
        ("incentive", "/ɪnˈsentɪv/", "激励", "Financial incentive.", "名词"),
        ("infrastructure", "/ˈɪnfrəstrʌktʃə(r)/", "基础设施", "Build infrastructure.", "名词"),
        ("innovation", "/ˌɪnəˈveɪʃn/", "创新", "Drive innovation.", "名词"),
        ("investment", "/ɪnˈvestmənt/", "投资", "Make an investment.", "名词"),
        ("liability", "/ˌlaɪəˈbɪləti/", "责任", "Legal liability.", "名词"),
        ("logistics", "/ləˈdʒɪstɪks/", "物流", "Supply chain logistics.", "名词"),
        ("management", "/ˈmænɪdʒmənt/", "管理", "Senior management.", "名词"),
        ("merger", "/ˈmɜːdʒə(r)/", "合并", "Company merger.", "名词"),
        ("negotiation", "/nɪˌɡəʊʃiˈeɪʃn/", "谈判", "Price negotiation.", "名词"),
        ("networking", "/ˈnetwɜːkɪŋ/", "人脉建立", "Business networking.", "名词"),
        ("operations", "/ˌɒpəˈreɪʃnz/", "运营", "Daily operations.", "名词"),
        ("partnership", "/ˈpɑːtnəʃɪp/", "合伙关系", "Form a partnership.", "名词"),
        ("portfolio", "/pɔːtˈfəʊliəʊ/", "投资组合", "Diversified portfolio.", "名词"),
        ("procurement", "/prəˈkjʊəmənt/", "采购", "Government procurement.", "名词"),
        ("profitability", "/ˌprɒfɪtəˈbɪləti/", "盈利能力", "Improve profitability.", "名词"),
        ("promotion", "/prəˈməʊʃn/", "晋升", "Job promotion.", "名词"),
        ("recruitment", "/rɪˈkruːtmənt/", "招聘", "Staff recruitment.", "名词"),
        ("revenue", "/ˈrevənjuː/", "收入", "Annual revenue.", "名词"),
        ("stakeholder", "/ˈsteɪkhəʊldə(r)/", "利益相关者", "Key stakeholder.", "名词"),
        ("strategy", "/ˈstrætədʒi/", "战略", "Business strategy.", "名词"),
        ("subsidiary", "/səbˈsɪdiəri/", "子公司", "Foreign subsidiary.", "名词"),
        ("tender", "/ˈtendə(r)/", "投标", "Submit a tender.", "名词"),
        ("turnover", "/ˈtɜːnəʊvə(r)/", "营业额", "High turnover.", "名词"),
        ("valuation", "/ˌvæljuˈeɪʃn/", "估值", "Company valuation.", "名词"),
        ("venture", "/ˈventʃə(r)/", "风险投资", "Joint venture.", "名词"),
        ("workforce", "/ˈwɜːkfɔːs/", "劳动力", "Skilled workforce.", "名词"),
        ("yield", "/jiːld/", "收益率", "High yield.", "名词"),
        ("agenda", "/əˈdʒendə/", "议程", "Meeting agenda.", "名词"),
        ("appraisal", "/əˈpreɪzl/", "评估", "Performance appraisal.", "名词"),
        ("brainstorm", "/ˈbreɪnstɔːm/", "头脑风暴", "Brainstorm ideas.", "动词"),
        ("deadline", "/ˈdedlaɪn/", "截止日期", "Meet the deadline.", "名词"),
        ("delegation", "/ˌdelɪˈɡeɪʃn/", "代表团", "Send a delegation.", "名词"),
        ("executive", "/ɪɡˈzekjətɪv/", "高管", "Senior executive.", "名词"),
        ("headquarters", "/ˌhedˈkwɔːtəz/", "总部", "Company headquarters.", "名词"),
        ("interview", "/ˈɪntəvjuː/", "面试", "Job interview.", "名词"),
        ("leadership", "/ˈliːdəʃɪp/", "领导力", "Strong leadership.", "名词"),
        ("marketing", "/ˈmɑːkɪtɪŋ/", "市场营销", "Digital marketing.", "名词"),
        ("meeting", "/ˈmiːtɪŋ/", "会议", "Attend a meeting.", "名词"),
        ("presentation", "/ˌpreznˈteɪʃn/", "演示", "Give a presentation.", "名词"),
        ("proposal", "/prəˈpəʊzl/", "提案", "Submit a proposal.", "名词"),
        ("recruitment", "/rɪˈkruːtmənt/", "招聘", "Recruitment process.", "名词"),
        ("resignation", "/ˌrezɪɡˈneɪʃn/", "辞职", "Hand in resignation.", "名词"),
        ("retirement", "/rɪˈtaɪəmənt/", "退休", "Plan for retirement.", "名词"),
        ("salary", "/ˈsæləri/", "薪水", "Annual salary.", "名词"),
        ("supervisor", "/ˈsuːpəvaɪzə(r)/", "主管", "Report to supervisor.", "名词"),
        ("training", "/ˈtreɪnɪŋ/", "培训", "Staff training.", "名词"),
        
        # 科技词汇 (60+)
        ("algorithm", "/ˈælɡərɪðəm/", "算法", "Search algorithm.", "名词"),
        ("application", "/ˌæplɪˈkeɪʃn/", "应用程序", "Mobile application.", "名词"),
        ("bandwidth", "/ˈbændwɪdθ/", "带宽", "High bandwidth.", "名词"),
        ("binary", "/ˈbaɪnəri/", "二进制", "Binary code.", "名词"),
        ("browser", "/ˈbraʊzə(r)/", "浏览器", "Web browser.", "名词"),
        ("cache", "/kæʃ/", "缓存", "Clear the cache.", "名词"),
        ("cloud", "/klaʊd/", "云", "Cloud computing.", "名词"),
        ("database", "/ˈdeɪtəbeɪs/", "数据库", "Access the database.", "名词"),
        ("debug", "/ˌdiːˈbʌɡ/", "调试", "Debug the code.", "动词"),
        ("digital", "/ˈdɪdʒɪtl/", "数字的", "Digital transformation.", "形容词"),
        ("domain", "/dəˈmeɪn/", "域名", "Register a domain.", "名词"),
        ("encryption", "/ɪnˈkrɪpʃn/", "加密", "Data encryption.", "名词"),
        ("firewall", "/ˈfaɪəwɔːl/", "防火墙", "Install firewall.", "名词"),
        ("hardware", "/ˈhɑːdweə(r)/", "硬件", "Computer hardware.", "名词"),
        ("interface", "/ˈɪntəfeɪs/", "接口", "User interface.", "名词"),
        ("latency", "/ˈleɪtnsi/", "延迟", "Reduce latency.", "名词"),
        ("malware", "/ˈmælweə(r)/", "恶意软件", "Remove malware.", "名词"),
        ("network", "/ˈnetwɜːk/", "网络", "Computer network.", "名词"),
        ("operating", "/ˈɒpəreɪtɪŋ/", "操作的", "Operating system.", "形容词"),
        ("platform", "/ˈplætfɔːm/", "平台", "Software platform.", "名词"),
        ("programming", "/ˈprəʊɡræmɪŋ/", "编程", "Learn programming.", "名词"),
        ("protocol", "/ˈprəʊtəkɒl/", "协议", "Network protocol.", "名词"),
        ("router", "/ˈruːtə(r)/", "路由器", "Wireless router.", "名词"),
        ("server", "/ˈsɜːvə(r)/", "服务器", "Web server.", "名词"),
        ("software", "/ˈsɒftweə(r)/", "软件", "Install software.", "名词"),
        ("storage", "/ˈstɔːrɪdʒ/", "存储", "Cloud storage.", "名词"),
        ("virtual", "/ˈvɜːtʃuəl/", "虚拟的", "Virtual reality.", "形容词"),
        ("wireless", "/ˈwaɪələs/", "无线的", "Wireless connection.", "形容词"),
        ("analytics", "/ˌænəˈlɪtɪks/", "分析", "Data analytics.", "名词"),
        ("automation", "/ˌɔːtəˈmeɪʃn/", "自动化", "Process automation.", "名词"),
        ("biometrics", "/ˌbaɪəˈmetrɪks/", "生物识别", "Use biometrics.", "名词"),
        ("cybersecurity", "/ˌsaɪbəsɪˈkjʊərəti/", "网络安全", "Enhance cybersecurity.", "名词"),
        ("deployment", "/dɪˈplɔɪmənt/", "部署", "Software deployment.", "名词"),
        ("integration", "/ˌɪntɪˈɡreɪʃn/", "集成", "System integration.", "名词"),
        ("maintenance", "/ˈmeɪntənəns/", "维护", "System maintenance.", "名词"),
        ("optimization", "/ˌɒptɪmaɪˈzeɪʃn/", "优化", "Performance optimization.", "名词"),
        ("scalability", "/ˌskeɪləˈbɪləti/", "可扩展性", "Ensure scalability.", "名词"),
        ("authentication", "/ɔːˌθentɪˈkeɪʃn/", "认证", "User authentication.", "名词"),
        ("authorization", "/ˌɔːθəraɪˈzeɪʃn/", "授权", "Access authorization.", "名词"),
        ("backup", "/ˈbækʌp/", "备份", "Create a backup.", "名词"),
        ("configuration", "/kənˌfɪɡjəˈreɪʃn/", "配置", "System configuration.", "名词"),
        ("connectivity", "/ˌkɒnekˈtɪvəti/", "连接性", "Network connectivity.", "名词"),
        ("development", "/dɪˈveləpmənt/", "开发", "Software development.", "名词"),
        ("infrastructure", "/ˈɪnfrəstrʌktʃə(r)/", "基础设施", "IT infrastructure.", "名词"),
        ("migration", "/maɪˈɡreɪʃn/", "迁移", "Data migration.", "名词"),
        ("monitoring", "/ˈmɒnɪtərɪŋ/", "监控", "System monitoring.", "名词"),
        ("recovery", "/rɪˈkʌvəri/", "恢复", "Disaster recovery.", "名词"),
        ("repository", "/rɪˈpɒzətri/", "仓库", "Code repository.", "名词"),
        ("synchronization", "/ˌsɪŋkrənaɪˈzeɪʃn/", "同步", "Data synchronization.", "名词"),
        ("testing", "/ˈtestɪŋ/", "测试", "Software testing.", "名词"),
        ("update", "/ʌpˈdeɪt/", "更新", "Install updates.", "名词"),
        ("upgrade", "/ʌpˈɡreɪd/", "升级", "System upgrade.", "名词"),
        ("version", "/ˈvɜːʃn/", "版本", "Latest version.", "名词"),
        
        # 文化/艺术词汇 (60+)
        ("aesthetic", "/iːsˈθetɪk/", "美学的", "Aesthetic appeal.", "形容词"),
        ("architect", "/ˈɑːkɪtekt/", "建筑师", "Famous architect.", "名词"),
        ("artistic", "/ɑːˈtɪstɪk/", "艺术的", "Artistic talent.", "形容词"),
        ("canvas", "/ˈkænvəs/", "画布", "Paint on canvas.", "名词"),
        ("ceramic", "/səˈræmɪk/", "陶瓷的", "Ceramic art.", "形容词"),
        ("choreography", "/ˌkɒriˈɒɡrəfi/", "编舞", "Dance choreography.", "名词"),
        ("classical", "/ˈklæsɪkl/", "古典的", "Classical music.", "形容词"),
        ("composition", "/ˌkɒmpəˈzɪʃn/", "构图", "Musical composition.", "名词"),
        ("contemporary", "/kənˈtemprəri/", "当代的", "Contemporary art.", "形容词"),
        ("creative", "/kriˈeɪtɪv/", "有创造力的", "Creative thinking.", "形容词"),
        ("culture", "/ˈkʌltʃə(r)/", "文化", "Pop culture.", "名词"),
        ("design", "/dɪˈzaɪn/", "设计", "Graphic design.", "名词"),
        ("drawing", "/ˈdrɔːɪŋ/", "绘画", "Pencil drawing.", "名词"),
        ("exhibition", "/ˌeksɪˈbɪʃn/", "展览", "Art exhibition.", "名词"),
        ("gallery", "/ˈɡæləri/", "画廊", "Visit the gallery.", "名词"),
        ("genre", "/ˈʒɒnrə/", "体裁", "Literary genre.", "名词"),
        ("heritage", "/ˈherɪtɪdʒ/", "遗产", "Cultural heritage.", "名词"),
        ("illumination", "/ɪˌljuːmɪˈneɪʃn/", "插图", "Book illumination.", "名词"),
        ("impressionism", "/ɪmˈpreʃənɪzəm/", "印象派", "French impressionism.", "名词"),
        ("inspiration", "/ˌɪnspəˈreɪʃn/", "灵感", "Find inspiration.", "名词"),
        ("landscape", "/ˈlændskeɪp/", "风景画", "Landscape painting.", "名词"),
        ("literature", "/ˈlɪtrətʃə(r)/", "文学", "English literature.", "名词"),
        ("masterpiece", "/ˈmɑːstəpiːs/", "杰作", "A true masterpiece.", "名词"),
        ("medieval", "/ˌmedɪˈiːvl/", "中世纪的", "Medieval art.", "形容词"),
        ("monument", "/ˈmɒnjumənt/", "纪念碑", "Historic monument.", "名词"),
        ("museum", "/mjuˈziːəm/", "博物馆", "Art museum.", "名词"),
        ("narrative", "/ˈnærətɪv/", "叙事", "Visual narrative.", "名词"),
        ("opera", "/ˈɒprə/", "歌剧", "Watch an opera.", "名词"),
        ("orchestra", "/ˈɔːkɪstrə/", "管弦乐队", "Symphony orchestra.", "名词"),
        ("performance", "/pəˈfɔːməns/", "表演", "Live performance.", "名词"),
        ("photography", "/fəˈtɒɡrəfi/", "摄影", "Digital photography.", "名词"),
        ("portrait", "/ˈpɔːtreɪt/", "肖像画", "Oil portrait.", "名词"),
        ("pottery", "/ˈpɒtəri/", "陶艺", "Make pottery.", "名词"),
        ("renaissance", "/rɪˈneɪsns/", "文艺复兴", "Renaissance art.", "名词"),
        ("romanticism", "/rəʊˈmæntɪsɪzəm/", "浪漫主义", "Romanticism period.", "名词"),
        ("sculpture", "/ˈskʌlptʃə(r)/", "雕塑", "Marble sculpture.", "名词"),
        ("sketch", "/sketʃ/", "素描", "Quick sketch.", "名词"),
        ("symphony", "/ˈsɪmfəni/", "交响乐", "Beethoven's symphony.", "名词"),
        ("technique", "/tekˈniːk/", "技巧", "Painting technique.", "名词"),
        ("theater", "/ˈθɪətə(r)/", "剧院", "Go to the theater.", "名词"),
        ("tradition", "/trəˈdɪʃn/", "传统", "Cultural tradition.", "名词"),
        ("visual", "/ˈvɪʒuəl/", "视觉的", "Visual arts.", "形容词"),
        ("watercolor", "/ˈwɔːtəkʌlə(r)/", "水彩画", "Watercolor painting.", "名词"),
        ("abstract", "/ˈæbstrækt/", "抽象的", "Abstract art.", "形容词"),
        ("baroque", "/bəˈrɒk/", "巴洛克风格的", "Baroque architecture.", "形容词"),
        ("gothic", "/ˈɡɒθɪk/", "哥特式的", "Gothic cathedral.", "形容词"),
        ("minimalist", "/ˈmɪnɪməlɪst/", "极简主义的", "Minimalist design.", "形容词"),
        ("modernist", "/ˈmɒdənɪst/", "现代主义的", "Modernist movement.", "形容词"),
        ("neoclassical", "/ˌniːəʊˈklæsɪkl/", "新古典主义的", "Neoclassical style.", "形容词"),
        ("realism", "/ˈriːəlɪzəm/", "现实主义", "Social realism.", "名词"),
        ("surrealism", "/səˈriːəlɪzəm/", "超现实主义", "Surrealism art.", "名词"),
        ("symbolism", "/ˈsɪmbəlɪzəm/", "象征主义", "Literary symbolism.", "名词"),
    ]
    
    added_count = 0
    skipped_count = 0
    
    for word in new_words:
        cursor.execute('SELECT COUNT(*) FROM words WHERE english = ?', (word[0],))
        if cursor.fetchone()[0] == 0:
            cursor.execute('INSERT INTO words (english, phonetic, chinese, example, category) VALUES (?, ?, ?, ?, ?)', word)
            added_count += 1
        else:
            skipped_count += 1
    
    conn.commit()
    
    cursor.execute('SELECT COUNT(*) FROM words')
    total_count = cursor.fetchone()[0]
    
    print(f'添加了 {added_count} 个新单词')
    print(f'跳过了 {skipped_count} 个已存在的单词')
    print(f'数据库总单词数: {total_count}')
    
    conn.close()

if __name__ == '__main__':
    expand_vocabulary_to_5000()
