import sqlite3

def expand_to_5000_batch10():
    conn = sqlite3.connect('../words.db')
    cursor = conn.cursor()
    
    new_words = [
        # 科学研究类
        {"english": "acceleration", "phonetic": "/əkˌseləˈreɪʃn/", "chinese": "n. 加速", "example": "Acceleration rate.", "category": "科学研究"},
        {"english": "adaptation", "phonetic": "/ˌædæpˈteɪʃn/", "chinese": "n. 适应", "example": "Climate adaptation.", "category": "科学研究"},
        {"english": "advancement", "phonetic": "/ədˈvænsmənt/", "chinese": "n. 进展", "example": "Technological advancement.", "category": "科学研究"},
        {"english": "affirmation", "phonetic": "/ˌæfərˈmeɪʃn/", "chinese": "n. 确认", "example": "Make affirmation.", "category": "科学研究"},
        {"english": "aggregation", "phonetic": "/ˌæɡrɪˈɡeɪʃn/", "chinese": "n. 聚合", "example": "Data aggregation.", "category": "科学研究"},
        {"english": "alignment", "phonetic": "/əˈlaɪnmənt/", "chinese": "n. 对齐", "example": "Strategic alignment.", "category": "科学研究"},
        {"english": "annotation", "phonetic": "/ˌænəˈteɪʃn/", "chinese": "n. 注释", "example": "Add annotation.", "category": "科学研究"},
        {"english": "application", "phonetic": "/ˌæplɪˈkeɪʃn/", "chinese": "n. 应用", "example": "Software application.", "category": "科学研究"},
        {"english": "approximation", "phonetic": "/əˌprɑːksɪˈmeɪʃn/", "chinese": "n. 近似", "example": "Make approximation.", "category": "科学研究"},
        {"english": "argumentation", "phonetic": "/ˌɑːrɡjumenˈteɪʃn/", "chinese": "n. 论证", "example": "Logical argumentation.", "category": "科学研究"},
        {"english": "articulation", "phonetic": "/ɑːrˌtɪkjʊˈleɪʃn/", "chinese": "n. 清晰表达", "example": "Clear articulation.", "category": "科学研究"},
        {"english": "assessment", "phonetic": "/əˈsesmənt/", "chinese": "n. 评估", "example": "Risk assessment.", "category": "科学研究"},
        {"english": "association", "phonetic": "/əˌsoʊsiˈeɪʃn/", "chinese": "n. 关联", "example": "Statistical association.", "category": "科学研究"},
        {"english": "assumption", "phonetic": "/əˈsʌmpʃn/", "chinese": "n. 假设", "example": "Make assumption.", "category": "科学研究"},
        {"english": "attenuation", "phonetic": "/əˌtenjuˈeɪʃn/", "chinese": "n. 衰减", "example": "Signal attenuation.", "category": "科学研究"},
        {"english": "authentication", "phonetic": "/ɔːˌθentɪˈkeɪʃn/", "chinese": "n. 认证", "example": "User authentication.", "category": "科学研究"},
        {"english": "authorization", "phonetic": "/ˌɔːθərəˈzeɪʃn/", "chinese": "n. 授权", "example": "Access authorization.", "category": "科学研究"},
        {"english": "automation", "phonetic": "/ˌɔːtəˈmeɪʃn/", "chinese": "n. 自动化", "example": "Process automation.", "category": "科学研究"},
        {"english": "averaging", "phonetic": "/ˈævərɪdʒɪŋ/", "chinese": "n. 平均", "example": "Data averaging.", "category": "科学研究"},
        {"english": "backpropagation", "phonetic": "/ˌbækprɑːpəˈɡeɪʃn/", "chinese": "n. 反向传播", "example": "Neural backpropagation.", "category": "科学研究"},
        {"english": "benchmarking", "phonetic": "/ˈbentʃmɑːrkɪŋ/", "chinese": "n. 基准测试", "example": "Performance benchmarking.", "category": "科学研究"},
        {"english": "bias", "phonetic": "/ˈbaɪəs/", "chinese": "n. 偏差", "example": "Selection bias.", "category": "科学研究"},
        {"english": "calibration", "phonetic": "/ˌkælɪˈbreɪʃn/", "chinese": "n. 校准", "example": "Instrument calibration.", "category": "科学研究"},
        {"english": "categorization", "phonetic": "/ˌkætəɡəraɪˈzeɪʃn/", "chinese": "n. 分类", "example": "Data categorization.", "category": "科学研究"},
        {"english": "causation", "phonetic": "/kɔːˈzeɪʃn/", "chinese": "n. 因果关系", "example": "Establish causation.", "category": "科学研究"},
        {"english": "characterization", "phonetic": "/ˌkærəktəraɪˈzeɪʃn/", "chinese": "n. 特征描述", "example": "Material characterization.", "category": "科学研究"},
        {"english": "classification", "phonetic": "/ˌklæsɪfɪˈkeɪʃn/", "chinese": "n. 分类", "example": "Image classification.", "category": "科学研究"},
        {"english": "clustering", "phonetic": "/ˈklʌstərɪŋ/", "chinese": "n. 聚类", "example": "Data clustering.", "category": "科学研究"},
        {"english": "codification", "phonetic": "/ˌkoʊdɪfɪˈkeɪʃn/", "chinese": "n. 编码", "example": "Legal codification.", "category": "科学研究"},
        {"english": "coherence", "phonetic": "/koʊˈhɪrəns/", "chinese": "n. 连贯性", "example": "Text coherence.", "category": "科学研究"},
        {"english": "collation", "phonetic": "/kəˈleɪʃn/", "chinese": "n. 整理", "example": "Data collation.", "category": "科学研究"},
        {"english": "collection", "phonetic": "/kəˈlekʃn/", "chinese": "n. 收集", "example": "Data collection.", "category": "科学研究"},
        {"english": "combination", "phonetic": "/ˌkɑːmbɪˈneɪʃn/", "chinese": "n. 组合", "example": "Linear combination.", "category": "科学研究"},
        {"english": "comparability", "phonetic": "/kəmˌpærəˈbɪləti/", "chinese": "n. 可比性", "example": "Ensure comparability.", "category": "科学研究"},
        {"english": "compilation", "phonetic": "/ˌkɑːmpɪˈleɪʃn/", "chinese": "n. 编译", "example": "Code compilation.", "category": "科学研究"},
        {"english": "completeness", "phonetic": "/kəmˈpliːtnəs/", "chinese": "n. 完整性", "example": "Data completeness.", "category": "科学研究"},
        {"english": "complexity", "phonetic": "/kəmˈpleksəti/", "chinese": "n. 复杂性", "example": "Computational complexity.", "category": "科学研究"},
        {"english": "compliance", "phonetic": "/kəmˈplaɪəns/", "chinese": "n. 合规", "example": "Regulatory compliance.", "category": "科学研究"},
        {"english": "composition", "phonetic": "/ˌkɑːmpəˈzɪʃn/", "chinese": "n. 组成", "example": "Chemical composition.", "category": "科学研究"},
        {"english": "computation", "phonetic": "/ˌkɑːmpjuˈteɪʃn/", "chinese": "n. 计算", "example": "Scientific computation.", "category": "科学研究"},
        {"english": "concentration", "phonetic": "/ˌkɑːnsənˈtreɪʃn/", "chinese": "n. 浓度", "example": "Solution concentration.", "category": "科学研究"},
        {"english": "conceptualization", "phonetic": "/kənˌseptʃuəlaɪˈzeɪʃn/", "chinese": "n. 概念化", "example": "Model conceptualization.", "category": "科学研究"},
        {"english": "configuration", "phonetic": "/kənˌfɪɡjʊˈreɪʃn/", "chinese": "n. 配置", "example": "System configuration.", "category": "科学研究"},
        {"english": "confirmation", "phonetic": "/ˌkɑːnfərˈmeɪʃn/", "chinese": "n. 确认", "example": "Get confirmation.", "category": "科学研究"},
        {"english": "connectivity", "phonetic": "/ˌkɑːnekˈtɪvəti/", "chinese": "n. 连接性", "example": "Network connectivity.", "category": "科学研究"},
        {"english": "consensus", "phonetic": "/kənˈsensəs/", "chinese": "n. 共识", "example": "Reach consensus.", "category": "科学研究"},
        {"english": "conservation", "phonetic": "/ˌkɑːnsərˈveɪʃn/", "chinese": "n. 保护", "example": "Energy conservation.", "category": "科学研究"},
        {"english": "consistency", "phonetic": "/kənˈsɪstənsi/", "chinese": "n. 一致性", "example": "Data consistency.", "category": "科学研究"},
        {"english": "construction", "phonetic": "/kənˈstrʌkʃn/", "chinese": "n. 构建", "example": "Theory construction.", "category": "科学研究"},
        {"english": "consumption", "phonetic": "/kənˈsʌmpʃn/", "chinese": "n. 消耗", "example": "Energy consumption.", "category": "科学研究"},
        {"english": "containment", "phonetic": "/kənˈteɪnmənt/", "chinese": "n. 控制", "example": "Virus containment.", "category": "科学研究"},
        {"english": "continuity", "phonetic": "/ˌkɑːntɪˈnuːəti/", "chinese": "n. 连续性", "example": "Business continuity.", "category": "科学研究"},
        {"english": "convergence", "phonetic": "/kənˈvɜːrdʒəns/", "chinese": "n. 收敛", "example": "Algorithm convergence.", "category": "科学研究"},
        {"english": "conversion", "phonetic": "/kənˈvɜːrʒn/", "chinese": "n. 转换", "example": "Data conversion.", "category": "科学研究"},
        {"english": "coordination", "phonetic": "/koʊˌɔːrdɪˈneɪʃn/", "chinese": "n. 协调", "example": "Project coordination.", "category": "科学研究"},
        {"english": "correction", "phonetic": "/kəˈrekʃn/", "chinese": "n. 纠正", "example": "Error correction.", "category": "科学研究"},
        {"english": "correlation", "phonetic": "/ˌkɔːrəˈleɪʃn/", "chinese": "n. 相关性", "example": "Statistical correlation.", "category": "科学研究"},
        {"english": "corruption", "phonetic": "/kəˈrʌpʃn/", "chinese": "n. 损坏", "example": "Data corruption.", "category": "科学研究"},
        {"english": "creation", "phonetic": "/kriˈeɪʃn/", "chinese": "n. 创造", "example": "Job creation.", "category": "科学研究"},
        {"english": "crystallization", "phonetic": "/ˌkrɪstəlaɪˈzeɪʃn/", "chinese": "n. 结晶", "example": "Protein crystallization.", "category": "科学研究"},
        {"english": "cultivation", "phonetic": "/ˌkʌltɪˈveɪʃn/", "chinese": "n. 培养", "example": "Cell cultivation.", "category": "科学研究"},
        {"english": "customization", "phonetic": "/ˌkʌstəmaɪˈzeɪʃn/", "chinese": "n. 定制", "example": "Product customization.", "category": "科学研究"},
        {"english": "decomposition", "phonetic": "/ˌdiːkɑːmpəˈzɪʃn/", "chinese": "n. 分解", "example": "Matrix decomposition.", "category": "科学研究"},
        {"english": "deduction", "phonetic": "/dɪˈdʌkʃn/", "chinese": "n. 推论", "example": "Logical deduction.", "category": "科学研究"},
        {"english": "definition", "phonetic": "/ˌdefɪˈnɪʃn/", "chinese": "n. 定义", "example": "Clear definition.", "category": "科学研究"},
        {"english": "degradation", "phonetic": "/ˌdeɡrəˈdeɪʃn/", "chinese": "n. 降解", "example": "Environmental degradation.", "category": "科学研究"},
        {"english": "demonstration", "phonetic": "/ˌdemənˈstreɪʃn/", "chinese": "n. 演示", "example": "Product demonstration.", "category": "科学研究"},
        {"english": "deployment", "phonetic": "/dɪˈplɔɪmənt/", "chinese": "n. 部署", "example": "Software deployment.", "category": "科学研究"},
        {"english": "derivation", "phonetic": "/ˌderɪˈveɪʃn/", "chinese": "n. 推导", "example": "Formula derivation.", "category": "科学研究"},
        {"english": "description", "phonetic": "/dɪˈskrɪpʃn/", "chinese": "n. 描述", "example": "Detailed description.", "category": "科学研究"},
        {"english": "design", "phonetic": "/dɪˈzaɪn/", "chinese": "n. 设计", "example": "Experimental design.", "category": "科学研究"},
        {"english": "detection", "phonetic": "/dɪˈtekʃn/", "chinese": "n. 检测", "example": "Fault detection.", "category": "科学研究"},
        {"english": "determination", "phonetic": "/dɪˌtɜːrmɪˈneɪʃn/", "chinese": "n. 测定", "example": "Structure determination.", "category": "科学研究"},
        {"english": "development", "phonetic": "/dɪˈveləpmənt/", "chinese": "n. 开发", "example": "Software development.", "category": "科学研究"},
        {"english": "deviation", "phonetic": "/ˌdiːviˈeɪʃn/", "chinese": "n. 偏差", "example": "Standard deviation.", "category": "科学研究"},
        {"english": "diagnosis", "phonetic": "/ˌdaɪəɡˈnoʊsɪs/", "chinese": "n. 诊断", "example": "System diagnosis.", "category": "科学研究"},
        {"english": "differentiation", "phonetic": "/ˌdɪfəˌrenʃiˈeɪʃn/", "chinese": "n. 区分", "example": "Cell differentiation.", "category": "科学研究"},
        {"english": "diffusion", "phonetic": "/dɪˈfjuːʒn/", "chinese": "n. 扩散", "example": "Gas diffusion.", "category": "科学研究"},
        {"english": "digitization", "phonetic": "/ˌdɪdʒɪtaɪˈzeɪʃn/", "chinese": "n. 数字化", "example": "Document digitization.", "category": "科学研究"},
        {"english": "dimensionality", "phonetic": "/ˌdaɪmenʃəˈnæləti/", "chinese": "n. 维度", "example": "Data dimensionality.", "category": "科学研究"},
        {"english": "discovery", "phonetic": "/dɪˈskʌvəri/", "chinese": "n. 发现", "example": "Scientific discovery.", "category": "科学研究"},
        {"english": "discretization", "phonetic": "/dɪˌskriːtaɪˈzeɪʃn/", "chinese": "n. 离散化", "example": "Time discretization.", "category": "科学研究"},
        {"english": "discrimination", "phonetic": "/dɪˌskrɪmɪˈneɪʃn/", "chinese": "n. 区分", "example": "Feature discrimination.", "category": "科学研究"},
        {"english": "dissemination", "phonetic": "/dɪˌsemɪˈneɪʃn/", "chinese": "n. 传播", "example": "Knowledge dissemination.", "category": "科学研究"},
        {"english": "distribution", "phonetic": "/ˌdɪstrɪˈbjuːʃn/", "chinese": "n. 分布", "example": "Normal distribution.", "category": "科学研究"},
        {"english": "divergence", "phonetic": "/daɪˈvɜːrdʒəns/", "chinese": "n. 发散", "example": "Vector divergence.", "category": "科学研究"},
        {"english": "documentation", "phonetic": "/ˌdɑːkjumenˈteɪʃn/", "chinese": "n. 文档", "example": "Technical documentation.", "category": "科学研究"},
        {"english": "duplication", "phonetic": "/ˌduːplɪˈkeɪʃn/", "chinese": "n. 复制", "example": "Gene duplication.", "category": "科学研究"},
        {"english": "duration", "phonetic": "/dʊˈreɪʃn/", "chinese": "n. 持续时间", "example": "Treatment duration.", "category": "科学研究"},
        {"english": "dynamic", "phonetic": "/daɪˈnæmɪk/", "chinese": "adj. 动态的", "example": "Dynamic programming.", "category": "科学研究"},
        {"english": "economics", "phonetic": "/ˌiːkəˈnɑːmɪks/", "chinese": "n. 经济学", "example": "Health economics.", "category": "科学研究"},
        {"english": "editing", "phonetic": "/ˈedɪtɪŋ/", "chinese": "n. 编辑", "example": "Video editing.", "category": "科学研究"},
        {"english": "elaboration", "phonetic": "/ɪˌlæbəˈreɪʃn/", "chinese": "n. 阐述", "example": "Theory elaboration.", "category": "科学研究"},
        {"english": "elasticity", "phonetic": "/ɪˌlæˈstɪsəti/", "chinese": "n. 弹性", "example": "Price elasticity.", "category": "科学研究"},
        {"english": "electrification", "phonetic": "/ɪˌlektrɪfɪˈkeɪʃn/", "chinese": "n. 电气化", "example": "Rural electrification.", "category": "科学研究"},
        {"english": "elevation", "phonetic": "/ˌelɪˈveɪʃn/", "chinese": "n. 海拔", "example": "High elevation.", "category": "科学研究"},
        {"english": "elimination", "phonetic": "/ɪˌlɪmɪˈneɪʃn/", "chinese": "n. 消除", "example": "Waste elimination.", "category": "科学研究"},
        {"english": "embodiment", "phonetic": "/ɪmˈbɑːdimənt/", "chinese": "n. 体现", "example": "Technology embodiment.", "category": "科学研究"},
        {"english": "emission", "phonetic": "/ɪˈmɪʃn/", "chinese": "n. 排放", "example": "Carbon emission.", "category": "科学研究"},
        {"english": "empowerment", "phonetic": "/ɪmˈpaʊərmənt/", "chinese": "n. 赋权", "example": "Patient empowerment.", "category": "科学研究"},
        {"english": "encryption", "phonetic": "/ɪnˈkrɪpʃn/", "chinese": "n. 加密", "example": "Data encryption.", "category": "科学研究"},
        {"english": "enhancement", "phonetic": "/ɪnˈhænsmənt/", "chinese": "n. 增强", "example": "Image enhancement.", "category": "科学研究"},
        {"english": "enrichment", "phonetic": "/ɪnˈrɪtʃmənt/", "chinese": "n. 丰富", "example": "Data enrichment.", "category": "科学研究"},
        {"english": "entailment", "phonetic": "/ɪnˈteɪlmənt/", "chinese": "n. 蕴含", "example": "Logical entailment.", "category": "科学研究"},
        {"english": "enumeration", "phonetic": "/ɪˌnuːməˈreɪʃn/", "chinese": "n. 列举", "example": "Feature enumeration.", "category": "科学研究"},
        {"english": "equilibrium", "phonetic": "/ˌiːkwɪˈlɪbriəm/", "chinese": "n. 平衡", "example": "Market equilibrium.", "category": "科学研究"},
        {"english": "estimation", "phonetic": "/ˌestɪˈmeɪʃn/", "chinese": "n. 估计", "example": "Parameter estimation.", "category": "科学研究"},
        {"english": "evaluation", "phonetic": "/ɪˌvæljuˈeɪʃn/", "chinese": "n. 评估", "example": "Performance evaluation.", "category": "科学研究"},
        {"english": "evolution", "phonetic": "/ˌevəˈluːʃn/", "chinese": "n. 进化", "example": "Software evolution.", "category": "科学研究"},
        {"english": "examination", "phonetic": "/ɪɡˌzæmɪˈneɪʃn/", "chinese": "n. 检查", "example": "Physical examination.", "category": "科学研究"},
        {"english": "exclusion", "phonetic": "/ɪkˈskluːʒn/", "chinese": "n. 排除", "example": "Feature exclusion.", "category": "科学研究"},
        {"english": "execution", "phonetic": "/ˌeksɪˈkjuːʃn/", "chinese": "n. 执行", "example": "Plan execution.", "category": "科学研究"},
        {"english": "expansion", "phonetic": "/ɪkˈspænʃn/", "chinese": "n. 扩展", "example": "Thermal expansion.", "category": "科学研究"},
        {"english": "experimentation", "phonetic": "/ɪkˌsperɪmenˈteɪʃn/", "chinese": "n. 实验", "example": "Animal experimentation.", "category": "科学研究"},
        {"english": "explanation", "phonetic": "/ˌekspləˈneɪʃn/", "chinese": "n. 解释", "example": "Provide explanation.", "category": "科学研究"},
        {"english": "exploration", "phonetic": "/ˌekspləˈreɪʃn/", "chinese": "n. 探索", "example": "Space exploration.", "category": "科学研究"},
        {"english": "extraction", "phonetic": "/ɪkˈstrækʃn/", "chinese": "n. 提取", "example": "Feature extraction.", "category": "科学研究"},
        {"english": "fabrication", "phonetic": "/ˌfæbrɪˈkeɪʃn/", "chinese": "n. 制造", "example": "Metal fabrication.", "category": "科学研究"},
        {"english": "facilitation", "phonetic": "/fəˌsɪlɪˈteɪʃn/", "chinese": "n. 促进", "example": "Learning facilitation.", "category": "科学研究"},
        {"english": "falsification", "phonetic": "/ˌfɔːlsɪfɪˈkeɪʃn/", "chinese": "n. 伪造", "example": "Data falsification.", "category": "科学研究"},
        {"english": "filtration", "phonetic": "/fɪlˈtreɪʃn/", "chinese": "n. 过滤", "example": "Water filtration.", "category": "科学研究"},
        {"english": "formalization", "phonetic": "/ˌfɔːrməlaɪˈzeɪʃn/", "chinese": "n. 形式化", "example": "Process formalization.", "category": "科学研究"},
        {"english": "formulation", "phonetic": "/ˌfɔːrmjʊˈleɪʃn/", "chinese": "n. 制定", "example": "Policy formulation.", "category": "科学研究"},
        {"english": "fragmentation", "phonetic": "/ˌfræɡmenˈteɪʃn/", "chinese": "n. 碎片化", "example": "Data fragmentation.", "category": "科学研究"},
        {"english": "functionalization", "phonetic": "/ˌfʌŋkʃənəlaɪˈzeɪʃn/", "chinese": "n. 功能化", "example": "Surface functionalization.", "category": "科学研究"},
        {"english": "generalization", "phonetic": "/ˌdʒenrəlaɪˈzeɪʃn/", "chinese": "n. 泛化", "example": "Model generalization.", "category": "科学研究"},
        {"english": "generation", "phonetic": "/ˌdʒenəˈreɪʃn/", "chinese": "n. 生成", "example": "Power generation.", "category": "科学研究"},
        {"english": "genomics", "phonetic": "/dʒəˈnoʊmɪks/", "chinese": "n. 基因组学", "example": "Human genomics.", "category": "科学研究"},
        {"english": "globalization", "phonetic": "/ˌɡloʊbəlaɪˈzeɪʃn/", "chinese": "n. 全球化", "example": "Economic globalization.", "category": "科学研究"},
        {"english": "gradation", "phonetic": "/ɡreɪˈdeɪʃn/", "chinese": "n. 渐变", "example": "Color gradation.", "category": "科学研究"},
        {"english": "granularity", "phonetic": "/ˌɡrænjʊˈlærəti/", "chinese": "n. 粒度", "example": "Data granularity.", "category": "科学研究"},
        {"english": "grouping", "phonetic": "/ˈɡruːpɪŋ/", "chinese": "n. 分组", "example": "Data grouping.", "category": "科学研究"},
        {"english": "harmonization", "phonetic": "/ˌhɑːrmənaɪˈzeɪʃn/", "chinese": "n. 协调", "example": "Standard harmonization.", "category": "科学研究"},
        {"english": "hypothesis", "phonetic": "/haɪˈpɑːθəsɪs/", "chinese": "n. 假设", "example": "Test hypothesis.", "category": "科学研究"},
        {"english": "identification", "phonetic": "/aɪˌdentɪfɪˈkeɪʃn/", "chinese": "n. 识别", "example": "User identification.", "category": "科学研究"},
        {"english": "illumination", "phonetic": "/ɪˌluːmɪˈneɪʃn/", "chinese": "n. 照明", "example": "Street illumination.", "category": "科学研究"},
        {"english": "illustration", "phonetic": "/ˌɪləˈstreɪʃn/", "chinese": "n. 说明", "example": "Provide illustration.", "category": "科学研究"},
        {"english": "implementation", "phonetic": "/ˌɪmplɪmenˈteɪʃn/", "chinese": "n. 实施", "example": "System implementation.", "category": "科学研究"},
        {"english": "implication", "phonetic": "/ˌɪmplɪˈkeɪʃn/", "chinese": "n. 含义", "example": "Policy implication.", "category": "科学研究"},
        {"english": "improvement", "phonetic": "/ɪmˈpruːvmənt/", "chinese": "n. 改进", "example": "Process improvement.", "category": "科学研究"},
        {"english": "inclusion", "phonetic": "/ɪnˈkluːʒn/", "chinese": "n. 包含", "example": "Feature inclusion.", "category": "科学研究"},
        {"english": "incorporation", "phonetic": "/ɪnˌkɔːrpəˈreɪʃn/", "chinese": "n. 合并", "example": "Data incorporation.", "category": "科学研究"},
        {"english": "industrialization", "phonetic": "/ɪnˌdʌstriəlaɪˈzeɪʃn/", "chinese": "n. 工业化", "example": "Rapid industrialization.", "category": "科学研究"},
        {"english": "inference", "phonetic": "/ˈɪnfərəns/", "chinese": "n. 推断", "example": "Statistical inference.", "category": "科学研究"},
        {"english": "information", "phonetic": "/ˌɪnfərˈmeɪʃn/", "chinese": "n. 信息", "example": "Process information.", "category": "科学研究"},
        {"english": "infrastructure", "phonetic": "/ˈɪnfrəstrʌktʃər/", "chinese": "n. 基础设施", "example": "Digital infrastructure.", "category": "科学研究"},
        {"english": "innovation", "phonetic": "/ˌɪnəˈveɪʃn/", "chinese": "n. 创新", "example": "Technological innovation.", "category": "科学研究"},
        {"english": "inspection", "phonetic": "/ɪnˈspekʃn/", "chinese": "n. 检查", "example": "Safety inspection.", "category": "科学研究"},
        {"english": "installation", "phonetic": "/ˌɪnstəˈleɪʃn/", "chinese": "n. 安装", "example": "Software installation.", "category": "科学研究"},
        {"english": "integration", "phonetic": "/ˌɪntɪˈɡreɪʃn/", "chinese": "n. 集成", "example": "System integration.", "category": "科学研究"},
        {"english": "intensity", "phonetic": "/ɪnˈtensəti/", "chinese": "n. 强度", "example": "Light intensity.", "category": "科学研究"},
        {"english": "interaction", "phonetic": "/ˌɪntərˈækʃn/", "chinese": "n. 交互", "example": "User interaction.", "category": "科学研究"},
        {"english": "interconnection", "phonetic": "/ˌɪntərkəˈnekʃn/", "chinese": "n. 互联", "example": "Network interconnection.", "category": "科学研究"},
        {"english": "interdependence", "phonetic": "/ˌɪntərdɪˈpendəns/", "chinese": "n. 相互依赖", "example": "Economic interdependence.", "category": "科学研究"},
        {"english": "interpretation", "phonetic": "/ɪnˌtɜːrprɪˈteɪʃn/", "chinese": "n. 解释", "example": "Data interpretation.", "category": "科学研究"},
        {"english": "intervention", "phonetic": "/ˌɪntərˈvenʃn/", "chinese": "n. 干预", "example": "Medical intervention.", "category": "科学研究"},
        {"english": "investigation", "phonetic": "/ɪnˌvestɪˈɡeɪʃn/", "chinese": "n. 调查", "example": "Criminal investigation.", "category": "科学研究"},
        {"english": "ionization", "phonetic": "/ˌaɪənaɪˈzeɪʃn/", "chinese": "n. 电离", "example": "Gas ionization.", "category": "科学研究"},
        {"english": "isolation", "phonetic": "/ˌaɪsəˈleɪʃn/", "chinese": "n. 隔离", "example": "Virus isolation.", "category": "科学研究"},
        {"english": "iteration", "phonetic": "/ˌɪtəˈreɪʃn/", "chinese": "n. 迭代", "example": "Design iteration.", "category": "科学研究"},
        {"english": "justification", "phonetic": "/ˌdʒʌstɪfɪˈkeɪʃn/", "chinese": "n. 理由", "example": "Provide justification.", "category": "科学研究"},
        {"english": "labeling", "phonetic": "/ˈleɪbəlɪŋ/", "chinese": "n. 标记", "example": "Data labeling.", "category": "科学研究"},
        {"english": "localization", "phonetic": "/ˌloʊkəlaɪˈzeɪʃn/", "chinese": "n. 本地化", "example": "Software localization.", "category": "科学研究"},
        {"english": "maintenance", "phonetic": "/ˈmeɪntənəns/", "chinese": "n. 维护", "example": "System maintenance.", "category": "科学研究"},
        {"english": "manipulation", "phonetic": "/məˌnɪpjʊˈleɪʃn/", "chinese": "n. 操作", "example": "Data manipulation.", "category": "科学研究"},
        {"english": "measurement", "phonetic": "/ˈmeʒərmənt/", "chinese": "n. 测量", "example": "Take measurement.", "category": "科学研究"},
        {"english": "mechanization", "phonetic": "/ˌmekənaɪˈzeɪʃn/", "chinese": "n. 机械化", "example": "Agricultural mechanization.", "category": "科学研究"},
        {"english": "mediation", "phonetic": "/ˌmiːdiˈeɪʃn/", "chinese": "n. 调解", "example": "Conflict mediation.", "category": "科学研究"},
        {"english": "memorization", "phonetic": "/ˌmeməraɪˈzeɪʃn/", "chinese": "n. 记忆", "example": "Rote memorization.", "category": "科学研究"},
        {"english": "migration", "phonetic": "/maɪˈɡreɪʃn/", "chinese": "n. 迁移", "example": "Data migration.", "category": "科学研究"},
        {"english": "minimization", "phonetic": "/ˌmɪnɪmaɪˈzeɪʃn/", "chinese": "n. 最小化", "example": "Cost minimization.", "category": "科学研究"},
        {"english": "modification", "phonetic": "/ˌmɑːdɪfɪˈkeɪʃn/", "chinese": "n. 修改", "example": "Genetic modification.", "category": "科学研究"},
        {"english": "modulation", "phonetic": "/ˌmɑːdʒəˈleɪʃn/", "chinese": "n. 调制", "example": "Signal modulation.", "category": "科学研究"},
        {"english": "monitoring", "phonetic": "/ˈmɑːnɪtərɪŋ/", "chinese": "n. 监控", "example": "Network monitoring.", "category": "科学研究"},
        {"english": "multiplication", "phonetic": "/ˌmʌltɪplɪˈkeɪʃn/", "chinese": "n. 乘法", "example": "Matrix multiplication.", "category": "科学研究"},
        {"english": "navigation", "phonetic": "/ˌnævɪˈɡeɪʃn/", "chinese": "n. 导航", "example": "Website navigation.", "category": "科学研究"},
        {"english": "negotiation", "phonetic": "/nɪˌɡoʊʃiˈeɪʃn/", "chinese": "n. 谈判", "example": "Price negotiation.", "category": "科学研究"},
        {"english": "normalization", "phonetic": "/ˌnɔːrməlaɪˈzeɪʃn/", "chinese": "n. 归一化", "example": "Data normalization.", "category": "科学研究"},
        {"english": "observation", "phonetic": "/ˌɑːbzərˈveɪʃn/", "chinese": "n. 观察", "example": "Scientific observation.", "category": "科学研究"},
        {"english": "optimization", "phonetic": "/ˌɑːptɪmɪˈzeɪʃn/", "chinese": "n. 优化", "example": "Code optimization.", "category": "科学研究"},
        {"english": "organization", "phonetic": "/ˌɔːrɡənaɪˈzeɪʃn/", "chinese": "n. 组织", "example": "Data organization.", "category": "科学研究"},
        {"english": "orientation", "phonetic": "/ˌɔːrientˈteɪʃn/", "chinese": "n. 定向", "example": "Spatial orientation.", "category": "科学研究"},
        {"english": "parameterization", "phonetic": "/pəˌræmɪtrəˈzeɪʃn/", "chinese": "n. 参数化", "example": "Model parameterization.", "category": "科学研究"},
        {"english": "partitioning", "phonetic": "/pɑːrˈtɪʃənɪŋ/", "chinese": "n. 分区", "example": "Disk partitioning.", "category": "科学研究"},
        {"english": "perception", "phonetic": "/pərˈsepʃn/", "chinese": "n. 感知", "example": "Visual perception.", "category": "科学研究"},
        {"english": "performance", "phonetic": "/pərˈfɔːrməns/", "chinese": "n. 性能", "example": "System performance.", "category": "科学研究"},
        {"english": "personalization", "phonetic": "/ˌpɜːrsənəlaɪˈzeɪʃn/", "chinese": "n. 个性化", "example": "Content personalization.", "category": "科学研究"},
        {"english": "persuasion", "phonetic": "/pərˈweɪʒn/", "chinese": "n. 说服", "example": "Use persuasion.", "category": "科学研究"},
        {"english": "perturbation", "phonetic": "/ˌpɜːrtərˈbeɪʃn/", "chinese": "n. 扰动", "example": "System perturbation.", "category": "科学研究"},
        {"english": "planning", "phonetic": "/ˈplænɪŋ/", "chinese": "n. 规划", "example": "Strategic planning.", "category": "科学研究"},
        {"english": "polarization", "phonetic": "/ˌpoʊləraɪˈzeɪʃn/", "chinese": "n. 极化", "example": "Light polarization.", "category": "科学研究"},
        {"english": "population", "phonetic": "/ˌpɑːpjʊˈleɪʃn/", "chinese": "n. 总体", "example": "Target population.", "category": "科学研究"},
        {"english": "positioning", "phonetic": "/pəˈzɪʃənɪŋ/", "chinese": "n. 定位", "example": "GPS positioning.", "category": "科学研究"},
        {"english": "post-processing", "phonetic": "/ˈpoʊst ˈprɑːsesɪŋ/", "chinese": "n. 后处理", "example": "Image post-processing.", "category": "科学研究"},
        {"english": "prediction", "phonetic": "/prɪˈdɪkʃn/", "chinese": "n. 预测", "example": "Make prediction.", "category": "科学研究"},
        {"english": "preparation", "phonetic": "/ˌprepəˈreɪʃn/", "chinese": "n. 准备", "example": "Sample preparation.", "category": "科学研究"},
        {"english": "presentation", "phonetic": "/ˌpriːzenˈteɪʃn/", "chinese": "n. 展示", "example": "Data presentation.", "category": "科学研究"},
        {"english": "preservation", "phonetic": "/ˌprezərˈveɪʃn/", "chinese": "n. 保护", "example": "Food preservation.", "category": "科学研究"},
        {"english": "prioritization", "phonetic": "/praɪˌɔːrətaɪˈzeɪʃn/", "chinese": "n. 优先级", "example": "Task prioritization.", "category": "科学研究"},
        {"english": "processing", "phonetic": "/ˈprɑːsesɪŋ/", "chinese": "n. 处理", "example": "Data processing.", "category": "科学研究"},
        {"english": "production", "phonetic": "/prəˈdʌkʃn/", "chinese": "n. 生产", "example": "Mass production.", "category": "科学研究"},
        {"english": "programming", "phonetic": "/ˈproʊɡræmɪŋ/", "chinese": "n. 编程", "example": "Learn programming.", "category": "科学研究"},
        {"english": "progression", "phonetic": "/prəˈɡreʃn/", "chinese": "n. 进展", "example": "Disease progression.", "category": "科学研究"},
        {"english": "projection", "phonetic": "/prəˈdʒekʃn/", "chinese": "n. 投影", "example": "Population projection.", "category": "科学研究"},
        {"english": "proliferation", "phonetic": "/prəˌlɪfəˈreɪʃn/", "chinese": "n. 扩散", "example": "Nuclear proliferation.", "category": "科学研究"},
        {"english": "propagation", "phonetic": "/ˌprɑːpəˈɡeɪʃn/", "chinese": "n. 传播", "example": "Signal propagation.", "category": "科学研究"},
        {"english": "proportionality", "phonetic": "/prəˌpɔːrʃəˈnæləti/", "chinese": "n. 比例", "example": "Direct proportionality.", "category": "科学研究"},
        {"english": "proposition", "phonetic": "/ˌprɑːpəˈzɪʃn/", "chinese": "n. 命题", "example": "Logical proposition.", "category": "科学研究"},
        {"english": "protection", "phonetic": "/prəˈtekʃn/", "chinese": "n. 保护", "example": "Data protection.", "category": "科学研究"},
        {"english": "protocol", "phonetic": "/ˈproʊtəkɑːl/", "chinese": "n. 协议", "example": "Network protocol.", "category": "科学研究"},
        {"english": "qualification", "phonetic": "/ˌkwɑːlɪfɪˈkeɪʃn/", "chinese": "n. 资格", "example": "Professional qualification.", "category": "科学研究"},
        {"english": "quantification", "phonetic": "/ˌkwɑːntɪfɪˈkeɪʃn/", "chinese": "n. 量化", "example": "Risk quantification.", "category": "科学研究"},
        {"english": "randomization", "phonetic": "/ˌrændəmaɪˈzeɪʃn/", "chinese": "n. 随机化", "example": "Sample randomization.", "category": "科学研究"},
        {"english": "rationalization", "phonetic": "/ˌræʃnəlaɪˈzeɪʃn/", "chinese": "n. 合理化", "example": "Process rationalization.", "category": "科学研究"},
        {"english": "reconstruction", "phonetic": "/ˌriːkənˈstrʌkʃn/", "chinese": "n. 重建", "example": "Data reconstruction.", "category": "科学研究"},
        {"english": "recovery", "phonetic": "/rɪˈkʌvəri/", "chinese": "n. 恢复", "example": "System recovery.", "category": "科学研究"},
        {"english": "recruitment", "phonetic": "/rɪˈkruːtmənt/", "chinese": "n. 招募", "example": "Participant recruitment.", "category": "科学研究"},
        {"english": "refinement", "phonetic": "/rɪˈfaɪnmənt/", "chinese": "n. 改进", "example": "Model refinement.", "category": "科学研究"},
        {"english": "reflection", "phonetic": "/rɪˈflekʃn/", "chinese": "n. 反射", "example": "Light reflection.", "category": "科学研究"},
        {"english": "reformation", "phonetic": "/ˌrefərˈmeɪʃn/", "chinese": "n. 改革", "example": "System reformation.", "category": "科学研究"},
        {"english": "registration", "phonetic": "/ˌredʒɪˈstreɪʃn/", "chinese": "n. 注册", "example": "Event registration.", "category": "科学研究"},
        {"english": "regulation", "phonetic": "/ˌreɡjʊˈleɪʃn/", "chinese": "n. 调节", "example": "Gene regulation.", "category": "科学研究"},
        {"english": "reinforcement", "phonetic": "/ˌriːɪnˈfɔːrsmənt/", "chinese": "n. 强化", "example": "Positive reinforcement.", "category": "科学研究"},
        {"english": "rejection", "phonetic": "/rɪˈdʒekʃn/", "chinese": "n. 拒绝", "example": "Hypothesis rejection.", "category": "科学研究"},
        {"english": "reliability", "phonetic": "/rɪˌlaɪəˈbɪləti/", "chinese": "n. 可靠性", "example": "System reliability.", "category": "科学研究"},
        {"english": "remediation", "phonetic": "/rɪˌmiːdiˈeɪʃn/", "chinese": "n. 修复", "example": "Environmental remediation.", "category": "科学研究"},
        {"english": "removal", "phonetic": "/rɪˈmuːvl/", "chinese": "n. 移除", "example": "Data removal.", "category": "科学研究"},
        {"english": "reorganization", "phonetic": "/ˌriːɔːrɡənaɪˈzeɪʃn/", "chinese": "n. 重组", "example": "Corporate reorganization.", "category": "科学研究"},
        {"english": "representation", "phonetic": "/ˌreprɪzenˈteɪʃn/", "chinese": "n. 表示", "example": "Data representation.", "category": "科学研究"},
        {"english": "reproduction", "phonetic": "/ˌriːprəˈdʌkʃn/", "chinese": "n. 繁殖", "example": "Cell reproduction.", "category": "科学研究"},
        {"english": "reservation", "phonetic": "/ˌrezərˈveɪʃn/", "chinese": "n. 保留", "example": "Make reservation.", "category": "科学研究"},
        {"english": "resolution", "phonetic": "/ˌrezəˈluːʃn/", "chinese": "n. 分辨率", "example": "High resolution.", "category": "科学研究"},
        {"english": "restriction", "phonetic": "/rɪˈstrɪkʃn/", "chinese": "n. 限制", "example": "Access restriction.", "category": "科学研究"},
        {"english": "retention", "phonetic": "/rɪˈtenʃn/", "chinese": "n. 保留", "example": "Data retention.", "category": "科学研究"},
        {"english": "retrieval", "phonetic": "/rɪˈtriːvl/", "chinese": "n. 检索", "example": "Information retrieval.", "category": "科学研究"},
        {"english": "revolution", "phonetic": "/ˌrevəˈluːʃn/", "chinese": "n. 革命", "example": "Industrial revolution.", "category": "科学研究"},
        {"english": "routing", "phonetic": "/ˈruːtɪŋ/", "chinese": "n. 路由", "example": "Packet routing.", "category": "科学研究"},
        {"english": "sampling", "phonetic": "/ˈsæmplɪŋ/", "chinese": "n. 采样", "example": "Random sampling.", "category": "科学研究"},
        {"english": "scaling", "phonetic": "/ˈskeɪlɪŋ/", "chinese": "n. 缩放", "example": "System scaling.", "category": "科学研究"},
        {"english": "scheduling", "phonetic": "/ˈskedʒuːlɪŋ/", "chinese": "n. 调度", "example": "Task scheduling.", "category": "科学研究"},
        {"english": "scrutiny", "phonetic": "/ˈskruːtəni/", "chinese": "n. 审查", "example": "Public scrutiny.", "category": "科学研究"},
        {"english": "segmentation", "phonetic": "/ˌseɡmenˈteɪʃn/", "chinese": "n. 分割", "example": "Image segmentation.", "category": "科学研究"},
        {"english": "selection", "phonetic": "/sɪˈlekʃn/", "chinese": "n. 选择", "example": "Feature selection.", "category": "科学研究"},
        {"english": "sensitivity", "phonetic": "/ˌsensəˈtɪvəti/", "chinese": "n. 敏感性", "example": "Price sensitivity.", "category": "科学研究"},
        {"english": "sequencing", "phonetic": "/ˈsiːkwənsɪŋ/", "chinese": "n. 测序", "example": "DNA sequencing.", "category": "科学研究"},
        {"english": "simulation", "phonetic": "/ˌsɪmjʊˈleɪʃn/", "chinese": "n. 模拟", "example": "Computer simulation.", "category": "科学研究"},
        {"english": "simplification", "phonetic": "/ˌsɪmplɪfɪˈkeɪʃn/", "chinese": "n. 简化", "example": "Process simplification.", "category": "科学研究"},
        {"english": "specialization", "phonetic": "/ˌspeʃəlaɪˈzeɪʃn/", "chinese": "n. 专业化", "example": "Job specialization.", "category": "科学研究"},
        {"english": "specification", "phonetic": "/ˌspesɪfɪˈkeɪʃn/", "chinese": "n. 规范", "example": "Technical specification.", "category": "科学研究"},
        {"english": "stabilization", "phonetic": "/ˌsteɪbəlaɪˈzeɪʃn/", "chinese": "n. 稳定", "example": "Price stabilization.", "category": "科学研究"},
        {"english": "standardization", "phonetic": "/ˌstændərdaɪˈzeɪʃn/", "chinese": "n. 标准化", "example": "Process standardization.", "category": "科学研究"},
        {"english": "statistic", "phonetic": "/stəˈtɪstɪk/", "chinese": "n. 统计量", "example": "Test statistic.", "category": "科学研究"},
        {"english": "storage", "phonetic": "/ˈstɔːrɪdʒ/", "chinese": "n. 存储", "example": "Data storage.", "category": "科学研究"},
        {"english": "stratification", "phonetic": "/ˌstrætɪfɪˈkeɪʃn/", "chinese": "n. 分层", "example": "Social stratification.", "category": "科学研究"},
        {"english": "structuring", "phonetic": "/ˈstrʌktʃərɪŋ/", "chinese": "n. 结构化", "example": "Data structuring.", "category": "科学研究"},
        {"english": "subdivision", "phonetic": "/ˌsʌbdɪˈvɪʒn/", "chinese": "n. 细分", "example": "Land subdivision.", "category": "科学研究"},
        {"english": "substitution", "phonetic": "/ˌsʌbstɪˈtuːʃn/", "chinese": "n. 替代", "example": "Import substitution.", "category": "科学研究"},
        {"english": "summation", "phonetic": "/sʌˈmeɪʃn/", "chinese": "n. 求和", "example": "Vector summation.", "category": "科学研究"},
        {"english": "supervision", "phonetic": "/ˌsuːpərˈvɪʒn/", "chinese": "n. 监督", "example": "Clinical supervision.", "category": "科学研究"},
        {"english": "suppression", "phonetic": "/səˈpreʃn/", "chinese": "n. 抑制", "example": "Noise suppression.", "category": "科学研究"},
        {"english": "surveillance", "phonetic": "/sɜːrˈveɪləns/", "chinese": "n. 监视", "example": "Health surveillance.", "category": "科学研究"},
        {"english": "sustainability", "phonetic": "/səˌsteɪnəˈbɪləti/", "chinese": "n. 可持续性", "example": "Environmental sustainability.", "category": "科学研究"},
        {"english": "symbolization", "phonetic": "/ˌsɪmbəlaɪˈzeɪʃn/", "chinese": "n. 象征化", "example": "Data symbolization.", "category": "科学研究"},
        {"english": "synchronization", "phonetic": "/ˌsɪŋkrənaɪˈzeɪʃn/", "chinese": "n. 同步", "example": "Data synchronization.", "category": "科学研究"},
        {"english": "synthesis", "phonetic": "/ˈsɪnθəsɪs/", "chinese": "n. 合成", "example": "Protein synthesis.", "category": "科学研究"},
        {"english": "systematization", "phonetic": "/ˌsɪstəmətaɪˈzeɪʃn/", "chinese": "n. 系统化", "example": "Knowledge systematization.", "category": "科学研究"},
        {"english": "tabulation", "phonetic": "/ˌtæbjʊˈleɪʃn/", "chinese": "n. 列表", "example": "Data tabulation.", "category": "科学研究"},
        {"english": "targeting", "phonetic": "/ˈtɑːrɡɪtɪŋ/", "chinese": "n. 定位", "example": "Drug targeting.", "category": "科学研究"},
        {"english": "testing", "phonetic": "/ˈtestɪŋ/", "chinese": "n. 测试", "example": "Software testing.", "category": "科学研究"},
        {"english": "therapeutic", "phonetic": "/ˌθerəˈpjuːtɪk/", "chinese": "adj. 治疗的", "example": "Therapeutic intervention.", "category": "科学研究"},
        {"english": "transformation", "phonetic": "/ˌtrænsfərˈmeɪʃn/", "chinese": "n. 转换", "example": "Data transformation.", "category": "科学研究"},
        {"english": "transition", "phonetic": "/trænˈzɪʃn/", "chinese": "n. 过渡", "example": "Energy transition.", "category": "科学研究"},
        {"english": "translation", "phonetic": "/trænzˈleɪʃn/", "chinese": "n. 翻译", "example": "Protein translation.", "category": "科学研究"},
        {"english": "transmission", "phonetic": "/trænzˈmɪʃn/", "chinese": "n. 传输", "example": "Data transmission.", "category": "科学研究"},
        {"english": "transportation", "phonetic": "/ˌtrænspɔːrˈteɪʃn/", "chinese": "n. 运输", "example": "Public transportation.", "category": "科学研究"},
        {"english": "treatment", "phonetic": "/ˈtriːtmənt/", "chinese": "n. 治疗", "example": "Medical treatment.", "category": "科学研究"},
        {"english": "validation", "phonetic": "/ˌvælɪˈdeɪʃn/", "chinese": "n. 验证", "example": "Model validation.", "category": "科学研究"},
        {"english": "variability", "phonetic": "/ˌveriəˈbɪləti/", "chinese": "n. 变异性", "example": "Genetic variability.", "category": "科学研究"},
        {"english": "verification", "phonetic": "/ˌverɪfɪˈkeɪʃn/", "chinese": "n. 核实", "example": "Identity verification.", "category": "科学研究"},
        {"english": "visualization", "phonetic": "/ˌvɪʒuəlaɪˈzeɪʃn/", "chinese": "n. 可视化", "example": "Data visualization.", "category": "科学研究"},
        {"english": "vulnerability", "phonetic": "/ˌvʌlnərəˈbɪləti/", "chinese": "n. 脆弱性", "example": "System vulnerability.", "category": "科学研究"},
        {"english": "weighting", "phonetic": "/ˈweɪtɪŋ/", "chinese": "n. 加权", "example": "Feature weighting.", "category": "科学研究"}
    ]
    
    added_count = 0
    for word in new_words:
        cursor.execute('''
            INSERT OR IGNORE INTO words (english, phonetic, chinese, example, category, subcategory)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (word['english'], word['phonetic'], word['chinese'], word['example'], word['category'], ''))
        
        if cursor.rowcount > 0:
            added_count += 1
    
    conn.commit()
    
    cursor.execute('SELECT COUNT(*) FROM words')
    total = cursor.fetchone()[0]
    
    print(f"成功添加 {added_count} 个新单词到数据库")
    print(f"数据库总单词数: {total}")
    
    conn.close()

if __name__ == "__main__":
    expand_to_5000_batch10()
