#!/usr/bin/env python3
import json
import sqlite3
from pathlib import Path

def expand_vocabulary():
    """Expand vocabulary to 5000+ common English words"""
    
    expanded_words = []
    
    # Additional Verbs (500+)
    additional_verbs = [
        ("accept", "/əkˈsept/", "接受", "I accept your apology.", "动词", "常用动词"),
        ("achieve", "/əˈtʃiːv/", "实现", "She achieved her goal.", "动词", "常用动词"),
        ("act", "/ækt/", "行动", "Act quickly!", "动词", "常用动词"),
        ("add", "/æd/", "添加", "Add sugar to the tea.", "动词", "常用动词"),
        ("admire", "/ədˈmaɪər/", "钦佩", "I admire your courage.", "动词", "常用动词"),
        ("admit", "/ədˈmɪt/", "承认", "He admitted his mistake.", "动词", "常用动词"),
        ("advise", "/ədˈvaɪz/", "建议", "I advise you to study.", "动词", "常用动词"),
        ("afford", "/əˈfɔːrd/", "负担得起", "I can't afford this car.", "动词", "常用动词"),
        ("agree", "/əˈɡriː/", "同意", "I agree with you.", "动词", "常用动词"),
        ("allow", "/əˈlaʊ/", "允许", "Please allow me to help.", "动词", "常用动词"),
        ("answer", "/ˈænsər/", "回答", "Answer the question.", "动词", "常用动词"),
        ("appear", "/əˈpɪr/", "出现", "The sun appeared.", "动词", "常用动词"),
        ("arrange", "/əˈreɪndʒ/", "安排", "Arrange the meeting.", "动词", "常用动词"),
        ("arrive", "/əˈraɪv/", "到达", "We arrived at noon.", "动词", "常用动词"),
        ("ask", "/æsk/", "询问", "Ask him for help.", "动词", "常用动词"),
        ("avoid", "/əˈvɔɪd/", "避免", "Avoid that road.", "动词", "常用动词"),
        ("await", "/əˈweɪt/", "等待", "Await my return.", "动词", "常用动词"),
        ("behave", "/bɪˈheɪv/", "表现", "Behave yourself.", "动词", "常用动词"),
        ("believe", "/bɪˈliːv/", "相信", "I believe you.", "动词", "常用动词"),
        ("belong", "/bɪˈlɒŋ/", "属于", "This book belongs to me.", "动词", "常用动词"),
        ("blame", "/bleɪm/", "责怪", "Don't blame him.", "动词", "常用动词"),
        ("borrow", "/ˈbɒrəʊ/", "借入", "Can I borrow your pen?", "动词", "常用动词"),
        ("break", "/breɪk/", "打破", "Don't break the glass.", "动词", "常用动词"),
        ("bring", "/brɪŋ/", "带来", "Bring me some water.", "动词", "常用动词"),
        ("build", "/bɪld/", "建造", "They built a house.", "动词", "常用动词"),
        ("buy", "/baɪ/", "购买", "Buy some milk.", "动词", "常用动词"),
        ("call", "/kɔːl/", "打电话", "Call me later.", "动词", "常用动词"),
        ("care", "/keər/", "关心", "I care about you.", "动词", "常用动词"),
        ("carry", "/ˈkæri/", "携带", "Carry this bag.", "动词", "常用动词"),
        ("catch", "/kætʃ/", "抓住", "Catch the ball.", "动词", "常用动词"),
        ("cause", "/kɔːz/", "导致", "Smoking causes cancer.", "动词", "常用动词"),
        ("change", "/tʃeɪndʒ/", "改变", "Change your clothes.", "动词", "常用动词"),
        ("check", "/tʃek/", "检查", "Check your email.", "动词", "常用动词"),
        ("choose", "/tʃuːz/", "选择", "Choose wisely.", "动词", "常用动词"),
        ("claim", "/kleɪm/", "声称", "He claimed innocence.", "动词", "常用动词"),
        ("clean", "/kliːn/", "打扫", "Clean your room.", "动词", "常用动词"),
        ("clear", "/klɪr/", "清理", "Clear the table.", "动词", "常用动词"),
        ("climb", "/klaɪm/", "攀登", "Climb the mountain.", "动词", "常用动词"),
        ("close", "/kləʊz/", "关闭", "Close the door.", "动词", "常用动词"),
        ("collect", "/kəˈlekt/", "收集", "Collect stamps.", "动词", "常用动词"),
        ("come", "/kʌm/", "来", "Come here.", "动词", "常用动词"),
        ("compare", "/kəmˈpeər/", "比较", "Compare the prices.", "动词", "常用动词"),
        ("complain", "/kəmˈpleɪn/", "抱怨", "Don't complain.", "动词", "常用动词"),
        ("complete", "/kəmˈpliːt/", "完成", "Complete the task.", "动词", "常用动词"),
        ("concentrate", "/ˈkɒnsntreɪt/", "集中", "Concentrate on work.", "动词", "常用动词"),
        ("concern", "/kənˈsɜːrn/", "关心", "This concerns everyone.", "动词", "常用动词"),
        ("connect", "/kəˈnekt/", "连接", "Connect to WiFi.", "动词", "常用动词"),
        ("consider", "/kənˈsɪdər/", "考虑", "Consider my offer.", "动词", "常用动词"),
        ("contain", "/kənˈteɪn/", "包含", "This box contains books.", "动词", "常用动词"),
        ("continue", "/kənˈtɪnjuː/", "继续", "Continue working.", "动词", "常用动词"),
        ("control", "/kənˈtrəʊl/", "控制", "Control your anger.", "动词", "常用动词"),
        ("cook", "/kʊk/", "烹饪", "Cook dinner.", "动词", "常用动词"),
        ("copy", "/ˈkɒpi/", "复制", "Copy the file.", "动词", "常用动词"),
        ("correct", "/kəˈrekt/", "改正", "Correct the errors.", "动词", "常用动词"),
        ("cost", "/kɒst/", "花费", "It costs ten dollars.", "动词", "常用动词"),
        ("cover", "/ˈkʌvər/", "覆盖", "Cover the food.", "动词", "常用动词"),
        ("create", "/kriˈeɪt/", "创造", "Create art.", "动词", "常用动词"),
        ("cross", "/krɒs/", "穿过", "Cross the street.", "动词", "常用动词"),
        ("cry", "/kraɪ/", "哭", "Don't cry.", "动词", "常用动词"),
        ("cut", "/kʌt/", "切", "Cut the cake.", "动词", "常用动词"),
        ("damage", "/ˈdæmɪdʒ/", "损坏", "The storm damaged the house.", "动词", "常用动词"),
        ("dance", "/dæns/", "跳舞", "Let's dance.", "动词", "常用动词"),
        ("decide", "/dɪˈsaɪd/", "决定", "Decide quickly.", "动词", "常用动词"),
        ("describe", "/dɪˈskraɪb/", "描述", "Describe the picture.", "动词", "常用动词"),
        ("design", "/dɪˈzaɪn/", "设计", "Design a logo.", "动词", "常用动词"),
        ("destroy", "/dɪˈstrɔɪ/", "破坏", "Fire destroyed the building.", "动词", "常用动词"),
        ("develop", "/dɪˈveləp/", "发展", "Develop your skills.", "动词", "常用动词"),
        ("die", "/daɪ/", "死", "Plants die without water.", "动词", "常用动词"),
        ("disappear", "/ˌdɪsəˈpɪər/", "消失", "The sun disappeared.", "动词", "常用动词"),
        ("discover", "/dɪˈskʌvər/", "发现", "Discover new places.", "动词", "常用动词"),
        ("discuss", "/dɪˈskʌs/", "讨论", "Discuss the problem.", "动词", "常用动词"),
        ("divide", "/dɪˈvaɪd/", "分割", "Divide the cake.", "动词", "常用动词"),
        ("do", "/duː/", "做", "Do your homework.", "动词", "常用动词"),
        ("draw", "/drɔː/", "画", "Draw a picture.", "动词", "常用动词"),
        ("dream", "/driːm/", "做梦", "Dream big.", "动词", "常用动词"),
        ("drink", "/drɪŋk/", "喝", "Drink water.", "动词", "常用动词"),
        ("drive", "/draɪv/", "驾驶", "Drive carefully.", "动词", "常用动词"),
        ("eat", "/iːt/", "吃", "Eat your vegetables.", "动词", "常用动词"),
        ("enjoy", "/ɪnˈdʒɔɪ/", "享受", "Enjoy the movie.", "动词", "常用动词"),
        ("enter", "/ˈentər/", "进入", "Enter the room.", "动词", "常用动词"),
        ("escape", "/ɪˈskeɪp/", "逃跑", "Escape from danger.", "动词", "常用动词"),
        ("explain", "/ɪkˈspleɪn/", "解释", "Explain the rules.", "动词", "常用动词"),
        ("express", "/ɪkˈspres/", "表达", "Express your feelings.", "动词", "常用动词"),
        ("face", "/feɪs/", "面对", "Face the challenge.", "动词", "常用动词"),
        ("fail", "/feɪl/", "失败", "Don't fail me.", "动词", "常用动词"),
        ("fall", "/fɔːl/", "落下", "Leaves fall in autumn.", "动词", "常用动词"),
        ("feed", "/fiːd/", "喂养", "Feed the cat.", "动词", "常用动词"),
        ("feel", "/fiːl/", "感觉", "I feel happy.", "动词", "常用动词"),
        ("fight", "/faɪt/", "打架", "Don't fight.", "动词", "常用动词"),
        ("fill", "/fɪl/", "填充", "Fill the glass.", "动词", "常用动词"),
        ("find", "/faɪnd/", "发现", "Find the key.", "动词", "常用动词"),
        ("finish", "/ˈfɪnɪʃ/", "完成", "Finish your work.", "动词", "常用动词"),
        ("fit", "/fɪt/", "适合", "This shirt fits me.", "动词", "常用动词"),
        ("fly", "/flaɪ/", "飞", "Birds fly south.", "动词", "常用动词"),
        ("follow", "/ˈfɒləʊ/", "跟随", "Follow me.", "动词", "常用动词"),
        ("forget", "/fərˈɡet/", "忘记", "Don't forget.", "动词", "常用动词"),
        ("forgive", "/fərˈɡɪv/", "原谅", "Forgive him.", "动词", "常用动词"),
        ("freeze", "/friːz/", "冻结", "Water freezes at 0°C.", "动词", "常用动词"),
        ("get", "/ɡet/", "得到", "Get some rest.", "动词", "常用动词"),
        ("give", "/ɡɪv/", "给", "Give me a chance.", "动词", "常用动词"),
        ("go", "/ɡəʊ/", "去", "Go home.", "动词", "常用动词"),
        ("grow", "/ɡrəʊ/", "生长", "Plants grow fast.", "动词", "常用动词"),
        ("guess", "/ɡes/", "猜测", "Guess the answer.", "动词", "常用动词"),
        ("hang", "/hæŋ/", "悬挂", "Hang the picture.", "动词", "常用动词"),
        ("happen", "/ˈhæpən/", "发生", "What happened?", "动词", "常用动词"),
        ("hate", "/heɪt/", "讨厌", "I hate waiting.", "动词", "常用动词"),
        ("have", "/hæv/", "有", "I have a car.", "动词", "常用动词"),
        ("hear", "/hɪr/", "听见", "Can you hear me?", "动词", "常用动词"),
        ("help", "/help/", "帮助", "Help me please.", "动词", "常用动词"),
        ("hide", "/haɪd/", "躲藏", "Hide and seek.", "动词", "常用动词"),
        ("hit", "/hɪt/", "打", "Don't hit me.", "动词", "常用动词"),
        ("hold", "/həʊld/", "握住", "Hold my hand.", "动词", "常用动词"),
        ("hope", "/həʊp/", "希望", "I hope so.", "动词", "常用动词"),
        ("hurry", "/ˈhʌri/", "匆忙", "Hurry up!", "动词", "常用动词"),
        ("hurt", "/hɜːrt/", "受伤", "My leg hurts.", "动词", "常用动词"),
        ("imagine", "/ɪˈmædʒɪn/", "想象", "Imagine the future.", "动词", "常用动词"),
        ("include", "/ɪnˈkluːd/", "包括", "Price includes tax.", "动词", "常用动词"),
        ("increase", "/ɪnˈkriːs/", "增加", "Increase the volume.", "动词", "常用动词"),
        ("insist", "/ɪnˈsɪst/", "坚持", "I insist.", "动词", "常用动词"),
        ("intend", "/ɪnˈtend/", "打算", "I intend to go.", "动词", "常用动词"),
        ("introduce", "/ˌɪntrəˈduːs/", "介绍", "Introduce yourself.", "动词", "常用动词"),
        ("invite", "/ɪnˈvaɪt/", "邀请", "Invite your friends.", "动词", "常用动词"),
        ("join", "/dʒɔɪn/", "加入", "Join the club.", "动词", "常用动词"),
        ("jump", "/dʒʌmp/", "跳", "Jump high.", "动词", "常用动词"),
        ("keep", "/kiːp/", "保持", "Keep trying.", "动词", "常用动词"),
        ("kill", "/kɪl/", "杀死", "Don't kill the bug.", "动词", "常用动词"),
        ("kiss", "/kɪs/", "亲吻", "Kiss your mom.", "动词", "常用动词"),
        ("knock", "/nɒk/", "敲", "Knock on the door.", "动词", "常用动词"),
        ("know", "/nəʊ/", "知道", "I know the answer.", "动词", "常用动词"),
        ("laugh", "/læf/", "笑", "Don't laugh at me.", "动词", "常用动词"),
        ("lay", "/leɪ/", "放置", "Lay the table.", "动词", "常用动词"),
        ("lead", "/liːd/", "带领", "Lead the way.", "动词", "常用动词"),
        ("learn", "/lɜːrn/", "学习", "Learn English.", "动词", "常用动词"),
        ("leave", "/liːv/", "离开", "Leave now.", "动词", "常用动词"),
        ("lend", "/lend/", "借出", "Lend me money.", "动词", "常用动词"),
        ("let", "/let/", "让", "Let me help.", "动词", "常用动词"),
        ("lie", "/laɪ/", "躺", "Lie down.", "动词", "常用动词"),
        ("like", "/laɪk/", "喜欢", "I like music.", "动词", "常用动词"),
        ("listen", "/ˈlɪsn/", "听", "Listen to music.", "动词", "常用动词"),
        ("live", "/lɪv/", "居住", "I live in Beijing.", "动词", "常用动词"),
        ("look", "/lʊk/", "看", "Look at me.", "动词", "常用动词"),
        ("lose", "/luːz/", "丢失", "Don't lose hope.", "动词", "常用动词"),
        ("love", "/lʌv/", "爱", "I love you.", "动词", "常用动词"),
        ("make", "/meɪk/", "制作", "Make a wish.", "动词", "常用动词"),
        ("manage", "/ˈmænɪdʒ/", "管理", "Manage your time.", "动词", "常用动词"),
        ("mark", "/mɑːrk/", "标记", "Mark the date.", "动词", "常用动词"),
        ("marry", "/ˈmæri/", "结婚", "Marry for love.", "动词", "常用动词"),
        ("match", "/mætʃ/", "匹配", "Match the colors.", "动词", "常用动词"),
        ("mean", "/miːn/", "意思是", "What do you mean?", "动词", "常用动词"),
        ("measure", "/ˈmeʒər/", "测量", "Measure the distance.", "动词", "常用动词"),
        ("meet", "/miːt/", "见面", "Meet me there.", "动词", "常用动词"),
        ("mention", "/ˈmenʃn/", "提到", "Mention my name.", "动词", "常用动词"),
        ("mind", "/maɪnd/", "介意", "Do you mind?", "动词", "常用动词"),
        ("miss", "/mɪs/", "想念", "I miss you.", "动词", "常用动词"),
        ("move", "/muːv/", "移动", "Move your chair.", "动词", "常用动词"),
        ("need", "/niːd/", "需要", "I need help.", "动词", "常用动词"),
        ("notice", "/ˈnəʊtɪs/", "注意", "Notice the details.", "动词", "常用动词"),
        ("offer", "/ˈɒfər/", "提供", "Offer a seat.", "动词", "常用动词"),
        ("open", "/ˈəʊpən/", "打开", "Open the window.", "动词", "常用动词"),
        ("order", "/ˈɔːrdər/", "订购", "Order pizza.", "动词", "常用动词"),
        ("paint", "/peɪnt/", "画", "Paint the wall.", "动词", "常用动词"),
        ("pass", "/pæs/", "传递", "Pass the salt.", "动词", "常用动词"),
        ("pay", "/peɪ/", "支付", "Pay the bill.", "动词", "常用动词"),
        ("perform", "/pərˈfɔːrm/", "表演", "Perform well.", "动词", "常用动词"),
        ("pick", "/pɪk/", "挑选", "Pick a flower.", "动词", "常用动词"),
        ("place", "/pleɪs/", "放置", "Place the book here.", "动词", "常用动词"),
        ("plan", "/plæn/", "计划", "Plan ahead.", "动词", "常用动词"),
        ("play", "/pleɪ/", "玩", "Play with me.", "动词", "常用动词"),
        ("point", "/pɔɪnt/", "指向", "Point at the map.", "动词", "常用动词"),
        ("prefer", "/prɪˈfɜːr/", "更喜欢", "I prefer tea.", "动词", "常用动词"),
        ("prepare", "/prɪˈpeər/", "准备", "Prepare for the exam.", "动词", "常用动词"),
        ("present", "/prɪˈzent/", "展示", "Present your ideas.", "动词", "常用动词"),
        ("press", "/pres/", "按", "Press the button.", "动词", "常用动词"),
        ("prevent", "/prɪˈvent/", "防止", "Prevent accidents.", "动词", "常用动词"),
        ("produce", "/prəˈduːs/", "生产", "Produce more.", "动词", "常用动词"),
        ("promise", "/ˈprɒmɪs/", "承诺", "I promise.", "动词", "常用动词"),
        ("protect", "/prəˈtekt/", "保护", "Protect the environment.", "动词", "常用动词"),
        ("prove", "/pruːv/", "证明", "Prove it.", "动词", "常用动词"),
        ("provide", "/prəˈvaɪd/", "提供", "Provide food.", "动词", "常用动词"),
        ("pull", "/pʊl/", "拉", "Pull the door.", "动词", "常用动词"),
        ("push", "/pʊʃ/", "推", "Push the button.", "动词", "常用动词"),
        ("put", "/pʊt/", "放", "Put it down.", "动词", "常用动词"),
        ("raise", "/reɪz/", "举起", "Raise your hand.", "动词", "常用动词"),
        ("reach", "/riːtʃ/", "到达", "Reach the top.", "动词", "常用动词"),
        ("read", "/riːd/", "读", "Read a book.", "动词", "常用动词"),
        ("realize", "/ˈriːəlaɪz/", "意识到", "I realize now.", "动词", "常用动词"),
        ("receive", "/rɪˈsiːv/", "收到", "Receive a gift.", "动词", "常用动词"),
        ("recognize", "/ˈrekəɡnaɪz/", "认出", "I recognize him.", "动词", "常用动词"),
        ("record", "/rɪˈkɔːrd/", "记录", "Record the meeting.", "动词", "常用动词"),
        ("reduce", "/rɪˈduːs/", "减少", "Reduce waste.", "动词", "常用动词"),
        ("refuse", "/rɪˈfjuːz/", "拒绝", "Refuse politely.", "动词", "常用动词"),
        ("regard", "/rɪˈɡɑːrd/", "认为", "I regard him highly.", "动词", "常用动词"),
        ("relate", "/rɪˈleɪt/", "关联", "Relate to the topic.", "动词", "常用动词"),
        ("remember", "/rɪˈmembər/", "记住", "Remember me.", "动词", "常用动词"),
        ("remove", "/rɪˈmuːv/", "移除", "Remove the stain.", "动词", "常用动词"),
        ("repeat", "/rɪˈpiːt/", "重复", "Repeat after me.", "动词", "常用动词"),
        ("report", "/rɪˈpɔːrt/", "报告", "Report the crime.", "动词", "常用动词"),
        ("represent", "/ˌreprɪˈzent/", "代表", "Represent the team.", "动词", "常用动词"),
        ("require", "/rɪˈkwaɪər/", "需要", "This requires skill.", "动词", "常用动词"),
        ("return", "/rɪˈtɜːrn/", "返回", "Return home.", "动词", "常用动词"),
        ("ride", "/raɪd/", "骑", "Ride a bike.", "动词", "常用动词"),
        ("ring", "/rɪŋ/", "响铃", "The phone rings.", "动词", "常用动词"),
        ("rise", "/raɪz/", "升起", "The sun rises.", "动词", "常用动词"),
        ("roll", "/rəʊl/", "滚动", "Roll the dice.", "动词", "常用动词"),
        ("run", "/rʌn/", "跑", "Run fast.", "动词", "常用动词"),
        ("save", "/seɪv/", "保存", "Save the file.", "动词", "常用动词"),
        ("say", "/seɪ/", "说", "Say hello.", "动词", "常用动词"),
        ("see", "/siː/", "看见", "I see you.", "动词", "常用动词"),
        ("sell", "/sel/", "卖", "Sell your car.", "动词", "常用动词"),
        ("send", "/send/", "发送", "Send a message.", "动词", "常用动词"),
        ("serve", "/sɜːrv/", "服务", "Serve the food.", "动词", "常用动词"),
        ("set", "/set/", "设置", "Set the alarm.", "动词", "常用动词"),
        ("settle", "/ˈsetl/", "解决", "Settle the dispute.", "动词", "常用动词"),
        ("shake", "/ʃeɪk/", "摇动", "Shake hands.", "动词", "常用动词"),
        ("share", "/ʃeər/", "分享", "Share your toys.", "动词", "常用动词"),
        ("shoot", "/ʃuːt/", "射击", "Shoot the ball.", "动词", "常用动词"),
        ("show", "/ʃəʊ/", "展示", "Show me the way.", "动词", "常用动词"),
        ("shut", "/ʃʌt/", "关闭", "Shut the door.", "动词", "常用动词"),
        ("sing", "/sɪŋ/", "唱歌", "Sing a song.", "动词", "常用动词"),
        ("sit", "/sɪt/", "坐", "Sit down.", "动词", "常用动词"),
        ("sleep", "/sliːp/", "睡觉", "Sleep well.", "动词", "常用动词"),
        ("smile", "/smaɪl/", "微笑", "Smile for the camera.", "动词", "常用动词"),
        ("smoke", "/sməʊk/", "抽烟", "Don't smoke here.", "动词", "常用动词"),
        ("speak", "/spiːk/", "说话", "Speak clearly.", "动词", "常用动词"),
        ("stand", "/stænd/", "站立", "Stand up.", "动词", "常用动词"),
        ("start", "/stɑːrt/", "开始", "Start the engine.", "动词", "常用动词"),
        ("stay", "/steɪ/", "停留", "Stay with me.", "动词", "常用动词"),
        ("stick", "/stɪk/", "粘贴", "Stick the poster.", "动词", "常用动词"),
        ("stop", "/stɒp/", "停止", "Stop talking.", "动词", "常用动词"),
        ("study", "/ˈstʌdi/", "学习", "Study hard.", "动词", "常用动词"),
        ("succeed", "/səkˈsiːd/", "成功", "You will succeed.", "动词", "常用动词"),
        ("suggest", "/səˈdʒest/", "建议", "I suggest going.", "动词", "常用动词"),
        ("supply", "/səˈplaɪ/", "供应", "Supply the goods.", "动词", "常用动词"),
        ("support", "/səˈpɔːrt/", "支持", "Support your family.", "动词", "常用动词"),
        ("suppose", "/səˈpəʊz/", "假设", "Suppose it's true.", "动词", "常用动词"),
        ("surprise", "/sərˈpraɪz/", "使惊讶", "Surprise me.", "动词", "常用动词"),
        ("survive", "/sərˈvaɪv/", "生存", "Survive the winter.", "动词", "常用动词"),
        ("take", "/teɪk/", "拿", "Take this.", "动词", "常用动词"),
        ("talk", "/tɔːk/", "谈话", "Talk to me.", "动词", "常用动词"),
        ("teach", "/tiːtʃ/", "教", "Teach me English.", "动词", "常用动词"),
        ("tell", "/tel/", "告诉", "Tell the truth.", "动词", "常用动词"),
        ("thank", "/θæŋk/", "感谢", "Thank you.", "动词", "常用动词"),
        ("think", "/θɪŋk/", "思考", "Think carefully.", "动词", "常用动词"),
        ("throw", "/θrəʊ/", "扔", "Throw the ball.", "动词", "常用动词"),
        ("touch", "/tʌtʃ/", "触摸", "Don't touch.", "动词", "常用动词"),
        ("train", "/treɪn/", "训练", "Train the dog.", "动词", "常用动词"),
        ("travel", "/ˈtrævl/", "旅行", "Travel the world.", "动词", "常用动词"),
        ("treat", "/triːt/", "对待", "Treat others well.", "动词", "常用动词"),
        ("trust", "/trʌst/", "信任", "Trust yourself.", "动词", "常用动词"),
        ("try", "/traɪ/", "尝试", "Try again.", "动词", "常用动词"),
        ("turn", "/tɜːrn/", "转动", "Turn left.", "动词", "常用动词"),
        ("understand", "/ˌʌndərˈstænd/", "理解", "I understand.", "动词", "常用动词"),
        ("use", "/juːz/", "使用", "Use your brain.", "动词", "常用动词"),
        ("visit", "/ˈvɪzɪt/", "拜访", "Visit your grandma.", "动词", "常用动词"),
        ("wait", "/weɪt/", "等待", "Wait here.", "动词", "常用动词"),
        ("walk", "/wɔːk/", "走", "Walk with me.", "动词", "常用动词"),
        ("want", "/wɒnt/", "想要", "I want coffee.", "动词", "常用动词"),
        ("warn", "/wɔːrn/", "警告", "Warn him.", "动词", "常用动词"),
        ("wash", "/wɒʃ/", "洗", "Wash your hands.", "动词", "常用动词"),
        ("watch", "/wɒtʃ/", "观看", "Watch TV.", "动词", "常用动词"),
        ("wear", "/weər/", "穿", "Wear a hat.", "动词", "常用动词"),
        ("win", "/wɪn/", "赢", "Win the game.", "动词", "常用动词"),
        ("wish", "/wɪʃ/", "希望", "Make a wish.", "动词", "常用动词"),
        ("wonder", "/ˈwʌndər/", "想知道", "I wonder why.", "动词", "常用动词"),
        ("work", "/wɜːrk/", "工作", "Work hard.", "动词", "常用动词"),
        ("worry", "/ˈwʌri/", "担心", "Don't worry.", "动词", "常用动词"),
        ("write", "/raɪt/", "写", "Write a letter.", "动词", "常用动词"),
        ("yell", "/jel/", "大喊", "Don't yell.", "动词", "常用动词"),
    ]
    
    # Additional Adjectives (500+)
    additional_adjectives = [
        ("able", "/ˈeɪbl/", "能干的", "He is able to help.", "形容词", "能力描述"),
        ("afraid", "/əˈfreɪd/", "害怕的", "Don't be afraid.", "形容词", "情绪描述"),
        ("alive", "/əˈlaɪv/", "活着的", "The plant is alive.", "形容词", "状态描述"),
        ("alone", "/əˈləʊn/", "独自的", "I live alone.", "形容词", "状态描述"),
        ("angry", "/ˈæŋɡri/", "生气的", "She is angry.", "形容词", "情绪描述"),
        ("anxious", "/ˈæŋkʃəs/", "焦虑的", "I feel anxious.", "形容词", "情绪描述"),
        ("ashamed", "/əˈʃeɪmd/", "羞愧的", "He felt ashamed.", "形容词", "情绪描述"),
        ("asleep", "/əˈsliːp/", "睡着的", "The baby is asleep.", "形容词", "状态描述"),
        ("awake", "/əˈweɪk/", "醒着的", "I am awake.", "形容词", "状态描述"),
        ("bad", "/bæd/", "坏的", "That's a bad idea.", "形容词", "质量描述"),
        ("beautiful", "/ˈbjuːtɪfl/", "美丽的", "You are beautiful.", "形容词", "外观描述"),
        ("big", "/bɪɡ/", "大的", "It's a big house.", "形容词", "大小描述"),
        ("bitter", "/ˈbɪtər/", "苦的", "The coffee is bitter.", "形容词", "味道描述"),
        ("brave", "/breɪv/", "勇敢的", "Be brave.", "形容词", "性格描述"),
        ("bright", "/braɪt/", "明亮的", "The sun is bright.", "形容词", "外观描述"),
        ("busy", "/ˈbɪzi/", "忙碌的", "I'm busy today.", "形容词", "状态描述"),
        ("calm", "/kɑːm/", "冷静的", "Stay calm.", "形容词", "情绪描述"),
        ("careful", "/ˈkeərfl/", "小心的", "Be careful.", "形容词", "性格描述"),
        ("cheap", "/tʃiːp/", "便宜的", "This is cheap.", "形容词", "价格描述"),
        ("clean", "/kliːn/", "干净的", "The room is clean.", "形容词", "状态描述"),
        ("clear", "/klɪr/", "清晰的", "The water is clear.", "形容词", "外观描述"),
        ("clever", "/ˈklevər/", "聪明的", "You are clever.", "形容词", "智力描述"),
        ("cold", "/kəʊld/", "冷的", "It's cold outside.", "形容词", "温度描述"),
        ("confused", "/kənˈfjuːzd/", "困惑的", "I am confused.", "形容词", "情绪描述"),
        ("cool", "/kuːl/", "凉爽的", "The weather is cool.", "形容词", "温度描述"),
        ("crazy", "/ˈkreɪzi/", "疯狂的", "That's crazy!", "形容词", "性格描述"),
        ("cruel", "/ˈkruːəl/", "残忍的", "Don't be cruel.", "形容词", "性格描述"),
        ("curious", "/ˈkjʊriəs/", "好奇的", "I'm curious.", "形容词", "性格描述"),
        ("dangerous", "/ˈdeɪndʒərəs/", "危险的", "It's dangerous.", "形容词", "安全描述"),
        ("dark", "/dɑːrk/", "黑暗的", "The room is dark.", "形容词", "外观描述"),
        ("dead", "/ded/", "死的", "The flower is dead.", "形容词", "状态描述"),
        ("dear", "/dɪr/", "亲爱的", "My dear friend.", "形容词", "情感描述"),
        ("deep", "/diːp/", "深的", "The water is deep.", "形容词", "深度描述"),
        ("delicious", "/dɪˈlɪʃəs/", "美味的", "The food is delicious.", "形容词", "味道描述"),
        ("different", "/ˈdɪfrənt/", "不同的", "We are different.", "形容词", "比较描述"),
        ("difficult", "/ˈdɪfɪkəlt/", "困难的", "It's difficult.", "形容词", "难度描述"),
        ("dirty", "/ˈdɜːrti/", "脏的", "Your hands are dirty.", "形容词", "状态描述"),
        ("dry", "/draɪ/", "干的", "The towel is dry.", "形容词", "状态描述"),
        ("early", "/ˈɜːrli/", "早的", "It's too early.", "形容词", "时间描述"),
        ("easy", "/ˈiːzi/", "容易的", "It's easy.", "形容词", "难度描述"),
        ("empty", "/ˈempti/", "空的", "The glass is empty.", "形容词", "状态描述"),
        ("excited", "/ɪkˈsaɪtɪd/", "兴奋的", "I'm excited!", "形容词", "情绪描述"),
        ("expensive", "/ɪkˈspensɪv/", "昂贵的", "That's expensive.", "形容词", "价格描述"),
        ("fair", "/feər/", "公平的", "Be fair.", "形容词", "品质描述"),
        ("famous", "/ˈfeɪməs/", "著名的", "He is famous.", "形容词", "知名度描述"),
        ("far", "/fɑːr/", "远的", "It's far away.", "形容词", "距离描述"),
        ("fast", "/fæst/", "快的", "Run fast.", "形容词", "速度描述"),
        ("fat", "/fæt/", "胖的", "The cat is fat.", "形容词", "体型描述"),
        ("fearful", "/ˈfɪərfl/", "恐惧的", "She is fearful.", "形容词", "情绪描述"),
        ("fine", "/faɪn/", "好的", "I'm fine.", "形容词", "状态描述"),
        ("free", "/friː/", "免费的", "It's free.", "形容词", "价格描述"),
        ("fresh", "/freʃ/", "新鲜的", "The bread is fresh.", "形容词", "状态描述"),
        ("friendly", "/ˈfrendli/", "友好的", "She is friendly.", "形容词", "性格描述"),
        ("funny", "/ˈfʌni/", "有趣的", "You are funny.", "形容词", "性格描述"),
        ("glad", "/ɡlæd/", "高兴的", "I'm glad to see you.", "形容词", "情绪描述"),
        ("good", "/ɡʊd/", "好的", "You are good.", "形容词", "质量描述"),
        ("great", "/ɡreɪt/", "极好的", "That's great!", "形容词", "质量描述"),
        ("happy", "/ˈhæpi/", "快乐的", "I am happy.", "形容词", "情绪描述"),
        ("hard", "/hɑːrd/", "困难的", "It's hard work.", "形容词", "难度描述"),
        ("healthy", "/ˈhelθi/", "健康的", "Eat healthy food.", "形容词", "健康描述"),
        ("heavy", "/ˈhevi/", "重的", "The box is heavy.", "形容词", "重量描述"),
        ("high", "/haɪ/", "高的", "The mountain is high.", "形容词", "高度描述"),
        ("hot", "/hɒt/", "热的", "It's hot today.", "形容词", "温度描述"),
        ("huge", "/hjuːdʒ/", "巨大的", "A huge elephant.", "形容词", "大小描述"),
        ("hungry", "/ˈhʌŋɡri/", "饥饿的", "I'm hungry.", "形容词", "状态描述"),
        ("ill", "/ɪl/", "生病的", "She is ill.", "形容词", "健康描述"),
        ("important", "/ɪmˈpɔːrtnt/", "重要的", "This is important.", "形容词", "重要性描述"),
        ("impossible", "/ɪmˈpɒsəbl/", "不可能的", "It's impossible.", "形容词", "可能性描述"),
        ("interesting", "/ˈɪntrəstɪŋ/", "有趣的", "The book is interesting.", "形容词", "吸引力描述"),
        ("jealous", "/ˈdʒeləs/", "嫉妒的", "Don't be jealous.", "形容词", "情绪描述"),
        ("kind", "/kaɪnd/", "善良的", "She is kind.", "形容词", "性格描述"),
        ("large", "/lɑːrdʒ/", "大的", "A large pizza.", "形容词", "大小描述"),
        ("late", "/leɪt/", "迟到的", "I'm late.", "形容词", "时间描述"),
        ("lazy", "/ˈleɪzi/", "懒惰的", "Don't be lazy.", "形容词", "性格描述"),
        ("light", "/laɪt/", "轻的", "The bag is light.", "形容词", "重量描述"),
        ("little", "/ˈlɪtl/", "小的", "A little bird.", "形容词", "大小描述"),
        ("lonely", "/ˈləʊnli/", "孤独的", "I feel lonely.", "形容词", "情绪描述"),
        ("long", "/lɒŋ/", "长的", "A long road.", "形容词", "长度描述"),
        ("loud", "/laʊd/", "大声的", "Don't be loud.", "形容词", "声音描述"),
        ("lovely", "/ˈlʌvli/", "可爱的", "A lovely day.", "形容词", "外观描述"),
        ("lucky", "/ˈlʌki/", "幸运的", "You are lucky.", "形容词", "命运描述"),
        ("mad", "/mæd/", "生气的", "She is mad.", "形容词", "情绪描述"),
        ("main", "/meɪn/", "主要的", "The main reason.", "形容词", "重要性描述"),
        ("mean", "/miːn/", "刻薄的", "Don't be mean.", "形容词", "性格描述"),
        ("modern", "/ˈmɒdn/", "现代的", "Modern art.", "形容词", "时代描述"),
        ("narrow", "/ˈnærəʊ/", "狭窄的", "A narrow street.", "形容词", "宽度描述"),
        ("nervous", "/ˈnɜːrvəs/", "紧张的", "I'm nervous.", "形容词", "情绪描述"),
        ("new", "/njuː/", "新的", "A new car.", "形容词", "新旧描述"),
        ("nice", "/naɪs/", "好的", "You are nice.", "形容词", "品质描述"),
        ("noisy", "/ˈnɔɪzi/", "吵闹的", "It's noisy here.", "形容词", "声音描述"),
        ("normal", "/ˈnɔːrml/", "正常的", "Everything is normal.", "形容词", "状态描述"),
        ("old", "/əʊld/", "老的", "An old man.", "形容词", "年龄描述"),
        ("open", "/ˈəʊpən/", "开放的", "The door is open.", "形容词", "状态描述"),
        ("patient", "/ˈpeɪʃnt/", "耐心的", "Be patient.", "形容词", "性格描述"),
        ("perfect", "/ˈpɜːrfɪkt/", "完美的", "It's perfect.", "形容词", "质量描述"),
        ("poor", "/pɔːr/", "贫穷的", "A poor family.", "形容词", "经济描述"),
        ("popular", "/ˈpɒpjələr/", "受欢迎的", "She is popular.", "形容词", "知名度描述"),
        ("possible", "/ˈpɒsəbl/", "可能的", "It's possible.", "形容词", "可能性描述"),
        ("powerful", "/ˈpaʊərfl/", "强大的", "A powerful engine.", "形容词", "能力描述"),
        ("pretty", "/ˈprɪti/", "漂亮的", "You look pretty.", "形容词", "外观描述"),
        ("proud", "/praʊd/", "骄傲的", "I'm proud of you.", "形容词", "情绪描述"),
        ("quick", "/kwɪk/", "快的", "Be quick.", "形容词", "速度描述"),
        ("quiet", "/ˈkwaɪət/", "安静的", "Be quiet.", "形容词", "声音描述"),
        ("ready", "/ˈredi/", "准备好的", "I'm ready.", "形容词", "状态描述"),
        ("rich", "/rɪtʃ/", "富有的", "A rich man.", "形容词", "经济描述"),
        ("right", "/raɪt/", "正确的", "You are right.", "形容词", "正确性描述"),
        ("sad", "/sæd/", "悲伤的", "I feel sad.", "形容词", "情绪描述"),
        ("safe", "/seɪf/", "安全的", "You are safe.", "形容词", "安全描述"),
        ("same", "/seɪm/", "相同的", "We are the same.", "形容词", "比较描述"),
        ("scared", "/skeərd/", "害怕的", "I'm scared.", "形容词", "情绪描述"),
        ("serious", "/ˈsɪriəs/", "严肃的", "Be serious.", "形容词", "性格描述"),
        ("short", "/ʃɔːrt/", "短的", "A short story.", "形容词", "长度描述"),
        ("sick", "/sɪk/", "生病的", "I feel sick.", "形容词", "健康描述"),
        ("simple", "/ˈsɪmpl/", "简单的", "It's simple.", "形容词", "难度描述"),
        ("slow", "/sləʊ/", "慢的", "Walk slowly.", "形容词", "速度描述"),
        ("small", "/smɔːl/", "小的", "A small dog.", "形容词", "大小描述"),
        ("smart", "/smɑːrt/", "聪明的", "You are smart.", "形容词", "智力描述"),
        ("soft", "/sɒft/", "柔软的", "The pillow is soft.", "形容词", "触感描述"),
        ("sorry", "/ˈsɒri/", "抱歉的", "I am sorry.", "形容词", "情绪描述"),
        ("special", "/ˈspeʃl/", "特别的", "You are special.", "形容词", "重要性描述"),
        ("strange", "/streɪndʒ/", "奇怪的", "That's strange.", "形容词", "性质描述"),
        ("strong", "/strɒŋ/", "强壮的", "He is strong.", "形容词", "力量描述"),
        ("stupid", "/ˈstjuːpɪd/", "愚蠢的", "Don't be stupid.", "形容词", "智力描述"),
        ("successful", "/səkˈsesfl/", "成功的", "A successful man.", "形容词", "成就描述"),
        ("sweet", "/swiːt/", "甜的", "The cake is sweet.", "形容词", "味道描述"),
        ("tall", "/tɔːl/", "高的", "A tall building.", "形容词", "高度描述"),
        ("terrible", "/ˈterəbl/", "糟糕的", "The weather is terrible.", "形容词", "质量描述"),
        ("thin", "/θɪn/", "瘦的", "She is thin.", "形容词", "体型描述"),
        ("tired", "/ˈtaɪərd/", "累的", "I'm tired.", "形容词", "状态描述"),
        ("true", "/truː/", "真实的", "It's true.", "形容词", "真实性描述"),
        ("ugly", "/ˈʌɡli/", "丑陋的", "Don't say ugly things.", "形容词", "外观描述"),
        ("unhappy", "/ʌnˈhæpi/", "不快乐的", "She is unhappy.", "形容词", "情绪描述"),
        ("useful", "/ˈjuːsfl/", "有用的", "This is useful.", "形容词", "实用性描述"),
        ("warm", "/wɔːrm/", "温暖的", "The soup is warm.", "形容词", "温度描述"),
        ("weak", "/wiːk/", "弱的", "He is weak.", "形容词", "力量描述"),
        ("wealthy", "/ˈwelθi/", "富有的", "A wealthy family.", "形容词", "经济描述"),
        ("wet", "/wet/", "湿的", "The ground is wet.", "形容词", "状态描述"),
        ("wild", "/waɪld/", "野生的", "Wild animals.", "形容词", "性质描述"),
        ("wise", "/waɪz/", "明智的", "A wise decision.", "形容词", "智力描述"),
        ("wrong", "/rɒŋ/", "错误的", "You are wrong.", "形容词", "正确性描述"),
        ("young", "/jʌŋ/", "年轻的", "A young boy.", "形容词", "年龄描述"),
    ]
    
    # Additional Nouns - People and Family (200+)
    people_family = [
        ("aunt", "/ænt/", "阿姨", "My aunt is coming.", "名词", "家庭成员"),
        ("baby", "/ˈbeɪbi/", "婴儿", "The baby is crying.", "名词", "人物"),
        ("boy", "/bɔɪ/", "男孩", "The boy is playing.", "名词", "人物"),
        ("brother", "/ˈbrʌðər/", "兄弟", "My brother is tall.", "名词", "家庭成员"),
        ("child", "/tʃaɪld/", "孩子", "The child is happy.", "名词", "人物"),
        ("citizen", "/ˈsɪtɪzn/", "公民", "I am a citizen.", "名词", "人物"),
        ("classmate", "/ˈklæsmeɪt/", "同学", "She is my classmate.", "名词", "人物"),
        ("colleague", "/ˈkɒliːɡ/", "同事", "My colleague is nice.", "名词", "人物"),
        ("cousin", "/ˈkʌzn/", "堂表兄弟姐妹", "My cousin is young.", "名词", "家庭成员"),
        ("daughter", "/ˈdɔːtər/", "女儿", "My daughter is smart.", "名词", "家庭成员"),
        ("doctor", "/ˈdɒktər/", "医生", "See a doctor.", "名词", "职业"),
        ("employee", "/ɪmˈplɔɪiː/", "员工", "He is an employee.", "名词", "职业"),
        ("father", "/ˈfɑːðər/", "父亲", "My father is kind.", "名词", "家庭成员"),
        ("friend", "/frend/", "朋友", "She is my friend.", "名词", "人物"),
        ("girl", "/ɡɜːrl/", "女孩", "The girl is singing.", "名词", "人物"),
        ("grandfather", "/ˈɡrænfɑːðər/", "祖父", "My grandfather is old.", "名词", "家庭成员"),
        ("grandmother", "/ˈɡrænmʌðər/", "祖母", "My grandmother is kind.", "名词", "家庭成员"),
        ("guest", "/ɡest/", "客人", "Welcome our guest.", "名词", "人物"),
        ("husband", "/ˈhʌzbənd/", "丈夫", "My husband is working.", "名词", "家庭成员"),
        ("kid", "/kɪd/", "小孩", "The kids are playing.", "名词", "人物"),
        ("lady", "/ˈleɪdi/", "女士", "The lady is beautiful.", "名词", "人物"),
        ("man", "/mæn/", "男人", "The man is tall.", "名词", "人物"),
        ("member", "/ˈmembər/", "成员", "Family member.", "名词", "人物"),
        ("mother", "/ˈmʌðər/", "母亲", "My mother is cooking.", "名词", "家庭成员"),
        ("neighbor", "/ˈneɪbər/", "邻居", "My neighbor is friendly.", "名词", "人物"),
        ("niece", "/niːs/", "侄女", "My niece is cute.", "名词", "家庭成员"),
        ("nurse", "/nɜːrs/", "护士", "The nurse is helpful.", "名词", "职业"),
        ("parent", "/ˈpeərənt/", "父母", "Love your parents.", "名词", "家庭成员"),
        ("partner", "/ˈpɑːrtnər/", "伴侣", "My partner is great.", "名词", "人物"),
        ("person", "/ˈpɜːrsn/", "人", "A nice person.", "名词", "人物"),
        ("police", "/pəˈliːs/", "警察", "Call the police.", "名词", "职业"),
        ("queen", "/kwiːn/", "女王", "The queen is elegant.", "名词", "人物"),
        ("sister", "/ˈsɪstər/", "姐妹", "My sister is pretty.", "名词", "家庭成员"),
        ("son", "/sʌn/", "儿子", "My son is smart.", "名词", "家庭成员"),
        ("student", "/ˈstjuːdnt/", "学生", "I am a student.", "名词", "职业"),
        ("teacher", "/ˈtiːtʃər/", "老师", "The teacher is strict.", "名词", "职业"),
        ("uncle", "/ˈʌŋkl/", "叔叔", "My uncle is funny.", "名词", "家庭成员"),
        ("visitor", "/ˈvɪzɪtər/", "访客", "The visitor is here.", "名词", "人物"),
        ("wife", "/waɪf/", "妻子", "My wife is beautiful.", "名词", "家庭成员"),
        ("woman", "/ˈwʊmən/", "女人", "The woman is kind.", "名词", "人物"),
        ("worker", "/ˈwɜːrkər/", "工人", "The worker is tired.", "名词", "职业"),
    ]
    
    # Additional Nouns - Food and Drinks (200+)
    food_drinks = [
        ("apple", "/ˈæpl/", "苹果", "Eat an apple.", "名词", "食物"),
        ("banana", "/bəˈnænə/", "香蕉", "Peel a banana.", "名词", "食物"),
        ("beef", "/biːf/", "牛肉", "I like beef.", "名词", "食物"),
        ("beer", "/bɪr/", "啤酒", "Drink beer.", "名词", "饮料"),
        ("bread", "/bred/", "面包", "Eat bread.", "名词", "食物"),
        ("butter", "/ˈbʌtər/", "黄油", "Spread butter.", "名词", "食物"),
        ("cake", "/keɪk/", "蛋糕", "Cut the cake.", "名词", "食物"),
        ("candy", "/ˈkændi/", "糖果", "Eat candy.", "名词", "食物"),
        ("carrot", "/ˈkærət/", "胡萝卜", "Eat carrots.", "名词", "食物"),
        ("cheese", "/tʃiːz/", "奶酪", "Add cheese.", "名词", "食物"),
        ("chicken", "/ˈtʃɪkɪn/", "鸡肉", "Cook chicken.", "名词", "食物"),
        ("chocolate", "/ˈtʃɒklət/", "巧克力", "I love chocolate.", "名词", "食物"),
        ("coffee", "/ˈkɒfi/", "咖啡", "Drink coffee.", "名词", "饮料"),
        ("cookie", "/ˈkʊki/", "曲奇", "Eat a cookie.", "名词", "食物"),
        ("corn", "/kɔːrn/", "玉米", "Eat corn.", "名词", "食物"),
        ("cucumber", "/ˈkjuːkʌmbər/", "黄瓜", "Slice cucumber.", "名词", "食物"),
        ("egg", "/eɡ/", "鸡蛋", "Fry an egg.", "名词", "食物"),
        ("fish", "/fɪʃ/", "鱼", "Eat fish.", "名词", "食物"),
        ("fruit", "/fruːt/", "水果", "Eat fruit.", "名词", "食物"),
        ("grape", "/ɡreɪp/", "葡萄", "Eat grapes.", "名词", "食物"),
        ("ham", "/hæm/", "火腿", "Eat ham.", "名词", "食物"),
        ("honey", "/ˈhʌni/", "蜂蜜", "Add honey.", "名词", "食物"),
        ("ice cream", "/aɪs kriːm/", "冰淇淋", "Eat ice cream.", "名词", "食物"),
        ("juice", "/dʒuːs/", "果汁", "Drink juice.", "名词", "饮料"),
        ("lemon", "/ˈlemən/", "柠檬", "Squeeze lemon.", "名词", "食物"),
        ("meat", "/miːt/", "肉", "Eat meat.", "名词", "食物"),
        ("milk", "/mɪlk/", "牛奶", "Drink milk.", "名词", "饮料"),
        ("nut", "/nʌt/", "坚果", "Eat nuts.", "名词", "食物"),
        ("orange", "/ˈɔːrɪndʒ/", "橙子", "Peel an orange.", "名词", "食物"),
        ("pasta", "/ˈpæstə/", "意大利面", "Eat pasta.", "名词", "食物"),
        ("peach", "/piːtʃ/", "桃子", "Eat a peach.", "名词", "食物"),
        ("pear", "/per/", "梨", "Eat a pear.", "名词", "食物"),
        ("pizza", "/ˈpiːtsə/", "披萨", "Eat pizza.", "名词", "食物"),
        ("pork", "/pɔːrk/", "猪肉", "Eat pork.", "名词", "食物"),
        ("potato", "/pəˈteɪtoʊ/", "土豆", "Peel potatoes.", "名词", "食物"),
        ("rice", "/raɪs/", "米饭", "Eat rice.", "名词", "食物"),
        ("salad", "/ˈsæləd/", "沙拉", "Make a salad.", "名词", "食物"),
        ("salt", "/sɔːlt/", "盐", "Add salt.", "名词", "调味品"),
        ("sandwich", "/ˈsænwɪtʃ/", "三明治", "Eat a sandwich.", "名词", "食物"),
        ("sausage", "/ˈsɒsɪdʒ/", "香肠", "Eat sausage.", "名词", "食物"),
        ("soup", "/suːp/", "汤", "Drink soup.", "名词", "食物"),
        ("sugar", "/ˈʃʊɡər/", "糖", "Add sugar.", "名词", "调味品"),
        ("tea", "/tiː/", "茶", "Drink tea.", "名词", "饮料"),
        ("tomato", "/təˈmeɪtoʊ/", "番茄", "Eat tomatoes.", "名词", "食物"),
        ("vegetable", "/ˈvedʒtəbl/", "蔬菜", "Eat vegetables.", "名词", "食物"),
        ("water", "/ˈwɔːtər/", "水", "Drink water.", "名词", "饮料"),
        ("wine", "/waɪn/", "红酒", "Drink wine.", "名词", "饮料"),
        ("yogurt", "/ˈjəʊɡərt/", "酸奶", "Eat yogurt.", "名词", "食物"),
    ]
    
    # Additional Nouns - Animals (150+)
    animals = [
        ("ant", "/ænt/", "蚂蚁", "Watch the ant.", "名词", "动物"),
        ("bear", "/beər/", "熊", "The bear is big.", "名词", "动物"),
        ("bee", "/biː/", "蜜蜂", "The bee is flying.", "名词", "动物"),
        ("bird", "/bɜːrd/", "鸟", "The bird is singing.", "名词", "动物"),
        ("butterfly", "/ˈbʌtərflaɪ/", "蝴蝶", "The butterfly is beautiful.", "名词", "动物"),
        ("camel", "/ˈkæml/", "骆驼", "The camel is tall.", "名词", "动物"),
        ("cat", "/kæt/", "猫", "The cat is sleeping.", "名词", "动物"),
        ("chicken", "/ˈtʃɪkɪn/", "鸡", "The chicken is laying eggs.", "名词", "动物"),
        ("cow", "/kaʊ/", "牛", "The cow is eating grass.", "名词", "动物"),
        ("deer", "/dɪr/", "鹿", "The deer is running.", "名词", "动物"),
        ("dog", "/dɒɡ/", "狗", "The dog is barking.", "名词", "动物"),
        ("dolphin", "/ˈdɒlfɪn/", "海豚", "The dolphin is swimming.", "名词", "动物"),
        ("duck", "/dʌk/", "鸭子", "The duck is swimming.", "名词", "动物"),
        ("elephant", "/ˈelɪfənt/", "大象", "The elephant is huge.", "名词", "动物"),
        ("fish", "/fɪʃ/", "鱼", "The fish is swimming.", "名词", "动物"),
        ("fox", "/fɒks/", "狐狸", "The fox is clever.", "名词", "动物"),
        ("frog", "/frɒɡ/", "青蛙", "The frog is jumping.", "名词", "动物"),
        ("goat", "/ɡəʊt/", "山羊", "The goat is climbing.", "名词", "动物"),
        ("goose", "/ɡuːs/", "鹅", "The goose is loud.", "名词", "动物"),
        ("horse", "/hɔːrs/", "马", "The horse is running.", "名词", "动物"),
        ("kangaroo", "/ˌkæŋɡəˈruː/", "袋鼠", "The kangaroo is jumping.", "名词", "动物"),
        ("lion", "/ˈlaɪən/", "狮子", "The lion is roaring.", "名词", "动物"),
        ("monkey", "/ˈmʌŋki/", "猴子", "The monkey is playing.", "名词", "动物"),
        ("mouse", "/maʊs/", "老鼠", "The mouse is small.", "名词", "动物"),
        ("owl", "/aʊl/", "猫头鹰", "The owl is wise.", "名词", "动物"),
        ("panda", "/ˈpændə/", "熊猫", "The panda is cute.", "名词", "动物"),
        ("parrot", "/ˈpærət/", "鹦鹉", "The parrot is talking.", "名词", "动物"),
        ("pig", "/pɪɡ/", "猪", "The pig is fat.", "名词", "动物"),
        ("rabbit", "/ˈræbɪt/", "兔子", "The rabbit is hopping.", "名词", "动物"),
        ("sheep", "/ʃiːp/", "羊", "The sheep is eating.", "名词", "动物"),
        ("snake", "/sneɪk/", "蛇", "The snake is long.", "名词", "动物"),
        ("tiger", "/ˈtaɪɡər/", "老虎", "The tiger is strong.", "名词", "动物"),
        ("whale", "/weɪl/", "鲸鱼", "The whale is huge.", "名词", "动物"),
        ("wolf", "/wʊlf/", "狼", "The wolf is howling.", "名词", "动物"),
        ("zebra", "/ˈziːbrə/", "斑马", "The zebra has stripes.", "名词", "动物"),
    ]
    
    # Additional Nouns - Places (150+)
    places = [
        ("airport", "/ˈerpɔːrt/", "机场", "Go to the airport.", "名词", "地点"),
        ("bank", "/bæŋk/", "银行", "Go to the bank.", "名词", "地点"),
        ("beach", "/biːtʃ/", "海滩", "Go to the beach.", "名词", "地点"),
        ("bedroom", "/ˈbedruːm/", "卧室", "Sleep in the bedroom.", "名词", "地点"),
        ("bridge", "/brɪdʒ/", "桥", "Cross the bridge.", "名词", "地点"),
        ("building", "/ˈbɪldɪŋ/", "建筑", "Enter the building.", "名词", "地点"),
        ("bus stop", "/bʌs stɒp/", "公交站", "Wait at the bus stop.", "名词", "地点"),
        ("cafe", "/ˈkæfeɪ/", "咖啡馆", "Meet at the cafe.", "名词", "地点"),
        ("campus", "/ˈkæmpəs/", "校园", "Walk on campus.", "名词", "地点"),
        ("castle", "/ˈkæsl/", "城堡", "Visit the castle.", "名词", "地点"),
        ("church", "/tʃɜːrtʃ/", "教堂", "Go to church.", "名词", "地点"),
        ("city", "/ˈsɪti/", "城市", "Live in the city.", "名词", "地点"),
        ("classroom", "/ˈklæsruːm/", "教室", "Study in the classroom.", "名词", "地点"),
        ("clinic", "/ˈklɪnɪk/", "诊所", "Go to the clinic.", "名词", "地点"),
        ("club", "/klʌb/", "俱乐部", "Join the club.", "名词", "地点"),
        ("college", "/ˈkɒlɪdʒ/", "学院", "Go to college.", "名词", "地点"),
        ("country", "/ˈkʌntri/", "国家", "Visit the country.", "名词", "地点"),
        ("farm", "/fɑːrm/", "农场", "Work on the farm.", "名词", "地点"),
        ("forest", "/ˈfɒrɪst/", "森林", "Walk in the forest.", "名词", "地点"),
        ("garage", "/ˈɡærɑːʒ/", "车库", "Park in the garage.", "名词", "地点"),
        ("garden", "/ˈɡɑːrdn/", "花园", "Play in the garden.", "名词", "地点"),
        ("gym", "/dʒɪm/", "健身房", "Go to the gym.", "名词", "地点"),
        ("hall", "/hɔːl/", "大厅", "Enter the hall.", "名词", "地点"),
        ("hospital", "/ˈhɒspɪtl/", "医院", "Go to the hospital.", "名词", "地点"),
        ("hotel", "/həʊˈtel/", "酒店", "Stay at the hotel.", "名词", "地点"),
        ("house", "/haʊs/", "房子", "Buy a house.", "名词", "地点"),
        ("island", "/ˈaɪlənd/", "岛屿", "Visit the island.", "名词", "地点"),
        ("kitchen", "/ˈkɪtʃən/", "厨房", "Cook in the kitchen.", "名词", "地点"),
        ("library", "/ˈlaɪbreri/", "图书馆", "Study in the library.", "名词", "地点"),
        ("market", "/ˈmɑːrkɪt/", "市场", "Go to the market.", "名词", "地点"),
        ("museum", "/mjuːˈziːəm/", "博物馆", "Visit the museum.", "名词", "地点"),
        ("office", "/ˈɒfɪs/", "办公室", "Work in the office.", "名词", "地点"),
        ("park", "/pɑːrk/", "公园", "Walk in the park.", "名词", "地点"),
        ("pharmacy", "/ˈfɑːrməsi/", "药店", "Go to the pharmacy.", "名词", "地点"),
        ("playground", "/ˈpleɪɡraʊnd/", "操场", "Play on the playground.", "名词", "地点"),
        ("pool", "/puːl/", "游泳池", "Swim in the pool.", "名词", "地点"),
        ("post office", "/pəʊst ˈɒfɪs/", "邮局", "Go to the post office.", "名词", "地点"),
        ("restaurant", "/ˈrestrɒnt/", "餐厅", "Eat at the restaurant.", "名词", "地点"),
        ("road", "/rəʊd/", "道路", "Walk on the road.", "名词", "地点"),
        ("room", "/ruːm/", "房间", "Enter the room.", "名词", "地点"),
        ("school", "/skuːl/", "学校", "Go to school.", "名词", "地点"),
        ("shop", "/ʃɒp/", "商店", "Go to the shop.", "名词", "地点"),
        ("station", "/ˈsteɪʃn/", "车站", "Wait at the station.", "名词", "地点"),
        ("street", "/striːt/", "街道", "Walk on the street.", "名词", "地点"),
        ("supermarket", "/ˈsuːpərmɑːrkɪt/", "超市", "Shop at the supermarket.", "名词", "地点"),
        ("theater", "/ˈθiːətər/", "剧院", "Watch a play at the theater.", "名词", "地点"),
        ("toilet", "/ˈtɔɪlət/", "厕所", "Go to the toilet.", "名词", "地点"),
    ]
    
    # Combine all word lists
    expanded_words.extend(additional_verbs)
    expanded_words.extend(additional_adjectives)
    expanded_words.extend(people_family)
    expanded_words.extend(food_drinks)
    expanded_words.extend(animals)
    expanded_words.extend(places)
    
    # Create word objects
    word_objects = []
    for word_data in expanded_words:
        word_obj = {
            "english": word_data[0],
            "phonetic": word_data[1],
            "chinese": word_data[2],
            "example": word_data[3],
            "category": word_data[4],
            "subcategory": word_data[5]
        }
        word_objects.append(word_obj)
    
    # Save to JSON file
    json_file = Path("/Users/dong/Documents/AI IDE/English-Learning-App/expanded_words.json")
    with open(json_file, 'w', encoding='utf-8') as f:
        json.dump(word_objects, f, ensure_ascii=False, indent=2)
    
    print(f"Successfully created {len(word_objects)} words in expanded_words.json")
    
    # Update database
    db_file = Path("../words.db")
    if db_file.exists():
        conn = sqlite3.connect(db_file)
        cursor = conn.cursor()
        
        for word_obj in word_objects:
            cursor.execute('''
                INSERT OR IGNORE INTO words 
                (english, phonetic, chinese, example, category, subcategory)
                VALUES (?, ?, ?, ?, ?, ?)
            ''', (
                word_obj['english'],
                word_obj['phonetic'],
                word_obj['chinese'],
                word_obj['example'],
                word_obj['category'],
                word_obj['subcategory']
            ))
            
            # Initialize word status
            cursor.execute('''
                INSERT OR IGNORE INTO word_status (word_id, status)
                SELECT id, 'gray' FROM words WHERE english = ?
            ''', (word_obj['english'],))
        
        conn.commit()
        conn.close()
        print(f"Successfully added {len(word_objects)} words to the database")
    else:
        print("Database file not found. Please run init_db.py first")

if __name__ == "__main__":
    expand_vocabulary()