#!/usr/bin/env python3
import json
import sqlite3
from pathlib import Path

def expand_vocabulary_part3():
    """Expand vocabulary to reach 5000+ words - Part 3"""
    
    expanded_words = []
    
    # Additional Verbs - More Advanced (300+)
    more_verbs = [
        ("accomplish", "/əˈkʌmplɪʃ/", "完成", "Accomplish your goals.", "动词", "高级动词"),
        ("accumulate", "/əˈkjuːmjəleɪt/", "积累", "Accumulate wealth.", "动词", "高级动词"),
        ("acknowledge", "/əkˈnɒlɪdʒ/", "承认", "Acknowledge the truth.", "动词", "高级动词"),
        ("acquire", "/əˈkwaɪər/", "获得", "Acquire knowledge.", "动词", "高级动词"),
        ("adapt", "/əˈdæpt/", "适应", "Adapt to changes.", "动词", "高级动词"),
        ("adjust", "/əˈdʒʌst/", "调整", "Adjust the settings.", "动词", "高级动词"),
        ("administer", "/ədˈmɪnɪstər/", "管理", "Administer the test.", "动词", "高级动词"),
        ("admire", "/ədˈmaɪər/", "钦佩", "Admire the view.", "动词", "高级动词"),
        ("advocate", "/ˈædvəkeɪt/", "提倡", "Advocate for change.", "动词", "高级动词"),
        ("affirm", "/əˈfɜːrm/", "确认", "Affirm your decision.", "动词", "高级动词"),
        ("aggravate", "/ˈæɡrəveɪt/", "恶化", "Don't aggravate the situation.", "动词", "高级动词"),
        ("allocate", "/ˈæləkeɪt/", "分配", "Allocate resources.", "动词", "高级动词"),
        ("alter", "/ˈɔːltər/", "改变", "Alter the plan.", "动词", "高级动词"),
        ("analyze", "/ˈænəlaɪz/", "分析", "Analyze the data.", "动词", "高级动词"),
        ("anticipate", "/ænˈtɪsɪpeɪt/", "预期", "Anticipate problems.", "动词", "高级动词"),
        ("apologize", "/əˈpɒlədʒaɪz/", "道歉", "Apologize sincerely.", "动词", "高级动词"),
        ("appreciate", "/əˈpriːʃieɪt/", "感激", "Appreciate your help.", "动词", "高级动词"),
        ("approach", "/əˈprəʊtʃ/", "接近", "Approach the problem.", "动词", "高级动词"),
        ("approve", "/əˈpruːv/", "批准", "Approve the request.", "动词", "高级动词"),
        ("argue", "/ˈɑːrɡjuː/", "争论", "Don't argue.", "动词", "高级动词"),
        ("arise", "/əˈraɪz/", "出现", "Problems may arise.", "动词", "高级动词"),
        ("arrest", "/əˈrest/", "逮捕", "Arrest the suspect.", "动词", "高级动词"),
        ("ascertain", "/ˌæsərˈteɪn/", "查明", "Ascertain the facts.", "动词", "高级动词"),
        ("assemble", "/əˈsembl/", "组装", "Assemble the furniture.", "动词", "高级动词"),
        ("assess", "/əˈses/", "评估", "Assess the damage.", "动词", "高级动词"),
        ("assist", "/əˈsɪst/", "协助", "Assist your colleagues.", "动词", "高级动词"),
        ("assume", "/əˈsuːm/", "假设", "Don't assume.", "动词", "高级动词"),
        ("assure", "/əˈʃʊr/", "保证", "I assure you.", "动词", "高级动词"),
        ("attach", "/əˈtætʃ/", "附加", "Attach the file.", "动词", "高级动词"),
        ("attain", "/əˈteɪn/", "达到", "Attain success.", "动词", "高级动词"),
        ("attempt", "/əˈtempt/", "尝试", "Attempt the task.", "动词", "高级动词"),
        ("attend", "/əˈtend/", "参加", "Attend the meeting.", "动词", "高级动词"),
        ("attract", "/əˈtrækt/", "吸引", "Attract attention.", "动词", "高级动词"),
        ("attribute", "/əˈtrɪbjuːt/", "归因于", "Attribute success to hard work.", "动词", "高级动词"),
        ("audit", "/ˈɔːdɪt/", "审计", "Audit the accounts.", "动词", "高级动词"),
        ("authenticate", "/ɔːˈθentɪkeɪt/", "认证", "Authenticate the user.", "动词", "高级动词"),
        ("authorize", "/ˈɔːθəraɪz/", "授权", "Authorize the payment.", "动词", "高级动词"),
        ("balance", "/ˈbæləns/", "平衡", "Balance the budget.", "动词", "高级动词"),
        ("ban", "/bæn/", "禁止", "Ban smoking.", "动词", "高级动词"),
        ("bar", "/bɑːr/", "禁止", "Bar the entrance.", "动词", "高级动词"),
        ("base", "/beɪs/", "基于", "Base your decision on facts.", "动词", "高级动词"),
        ("bear", "/beər/", "忍受", "Bear with me.", "动词", "高级动词"),
        ("beat", "/biːt/", "击败", "Beat the competition.", "动词", "高级动词"),
        ("become", "/bɪˈkʌm/", "变成", "Become successful.", "动词", "高级动词"),
        ("begin", "/bɪˈɡɪn/", "开始", "Begin the project.", "动词", "高级动词"),
        ("behave", "/bɪˈheɪv/", "表现", "Behave properly.", "动词", "高级动词"),
        ("belong", "/bɪˈlɒŋ/", "属于", "Belong to the team.", "动词", "高级动词"),
        ("benefit", "/ˈbenɪfɪt/", "受益", "Benefit from experience.", "动词", "高级动词"),
        ("bet", "/bet/", "打赌", "Bet on the winner.", "动词", "高级动词"),
        ("bind", "/baɪnd/", "绑定", "Bind the documents.", "动词", "高级动词"),
        ("blame", "/bleɪm/", "责怪", "Don't blame others.", "动词", "高级动词"),
        ("bless", "/bles/", "保佑", "God bless you.", "动词", "高级动词"),
        ("block", "/blɒk/", "阻挡", "Block the road.", "动词", "高级动词"),
        ("board", "/bɔːrd/", "登机", "Board the plane.", "动词", "高级动词"),
        ("boil", "/bɔɪl/", "煮沸", "Boil the water.", "动词", "高级动词"),
        ("book", "/bʊk/", "预订", "Book a hotel.", "动词", "高级动词"),
        ("boost", "/buːst/", "促进", "Boost morale.", "动词", "高级动词"),
        ("borrow", "/ˈbɒrəʊ/", "借入", "Borrow money.", "动词", "高级动词"),
        ("bounce", "/baʊns/", "弹跳", "Bounce the ball.", "动词", "高级动词"),
        ("bound", "/baʊnd/", "束缚", "Be bound by rules.", "动词", "高级动词"),
        ("brake", "/breɪk/", "刹车", "Brake the car.", "动词", "高级动词"),
        ("breed", "/briːd/", "繁殖", "Breed animals.", "动词", "高级动词"),
        ("brighten", "/ˈbraɪtn/", "使明亮", "Brighten the room.", "动词", "高级动词"),
        ("broadcast", "/ˈbrɔːdkæst/", "广播", "Broadcast the news.", "动词", "高级动词"),
        ("broke", "/brəʊk/", "打破", "Broke the record.", "动词", "高级动词"),
        ("brought", "/brɔːt/", "带来", "Brought good news.", "动词", "高级动词"),
        ("build", "/bɪld/", "建造", "Build a house.", "动词", "高级动词"),
        ("burn", "/bɜːrn/", "燃烧", "Burn the calories.", "动词", "高级动词"),
        ("burst", "/bɜːrst/", "爆发", "Burst into laughter.", "动词", "高级动词"),
        ("calculate", "/ˈkælkjʊleɪt/", "计算", "Calculate the cost.", "动词", "高级动词"),
        ("call", "/kɔːl/", "呼叫", "Call me later.", "动词", "高级动词"),
        ("cancel", "/ˈkænsəl/", "取消", "Cancel the appointment.", "动词", "高级动词"),
        ("capture", "/ˈkæptʃər/", "捕捉", "Capture the moment.", "动词", "高级动词"),
        ("care", "/keər/", "关心", "Care for others.", "动词", "高级动词"),
        ("carry", "/ˈkæri/", "携带", "Carry the luggage.", "动词", "高级动词"),
        ("cast", "/kæst/", "投掷", "Cast a vote.", "动词", "高级动词"),
        ("catalog", "/ˈkætəlɒɡ/", "编目", "Catalog the items.", "动词", "高级动词"),
        ("catch", "/kætʃ/", "抓住", "Catch the bus.", "动词", "高级动词"),
        ("cause", "/kɔːz/", "导致", "Cause trouble.", "动词", "高级动词"),
        ("celebrate", "/ˈselɪbreɪt/", "庆祝", "Celebrate success.", "动词", "高级动词"),
        ("challenge", "/ˈtʃælɪndʒ/", "挑战", "Challenge yourself.", "动词", "高级动词"),
        ("change", "/tʃeɪndʒ/", "改变", "Change the world.", "动词", "高级动词"),
        ("charge", "/tʃɑːrdʒ/", "收费", "Charge the battery.", "动词", "高级动词"),
        ("chase", "/tʃeɪs/", "追逐", "Chase your dreams.", "动词", "高级动词"),
        ("chat", "/tʃæt/", "聊天", "Chat with friends.", "动词", "高级动词"),
        ("check", "/tʃek/", "检查", "Check the email.", "动词", "高级动词"),
        ("cheer", "/tʃɪr/", "欢呼", "Cheer for the team.", "动词", "高级动词"),
        ("chew", "/tʃuː/", "咀嚼", "Chew slowly.", "动词", "高级动词"),
        ("choke", "/tʃəʊk/", "窒息", "Don't choke.", "动词", "高级动词"),
        ("choose", "/tʃuːz/", "选择", "Choose wisely.", "动词", "高级动词"),
        ("claim", "/kleɪm/", "声称", "Claim your prize.", "动词", "高级动词"),
        ("clarify", "/ˈklærəfaɪ/", "澄清", "Clarify the situation.", "动词", "高级动词"),
        ("clash", "/klæʃ/", "冲突", "Clash with others.", "动词", "高级动词"),
        ("clean", "/kliːn/", "清洁", "Clean the room.", "动词", "高级动词"),
        ("clear", "/klɪr/", "清除", "Clear the desk.", "动词", "高级动词"),
        ("climb", "/klaɪm/", "攀登", "Climb the ladder.", "动词", "高级动词"),
        ("cling", "/klɪŋ/", "依附", "Cling to hope.", "动词", "高级动词"),
        ("close", "/kləʊz/", "关闭", "Close the door.", "动词", "高级动词"),
        ("collect", "/kəˈlekt/", "收集", "Collect stamps.", "动词", "高级动词"),
        ("combine", "/kəmˈbaɪn/", "结合", "Combine ingredients.", "动词", "高级动词"),
        ("come", "/kʌm/", "来", "Come here.", "动词", "高级动词"),
        ("command", "/kəˈmænd/", "命令", "Command respect.", "动词", "高级动词"),
        ("commit", "/kəˈmɪt/", "承诺", "Commit to excellence.", "动词", "高级动词"),
        ("communicate", "/kəˈmjuːnɪkeɪt/", "交流", "Communicate effectively.", "动词", "高级动词"),
        ("compare", "/kəmˈpeər/", "比较", "Compare prices.", "动词", "高级动词"),
        ("compete", "/kəmˈpiːt/", "竞争", "Compete fairly.", "动词", "高级动词"),
        ("complain", "/kəmˈpleɪn/", "抱怨", "Don't complain.", "动词", "高级动词"),
        ("complete", "/kəmˈpliːt/", "完成", "Complete the task.", "动词", "高级动词"),
        ("compose", "/kəmˈpəʊz/", "组成", "Compose a song.", "动词", "高级动词"),
        ("compromise", "/ˈkɒmprəmaɪz/", "妥协", "Compromise when needed.", "动词", "高级动词"),
        ("conceal", "/kənˈsiːl/", "隐藏", "Conceal the truth.", "动词", "高级动词"),
        ("concentrate", "/ˈkɒnsntreɪt/", "集中", "Concentrate on work.", "动词", "高级动词"),
        ("conclude", "/kənˈkluːd/", "推断", "Conclude the meeting.", "动词", "高级动词"),
        ("conduct", "/kənˈdʌkt/", "进行", "Conduct research.", "动词", "高级动词"),
        ("confess", "/kənˈfes/", "坦白", "Confess your sins.", "动词", "高级动词"),
        ("confirm", "/kənˈfɜːrm/", "确认", "Confirm the details.", "动词", "高级动词"),
        ("conflict", "/kənˈflɪkt/", "冲突", "Conflict arises.", "动词", "高级动词"),
        ("confuse", "/kənˈfjuːz/", "使困惑", "Don't confuse me.", "动词", "高级动词"),
        ("connect", "/kəˈnekt/", "连接", "Connect to WiFi.", "动词", "高级动词"),
        ("conquer", "/ˈkɒŋkər/", "征服", "Conquer your fears.", "动词", "高级动词"),
        ("consent", "/kənˈsent/", "同意", "Give your consent.", "动词", "高级动词"),
        ("consider", "/kənˈsɪdər/", "考虑", "Consider the options.", "动词", "高级动词"),
        ("consist", "/kənˈsɪst/", "由...组成", "Consist of facts.", "动词", "高级动词"),
        ("construct", "/kənˈstrʌkt/", "建造", "Construct a building.", "动词", "高级动词"),
        ("consult", "/kənˈsʌlt/", "咨询", "Consult an expert.", "动词", "高级动词"),
        ("consume", "/kənˈsuːm/", "消耗", "Consume energy.", "动词", "高级动词"),
        ("contact", "/ˈkɒntækt/", "联系", "Contact me soon.", "动词", "高级动词"),
        ("contain", "/kənˈteɪn/", "包含", "Contain the virus.", "动词", "高级动词"),
        ("continue", "/kənˈtɪnjuː/", "继续", "Continue working.", "动词", "高级动词"),
        ("contract", "/kənˈtrækt/", "收缩", "Contract the muscles.", "动词", "高级动词"),
        ("contrast", "/kənˈtræst/", "对比", "Contrast the styles.", "动词", "高级动词"),
        ("contribute", "/kənˈtrɪbjuːt/", "贡献", "Contribute to society.", "动词", "高级动词"),
        ("control", "/kənˈtrəʊl/", "控制", "Control your emotions.", "动词", "高级动词"),
        ("convert", "/kənˈvɜːrt/", "转换", "Convert to PDF.", "动词", "高级动词"),
        ("convince", "/kənˈvɪns/", "说服", "Convince them.", "动词", "高级动词"),
        ("cook", "/kʊk/", "烹饪", "Cook dinner.", "动词", "高级动词"),
        ("cooperate", "/kəʊˈɒpəreɪt/", "合作", "Cooperate with others.", "动词", "高级动词"),
        ("coordinate", "/kəʊˈɔːrdɪneɪt/", "协调", "Coordinate the team.", "动词", "高级动词"),
        ("copy", "/ˈkɒpi/", "复制", "Copy the file.", "动词", "高级动词"),
        ("correct", "/kəˈrekt/", "改正", "Correct the errors.", "动词", "高级动词"),
        ("correspond", "/ˌkɒrɪˈspɒnd/", "通信", "Correspond regularly.", "动词", "高级动词"),
        ("count", "/kaʊnt/", "数数", "Count to ten.", "动词", "高级动词"),
        ("cover", "/ˈkʌvər/", "覆盖", "Cover the expenses.", "动词", "高级动词"),
        ("crash", "/kræʃ/", "坠毁", "The plane crashed.", "动词", "高级动词"),
        ("create", "/kriˈeɪt/", "创造", "Create art.", "动词", "高级动词"),
        ("creep", "/kriːp/", "爬行", "Creep slowly.", "动词", "高级动词"),
        ("criticize", "/ˈkrɪtɪsaɪz/", "批评", "Criticize constructively.", "动词", "高级动词"),
        ("cross", "/krɒs/", "穿过", "Cross the street.", "动词", "高级动词"),
        ("crush", "/krʌʃ/", "压碎", "Crush the can.", "动词", "高级动词"),
        ("cry", "/kraɪ/", "哭", "Don't cry.", "动词", "高级动词"),
        ("cultivate", "/ˈkʌltɪveɪt/", "培养", "Cultivate habits.", "动词", "高级动词"),
        ("cure", "/kjʊər/", "治愈", "Cure the disease.", "动词", "高级动词"),
        ("curl", "/kɜːrl/", "卷曲", "Curl your hair.", "动词", "高级动词"),
        ("damage", "/ˈdæmɪdʒ/", "损坏", "Damage the car.", "动词", "高级动词"),
        ("dance", "/dæns/", "跳舞", "Dance with joy.", "动词", "高级动词"),
        ("dare", "/deər/", "敢于", "Dare to dream.", "动词", "高级动词"),
        ("deal", "/diːl/", "处理", "Deal with it.", "动词", "高级动词"),
        ("debate", "/dɪˈbeɪt/", "辩论", "Debate the issue.", "动词", "高级动词"),
        ("decay", "/dɪˈkeɪ/", "腐烂", "The fruit decayed.", "动词", "高级动词"),
        ("decide", "/dɪˈsaɪd/", "决定", "Decide now.", "动词", "高级动词"),
        ("declare", "/dɪˈkleər/", "宣布", "Declare independence.", "动词", "高级动词"),
        ("decline", "/dɪˈklaɪn/", "拒绝", "Decline the offer.", "动词", "高级动词"),
        ("decrease", "/dɪˈkriːs/", "减少", "Decrease the volume.", "动词", "高级动词"),
        ("dedicate", "/ˈdedɪkeɪt/", "奉献", "Dedicate yourself.", "动词", "高级动词"),
        ("defeat", "/dɪˈfiːt/", "击败", "Defeat the enemy.", "动词", "高级动词"),
        ("defend", "/dɪˈfend/", "防守", "Defend your position.", "动词", "高级动词"),
        ("define", "/dɪˈfaɪn/", "定义", "Define the terms.", "动词", "高级动词"),
        ("delay", "/dɪˈleɪ/", "推迟", "Delay the flight.", "动词", "高级动词"),
        ("delete", "/dɪˈliːt/", "删除", "Delete the file.", "动词", "高级动词"),
        ("deliver", "/dɪˈlɪvər/", "交付", "Deliver the package.", "动词", "高级动词"),
        ("demand", "/dɪˈmænd/", "要求", "Demand excellence.", "动词", "高级动词"),
        ("demonstrate", "/ˈdemənstreɪt/", "演示", "Demonstrate your skills.", "动词", "高级动词"),
        ("deny", "/dɪˈnaɪ/", "否认", "Deny the accusation.", "动词", "高级动词"),
        ("depend", "/dɪˈpend/", "依靠", "Depend on yourself.", "动词", "高级动词"),
        ("deposit", "/dɪˈpɒzɪt/", "存款", "Deposit money.", "动词", "高级动词"),
        ("depress", "/dɪˈpres/", "使沮丧", "Don't depress me.", "动词", "高级动词"),
        ("describe", "/dɪˈskraɪb/", "描述", "Describe the scene.", "动词", "高级动词"),
        ("deserve", "/dɪˈzɜːrv/", "值得", "You deserve it.", "动词", "高级动词"),
        ("design", "/dɪˈzaɪn/", "设计", "Design the logo.", "动词", "高级动词"),
        ("desire", "/dɪˈzaɪər/", "渴望", "Desire success.", "动词", "高级动词"),
        ("destroy", "/dɪˈstrɔɪ/", "破坏", "Destroy the evidence.", "动词", "高级动词"),
        ("detach", "/dɪˈtætʃ/", "分离", "Detach the part.", "动词", "高级动词"),
        ("develop", "/dɪˈveləp/", "发展", "Develop your skills.", "动词", "高级动词"),
        ("devote", "/dɪˈvəʊt/", "奉献", "Devote time.", "动词", "高级动词"),
        ("diagnose", "/ˈdaɪəɡnəʊz/", "诊断", "Diagnose the problem.", "动词", "高级动词"),
        ("dictate", "/dɪkˈteɪt/", "口述", "Dictate the letter.", "动词", "高级动词"),
        ("differ", "/ˈdɪfər/", "不同", "Opinions differ.", "动词", "高级动词"),
        ("digest", "/daɪˈdʒest/", "消化", "Digest the food.", "动词", "高级动词"),
        ("diminish", "/dɪˈmɪnɪʃ/", "减少", "Diminish the risk.", "动词", "高级动词"),
        ("direct", "/dəˈrekt/", "指导", "Direct the traffic.", "动词", "高级动词"),
        ("disagree", "/ˌdɪsəˈɡriː/", "不同意", "I disagree.", "动词", "高级动词"),
        ("disappear", "/ˌdɪsəˈpɪər/", "消失", "Disappear quickly.", "动词", "高级动词"),
        ("disappoint", "/ˌdɪsəˈpɔɪnt/", "使失望", "Don't disappoint me.", "动词", "高级动词"),
        ("disapprove", "/ˌdɪsəˈpruːv/", "不赞成", "Disapprove of this.", "动词", "高级动词"),
        ("disarm", "/dɪsˈɑːrm/", "解除武装", "Disarm the bomb.", "动词", "高级动词"),
        ("discharge", "/dɪsˈtʃɑːrdʒ/", "释放", "Discharge the patient.", "动词", "高级动词"),
        ("discipline", "/ˈdɪsəplɪn/", "纪律", "Discipline yourself.", "动词", "高级动词"),
        ("disconnect", "/ˌdɪskəˈnekt/", "断开连接", "Disconnect the cable.", "动词", "高级动词"),
        ("discount", "/dɪsˈkaʊnt/", "打折", "Discount the price.", "动词", "高级动词"),
        ("discover", "/dɪˈskʌvər/", "发现", "Discover new things.", "动词", "高级动词"),
        ("discriminate", "/dɪˈskrɪmɪneɪt/", "歧视", "Don't discriminate.", "动词", "高级动词"),
        ("discuss", "/dɪˈskʌs/", "讨论", "Discuss the plan.", "动词", "高级动词"),
        ("dislike", "/dɪsˈlaɪk/", "不喜欢", "I dislike waiting.", "动词", "高级动词"),
        ("dismiss", "/dɪsˈmɪs/", "解雇", "Dismiss the employee.", "动词", "高级动词"),
        ("display", "/dɪˈspleɪ/", "展示", "Display the art.", "动词", "高级动词"),
        ("dispose", "/dɪˈspəʊz/", "处理", "Dispose of waste.", "动词", "高级动词"),
        ("dispute", "/dɪˈspjuːt/", "争议", "Dispute the claim.", "动词", "高级动词"),
        ("dissolve", "/dɪˈzɒlv/", "溶解", "Dissolve the sugar.", "动词", "高级动词"),
        ("distinguish", "/dɪˈstɪŋɡwɪʃ/", "区分", "Distinguish between them.", "动词", "高级动词"),
        ("distort", "/dɪˈstɔːrt/", "扭曲", "Distort the facts.", "动词", "高级动词"),
        ("distract", "/dɪˈstrækt/", "分心", "Don't distract me.", "动词", "高级动词"),
        ("distress", "/dɪˈstres/", "使痛苦", "Distress the enemy.", "动词", "高级动词"),
        ("distribute", "/dɪˈstrɪbjuːt/", "分发", "Distribute the flyers.", "动词", "高级动词"),
        ("disturb", "/dɪˈstɜːrb/", "打扰", "Don't disturb.", "动词", "高级动词"),
        ("diverge", "/daɪˈvɜːrdʒ/", "分歧", "Opinions diverge.", "动词", "高级动词"),
        ("divide", "/dɪˈvaɪd/", "分割", "Divide the work.", "动词", "高级动词"),
        ("divorce", "/dɪˈvɔːrs/", "离婚", "Divorce peacefully.", "动词", "高级动词"),
        ("do", "/duː/", "做", "Do your best.", "动词", "高级动词"),
        ("dock", "/dɒk/", "停靠", "Dock the ship.", "动词", "高级动词"),
        ("dominate", "/ˈdɒmɪneɪt/", "支配", "Dominate the market.", "动词", "高级动词"),
        ("donate", "/ˈdəʊneɪt/", "捐赠", "Donate to charity.", "动词", "高级动词"),
        ("double", "/ˈdʌbl/", "加倍", "Double the effort.", "动词", "高级动词"),
        ("doubt", "/daʊt/", "怀疑", "I doubt it.", "动词", "高级动词"),
        ("draft", "/dræft/", "起草", "Draft the document.", "动词", "高级动词"),
        ("drag", "/dræɡ/", "拖拽", "Drag the file.", "动词", "高级动词"),
        ("drain", "/dreɪn/", "排水", "Drain the water.", "动词", "高级动词"),
        ("dramatize", "/ˈdræmətaɪz/", "戏剧化", "Don't dramatize.", "动词", "高级动词"),
        ("draw", "/drɔː/", "画", "Draw a picture.", "动词", "高级动词"),
        ("dream", "/driːm/", "做梦", "Dream big.", "动词", "高级动词"),
        ("dress", "/dres/", "穿衣", "Dress up.", "动词", "高级动词"),
        ("drift", "/drɪft/", "漂移", "Drift away.", "动词", "高级动词"),
        ("drill", "/drɪl/", "钻孔", "Drill the hole.", "动词", "高级动词"),
        ("drink", "/drɪŋk/", "喝", "Drink water.", "动词", "高级动词"),
        ("drive", "/draɪv/", "驾驶", "Drive safely.", "动词", "高级动词"),
        ("drop", "/drɒp/", "掉落", "Drop the ball.", "动词", "高级动词"),
        ("drown", "/draʊn/", "淹死", "Don't drown.", "动词", "高级动词"),
        ("dry", "/draɪ/", "弄干", "Dry your hair.", "动词", "高级动词"),
        ("duplicate", "/ˈduːplɪkeɪt/", "复制", "Duplicate the file.", "动词", "高级动词"),
        ("dust", "/dʌst/", "除尘", "Dust the shelves.", "动词", "高级动词"),
        ("dwell", "/dwel/", "居住", "Dwell in the past.", "动词", "高级动词"),
        ("earn", "/ɜːrn/", "赚取", "Earn money.", "动词", "高级动词"),
        ("ease", "/iːz/", "减轻", "Ease the pain.", "动词", "高级动词"),
        ("eat", "/iːt/", "吃", "Eat healthy.", "动词", "高级动词"),
        ("echo", "/ˈekəʊ/", "回响", "Echo the sound.", "动词", "高级动词"),
        ("edit", "/ˈedɪt/", "编辑", "Edit the video.", "动词", "高级动词"),
        ("educate", "/ˈedʒukeɪt/", "教育", "Educate yourself.", "动词", "高级动词"),
        ("effect", "/ɪˈfekt/", "实现", "Effect change.", "动词", "高级动词"),
        ("elaborate", "/ɪˈlæbəreɪt/", "详细说明", "Elaborate on that.", "动词", "高级动词"),
        ("elapse", "/ɪˈlæps/", "流逝", "Time elapsed.", "动词", "高级动词"),
        ("elect", "/ɪˈlekt/", "选举", "Elect the president.", "动词", "高级动词"),
        ("elevate", "/ˈelɪveɪt/", "提升", "Elevate your game.", "动词", "高级动词"),
        ("eliminate", "/ɪˈlɪmɪneɪt/", "消除", "Eliminate waste.", "动词", "高级动词"),
        ("embrace", "/ɪmˈbreɪs/", "拥抱", "Embrace change.", "动词", "高级动词"),
        ("emerge", "/ɪˈmɜːrdʒ/", "出现", "Problems emerge.", "动词", "高级动词"),
        ("emit", "/ɪˈmɪt/", "发出", "Emit light.", "动词", "高级动词"),
        ("emphasize", "/ˈemfəsaɪz/", "强调", "Emphasize the point.", "动词", "高级动词"),
        ("employ", "/ɪmˈplɔɪ/", "雇佣", "Employ new staff.", "动词", "高级动词"),
        ("empty", "/ˈempti/", "倒空", "Empty the trash.", "动词", "高级动词"),
        ("enable", "/ɪˈneɪbl/", "使能够", "Enable the feature.", "动词", "高级动词"),
        ("enclose", "/ɪnˈkləʊz/", "附上", "Enclose the document.", "动词", "高级动词"),
        ("encounter", "/ɪnˈkaʊntər/", "遭遇", "Encounter problems.", "动词", "高级动词"),
        ("encourage", "/ɪnˈkʌrɪdʒ/", "鼓励", "Encourage others.", "动词", "高级动词"),
        ("end", "/end/", "结束", "End the call.", "动词", "高级动词"),
        ("endure", "/ɪnˈdjʊər/", "忍受", "Endure the pain.", "动词", "高级动词"),
        ("engage", "/ɪnˈɡeɪdʒ/", "参与", "Engage the audience.", "动词", "高级动词"),
        ("enhance", "/ɪnˈhæns/", "增强", "Enhance the image.", "动词", "高级动词"),
        ("enjoy", "/ɪnˈdʒɔɪ/", "享受", "Enjoy life.", "动词", "高级动词"),
        ("enlarge", "/ɪnˈlɑːrdʒ/", "扩大", "Enlarge the photo.", "动词", "高级动词"),
        ("enlighten", "/ɪnˈlaɪtn/", "启发", "Enlighten me.", "动词", "高级动词"),
        ("enlist", "/ɪnˈlɪst/", "征募", "Enlist in the army.", "动词", "高级动词"),
        ("ensure", "/ɪnˈʃʊr/", "确保", "Ensure quality.", "动词", "高级动词"),
        ("enter", "/ˈentər/", "进入", "Enter the room.", "动词", "高级动词"),
        ("entertain", "/ˌentərˈteɪn/", "娱乐", "Entertain the guests.", "动词", "高级动词"),
        ("entitle", "/ɪnˈtaɪtl/", "给...权利", "Entitle to benefits.", "动词", "高级动词"),
        ("entrust", "/ɪnˈtrʌst/", "委托", "Entrust the task.", "动词", "高级动词"),
        ("envy", "/ˈenvi/", "嫉妒", "Don't envy others.", "动词", "高级动词"),
        ("equal", "/ˈiːkwəl/", "等于", "Equal opportunity.", "动词", "高级动词"),
        ("equip", "/ɪˈkwɪp/", "装备", "Equip the team.", "动词", "高级动词"),
        ("erase", "/ɪˈreɪz/", "擦除", "Erase the board.", "动词", "高级动词"),
        ("erect", "/ɪˈrekt/", "建立", "Erect the building.", "动词", "高级动词"),
        ("escape", "/ɪˈskeɪp/", "逃跑", "Escape danger.", "动词", "高级动词"),
        ("escort", "/ɪˈskɔːt/", "护送", "Escort the guest.", "动词", "高级动词"),
        ("establish", "/ɪˈstæblɪʃ/", "建立", "Establish rapport.", "动词", "高级动词"),
        ("estimate", "/ˈestɪmeɪt/", "估计", "Estimate the cost.", "动词", "高级动词"),
        ("evaluate", "/ɪˈvæljueɪt/", "评估", "Evaluate performance.", "动词", "高级动词"),
        ("evaporate", "/ɪˈvæpəreɪt/", "蒸发", "Water evaporates.", "动词", "高级动词"),
        ("evolve", "/ɪˈvɒlv/", "进化", "Evolve over time.", "动词", "高级动词"),
        ("exaggerate", "/ɪɡˈzædʒəreɪt/", "夸大", "Don't exaggerate.", "动词", "高级动词"),
        ("examine", "/ɪɡˈzæmɪn/", "检查", "Examine the evidence.", "动词", "高级动词"),
        ("exceed", "/ɪkˈsiːd/", "超过", "Exceed expectations.", "动词", "高级动词"),
        ("exchange", "/ɪksˈtʃeɪndʒ/", "交换", "Exchange ideas.", "动词", "高级动词"),
        ("excite", "/ɪkˈsaɪt/", "使兴奋", "Excite the crowd.", "动词", "高级动词"),
        ("exclude", "/ɪkˈskluːd/", "排除", "Exclude the outliers.", "动词", "高级动词"),
        ("execute", "/ˈeksɪkjuːt/", "执行", "Execute the plan.", "动词", "高级动词"),
        ("exempt", "/ɪɡˈzempt/", "免除", "Exempt from tax.", "动词", "高级动词"),
        ("exercise", "/ˈeksəsaɪz/", "锻炼", "Exercise daily.", "动词", "高级动词"),
        ("exert", "/ɪɡˈzɜːrt/", "施加", "Exert influence.", "动词", "高级动词"),
        ("exhaust", "/ɪɡˈzɔːst/", "耗尽", "Exhaust the resources.", "动词", "高级动词"),
        ("exhibit", "/ɪɡˈzɪbɪt/", "展示", "Exhibit the work.", "动词", "高级动词"),
        ("exist", "/ɪɡˈzɪst/", "存在", "Problems exist.", "动词", "高级动词"),
        ("expand", "/ɪkˈspænd/", "扩大", "Expand your business.", "动词", "高级动词"),
        ("expect", "/ɪkˈspekt/", "期望", "Expect the best.", "动词", "高级动词"),
        ("expel", "/ɪkˈspel/", "驱逐", "Expel the student.", "动词", "高级动词"),
        ("expend", "/ɪkˈspend/", "花费", "Expend energy.", "动词", "高级动词"),
        ("experience", "/ɪkˈspɪəriəns/", "体验", "Experience life.", "动词", "高级动词"),
        ("experiment", "/ɪkˈsperɪment/", "实验", "Experiment freely.", "动词", "高级动词"),
        ("explain", "/ɪkˈspleɪn/", "解释", "Explain clearly.", "动词", "高级动词"),
        ("explode", "/ɪkˈspləʊd/", "爆炸", "The bomb exploded.", "动词", "高级动词"),
        ("exploit", "/ɪkˈsplɔɪt/", "利用", "Exploit resources.", "动词", "高级动词"),
        ("explore", "/ɪkˈsplɔːr/", "探索", "Explore the world.", "动词", "高级动词"),
        ("export", "/ɪkˈspɔːt/", "出口", "Export goods.", "动词", "高级动词"),
        ("expose", "/ɪkˈspəʊz/", "暴露", "Expose the truth.", "动词", "高级动词"),
        ("express", "/ɪkˈspres/", "表达", "Express yourself.", "动词", "高级动词"),
        ("extend", "/ɪkˈstend/", "延伸", "Extend the deadline.", "动词", "高级动词"),
        ("extinguish", "/ɪkˈstɪŋɡwɪʃ/", "熄灭", "Extinguish the fire.", "动词", "高级动词"),
        ("extract", "/ɪkˈstrækt/", "提取", "Extract the data.", "动词", "高级动词"),
        ("face", "/feɪs/", "面对", "Face reality.", "动词", "高级动词"),
        ("facilitate", "/fəˈsɪlɪteɪt/", "促进", "Facilitate growth.", "动词", "高级动词"),
        ("fade", "/feɪd/", "褪色", "Colors fade.", "动词", "高级动词"),
        ("fail", "/feɪl/", "失败", "Never fail.", "动词", "高级动词"),
        ("faint", "/feɪnt/", "昏倒", "She fainted.", "动词", "高级动词"),
        ("fall", "/fɔːl/", "落下", "Fall in love.", "动词", "高级动词"),
        ("falsify", "/ˈfɔːlsɪfaɪ/", "伪造", "Falsify documents.", "动词", "高级动词"),
        ("fascinate", "/ˈfæsɪneɪt/", "使着迷", "Fascinate the audience.", "动词", "高级动词"),
        ("fashion", "/ˈfæʃn/", "制作", "Fashion a solution.", "动词", "高级动词"),
        ("fasten", "/ˈfæsn/", "固定", "Fasten the seatbelt.", "动词", "高级动词"),
        ("fault", "/fɔːlt/", "挑剔", "Don't fault me.", "动词", "高级动词"),
        ("favor", "/ˈfeɪvər/", "偏爱", "Favor the bold.", "动词", "高级动词"),
        ("fear", "/fɪr/", "害怕", "Fear nothing.", "动词", "高级动词"),
        ("feed", "/fiːd/", "喂养", "Feed the hungry.", "动词", "高级动词"),
        ("feel", "/fiːl/", "感觉", "Feel the rhythm.", "动词", "高级动词"),
        ("fence", "/fens/", "围住", "Fence the yard.", "动词", "高级动词"),
        ("fetch", "/fetʃ/", "取来", "Fetch the water.", "动词", "高级动词"),
        ("fight", "/faɪt/", "战斗", "Fight for rights.", "动词", "高级动词"),
        ("figure", "/ˈfɪɡjər/", "计算", "Figure it out.", "动词", "高级动词"),
        ("file", "/faɪl/", "归档", "File the report.", "动词", "高级动词"),
        ("fill", "/fɪl/", "填充", "Fill the form.", "动词", "高级动词"),
        ("filter", "/ˈfɪltər/", "过滤", "Filter the water.", "动词", "高级动词"),
        ("finance", "/ˈfaɪnæns/", "资助", "Finance the project.", "动词", "高级动词"),
        ("find", "/faɪnd/", "发现", "Find the answer.", "动词", "高级动词"),
        ("fine", "/faɪn/", "罚款", "Fine the driver.", "动词", "高级动词"),
        ("finish", "/ˈfɪnɪʃ/", "完成", "Finish strong.", "动词", "高级动词"),
        ("fire", "/faɪər/", "解雇", "Fire the employee.", "动词", "高级动词"),
        ("firm", "/fɜːrm/", "使坚固", "Firm the ground.", "动词", "高级动词"),
        ("fit", "/fɪt/", "适合", "Fit perfectly.", "动词", "高级动词"),
        ("fix", "/fɪks/", "修理", "Fix the problem.", "动词", "高级动词"),
        ("flag", "/flæɡ/", "标记", "Flag the issue.", "动词", "高级动词"),
        ("flame", "/fleɪm/", "燃烧", "Flame up.", "动词", "高级动词"),
        ("flash", "/flæʃ/", "闪烁", "Flash the light.", "动词", "高级动词"),
        ("flatten", "/ˈflætn/", "弄平", "Flatten the dough.", "动词", "高级动词"),
        ("flavor", "/ˈfleɪvər/", "调味", "Flavor the dish.", "动词", "高级动词"),
        ("flee", "/fliː/", "逃跑", "Flee the scene.", "动词", "高级动词"),
        ("float", "/fləʊt/", "漂浮", "Float on water.", "动词", "高级动词"),
        ("flock", "/flɒk/", "聚集", "Birds flock together.", "动词", "高级动词"),
        ("flood", "/flʌd/", "淹没", "Flood the market.", "动词", "高级动词"),
        ("flow", "/fləʊ/", "流动", "Let it flow.", "动词", "高级动词"),
        ("flower", "/ˈflaʊər/", "开花", "Flowers bloom.", "动词", "高级动词"),
        ("flutter", "/ˈflʌtər/", "拍动", "Butterflies flutter.", "动词", "高级动词"),
        ("fly", "/flaɪ/", "飞", "Fly high.", "动词", "高级动词"),
        ("focus", "/ˈfəʊkəs/", "集中", "Focus on success.", "动词", "高级动词"),
        ("fold", "/fəʊld/", "折叠", "Fold the clothes.", "动词", "高级动词"),
        ("follow", "/ˈfɒləʊ/", "跟随", "Follow your heart.", "动词", "高级动词"),
        ("forbid", "/fərˈbɪd/", "禁止", "Forbid entry.", "动词", "高级动词"),
        ("force", "/fɔːrs/", "强迫", "Force the issue.", "动词", "高级动词"),
        ("forecast", "/ˈfɔːrkæst/", "预测", "Forecast the weather.", "动词", "高级动词"),
        ("forge", "/fɔːrdʒ/", "锻造", "Forge ahead.", "动词", "高级动词"),
        ("forget", "/fərˈɡet/", "忘记", "Forget the past.", "动词", "高级动词"),
        ("forgive", "/fərˈɡɪv/", "原谅", "Forgive and forget.", "动词", "高级动词"),
        ("form", "/fɔːrm/", "形成", "Form a habit.", "动词", "高级动词"),
        ("formalize", "/ˈfɔːrməlaɪz/", "使正式", "Formalize the agreement.", "动词", "高级动词"),
        ("format", "/ˈfɔːrmæt/", "格式化", "Format the disk.", "动词", "高级动词"),
        ("formulate", "/ˈfɔːrmjʊleɪt/", "制定", "Formulate a plan.", "动词", "高级动词"),
        ("forsake", "/fərˈseɪk/", "抛弃", "Forsake the old ways.", "动词", "高级动词"),
        ("fortify", "/ˈfɔːrtɪfaɪ/", "加强", "Fortify the defense.", "动词", "高级动词"),
        ("foster", "/ˈfɒstər/", "培养", "Foster growth.", "动词", "高级动词"),
        ("found", "/faʊnd/", "建立", "Found a company.", "动词", "高级动词"),
        ("frame", "/freɪm/", "构陷", "Frame the picture.", "动词", "高级动词"),
        ("freeze", "/friːz/", "冻结", "Freeze the assets.", "动词", "高级动词"),
        ("frighten", "/ˈfraɪtn/", "使害怕", "Don't frighten me.", "动词", "高级动词"),
        ("frown", "/fraʊn/", "皱眉", "Don't frown.", "动词", "高级动词"),
        ("fry", "/fraɪ/", "油炸", "Fry the egg.", "动词", "高级动词"),
        ("fulfill", "/fʊlˈfɪl/", "履行", "Fulfill your promise.", "动词", "高级动词"),
        ("function", "/ˈfʌŋkʃn/", "运行", "Function properly.", "动词", "高级动词"),
        ("fund", "/fʌnd/", "资助", "Fund the project.", "动词", "高级动词"),
        ("furnish", "/ˈfɜːrnɪʃ/", "提供", "Furnish the room.", "动词", "高级动词"),
        ("fuse", "/fjuːz/", "熔合", "Fuse the metals.", "动词", "高级动词"),
        ("gain", "/ɡeɪn/", "获得", "Gain experience.", "动词", "高级动词"),
        ("gaze", "/ɡeɪz/", "凝视", "Gaze at the stars.", "动词", "高级动词"),
        ("generate", "/ˈdʒenəreɪt/", "产生", "Generate income.", "动词", "高级动词"),
        ("get", "/ɡet/", "得到", "Get started.", "动词", "高级动词"),
        ("give", "/ɡɪv/", "给予", "Give your best.", "动词", "高级动词"),
        ("glance", "/ɡlæns/", "瞥见", "Glance at the clock.", "动词", "高级动词"),
        ("glare", "/ɡleər/", "怒视", "Don't glare.", "动词", "高级动词"),
        ("glide", "/ɡlaɪd/", "滑行", "Glide smoothly.", "动词", "高级动词"),
        ("glimpse", "/ɡlɪmps/", "瞥见", "Glimpse the future.", "动词", "高级动词"),
        ("glitter", "/ˈɡlɪtər/", "闪烁", "Diamonds glitter.", "动词", "高级动词"),
        ("gloat", "/ɡləʊt/", "幸灾乐祸", "Don't gloat.", "动词", "高级动词"),
        ("gloom", "/ɡluːm/", "忧郁", "Don't gloom.", "动词", "高级动词"),
        ("glow", "/ɡləʊ/", "发光", "The sun glows.", "动词", "高级动词"),
        ("glue", "/ɡluː/", "粘合", "Glue the paper.", "动词", "高级动词"),
        ("go", "/ɡəʊ/", "去", "Go for it.", "动词", "高级动词"),
        ("govern", "/ˈɡʌvərn/", "统治", "Govern wisely.", "动词", "高级动词"),
        ("grab", "/ɡræb/", "抓取", "Grab the opportunity.", "动词", "高级动词"),
        ("grace", "/ɡreɪs/", "使优雅", "Grace the occasion.", "动词", "高级动词"),
        ("grade", "/ɡreɪd/", "评分", "Grade the papers.", "动词", "高级动词"),
        ("graduate", "/ˈɡrædʒueɪt/", "毕业", "Graduate with honors.", "动词", "高级动词"),
        ("grain", "/ɡreɪn/", "使成颗粒状", "Grain the photo.", "动词", "高级动词"),
        ("grant", "/ɡrænt/", "授予", "Grant permission.", "动词", "高级动词"),
        ("grasp", "/ɡræsp/", "抓住", "Grasp the concept.", "动词", "高级动词"),
        ("grate", "/ɡreɪt/", "磨碎", "Grate the cheese.", "动词", "高级动词"),
        ("grieve", "/ɡriːv/", "悲伤", "Don't grieve.", "动词", "高级动词"),
        ("grind", "/ɡraɪnd/", "研磨", "Grind the coffee.", "动词", "高级动词"),
        ("grip", "/ɡrɪp/", "紧握", "Grip the wheel.", "动词", "高级动词"),
        ("groan", "/ɡrəʊn/", "呻吟", "Don't groan.", "动词", "高级动词"),
        ("grow", "/ɡrəʊ/", "生长", "Grow stronger.", "动词", "高级动词"),
        ("guarantee", "/ˌɡærənˈtiː/", "保证", "Guarantee satisfaction.", "动词", "高级动词"),
        ("guard", "/ɡɑːrd/", "守卫", "Guard the treasure.", "动词", "高级动词"),
        ("guess", "/ɡes/", "猜测", "Guess what?", "动词", "高级动词"),
        ("guide", "/ɡaɪd/", "指导", "Guide the team.", "动词", "高级动词"),
        ("guilt", "/ɡɪlt/", "使内疚", "Don't guilt me.", "动词", "高级动词"),
        ("halt", "/hɔːlt/", "停止", "Halt production.", "动词", "高级动词"),
        ("hammer", "/ˈhæmər/", "锤击", "Hammer the nail.", "动词", "高级动词"),
        ("hand", "/hænd/", "递给", "Hand it over.", "动词", "高级动词"),
        ("handle", "/ˈhændl/", "处理", "Handle with care.", "动词", "高级动词"),
        ("hang", "/hæŋ/", "悬挂", "Hang up the phone.", "动词", "高级动词"),
        ("happen", "/ˈhæpən/", "发生", "Anything can happen.", "动词", "高级动词"),
        ("harass", "/həˈræs/", "骚扰", "Don't harass.", "动词", "高级动词"),
        ("harm", "/hɑːrm/", "伤害", "Harm no one.", "动词", "高级动词"),
        ("harvest", "/ˈhɑːrvɪst/", "收获", "Harvest the crops.", "动词", "高级动词"),
        ("haste", "/heɪst/", "匆忙", "Make haste.", "动词", "高级动词"),
        ("hatch", "/hætʃ/", "孵化", "Hatch the plan.", "动词", "高级动词"),
        ("hate", "/heɪt/", "讨厌", "Hate the sin.", "动词", "高级动词"),
        ("haunt", "/hɔːnt/", "萦绕", "Memories haunt.", "动词", "高级动词"),
        ("have", "/hæv/", "有", "Have faith.", "动词", "高级动词"),
        ("heal", "/hiːl/", "治愈", "Heal the wound.", "动词", "高级动词"),
        ("heap", "/hiːp/", "堆积", "Heap the praise.", "动词", "高级动词"),
        ("hear", "/hɪr/", "听见", "Hear the music.", "动词", "高级动词"),
        ("heat", "/hiːt/", "加热", "Heat the water.", "动词", "高级动词"),
        ("help", "/help/", "帮助", "Help yourself.", "动词", "高级动词"),
        ("hide", "/haɪd/", "隐藏", "Hide and seek.", "动词", "高级动词"),
        ("highlight", "/ˈhaɪlaɪt/", "突出", "Highlight the text.", "动词", "高级动词"),
        ("hinder", "/ˈhɪndər/", "阻碍", "Don't hinder progress.", "动词", "高级动词"),
        ("hint", "/hɪnt/", "暗示", "Hint at the truth.", "动词", "高级动词"),
        ("hire", "/ˈhaɪər/", "雇佣", "Hire new talent.", "动词", "高级动词"),
        ("hit", "/hɪt/", "击打", "Hit the target.", "动词", "高级动词"),
        ("hoist", "/hɔɪst/", "升起", "Hoist the flag.", "动词", "高级动词"),
        ("hold", "/həʊld/", "持有", "Hold on tight.", "动词", "高级动词"),
        ("hollow", "/ˈhɒləʊ/", "挖空", "Hollow the tree.", "动词", "高级动词"),
        ("honor", "/ˈɒnər/", "尊敬", "Honor your parents.", "动词", "高级动词"),
        ("hook", "/hʊk/", "钩住", "Hook the fish.", "动词", "高级动词"),
        ("hope", "/həʊp/", "希望", "Hope for the best.", "动词", "高级动词"),
        ("hop", "/hɒp/", "跳跃", "Hop to it.", "动词", "高级动词"),
        ("horror", "/ˈhɒrər/", "使恐惧", "Horror strikes.", "动词", "高级动词"),
        ("host", "/həʊst/", "主持", "Host the show.", "动词", "高级动词"),
        ("hover", "/ˈhʌvər/", "盘旋", "Helicopters hover.", "动词", "高级动词"),
        ("hug", "/hʌɡ/", "拥抱", "Hug your loved ones.", "动词", "高级动词"),
        ("hum", "/hʌm/", "哼唱", "Hum a tune.", "动词", "高级动词"),
        ("humiliate", "/hjuːˈmɪlieɪt/", "羞辱", "Don't humiliate.", "动词", "高级动词"),
        ("hunt", "/hʌnt/", "狩猎", "Hunt for treasure.", "动词", "高级动词"),
        ("hurry", "/ˈhʌri/", "匆忙", "Don't hurry.", "动词", "高级动词"),
        ("hurt", "/hɜːrt/", "受伤", "Don't hurt yourself.", "动词", "高级动词"),
        ("hush", "/hʌʃ/", "安静", "Hush now.", "动词", "高级动词"),
        ("hustle", "/ˈhʌsl/", "催促", "Hustle hard.", "动词", "高级动词"),
        ("identify", "/aɪˈdentɪfaɪ/", "识别", "Identify the problem.", "动词", "高级动词"),
        ("ignite", "/ɪɡˈnaɪt/", "点燃", "Ignite the passion.", "动词", "高级动词"),
        ("ignore", "/ɪɡˈnɔːr/", "忽视", "Don't ignore me.", "动词", "高级动词"),
        ("illustrate", "/ˈɪləstreɪt/", "说明", "Illustrate the point.", "动词", "高级动词"),
        ("imagine", "/ɪˈmædʒɪn/", "想象", "Imagine the possibilities.", "动词", "高级动词"),
        ("imitate", "/ˈɪmɪteɪt/", "模仿", "Imitate success.", "动词", "高级动词"),
        ("immerse", "/ɪˈmɜːrs/", "沉浸", "Immerse yourself.", "动词", "高级动词"),
        ("immigrate", "/ˈɪmɪɡreɪt/", "移民", "Immigrate to Canada.", "动词", "高级动词"),
        ("impair", "/ɪmˈpeər/", "损害", "Impair the function.", "动词", "高级动词"),
        ("impart", "/ɪmˈpɑːrt/", "传授", "Impart knowledge.", "动词", "高级动词"),
        ("impede", "/ɪmˈpiːd/", "阻碍", "Don't impede progress.", "动词", "高级动词"),
        ("imply", "/ɪmˈplaɪ/", "暗示", "Imply the meaning.", "动词", "高级动词"),
        ("import", "/ɪmˈpɔːrt/", "进口", "Import goods.", "动词", "高级动词"),
        ("impose", "/ɪmˈpəʊz/", "强加", "Impose rules.", "动词", "高级动词"),
        ("impress", "/ɪmˈpres/", "给...留下印象", "Impress the boss.", "动词", "高级动词"),
        ("imprison", "/ɪmˈprɪzn/", "监禁", "Imprison the criminal.", "动词", "高级动词"),
        ("improve", "/ɪmˈpruːv/", "改善", "Improve daily.", "动词", "高级动词"),
        ("include", "/ɪnˈkluːd/", "包括", "Include everyone.", "动词", "高级动词"),
        ("incorporate", "/ɪnˈkɔːpəreɪt/", "合并", "Incorporate feedback.", "动词", "高级动词"),
        ("increase", "/ɪnˈkriːs/", "增加", "Increase sales.", "动词", "高级动词"),
        ("incur", "/ɪnˈkɜːr/", "招致", "Incur debt.", "动词", "高级动词"),
        ("indicate", "/ˈɪndɪkeɪt/", "表明", "Indicate your choice.", "动词", "高级动词"),
        ("induce", "/ɪnˈduːs/", "引诱", "Induce labor.", "动词", "高级动词"),
        ("inevitable", "/ɪnˈevɪtəbl/", "不可避免的", "Change is inevitable.", "形容词", "性质描述"),
        ("infect", "/ɪnˈfekt/", "感染", "Infect the computer.", "动词", "高级动词"),
        ("infer", "/ɪnˈfɜːr/", "推断", "Infer the meaning.", "动词", "高级动词"),
        ("influence", "/ˈɪnfluəns/", "影响", "Influence others.", "动词", "高级动词"),
        ("inform", "/ɪnˈfɔːrm/", "通知", "Inform the police.", "动词", "高级动词"),
        ("inhabit", "/ɪnˈhæbɪt/", "居住于", "Inhabit the island.", "动词", "高级动词"),
        ("inherit", "/ɪnˈherɪt/", "继承", "Inherit the throne.", "动词", "高级动词"),
        ("initiate", "/ɪˈnɪʃieɪt/", "开始", "Initiate the process.", "动词", "高级动词"),
        ("inject", "/ɪnˈdʒekt/", "注射", "Inject the medicine.", "动词", "高级动词"),
        ("injure", "/ˈɪndʒər/", "伤害", "Don't injure yourself.", "动词", "高级动词"),
        ("inquire", "/ɪnˈkwaɪər/", "询问", "Inquire about the price.", "动词", "高级动词"),
        ("insert", "/ɪnˈsɜːrt/", "插入", "Insert the key.", "动词", "高级动词"),
        ("insist", "/ɪnˈsɪst/", "坚持", "Insist on quality.", "动词", "高级动词"),
        ("inspect", "/ɪnˈspekt/", "检查", "Inspect the vehicle.", "动词", "高级动词"),
        ("inspire", "/ɪnˈspaɪər/", "激励", "Inspire greatness.", "动词", "高级动词"),
        ("install", "/ɪnˈstɔːl/", "安装", "Install the software.", "动词", "高级动词"),
        ("institute", "/ˈɪnstɪtuːt/", "建立", "Institute reforms.", "动词", "高级动词"),
        ("instruct", "/ɪnˈstrʌkt/", "指导", "Instruct the class.", "动词", "高级动词"),
        ("insult", "/ɪnˈsʌlt/", "侮辱", "Don't insult me.", "动词", "高级动词"),
        ("insure", "/ɪnˈʃʊər/", "投保", "Insure your car.", "动词", "高级动词"),
        ("integrate", "/ˈɪntɪɡreɪt/", "整合", "Integrate the systems.", "动词", "高级动词"),
        ("intend", "/ɪnˈtend/", "打算", "Intend to succeed.", "动词", "高级动词"),
        ("intensify", "/ɪnˈtensɪfaɪ/", "加强", "Intensify the effort.", "动词", "高级动词"),
        ("interact", "/ˌɪntərˈækt/", "互动", "Interact with others.", "动词", "高级动词"),
        ("interest", "/ˈɪntrəst/", "使感兴趣", "Interest the audience.", "动词", "高级动词"),
        ("interfere", "/ˌɪntərˈfɪər/", "干涉", "Don't interfere.", "动词", "高级动词"),
        ("interpret", "/ɪnˈtɜːrprɪt/", "解释", "Interpret the data.", "动词", "高级动词"),
        ("interrupt", "/ˌɪntəˈrʌpt/", "打断", "Don't interrupt.", "动词", "高级动词"),
        ("intersect", "/ˌɪntərˈsekt/", "相交", "Lines intersect.", "动词", "高级动词"),
        ("intervene", "/ˌɪntərˈviːn/", "干预", "Intervene early.", "动词", "高级动词"),
        ("interview", "/ˈɪntərvjuː/", "面试", "Interview candidates.", "动词", "高级动词"),
        ("introduce", "/ˌɪntrəˈduːs/", "介绍", "Introduce yourself.", "动词", "高级动词"),
        ("invent", "/ɪnˈvent/", "发明", "Invent the future.", "动词", "高级动词"),
        ("invest", "/ɪnˈvest/", "投资", "Invest wisely.", "动词", "高级动词"),
        ("investigate", "/ɪnˈvestɪɡeɪt/", "调查", "Investigate the crime.", "动词", "高级动词"),
        ("invite", "/ɪnˈvaɪt/", "邀请", "Invite your friends.", "动词", "高级动词"),
        ("involve", "/ɪnˈvɒlv/", "涉及", "Involve everyone.", "动词", "高级动词"),
        ("iron", "/ˈaɪərn/", "熨烫", "Iron the clothes.", "动词", "高级动词"),
        ("irritate", "/ˈɪrɪteɪt/", "激怒", "Don't irritate me.", "动词", "高级动词"),
        ("isolate", "/ˈaɪsəleɪt/", "隔离", "Isolate the patient.", "动词", "高级动词"),
        ("issue", "/ˈɪʃuː/", "发布", "Issue the command.", "动词", "高级动词"),
        ("jack", "/dʒæk/", "顶起", "Jack up the car.", "动词", "高级动词"),
        ("jam", "/dʒæm/", "塞进", "Jam the door.", "动词", "高级动词"),
        ("jeer", "/dʒɪr/", "嘲笑", "Don't jeer.", "动词", "高级动词"),
        ("jerk", "/dʒɜːrk/", "猛拉", "Jerk the rope.", "动词", "高级动词"),
        ("join", "/dʒɔɪn/", "加入", "Join the team.", "动词", "高级动词"),
        ("joke", "/dʒəʊk/", "开玩笑", "Don't joke.", "动词", "高级动词"),
        ("jolt", "/dʒəʊlt/", "震动", "Jolt the system.", "动词", "高级动词"),
        ("judge", "/dʒʌdʒ/", "判断", "Judge fairly.", "动词", "高级动词"),
        ("juggle", "/ˈdʒʌɡl/", "玩杂耍", "Juggle the tasks.", "动词", "高级动词"),
        ("jump", "/dʒʌmp/", "跳跃", "Jump for joy.", "动词", "高级动词"),
        ("justify", "/ˈdʒʌstɪfaɪ/", "证明...正当", "Justify your actions.", "动词", "高级动词"),
        ("keep", "/kiːp/", "保持", "Keep going.", "动词", "高级动词"),
        ("kick", "/kɪk/", "踢", "Kick the ball.", "动词", "高级动词"),
        ("kill", "/kɪl/", "杀死", "Kill the process.", "动词", "高级动词"),
        ("kiss", "/kɪs/", "亲吻", "Kiss goodbye.", "动词", "高级动词"),
        ("kneel", "/niːl/", "跪下", "Kneel in prayer.", "动词", "高级动词"),
        ("knit", "/nɪt/", "编织", "Knit a sweater.", "动词", "高级动词"),
        ("knock", "/nɒk/", "敲", "Knock on the door.", "动词", "高级动词"),
        ("knot", "/nɒt/", "打结", "Knot the rope.", "动词", "高级动词"),
        ("know", "/nəʊ/", "知道", "Know yourself.", "动词", "高级动词"),
        ("label", "/ˈleɪbl/", "标记", "Label the package.", "动词", "高级动词"),
        ("lack", "/læk/", "缺乏", "Lack nothing.", "动词", "高级动词"),
        ("lag", "/læɡ/", "滞后", "Don't lag behind.", "动词", "高级动词"),
        ("land", "/lænd/", "着陆", "Land safely.", "动词", "高级动词"),
        ("last", "/læst/", "持续", "Last forever.", "动词", "高级动词"),
        ("laugh", "/læf/", "笑", "Laugh often.", "动词", "高级动词"),
        ("launch", "/lɔːntʃ/", "发射", "Launch the rocket.", "动词", "高级动词"),
        ("lavish", "/ˈlævɪʃ/", "慷慨给予", "Lavish praise.", "动词", "高级动词"),
        ("lay", "/leɪ/", "放置", "Lay the foundation.", "动词", "高级动词"),
        ("lead", "/liː